-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
---------------------------- shell.as -----------------------------
-- Copyright Swiss Federal Polytechnic Institute Zurich, 1995
--
#include "sumit"

macro {
	Z	== SingleInteger;
	TX	== TextWriter;
	TAB	== SymbolTable;
	NL	== newline;
}

#if ASDOC
\thistype{Shell}
\History{Manuel Bronstein}{10/01/96}{created}
\Usage{import from \this(P, R, E)}
\Params{
P & Parser & A parser type for the input\\
R & PartialRing & Resulting type of the evaluation\\
E & Evaluator R & An interpreter with target type R\\
}
\Descr{\this(P, R, E) provides a basic read-eval-loop that converts its input
to expressions of type R.}
\begin{exports}
banner: & (TW, String) $\to$ TW & Print a banner\\
shell!: & (P, TW, TW, SymbolTable R, Boolean) $\to$ SingleInteger &
Read-eval loop\\
\end{exports}
\begin{aswhere}
TW &==& TextWriter\\
\end{aswhere}
#endif

Shell(P:Parser, R:PartialRing, E:Evaluator R): with {
	banner: (TX, String) -> TX;
#if ASDOC
\aspage{banner}
\Usage{\name(p, s)}
\Signature{(TextWriter, String)}{TextWriter}
\Params{
{\em p} & TextWriter & The port to write to\\
{\em s} & String & A name to center in the banner\\
}
\Descr{Writes the default \sumit~banner to the port p.}
\Remarks{The string s is automatically centered in the banner. In order
for the banner to look ok, it must have a maximum of 33 characters.}
\begin{asex}
\begin{ttyout}
banner(print, "B E R N I N A");
\end{ttyout}
prints the following banner:
\begin{verbatim}
                                                          /\    
      -----  it                                          /| \    
      \                   B E R N I N A                 / |  \    
       \                                               |   \  \   
       /                 A Sum^it server               |    |  \  
      /                                                /     \  \ 
      -----                                           /      |   \
                                                     /       /    \


\end{verbatim}
\end{asex}
#endif
	shell!: (P, TX, TX, TAB R, Boolean) -> Z;
#if ASDOC
\aspage{shell!}
\Usage{\name(r, p1, p2, t, verbose?)}
\Signature{(P, TextWriter, TextWriter, SymbolTable R, Boolean)}{SingleInteger}
\Params{
{\em r} & P & A parser\\
{\em p1,p2} & TextWriter & The ports to write to\\
{\em t} & SymbolTable R & The initial symbol table\\
{\em verbose?} & Boolean & Select verbose or quiet mode\\
}
\Descr{Starts a read-eval loop which takes its input from r and writes
its output to p1 or p2. Mathematical output generated by user commands
is written to p1, while prompts and execution times are written to p2.
if verbose? is false (quiet mode), nothing is printed to p2 and no
prompts or execution times are communicated.
The table t contains the initial environment, and can be modified by the loop.
Returns an integer $n = b_1 b_0$ where $b_0$ is 1 if a syntax error occured,
0 otherwise, and $b_1$ is 1 if any other error occured, 0 otherwise.}
#endif
} == add {
	local prompt(p:TX, n:Z):TX == p << newline << n << " --> ";

	local err1(p:TX, msg:String, verbose?:Boolean):() == {
		if verbose? then p << "*** " << msg << " ***" << newline;
	}

-- title is automatically centered in a 33-character field
	banner(p:TX, title:String):TX == {
		import from Z;
		n := max(0, 33 - #title);	-- total # of spaces to add
		n2 := n quo 2;
		left := new n2;
		right := new(n - n2);
		p << NL;
p << "                                                          /\    " << NL;
p << "      -----  it                                          /| \    " << NL;
p << "      \         "  << left << title << right << "       / |  \    " << NL;
p << "       \                                               |   \  \   " << NL;
p << "       /                 A Sum^it server               |    |  \  " << NL;
p << "      /                                                /     \  \ " << NL;
p << "      -----                                           /      |   \" << NL;
p << "                   Use ^D to terminate session       /       /    \"<< NL;
		p << NL << NL;
	}

	-- return true if an error has occured
	shell!(pin:P, pout:TX, ptime:TX, t:TAB R, verb?:Boolean):Z == {
		import from Z, Partial ExpressionTree;
		err:Z := 0;
		count:Z := 1;
		if verb? then prompt(ptime, count);
		while ~eof? pin repeat {
			if failed?(tree := parse! pin) then {
				err := err \/ 1;
				err1(pout, "syntax error", verb? and ~eof? pin);
			}
			else
				if process(pout, ptime, retract tree, t, verb?)
							then err := err \/ 2;
			count := next count;
			if verb? then prompt(ptime, count);
		}
		if verb? then ptime << newline;
		err;
	}

	-- return true if an error has occured
	local process(p:TX, ptime:TX, tree:ExpressionTree, t:TAB R,
		verbose?:Boolean):Boolean == {
			import from E, R, Partial R, Timer;
			clock := timer();
			start! clock;
			result := eval!(p, tree, t);
			msecs := stop! clock;
			if (err? := failed? result) then
				err1(p, "failed to evaluate", true);
			if verbose? then printTime(ptime, msecs);
			err?;
	}

	local printTime(p:TX, time:Z):TX == {
		import from Timer;
		(h, m, s, u) := HMS time;
		p << h << ":";
		if m < 10 then p << "0";
		p << m << ":";
		if s < 10 then p << "0";
		p << s << ".";
		if u < 100 then p << "0";
		if u < 10 then p << "0";
		p << u << newline;
	}
}
