//
// Java generated by aldor from file basictuple.ao
//
package aldorcode;
import foamj.FoamContext;
import foamj.Foam;
import foamj.EnvRecord;
import foamj.Record;
import foamj.FoamClass;
import foamj.MultiRecord;
import foamj.Format;
import foamj.Math;
import foamj.Word;
import foamj.Value;
import foamj.Env;
import foamj.Clos;
import foamj.Fn;
import foamj.Globals;
/**
 * Generated by genjava - basictuple
 */

public class basictuple implements FoamClass {
    private static Format FORMAT_0 = new Format(16);
    private static Format FORMAT_5 = new Format(3);
    private static Format FORMAT_8 = new Format(1);
    private static Format FORMAT_9 = new Format(11);
    private static Format FORMAT_11 = new Format(2);
    private Clos basictuple_init;
    private Clos runtime_init;
    private Clos foamcat_init;
    private FoamContext ctxt;
    public basictuple(FoamContext ctxt) {
        this.ctxt = ctxt;
        basictuple_init = new Clos(null, C0_basictuple);
        runtime_init = ctxt.createLoadFn("runtime");
        foamcat_init = ctxt.createLoadFn("foamcat");
    }
    
    public void run() {
        basictuple_init.getProg().ocall(basictuple_init.getEnv());
    }
    
    private Fn C0_basictuple = new Fn("C0_basictuple") { 
        public Value ocall(Env env, Value ... vals) {
            c0_basictuple(env);
            return null;
        }

    };
    private void c0_basictuple(Env env1) {
        Word [] t1, t2;
        Record t3, t4;
        Clos t0 = null;
        final Env env0 = new Env(new EnvRecord(FORMAT_11), env1);
        final EnvRecord lvl0 = env0.level();
        ccall_Xx(runtime_init);
        Globals.setGlobal("basictuple", Clos.fromValue(Globals.getGlobal("noOperation")));
        t0 = new Clos(env0, C14_foamcat_MINUS_init);
        Globals.setGlobal("basictuple_BasicTuple_825667711", (Value)ccall_WxC(Clos.fromValue(Globals.getGlobal("domainMake")), new Clos(env0, C1_addLevel0)));
        lvl0.setField(1, "", Value.U.fromBool(false));
        t1 = new Word[10];
        t2 = new Word[10];
        t1[0] = Word.U.fromSInt(200102);
        t2[0] = Word.U.fromArray("=\0".toCharArray());
        t1[1] = Word.U.fromSInt(51509389);
        t2[1] = Word.U.fromArray("~=\0".toCharArray());
        t1[2] = Word.U.fromSInt(609528375);
        t2[2] = Word.U.fromArray("tuple\0".toCharArray());
        t1[3] = Word.U.fromSInt(379591369);
        t2[3] = Word.U.fromArray("element\0".toCharArray());
        t1[4] = Word.U.fromSInt(255806968);
        t2[4] = Word.U.fromArray("sample\0".toCharArray());
        t1[5] = Word.U.fromSInt(864625472);
        t2[5] = Word.U.fromArray("case\0".toCharArray());
        t1[6] = Word.U.fromSInt(614579040);
        t2[6] = Word.U.fromArray("dispose!\0".toCharArray());
        t1[7] = Word.U.fromSInt(437828088);
        t2[7] = Word.U.fromArray("length\0".toCharArray());
        t1[8] = Word.U.fromSInt(51492426);
        t2[8] = Word.U.fromArray("<<\0".toCharArray());
        t1[9] = Word.U.fromSInt(746853960);
        t2[9] = Word.U.fromArray("hash\0".toCharArray());
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(10));
        t3.setField(1, "nsize", Value.U.fromSInt(10));
        t3.setField(2, "values", (Value)Word.U.fromArray(t1));
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(10));
        t4.setField(1, "nsize", Value.U.fromSInt(10));
        t4.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWW(Clos.fromValue(Globals.getGlobal("rtAddStrings")), Word.U.fromRec(t3), Word.U.fromRec(t4));
        lvl0.setField(0, "BasicType", (Value)ccall_WxCI(Clos.fromValue(Globals.getGlobal("rtLazyCatFrInit")), t0, 0));
        return;
    }
    
    private Fn C1_addLevel0 = new Fn("C1_addLevel0") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c1_addLevel0(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c1_addLevel0(Env env1, Word p0_domain) {
        final Env env0 = new Env(null, env1);
        ccall_WxWW(Clos.fromValue(Globals.getGlobal("domainAddNameFn!")), p0_domain, ccall_WxA(Clos.fromValue(Globals.getGlobal("rtConstNameFn")), "BasicTuple\0".toCharArray()));
        ccall_WxWI(Clos.fromValue(Globals.getGlobal("domainAddHash!")), p0_domain, 800448518);
        return new Clos(env0, C2_addLevel1);
    }
    
    private Fn C2_addLevel1 = new Fn("C2_addLevel1") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c2_addLevel1(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c2_addLevel1(Env env1, Word p0_domain, Word p1_hashcode) {
        Word [] t0, t1, t2;
        Record t3, t4, t5;
        int t7 = 0, t8 = 0, t9 = 0, t10 = 0, t11 = 0, t12 = 0, t13 = 0, t14, t15;
        Word t6;
        final Env env2 = env1.parent();
        final Env env0 = new Env(new EnvRecord(FORMAT_9), env1);
        final EnvRecord lvl0 = env0.level();
        final EnvRecord lvl2 = env2.level();
        t0 = new Word[11];
        t1 = new Word[11];
        t2 = new Word[11];
        t6 = ccall_WxW(Clos.fromValue(Globals.getGlobal("domainMakeDispatch")), p0_domain);
        lvl0.setField(10, "", Value.U.fromSInt(p1_hashcode.toSInt()));
        lvl0.setField(9, "tuple", new Clos(env0, C3_tuple));
        lvl0.setField(8, "=", new Clos(env0, C4__EQ_));
        lvl0.setField(7, "~=", new Clos(env0, C5__TILDE__EQ_));
        lvl0.setField(5, "<<", new Clos(env0, C6__LT__LT_));
        lvl0.setField(4, "length", new Clos(env0, C7_length));
        lvl0.setField(3, "element", new Clos(env0, C8_element));
        lvl0.setField(2, "dispose!", new Clos(env0, C9_dispose_BANG_));
        lvl0.setField(1, "hash", new Clos(env0, C10_hash));
        lvl0.setField(6, "<<", new Clos(env0, C11__LT__LT_));
        lvl0.setField(0, "case", new Clos(env0, C13_case));
        t7 = Math.hashCombine(lvl0.getField(10, "").toSInt(), 453890011);
        t14 = Math.hashCombine(lvl0.getField(10, "").toSInt(), 51489085);
        t8 = Math.hashCombine(740244383, Math.hashCombine(32236, Math.hashCombine(lvl0.getField(10, "").toSInt(), t14)));
        t9 = Math.hashCombine(182752316, Math.hashCombine(32236, Math.hashCombine(lvl0.getField(10, "").toSInt(), 102896482)));
        t15 = Math.hashCombine(32236, t14);
        t10 = Math.hashCombine(33717313, t15);
        t11 = Math.hashCombine(195553216, Math.hashCombine(32236, Math.hashCombine(33717313, t14)));
        t12 = Math.hashCombine(755420535, t15);
        t13 = lvl0.getField(10, "").toSInt();
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(11));
        t3.setField(1, "nsize", Value.U.fromSInt(11));
        t3.setField(2, "values", (Value)Word.U.fromArray(t0));
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(11));
        t4.setField(1, "nsize", Value.U.fromSInt(11));
        t4.setField(2, "values", (Value)Word.U.fromArray(t1));
        t5 = new Record(FORMAT_5);
        t5.setField(0, "size", Value.U.fromSInt(11));
        t5.setField(1, "nsize", Value.U.fromSInt(11));
        t5.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWRRR(Clos.fromValue(Globals.getGlobal("domainAddExports!")), p0_domain, t3, t4, t5);
        ccall_WxWWW(Clos.fromValue(Globals.getGlobal("domainAddDefaults!")), p0_domain, Word.U.fromValue(lvl2.getField(0, "BasicType")), t6);
        t0[0] = Word.U.fromSInt(609528375);
        t1[0] = Word.U.fromSInt(t7);
        t2[0] = Word.U.fromClos(Clos.fromValue(lvl0.getField(9, "tuple")));
        t0[1] = Word.U.fromSInt(200102);
        t1[1] = Word.U.fromSInt(t8);
        t2[1] = Word.U.fromClos(Clos.fromValue(lvl0.getField(8, "=")));
        t0[2] = Word.U.fromSInt(51509389);
        t1[2] = Word.U.fromSInt(t8);
        t2[2] = Word.U.fromClos(Clos.fromValue(lvl0.getField(7, "~=")));
        t0[3] = Word.U.fromSInt(51492426);
        t1[3] = Word.U.fromSInt(t9);
        t2[3] = Word.U.fromClos(Clos.fromValue(lvl0.getField(5, "<<")));
        t0[4] = Word.U.fromSInt(437828088);
        t1[4] = Word.U.fromSInt(t10);
        t2[4] = Word.U.fromClos(Clos.fromValue(lvl0.getField(4, "length")));
        t0[5] = Word.U.fromSInt(379591369);
        t1[5] = Word.U.fromSInt(t11);
        t2[5] = Word.U.fromClos(Clos.fromValue(lvl0.getField(3, "element")));
        t0[6] = Word.U.fromSInt(614579040);
        t1[6] = Word.U.fromSInt(t15);
        t2[6] = Word.U.fromClos(Clos.fromValue(lvl0.getField(2, "dispose!")));
        t0[7] = Word.U.fromSInt(746853960);
        t1[7] = Word.U.fromSInt(t10);
        t2[7] = Word.U.fromClos(Clos.fromValue(lvl0.getField(1, "hash")));
        t0[8] = Word.U.fromSInt(51492426);
        t1[8] = Word.U.fromSInt(t12);
        t2[8] = Word.U.fromClos(Clos.fromValue(lvl0.getField(6, "<<")));
        t0[9] = Word.U.fromSInt(864625472);
        t1[9] = Word.U.fromSInt(t8);
        t2[9] = Word.U.fromClos(Clos.fromValue(lvl0.getField(0, "case")));
        t0[10] = Word.U.fromSInt(255806968);
        t1[10] = Word.U.fromSInt(t13);
        t2[10] = null;
        return p0_domain;
    }
    
    private Fn C3_tuple = new Fn("C3_tuple") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c3_tuple(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c3_tuple(Env env1, Word p0_t) {
        return p0_t;
    }
    
    private Fn C4__EQ_ = new Fn("C4__EQ_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c4__EQ_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c4__EQ_(Env env1, Word p0_a, Word p1_b) {
        return Word.U.fromBool(true);
    }
    
    private Fn C5__TILDE__EQ_ = new Fn("C5__TILDE__EQ_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c5__TILDE__EQ_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c5__TILDE__EQ_(Env env1, Word p0_a, Word p1_b) {
        return Word.U.fromBool(false);
    }
    
    private Fn C6__LT__LT_ = new Fn("C6__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c6__LT__LT_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c6__LT__LT_(Env env1, Word p0_p, Word p1_t) {
        int t19, t20_a, t21_high;
        Word t18;
        Clos t0 = null, t1 = null, t2 = null, t3 = null, t4 = null, t5 = null, t6 = null, t7 = null, t8 = null, t9 = null, t10 = null, t11 = null, t12 = null, t13 = null, t14 = null, t15 = null, t16 = null, t17 = null;
        MultiRecord var1 = ccall_CCCx((Clos)p0_p);
        t6 = Clos.fromValue(var1.getField(0, ""));
        t7 = Clos.fromValue(var1.getField(1, ""));
        t8 = Clos.fromValue(var1.getField(2, ""));
        ccall_WxWWW(t7, Word.U.fromArray("(tuple: \0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
        t19 = ((Record)p1_t).getField(0, "size").toSInt();
        t18 = Foam.formatSInt(t19);
        MultiRecord var3 = ccall_CCCx((Clos)p0_p);
        t15 = Clos.fromValue(var3.getField(0, ""));
        t16 = Clos.fromValue(var3.getField(1, ""));
        t17 = Clos.fromValue(var3.getField(2, ""));
        ccall_WxWWW(t16, t18, Word.U.fromSInt(1), Word.U.fromSInt(0));
        MultiRecord var5 = ccall_CCCx((Clos)p0_p);
        t9 = Clos.fromValue(var5.getField(0, ""));
        t10 = Clos.fromValue(var5.getField(1, ""));
        t11 = Clos.fromValue(var5.getField(2, ""));
        ccall_WxWWW(t10, Word.U.fromArray(" \0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
        t21_high = ((Record)p1_t).getField(0, "size").toSInt();
        t20_a = 1;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            case 0: 
            if (t20_a <= t21_high) {target = 1; continue;}
            MultiRecord var7 = ccall_CCCx((Clos)p0_p);
            t12 = Clos.fromValue(var7.getField(0, ""));
            t13 = Clos.fromValue(var7.getField(1, ""));
            t14 = Clos.fromValue(var7.getField(2, ""));
            ccall_WxWWW(t13, Word.U.fromArray(")\0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
            return p0_p;
            case 1: 
            MultiRecord var9 = ccall_CCCx((Clos)p0_p);
            t3 = Clos.fromValue(var9.getField(0, ""));
            t4 = Clos.fromValue(var9.getField(1, ""));
            t5 = Clos.fromValue(var9.getField(2, ""));
            ccall_WxWWW(t4, Word.U.fromArray("??\0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
            MultiRecord var11 = ccall_CCCx((Clos)p0_p);
            t0 = Clos.fromValue(var11.getField(0, ""));
            t1 = Clos.fromValue(var11.getField(1, ""));
            t2 = Clos.fromValue(var11.getField(2, ""));
            ccall_WxWWW(t1, Word.U.fromArray(" \0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
            t20_a = t20_a + 1;
            target = 0;
            continue;}
        }
    }
    
    private Fn C7_length = new Fn("C7_length") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c7_length(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c7_length(Env env1, Word p0_x) {
        return Word.U.fromSInt(((Record)p0_x).getField(0, "size").toSInt());
    }
    
    private Fn C8_element = new Fn("C8_element") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c8_element(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c8_element(Env env1, Word p0_x, Word p1_n) {
        return ((Word [])((Record)p0_x).getField(1, "values").toArray())[p1_n.toSInt() - 1];
    }
    
    private Fn C9_dispose_BANG_ = new Fn("C9_dispose_BANG_") { 
        public Value ocall(Env env, Value ... vals) {
            c9_dispose_BANG_(env, Word.U.fromValue(vals[0]));
            return null;
        }

    };
    private void c9_dispose_BANG_(Env env1, Word p0_x) {
        return;
    }
    
    private Fn C10_hash = new Fn("C10_hash") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c10_hash(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c10_hash(Env env1, Word p0_x) {
        int t0_elem = 0, t1_result, t2_a, t3_high;
        t1_result = ((Record)p0_x).getField(0, "size").toSInt();
        t3_high = ((Record)p0_x).getField(0, "size").toSInt();
        t2_a = 1;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            case 0: 
            if (t2_a <= t3_high) {target = 1; continue;}
            return Word.U.fromSInt(t1_result);
            case 1: 
            t0_elem = ((Word [])((Record)p0_x).getField(1, "values").toArray())[t2_a - 1].toSInt();
            t1_result = t1_result ^ t0_elem;
            t2_a = t2_a + 1;
            target = 0;
            continue;}
        }
    }
    
    private Fn C11__LT__LT_ = new Fn("C11__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c11__LT__LT_(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c11__LT__LT_(Env env1, Word p0_x) {
        final Env env0 = new Env(new EnvRecord(FORMAT_8), env1);
        final EnvRecord lvl0 = env0.level();
        lvl0.setField(0, "x", (Value)p0_x);
        return new Clos(env0, C12__LT__LT_);
    }
    
    private Fn C12__LT__LT_ = new Fn("C12__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c12__LT__LT_(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c12__LT__LT_(Env env1, Word p0_p) {
        int t19, t21_a, t22_high;
        Word t18, t20;
        Clos t0 = null, t1 = null, t2 = null, t3 = null, t4 = null, t5 = null, t6 = null, t7 = null, t8 = null, t9 = null, t10 = null, t11 = null, t12 = null, t13 = null, t14 = null, t15 = null, t16 = null, t17 = null;
        final EnvRecord lvl1 = env1.level();
        t20 = Word.U.fromValue(lvl1.getField(0, "x"));
        MultiRecord var1 = ccall_CCCx((Clos)p0_p);
        t6 = Clos.fromValue(var1.getField(0, ""));
        t7 = Clos.fromValue(var1.getField(1, ""));
        t8 = Clos.fromValue(var1.getField(2, ""));
        ccall_WxWWW(t7, Word.U.fromArray("(tuple: \0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
        t19 = ((Record)t20).getField(0, "size").toSInt();
        t18 = Foam.formatSInt(t19);
        MultiRecord var3 = ccall_CCCx((Clos)p0_p);
        t15 = Clos.fromValue(var3.getField(0, ""));
        t16 = Clos.fromValue(var3.getField(1, ""));
        t17 = Clos.fromValue(var3.getField(2, ""));
        ccall_WxWWW(t16, t18, Word.U.fromSInt(1), Word.U.fromSInt(0));
        MultiRecord var5 = ccall_CCCx((Clos)p0_p);
        t9 = Clos.fromValue(var5.getField(0, ""));
        t10 = Clos.fromValue(var5.getField(1, ""));
        t11 = Clos.fromValue(var5.getField(2, ""));
        ccall_WxWWW(t10, Word.U.fromArray(" \0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
        t22_high = ((Record)t20).getField(0, "size").toSInt();
        t21_a = 1;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            case 0: 
            if (t21_a <= t22_high) {target = 1; continue;}
            MultiRecord var7 = ccall_CCCx((Clos)p0_p);
            t12 = Clos.fromValue(var7.getField(0, ""));
            t13 = Clos.fromValue(var7.getField(1, ""));
            t14 = Clos.fromValue(var7.getField(2, ""));
            ccall_WxWWW(t13, Word.U.fromArray(")\0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
            return p0_p;
            case 1: 
            MultiRecord var9 = ccall_CCCx((Clos)p0_p);
            t3 = Clos.fromValue(var9.getField(0, ""));
            t4 = Clos.fromValue(var9.getField(1, ""));
            t5 = Clos.fromValue(var9.getField(2, ""));
            ccall_WxWWW(t4, Word.U.fromArray("??\0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
            MultiRecord var11 = ccall_CCCx((Clos)p0_p);
            t0 = Clos.fromValue(var11.getField(0, ""));
            t1 = Clos.fromValue(var11.getField(1, ""));
            t2 = Clos.fromValue(var11.getField(2, ""));
            ccall_WxWWW(t1, Word.U.fromArray(" \0".toCharArray()), Word.U.fromSInt(1), Word.U.fromSInt(0));
            t21_a = t21_a + 1;
            target = 0;
            continue;}
        }
    }
    
    private Fn C13_case = new Fn("C13_case") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c13_case(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c13_case(Env env1, Word p0_x, Word p1_y) {
        return Word.U.fromBool(true);
    }
    
    private Fn C14_foamcat_MINUS_init = new Fn("C14_foamcat_MINUS_init") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c14_foamcat_MINUS_init(env, vals[0].toSInt());
            return (Value)ret;
        }

    };
    private Word c14_foamcat_MINUS_init(Env env1, int p0_idx) {
        final EnvRecord lvl1 = env1.level();
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (lvl1.getField(1, "").toBool()) {target = 0; continue;}
            lvl1.setField(1, "", Value.U.fromBool(true));
            ccall_Xx(foamcat_init);
            case 0: 
            return Word.U.fromValue(Globals.getGlobal("foamcat_BasicType_906312337"));}
        }
    }
    
    private static MultiRecord ccall_CCCx(Clos _0) {
        Value result = _0.call();
        return result.toMulti();
    }
    
    private static Word ccall_WxW(Clos _0, Word _1) {
        Value result = _0.call((Value)_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWRRR(Clos _0, Word _1, Record _2, Record _3, Record _4) {
        _0.call((Value)_1, _2, _3, _4);
        return;
    }
    
    private static Word ccall_WxWWW(Clos _0, Word _1, Word _2, Word _3) {
        Value result = _0.call((Value)_1, (Value)_2, (Value)_3);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxA(Clos _0, char [] _1) {
        Value result = _0.call(Value.U.fromArray(_1));
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWW(Clos _0, Word _1, Word _2) {
        Value result = _0.call((Value)_1, (Value)_2);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWI(Clos _0, Word _1, int _2) {
        Value result = _0.call((Value)_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }
    
    private static void ccall_Xx(Clos _0) {
        _0.call();
        return;
    }
    
    private static Word ccall_WxC(Clos _0, Clos _1) {
        Value result = _0.call(_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWW(Clos _0, Word _1, Word _2) {
        _0.call((Value)_1, (Value)_2);
        return;
    }
    
    private static Word ccall_WxCI(Clos _0, Clos _1, int _2) {
        Value result = _0.call(_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }

}
