//
// Java generated by aldor from file catdispatchvector.ao
//
package aldorcode;
import foamj.FoamContext;
import foamj.EnvRecord;
import foamj.Record;
import foamj.FoamClass;
import foamj.Format;
import foamj.Math;
import foamj.Word;
import foamj.Value;
import foamj.Env;
import foamj.Clos;
import foamj.Fn;
import foamj.Globals;
/**
 * Generated by genjava - catdispatchvector
 */

public class catdispatchvector implements FoamClass {
    private static Format FORMAT_0 = new Format(15);
    private static Format FORMAT_5 = new Format(3);
    private static Format FORMAT_6 = new Format(8);
    private static Format FORMAT_7 = new Format(0);
    private static Format FORMAT_8 = new Format(16);
    private static Format FORMAT_10 = new Format(2);
    private Clos catdispatchvector_init;
    private Clos runtime_init;
    private Clos foamcat_init;
    private FoamContext ctxt;
    public catdispatchvector(FoamContext ctxt) {
        this.ctxt = ctxt;
        catdispatchvector_init = new Clos(null, C0_catdispatchvector);
        runtime_init = ctxt.createLoadFn("runtime");
        foamcat_init = ctxt.createLoadFn("foamcat");
    }
    
    public void run() {
        catdispatchvector_init.getProg().ocall(catdispatchvector_init.getEnv());
    }
    
    private Fn C0_catdispatchvector = new Fn("C0_catdispatchvector") { 
        public Value ocall(Env env, Value ... vals) {
            c0_catdispatchvector(env);
            return null;
        }

    };
    private void c0_catdispatchvector(Env env1) {
        Word [] t1, t2;
        Record t3, t4;
        Clos t0 = null;
        final Env env0 = new Env(new EnvRecord(FORMAT_10), env1);
        final EnvRecord lvl0 = env0.level();
        ccall_Xx(runtime_init);
        Globals.setGlobal("catdispatchvector", Clos.fromValue(Globals.getGlobal("noOperation")));
        t0 = new Clos(env0, C19_foamcat_MINUS_init);
        Globals.setGlobal("catdispatchvector_CatDispatchVector_538644671", (Value)ccall_WxC(Clos.fromValue(Globals.getGlobal("domainMake")), new Clos(env0, C1_addLevel0)));
        lvl0.setField(1, "", Value.U.fromBool(false));
        t1 = new Word[15];
        t2 = new Word[15];
        t1[0] = Word.U.fromSInt(200102);
        t2[0] = Word.U.fromArray("=\0".toCharArray());
        t1[1] = Word.U.fromSInt(981411809);
        t2[1] = Word.U.fromArray("parentGetter\0".toCharArray());
        t1[2] = Word.U.fromSInt(51509389);
        t2[2] = Word.U.fromArray("~=\0".toCharArray());
        t1[3] = Word.U.fromSInt(8616224);
        t2[3] = Word.U.fromArray("namer\0".toCharArray());
        t1[4] = Word.U.fromSInt(1039960049);
        t2[4] = Word.U.fromArray("hasher\0".toCharArray());
        t1[5] = Word.U.fromSInt(720263169);
        t2[5] = Word.U.fromArray("getter\0".toCharArray());
        t1[6] = Word.U.fromSInt(255806968);
        t2[6] = Word.U.fromArray("sample\0".toCharArray());
        t1[7] = Word.U.fromSInt(864625472);
        t2[7] = Word.U.fromArray("case\0".toCharArray());
        t1[8] = Word.U.fromSInt(5509732);
        t2[8] = Word.U.fromArray("test\0".toCharArray());
        t1[9] = Word.U.fromSInt(880992424);
        t2[9] = Word.U.fromArray("reserved\0".toCharArray());
        t1[10] = Word.U.fromSInt(318528389);
        t2[10] = Word.U.fromArray("new\0".toCharArray());
        t1[11] = Word.U.fromSInt(746853960);
        t2[11] = Word.U.fromArray("hash\0".toCharArray());
        t1[12] = Word.U.fromSInt(51492426);
        t2[12] = Word.U.fromArray("<<\0".toCharArray());
        t1[13] = Word.U.fromSInt(1050144703);
        t2[13] = Word.U.fromArray("parentCounter\0".toCharArray());
        t1[14] = Word.U.fromSInt(765940678);
        t2[14] = Word.U.fromArray("builder\0".toCharArray());
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(15));
        t3.setField(1, "nsize", Value.U.fromSInt(15));
        t3.setField(2, "values", (Value)Word.U.fromArray(t1));
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(15));
        t4.setField(1, "nsize", Value.U.fromSInt(15));
        t4.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWW(Clos.fromValue(Globals.getGlobal("rtAddStrings")), Word.U.fromRec(t3), Word.U.fromRec(t4));
        lvl0.setField(0, "Conditional", (Value)ccall_WxCI(Clos.fromValue(Globals.getGlobal("rtLazyCatFrInit")), t0, 0));
        return;
    }
    
    private Fn C1_addLevel0 = new Fn("C1_addLevel0") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c1_addLevel0(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c1_addLevel0(Env env1, Word p0_domain) {
        final Env env0 = new Env(null, env1);
        ccall_WxWW(Clos.fromValue(Globals.getGlobal("domainAddNameFn!")), p0_domain, ccall_WxA(Clos.fromValue(Globals.getGlobal("rtConstNameFn")), "CatDispatchVector\0".toCharArray()));
        ccall_WxWI(Clos.fromValue(Globals.getGlobal("domainAddHash!")), p0_domain, 858894004);
        return new Clos(env0, C2_addLevel1);
    }
    
    private Fn C2_addLevel1 = new Fn("C2_addLevel1") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c2_addLevel1(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c2_addLevel1(Env env1, Word p0_domain, Word p1_hashcode) {
        Word [] t0, t1, t2;
        Record t3, t4, t5;
        Word t6;
        int t7 = 0, t8 = 0, t9 = 0, t10 = 0, t11 = 0, t12 = 0, t13 = 0, t14 = 0, t15 = 0, t16 = 0, t17 = 0, t18 = 0, t19 = 0, t20, t21;
        final Env env2 = env1.parent();
        final Env env0 = new Env(new EnvRecord(FORMAT_8), env1);
        final EnvRecord lvl0 = env0.level();
        final EnvRecord lvl2 = env2.level();
        t0 = new Word[16];
        t1 = new Word[16];
        t2 = new Word[16];
        t6 = ccall_WxW(Clos.fromValue(Globals.getGlobal("domainMakeDispatch")), p0_domain);
        lvl0.setField(15, "", Value.U.fromSInt(p1_hashcode.toSInt()));
        lvl0.setField(14, "new", new Clos(env0, C3_new));
        lvl0.setField(13, "builder", new Clos(env0, C4_builder));
        lvl0.setField(12, "reserved", new Clos(env0, C5_reserved));
        lvl0.setField(11, "getter", new Clos(env0, C6_getter));
        lvl0.setField(10, "hasher", new Clos(env0, C7_hasher));
        lvl0.setField(9, "parentCounter", new Clos(env0, C8_parentCounter));
        lvl0.setField(8, "parentGetter", new Clos(env0, C9_parentGetter));
        lvl0.setField(7, "namer", new Clos(env0, C10_namer));
        lvl0.setField(6, "=", new Clos(env0, C11__EQ_));
        lvl0.setField(4, "<<", new Clos(env0, C12__LT__LT_));
        lvl0.setField(3, "test", new Clos(env0, C13_test));
        lvl0.setField(2, "~=", new Clos(env0, C14__TILDE__EQ_));
        lvl0.setField(5, "<<", new Clos(env0, C15__LT__LT_));
        lvl0.setField(1, "hash", new Clos(env0, C17_hash));
        lvl0.setField(0, "case", new Clos(env0, C18_case));
        t7 = Math.hashCombine(lvl0.getField(15, "").toSInt(), 365660354);
        t20 = Math.hashCombine(lvl0.getField(15, "").toSInt(), 51489085);
        t21 = Math.hashCombine(32236, t20);
        t8 = Math.hashCombine(988179034, t21);
        t9 = Math.hashCombine(195553216, t21);
        t10 = Math.hashCombine(381112449, t21);
        t11 = Math.hashCombine(134599461, t21);
        t12 = Math.hashCombine(652410077, t21);
        t13 = Math.hashCombine(927933311, t21);
        t14 = Math.hashCombine(740244383, Math.hashCombine(32236, Math.hashCombine(lvl0.getField(15, "").toSInt(), t20)));
        t15 = Math.hashCombine(182752316, Math.hashCombine(32236, Math.hashCombine(lvl0.getField(15, "").toSInt(), 102896482)));
        t16 = Math.hashCombine(740244383, t21);
        t17 = Math.hashCombine(755420535, t21);
        t18 = Math.hashCombine(33717313, t21);
        t19 = lvl0.getField(15, "").toSInt();
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(16));
        t3.setField(1, "nsize", Value.U.fromSInt(16));
        t3.setField(2, "values", (Value)Word.U.fromArray(t0));
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(16));
        t4.setField(1, "nsize", Value.U.fromSInt(16));
        t4.setField(2, "values", (Value)Word.U.fromArray(t1));
        t5 = new Record(FORMAT_5);
        t5.setField(0, "size", Value.U.fromSInt(16));
        t5.setField(1, "nsize", Value.U.fromSInt(16));
        t5.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWRRR(Clos.fromValue(Globals.getGlobal("domainAddExports!")), p0_domain, t3, t4, t5);
        ccall_WxWWW(Clos.fromValue(Globals.getGlobal("domainAddDefaults!")), p0_domain, Word.U.fromValue(lvl2.getField(0, "Conditional")), t6);
        t0[0] = Word.U.fromSInt(318528389);
        t1[0] = Word.U.fromSInt(t7);
        t2[0] = Word.U.fromClos(Clos.fromValue(lvl0.getField(14, "new")));
        t0[1] = Word.U.fromSInt(765940678);
        t1[1] = Word.U.fromSInt(t8);
        t2[1] = Word.U.fromClos(Clos.fromValue(lvl0.getField(13, "builder")));
        t0[2] = Word.U.fromSInt(880992424);
        t1[2] = Word.U.fromSInt(t9);
        t2[2] = Word.U.fromClos(Clos.fromValue(lvl0.getField(12, "reserved")));
        t0[3] = Word.U.fromSInt(720263169);
        t1[3] = Word.U.fromSInt(t10);
        t2[3] = Word.U.fromClos(Clos.fromValue(lvl0.getField(11, "getter")));
        t0[4] = Word.U.fromSInt(1039960049);
        t1[4] = Word.U.fromSInt(t11);
        t2[4] = Word.U.fromClos(Clos.fromValue(lvl0.getField(10, "hasher")));
        t0[5] = Word.U.fromSInt(1050144703);
        t1[5] = Word.U.fromSInt(t11);
        t2[5] = Word.U.fromClos(Clos.fromValue(lvl0.getField(9, "parentCounter")));
        t0[6] = Word.U.fromSInt(981411809);
        t1[6] = Word.U.fromSInt(t12);
        t2[6] = Word.U.fromClos(Clos.fromValue(lvl0.getField(8, "parentGetter")));
        t0[7] = Word.U.fromSInt(8616224);
        t1[7] = Word.U.fromSInt(t13);
        t2[7] = Word.U.fromClos(Clos.fromValue(lvl0.getField(7, "namer")));
        t0[8] = Word.U.fromSInt(200102);
        t1[8] = Word.U.fromSInt(t14);
        t2[8] = Word.U.fromClos(Clos.fromValue(lvl0.getField(6, "=")));
        t0[9] = Word.U.fromSInt(51492426);
        t1[9] = Word.U.fromSInt(t15);
        t2[9] = Word.U.fromClos(Clos.fromValue(lvl0.getField(4, "<<")));
        t0[10] = Word.U.fromSInt(5509732);
        t1[10] = Word.U.fromSInt(t16);
        t2[10] = Word.U.fromClos(Clos.fromValue(lvl0.getField(3, "test")));
        t0[11] = Word.U.fromSInt(51509389);
        t1[11] = Word.U.fromSInt(t14);
        t2[11] = Word.U.fromClos(Clos.fromValue(lvl0.getField(2, "~=")));
        t0[12] = Word.U.fromSInt(51492426);
        t1[12] = Word.U.fromSInt(t17);
        t2[12] = Word.U.fromClos(Clos.fromValue(lvl0.getField(5, "<<")));
        t0[13] = Word.U.fromSInt(746853960);
        t1[13] = Word.U.fromSInt(t18);
        t2[13] = Word.U.fromClos(Clos.fromValue(lvl0.getField(1, "hash")));
        t0[14] = Word.U.fromSInt(864625472);
        t1[14] = Word.U.fromSInt(t14);
        t2[14] = Word.U.fromClos(Clos.fromValue(lvl0.getField(0, "case")));
        t0[15] = Word.U.fromSInt(255806968);
        t1[15] = Word.U.fromSInt(t19);
        t2[15] = null;
        return p0_domain;
    }
    
    private Fn C3_new = new Fn("C3_new") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c3_new(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]), Word.U.fromValue(vals[2]), Word.U.fromValue(vals[3]), Word.U.fromValue(vals[4]), Word.U.fromValue(vals[5]));
            return (Value)ret;
        }

    };
    private Word c3_new(Env env1, Word p0_namer, Word p1_builder, Word p2_getter, Word p3_hasher, Word p4_parentCounter, Word p5_parentGetter) {
        Record t0;
        t0 = new Record(FORMAT_6);
        t0.setField(0, "tag", (Value)Word.U.fromSInt(10));
        t0.setField(1, "namer", (Clos)p0_namer);
        t0.setField(2, "noname", (Value)null);
        t0.setField(3, "getter", (Clos)p2_getter);
        t0.setField(4, "hasher", (Clos)p3_hasher);
        t0.setField(5, "builder", (Clos)p1_builder);
        t0.setField(6, "parentCounter", (Clos)p4_parentCounter);
        t0.setField(7, "parentGetter", (Clos)p5_parentGetter);
        return Word.U.fromRec(t0);
    }
    
    private Fn C4_builder = new Fn("C4_builder") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c4_builder(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c4_builder(Env env1, Word p0_cdv) {
        return Clos.fromValue(((Record)p0_cdv).getField(5, "builder"));
    }
    
    private Fn C5_reserved = new Fn("C5_reserved") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c5_reserved(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c5_reserved(Env env1, Word p0_cdv) {
        return Word.U.fromValue(((Record)p0_cdv).getField(2, "noname"));
    }
    
    private Fn C6_getter = new Fn("C6_getter") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c6_getter(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c6_getter(Env env1, Word p0_cdv) {
        return Clos.fromValue(((Record)p0_cdv).getField(3, "getter"));
    }
    
    private Fn C7_hasher = new Fn("C7_hasher") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c7_hasher(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c7_hasher(Env env1, Word p0_cdv) {
        return Clos.fromValue(((Record)p0_cdv).getField(4, "hasher"));
    }
    
    private Fn C8_parentCounter = new Fn("C8_parentCounter") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c8_parentCounter(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c8_parentCounter(Env env1, Word p0_cdv) {
        return Clos.fromValue(((Record)p0_cdv).getField(6, "parentCounter"));
    }
    
    private Fn C9_parentGetter = new Fn("C9_parentGetter") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c9_parentGetter(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c9_parentGetter(Env env1, Word p0_cdv) {
        return Clos.fromValue(((Record)p0_cdv).getField(7, "parentGetter"));
    }
    
    private Fn C10_namer = new Fn("C10_namer") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c10_namer(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c10_namer(Env env1, Word p0_cdv) {
        return Clos.fromValue(((Record)p0_cdv).getField(1, "namer"));
    }
    
    private Fn C11__EQ_ = new Fn("C11__EQ_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c11__EQ_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c11__EQ_(Env env1, Word p0_d1, Word p1_d2) {
        return Word.U.fromBool(Word.U.toPtr(p0_d1) == Word.U.toPtr(p1_d2));
    }
    
    private Fn C12__LT__LT_ = new Fn("C12__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c12__LT__LT_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c12__LT__LT_(Env env1, Word p0_p, Word p1_d) {
        return p0_p;
    }
    
    private Fn C13_test = new Fn("C13_test") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c13_test(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c13_test(Env env1, Word p0_d) {
        return Word.U.fromBool(!(Word.U.toPtr(p0_d) == null));
    }
    
    private Fn C14__TILDE__EQ_ = new Fn("C14__TILDE__EQ_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c14__TILDE__EQ_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c14__TILDE__EQ_(Env env1, Word p0_x, Word p1_y) {
        return Word.U.fromBool(!(Word.U.toPtr(p0_x) == Word.U.toPtr(p1_y)));
    }
    
    private Fn C15__LT__LT_ = new Fn("C15__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c15__LT__LT_(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c15__LT__LT_(Env env1, Word p0_x) {
        final Env env0 = new Env(new EnvRecord(FORMAT_7), env1);
        return new Clos(env0, C16__LT__LT_);
    }
    
    private Fn C16__LT__LT_ = new Fn("C16__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c16__LT__LT_(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c16__LT__LT_(Env env1, Word p0_p) {
        return p0_p;
    }
    
    private Fn C17_hash = new Fn("C17_hash") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c17_hash(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c17_hash(Env env1, Word p0_x) {
        return Word.U.fromSInt(0);
    }
    
    private Fn C18_case = new Fn("C18_case") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c18_case(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c18_case(Env env1, Word p0_x, Word p1_y) {
        return Word.U.fromBool(Word.U.toPtr(p0_x) == Word.U.toPtr(p1_y));
    }
    
    private Fn C19_foamcat_MINUS_init = new Fn("C19_foamcat_MINUS_init") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c19_foamcat_MINUS_init(env, vals[0].toSInt());
            return (Value)ret;
        }

    };
    private Word c19_foamcat_MINUS_init(Env env1, int p0_idx) {
        final EnvRecord lvl1 = env1.level();
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (lvl1.getField(1, "").toBool()) {target = 0; continue;}
            lvl1.setField(1, "", Value.U.fromBool(true));
            ccall_Xx(foamcat_init);
            case 0: 
            return Word.U.fromValue(Globals.getGlobal("foamcat_Conditional_436267619"));}
        }
    }
    
    private static Word ccall_WxW(Clos _0, Word _1) {
        Value result = _0.call((Value)_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWRRR(Clos _0, Word _1, Record _2, Record _3, Record _4) {
        _0.call((Value)_1, _2, _3, _4);
        return;
    }
    
    private static Word ccall_WxWWW(Clos _0, Word _1, Word _2, Word _3) {
        Value result = _0.call((Value)_1, (Value)_2, (Value)_3);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxA(Clos _0, char [] _1) {
        Value result = _0.call(Value.U.fromArray(_1));
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWW(Clos _0, Word _1, Word _2) {
        Value result = _0.call((Value)_1, (Value)_2);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWI(Clos _0, Word _1, int _2) {
        Value result = _0.call((Value)_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }
    
    private static void ccall_Xx(Clos _0) {
        _0.call();
        return;
    }
    
    private static Word ccall_WxC(Clos _0, Clos _1) {
        Value result = _0.call(_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWW(Clos _0, Word _1, Word _2) {
        _0.call((Value)_1, (Value)_2);
        return;
    }
    
    private static Word ccall_WxCI(Clos _0, Clos _1, int _2) {
        Value result = _0.call(_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }

}
