//
// Java generated by aldor from file pointerdomain.ao
//
package aldorcode;
import foamj.FoamContext;
import foamj.EnvRecord;
import foamj.Record;
import foamj.FoamClass;
import foamj.FoamException;
import foamj.Format;
import foamj.Math;
import foamj.Word;
import foamj.Value;
import foamj.Env;
import foamj.Clos;
import foamj.Fn;
import foamj.Globals;
/**
 * Generated by genjava - pointerdomain
 */

public class pointerdomain implements FoamClass {
    private static Format FORMAT_0 = new Format(15);
    private static Format FORMAT_5 = new Format(3);
    private static Format FORMAT_6 = new Format(2);
    private static Format FORMAT_7 = new Format(0);
    private static Format FORMAT_8 = new Format(13);
    private static Format FORMAT_10 = new Format(2);
    private Clos pointerdomain_init;
    private Clos runtime_init;
    private Clos foamcat_init;
    private FoamContext ctxt;
    public pointerdomain(FoamContext ctxt) {
        this.ctxt = ctxt;
        pointerdomain_init = new Clos(null, C0_pointerdomain);
        runtime_init = ctxt.createLoadFn("runtime");
        foamcat_init = ctxt.createLoadFn("foamcat");
    }
    
    public void run() {
        pointerdomain_init.getProg().ocall(pointerdomain_init.getEnv());
    }
    
    private Fn C0_pointerdomain = new Fn("C0_pointerdomain") { 
        public Value ocall(Env env, Value ... vals) {
            c0_pointerdomain(env);
            return null;
        }

    };
    private void c0_pointerdomain(Env env1) {
        Word [] t1, t2;
        Record t3, t4;
        Clos t0 = null;
        final Env env0 = new Env(new EnvRecord(FORMAT_10), env1);
        final EnvRecord lvl0 = env0.level();
        ccall_Xx(runtime_init);
        Globals.setGlobal("pointerdomain", Clos.fromValue(Globals.getGlobal("noOperation")));
        t0 = new Clos(env0, C16_foamcat_MINUS_init);
        Globals.setGlobal("pointerdomain_PointerDomain_1001262071", (Value)ccall_WxC(Clos.fromValue(Globals.getGlobal("domainMake")), new Clos(env0, C1_addLevel0)));
        lvl0.setField(1, "", Value.U.fromBool(false));
        t1 = new Word[12];
        t2 = new Word[12];
        t1[0] = Word.U.fromSInt(200102);
        t2[0] = Word.U.fromArray("=\0".toCharArray());
        t1[1] = Word.U.fromSInt(51509389);
        t2[1] = Word.U.fromArray("~=\0".toCharArray());
        t1[2] = Word.U.fromSInt(318604155);
        t2[2] = Word.U.fromArray("get\0".toCharArray());
        t1[3] = Word.U.fromSInt(783167045);
        t2[3] = Word.U.fromArray("name\0".toCharArray());
        t1[4] = Word.U.fromSInt(255806968);
        t2[4] = Word.U.fromArray("sample\0".toCharArray());
        t1[5] = Word.U.fromSInt(864625472);
        t2[5] = Word.U.fromArray("case\0".toCharArray());
        t1[6] = Word.U.fromSInt(5509732);
        t2[6] = Word.U.fromArray("test\0".toCharArray());
        t1[7] = Word.U.fromSInt(883586323);
        t2[7] = Word.U.fromArray("deref\0".toCharArray());
        t1[8] = Word.U.fromSInt(318528389);
        t2[8] = Word.U.fromArray("new\0".toCharArray());
        t1[9] = Word.U.fromSInt(141765223);
        t2[9] = Word.U.fromArray("inheritTo\0".toCharArray());
        t1[10] = Word.U.fromSInt(51492426);
        t2[10] = Word.U.fromArray("<<\0".toCharArray());
        t1[11] = Word.U.fromSInt(746853960);
        t2[11] = Word.U.fromArray("hash\0".toCharArray());
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(12));
        t3.setField(1, "nsize", Value.U.fromSInt(12));
        t3.setField(2, "values", (Value)Word.U.fromArray(t1));
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(12));
        t4.setField(1, "nsize", Value.U.fromSInt(12));
        t4.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWW(Clos.fromValue(Globals.getGlobal("rtAddStrings")), Word.U.fromRec(t3), Word.U.fromRec(t4));
        lvl0.setField(0, "Conditional", (Value)ccall_WxCI(Clos.fromValue(Globals.getGlobal("rtLazyCatFrInit")), t0, 0));
        return;
    }
    
    private Fn C1_addLevel0 = new Fn("C1_addLevel0") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c1_addLevel0(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c1_addLevel0(Env env1, Word p0_domain) {
        final Env env0 = new Env(null, env1);
        ccall_WxWW(Clos.fromValue(Globals.getGlobal("domainAddNameFn!")), p0_domain, ccall_WxA(Clos.fromValue(Globals.getGlobal("rtConstNameFn")), "PointerDomain\0".toCharArray()));
        ccall_WxWI(Clos.fromValue(Globals.getGlobal("domainAddHash!")), p0_domain, 113730958);
        return new Clos(env0, C2_addLevel1);
    }
    
    private Fn C2_addLevel1 = new Fn("C2_addLevel1") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c2_addLevel1(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c2_addLevel1(Env env1, Word p0_domain, Word p1_hashcode) {
        Word [] t0, t1, t2;
        Record t3, t4, t5;
        int t7 = 0, t8 = 0, t9 = 0, t10 = 0, t11 = 0, t12 = 0, t13 = 0, t14 = 0, t15 = 0, t16 = 0, t17, t18;
        Word t6;
        final Env env2 = env1.parent();
        final Env env0 = new Env(new EnvRecord(FORMAT_8), env1);
        final EnvRecord lvl0 = env0.level();
        final EnvRecord lvl2 = env2.level();
        t0 = new Word[13];
        t1 = new Word[13];
        t2 = new Word[13];
        t6 = ccall_WxW(Clos.fromValue(Globals.getGlobal("domainMakeDispatch")), p0_domain);
        lvl0.setField(12, "", Value.U.fromSInt(p1_hashcode.toSInt()));
        lvl0.setField(11, "new", new Clos(env0, C3_new));
        lvl0.setField(10, "deref", new Clos(env0, C4_deref));
        lvl0.setField(9, "name", new Clos(env0, C5_name));
        lvl0.setField(8, "hash", new Clos(env0, C6_hash));
        lvl0.setField(7, "get", new Clos(env0, C7_get));
        lvl0.setField(6, "inheritTo", new Clos(env0, C8_inheritTo));
        lvl0.setField(5, "=", new Clos(env0, C9__EQ_));
        lvl0.setField(3, "<<", new Clos(env0, C10__LT__LT_));
        lvl0.setField(2, "test", new Clos(env0, C11_test));
        lvl0.setField(1, "~=", new Clos(env0, C12__TILDE__EQ_));
        lvl0.setField(4, "<<", new Clos(env0, C13__LT__LT_));
        lvl0.setField(0, "case", new Clos(env0, C15_case));
        t17 = Math.hashCombine(lvl0.getField(12, "").toSInt(), 51489085);
        t18 = Math.hashCombine(32236, t17);
        t7 = Math.hashCombine(1073128398, t18);
        t8 = Math.hashCombine(411206131, t18);
        t9 = Math.hashCombine(33717313, t18);
        t10 = Math.hashCombine(313017700, Math.hashCombine(32236, Math.hashCombine(740244383, Math.hashCombine(313017700, Math.hashCombine(33717313, Math.hashCombine(33717313, Math.hashCombine(1073128398, t17)))))));
        t11 = Math.hashCombine(1073128398, Math.hashCombine(32236, Math.hashCombine(1073128398, Math.hashCombine(lvl0.getField(12, "").toSInt(), 589220475))));
        t12 = Math.hashCombine(740244383, Math.hashCombine(32236, Math.hashCombine(lvl0.getField(12, "").toSInt(), t17)));
        t13 = Math.hashCombine(182752316, Math.hashCombine(32236, Math.hashCombine(lvl0.getField(12, "").toSInt(), 102896482)));
        t14 = Math.hashCombine(740244383, t18);
        t15 = Math.hashCombine(755420535, t18);
        t16 = lvl0.getField(12, "").toSInt();
        t3 = new Record(FORMAT_5);
        t3.setField(0, "size", Value.U.fromSInt(13));
        t3.setField(1, "nsize", Value.U.fromSInt(13));
        t3.setField(2, "values", (Value)Word.U.fromArray(t0));
        t4 = new Record(FORMAT_5);
        t4.setField(0, "size", Value.U.fromSInt(13));
        t4.setField(1, "nsize", Value.U.fromSInt(13));
        t4.setField(2, "values", (Value)Word.U.fromArray(t1));
        t5 = new Record(FORMAT_5);
        t5.setField(0, "size", Value.U.fromSInt(13));
        t5.setField(1, "nsize", Value.U.fromSInt(13));
        t5.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWRRR(Clos.fromValue(Globals.getGlobal("domainAddExports!")), p0_domain, t3, t4, t5);
        ccall_WxWWW(Clos.fromValue(Globals.getGlobal("domainAddDefaults!")), p0_domain, Word.U.fromValue(lvl2.getField(0, "Conditional")), t6);
        t0[0] = Word.U.fromSInt(318528389);
        t1[0] = Word.U.fromSInt(372312350);
        t2[0] = Word.U.fromClos(Clos.fromValue(lvl0.getField(11, "new")));
        t0[1] = Word.U.fromSInt(883586323);
        t1[1] = Word.U.fromSInt(t7);
        t2[1] = Word.U.fromClos(Clos.fromValue(lvl0.getField(10, "deref")));
        t0[2] = Word.U.fromSInt(783167045);
        t1[2] = Word.U.fromSInt(t8);
        t2[2] = Word.U.fromClos(Clos.fromValue(lvl0.getField(9, "name")));
        t0[3] = Word.U.fromSInt(746853960);
        t1[3] = Word.U.fromSInt(t9);
        t2[3] = Word.U.fromClos(Clos.fromValue(lvl0.getField(8, "hash")));
        t0[4] = Word.U.fromSInt(318604155);
        t1[4] = Word.U.fromSInt(t10);
        t2[4] = Word.U.fromClos(Clos.fromValue(lvl0.getField(7, "get")));
        t0[5] = Word.U.fromSInt(141765223);
        t1[5] = Word.U.fromSInt(t11);
        t2[5] = Word.U.fromClos(Clos.fromValue(lvl0.getField(6, "inheritTo")));
        t0[6] = Word.U.fromSInt(200102);
        t1[6] = Word.U.fromSInt(t12);
        t2[6] = Word.U.fromClos(Clos.fromValue(lvl0.getField(5, "=")));
        t0[7] = Word.U.fromSInt(51492426);
        t1[7] = Word.U.fromSInt(t13);
        t2[7] = Word.U.fromClos(Clos.fromValue(lvl0.getField(3, "<<")));
        t0[8] = Word.U.fromSInt(5509732);
        t1[8] = Word.U.fromSInt(t14);
        t2[8] = Word.U.fromClos(Clos.fromValue(lvl0.getField(2, "test")));
        t0[9] = Word.U.fromSInt(51509389);
        t1[9] = Word.U.fromSInt(t12);
        t2[9] = Word.U.fromClos(Clos.fromValue(lvl0.getField(1, "~=")));
        t0[10] = Word.U.fromSInt(51492426);
        t1[10] = Word.U.fromSInt(t15);
        t2[10] = Word.U.fromClos(Clos.fromValue(lvl0.getField(4, "<<")));
        t0[11] = Word.U.fromSInt(864625472);
        t1[11] = Word.U.fromSInt(t12);
        t2[11] = Word.U.fromClos(Clos.fromValue(lvl0.getField(0, "case")));
        t0[12] = Word.U.fromSInt(255806968);
        t1[12] = Word.U.fromSInt(t16);
        t2[12] = null;
        return p0_domain;
    }
    
    private Fn C3_new = new Fn("C3_new") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c3_new(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c3_new(Env env1, Word p0_fn) {
        Record t0;
        t0 = new Record(FORMAT_6);
        t0.setField(0, "tag", Value.U.fromSInt(0));
        t0.setField(1, "value", (Value)p0_fn);
        return Word.U.fromRec(t0);
    }
    
    private Fn C4_deref = new Fn("C4_deref") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c4_deref(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c4_deref(Env env1, Word p0_d) {
        Word t0_nd = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 1) {target = 4; continue;}
            throw new FoamException(103);
            case 4: 
            return Word.U.fromValue(((Record)p0_d).getField(1, "value"));
            case 0: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            t0_nd = ccall_Wx((Clos)Word.U.fromValue(((Record)p0_d).getField(1, "value")));
            if (Word.U.toPtr(t0_nd) == null) {target = 3; continue;}
            ((Record)p0_d).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_d).setField(1, "value", (Value)t0_nd);
            target = 1;
            continue;
            case 3: 
            throw new FoamException(102);}
        }
    }
    
    private Fn C5_name = new Fn("C5_name") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c5_name(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c5_name(Env env1, Word p0_d) {
        Record t2 = null;
        Word t1 = null, t3 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 1) {target = 4; continue;}
            throw new FoamException(103);
            case 4: 
            t2 = (Record)Word.U.fromValue(((Record)p0_d).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "dispatcher"));
            t0 = Clos.fromValue(((Record)t1).getField(1, "namer"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "domainRep")));
            case 0: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            t3 = ccall_Wx((Clos)Word.U.fromValue(((Record)p0_d).getField(1, "value")));
            if (Word.U.toPtr(t3) == null) {target = 3; continue;}
            ((Record)p0_d).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_d).setField(1, "value", (Value)t3);
            target = 1;
            continue;
            case 3: 
            throw new FoamException(102);}
        }
    }
    
    private Fn C6_hash = new Fn("C6_hash") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c6_hash(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c6_hash(Env env1, Word p0_d) {
        Record t2 = null;
        Word t1 = null, t3 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 1) {target = 4; continue;}
            throw new FoamException(103);
            case 4: 
            t2 = (Record)Word.U.fromValue(((Record)p0_d).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "dispatcher"));
            t0 = Clos.fromValue(((Record)t1).getField(4, "hasher"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "domainRep")));
            case 0: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            t3 = ccall_Wx((Clos)Word.U.fromValue(((Record)p0_d).getField(1, "value")));
            if (Word.U.toPtr(t3) == null) {target = 3; continue;}
            ((Record)p0_d).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_d).setField(1, "value", (Value)t3);
            target = 1;
            continue;
            case 3: 
            throw new FoamException(102);}
        }
    }
    
    private Fn C7_get = new Fn("C7_get") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c7_get(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]), Word.U.fromValue(vals[2]), Word.U.fromValue(vals[3]), Word.U.fromValue(vals[4]), Word.U.fromValue(vals[5]));
            return (Value)ret;
        }

    };
    private Word c7_get(Env env1, Word p0_d, Word p1_pc, Word p2_n1, Word p3_n2, Word p4_box, Word p5_skip) {
        Record t2 = null;
        Word t1 = null, t3 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 1) {target = 4; continue;}
            throw new FoamException(103);
            case 4: 
            t2 = (Record)Word.U.fromValue(((Record)p0_d).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "dispatcher"));
            t0 = Clos.fromValue(((Record)t1).getField(3, "getter"));
            return ccall_WxWWWWWW(t0, Word.U.fromValue(t2.getField(1, "domainRep")), p1_pc, p2_n1, p3_n2, p4_box, p5_skip);
            case 0: 
            if (((Record)p0_d).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            t3 = ccall_Wx((Clos)Word.U.fromValue(((Record)p0_d).getField(1, "value")));
            if (Word.U.toPtr(t3) == null) {target = 3; continue;}
            ((Record)p0_d).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_d).setField(1, "value", (Value)t3);
            target = 1;
            continue;
            case 3: 
            throw new FoamException(102);}
        }
    }
    
    private Fn C8_inheritTo = new Fn("C8_inheritTo") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c8_inheritTo(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]), Word.U.fromValue(vals[2]));
            return (Value)ret;
        }

    };
    private Word c8_inheritTo(Env env1, Word p0_fn, Word p1_d, Word p2_d2) {
        Record t3 = null;
        Word t0 = null, t2 = null, t4 = null;
        Clos t1 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p1_d).getField(0, "tag").toSInt() == 1) {target = 0; continue;}
            if (((Record)p1_d).getField(0, "tag").toSInt() == 0) {target = 3; continue;}
            case 4: 
            if (((Record)p1_d).getField(0, "tag").toSInt() == 1) {target = 7; continue;}
            throw new FoamException(103);
            case 7: 
            t0 = ccall_WxWW((Clos)p0_fn, Word.U.fromValue(((Record)p1_d).getField(1, "value")), p2_d2);
            case 1: 
            return t0;
            case 3: 
            if (((Record)p1_d).getField(0, "tag").toSInt() == 0) {target = 5; continue;}
            throw new FoamException(103);
            case 5: 
            t4 = ccall_Wx((Clos)Word.U.fromValue(((Record)p1_d).getField(1, "value")));
            if (Word.U.toPtr(t4) == null) {target = 6; continue;}
            ((Record)p1_d).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p1_d).setField(1, "value", (Value)t4);
            target = 4;
            continue;
            case 6: 
            throw new FoamException(102);
            case 0: 
            if (((Record)p1_d).getField(0, "tag").toSInt() == 1) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            t3 = (Record)Word.U.fromValue(((Record)p1_d).getField(1, "value"));
            t2 = Word.U.fromValue(t3.getField(0, "dispatcher"));
            t1 = Clos.fromValue(((Record)t2).getField(5, "inheriter"));
            t0 = ccall_WxWW(t1, Word.U.fromValue(t3.getField(1, "domainRep")), p2_d2);
            target = 1;
            continue;}
        }
    }
    
    private Fn C9__EQ_ = new Fn("C9__EQ_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c9__EQ_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c9__EQ_(Env env1, Word p0_d1, Word p1_d2) {
        return Word.U.fromBool(Word.U.toPtr(p0_d1) == Word.U.toPtr(p1_d2));
    }
    
    private Fn C10__LT__LT_ = new Fn("C10__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c10__LT__LT_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c10__LT__LT_(Env env1, Word p0_p, Word p1_d) {
        return p0_p;
    }
    
    private Fn C11_test = new Fn("C11_test") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c11_test(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c11_test(Env env1, Word p0_d) {
        return Word.U.fromBool(!(Word.U.toPtr(p0_d) == null));
    }
    
    private Fn C12__TILDE__EQ_ = new Fn("C12__TILDE__EQ_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c12__TILDE__EQ_(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c12__TILDE__EQ_(Env env1, Word p0_x, Word p1_y) {
        return Word.U.fromBool(!(Word.U.toPtr(p0_x) == Word.U.toPtr(p1_y)));
    }
    
    private Fn C13__LT__LT_ = new Fn("C13__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c13__LT__LT_(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c13__LT__LT_(Env env1, Word p0_x) {
        final Env env0 = new Env(new EnvRecord(FORMAT_7), env1);
        return new Clos(env0, C14__LT__LT_);
    }
    
    private Fn C14__LT__LT_ = new Fn("C14__LT__LT_") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c14__LT__LT_(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c14__LT__LT_(Env env1, Word p0_p) {
        return p0_p;
    }
    
    private Fn C15_case = new Fn("C15_case") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c15_case(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c15_case(Env env1, Word p0_x, Word p1_y) {
        return Word.U.fromBool(Word.U.toPtr(p0_x) == Word.U.toPtr(p1_y));
    }
    
    private Fn C16_foamcat_MINUS_init = new Fn("C16_foamcat_MINUS_init") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c16_foamcat_MINUS_init(env, vals[0].toSInt());
            return (Value)ret;
        }

    };
    private Word c16_foamcat_MINUS_init(Env env1, int p0_idx) {
        final EnvRecord lvl1 = env1.level();
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (lvl1.getField(1, "").toBool()) {target = 0; continue;}
            lvl1.setField(1, "", Value.U.fromBool(true));
            ccall_Xx(foamcat_init);
            case 0: 
            return Word.U.fromValue(Globals.getGlobal("foamcat_Conditional_436267619"));}
        }
    }
    
    private static Word ccall_WxWWWWWW(Clos _0, Word _1, Word _2, Word _3, Word _4, Word _5, Word _6) {
        Value result = _0.call((Value)_1, (Value)_2, (Value)_3, (Value)_4, (Value)_5, (Value)_6);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_Wx(Clos _0) {
        Value result = _0.call();
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxW(Clos _0, Word _1) {
        Value result = _0.call((Value)_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWRRR(Clos _0, Word _1, Record _2, Record _3, Record _4) {
        _0.call((Value)_1, _2, _3, _4);
        return;
    }
    
    private static Word ccall_WxWWW(Clos _0, Word _1, Word _2, Word _3) {
        Value result = _0.call((Value)_1, (Value)_2, (Value)_3);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxA(Clos _0, char [] _1) {
        Value result = _0.call(Value.U.fromArray(_1));
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWW(Clos _0, Word _1, Word _2) {
        Value result = _0.call((Value)_1, (Value)_2);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWI(Clos _0, Word _1, int _2) {
        Value result = _0.call((Value)_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }
    
    private static void ccall_Xx(Clos _0) {
        _0.call();
        return;
    }
    
    private static Word ccall_WxC(Clos _0, Clos _1) {
        Value result = _0.call(_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWW(Clos _0, Word _1, Word _2) {
        _0.call((Value)_1, (Value)_2);
        return;
    }
    
    private static Word ccall_WxCI(Clos _0, Clos _1, int _2) {
        Value result = _0.call(_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }

}
