//
// Java generated by aldor from file ptrcatobj.ao
//
package aldorcode;
import foamj.FoamContext;
import foamj.EnvRecord;
import foamj.Record;
import foamj.FoamClass;
import foamj.FoamException;
import foamj.Format;
import foamj.Math;
import foamj.Word;
import foamj.Value;
import foamj.Env;
import foamj.Clos;
import foamj.Globals;
import foamj.Fn;
/**
 * Generated by genjava - ptrcatobj
 */

public class ptrcatobj implements FoamClass {
    private static Format FORMAT_0 = new Format(10);
    private static Format FORMAT_9 = new Format(3);
    private static Format FORMAT_10 = new Format(2);
    private static Format FORMAT_11 = new Format(10);
    private static Format FORMAT_13 = new Format(0);
    private static Format FORMAT_15 = new Format(8);
    private static Format FORMAT_16 = new Format(2);
    private Clos ptrcatobj_init;
    private Clos runtime_init;
    private FoamContext ctxt;
    public ptrcatobj(FoamContext ctxt) {
        this.ctxt = ctxt;
        ptrcatobj_init = new Clos(null, C0_ptrcatobj);
        runtime_init = ctxt.createLoadFn("runtime");
    }
    
    public void run() {
        ptrcatobj_init.getProg().ocall(ptrcatobj_init.getEnv());
    }
    
    private Fn C0_ptrcatobj = new Fn("C0_ptrcatobj") { 
        public Value ocall(Env env, Value ... vals) {
            c0_ptrcatobj(env);
            return null;
        }

    };
    private void c0_ptrcatobj(Env env1) {
        Word [] t0, t1;
        Record t2, t3;
        final Env env0 = new Env(new EnvRecord(FORMAT_13), env1);
        ccall_Xx(runtime_init);
        Globals.setGlobal("ptrcatobj", Clos.fromValue(Globals.getGlobal("noOperation")));
        Globals.setGlobal("ptrcatobj_PointerCatObj_352884991", (Value)ccall_WxC(Clos.fromValue(Globals.getGlobal("domainMake")), new Clos(env0, C1_addLevel0)));
        t0 = new Word[9];
        t1 = new Word[9];
        t0[0] = Word.U.fromSInt(798033327);
        t1[0] = Word.U.fromArray("parentCount0\0".toCharArray());
        t0[1] = Word.U.fromSInt(797050388);
        t1[1] = Word.U.fromArray("get0\0".toCharArray());
        t0[2] = Word.U.fromSInt(680881121);
        t1[2] = Word.U.fromArray("hash0\0".toCharArray());
        t0[3] = Word.U.fromSInt(883586323);
        t1[3] = Word.U.fromArray("deref\0".toCharArray());
        t0[4] = Word.U.fromSInt(318528389);
        t1[4] = Word.U.fromArray("new\0".toCharArray());
        t0[5] = Word.U.fromSInt(829109748);
        t1[5] = Word.U.fromArray("parentGet0\0".toCharArray());
        t0[6] = Word.U.fromSInt(8616158);
        t1[6] = Word.U.fromArray("name0\0".toCharArray());
        t0[7] = Word.U.fromSInt(277869983);
        t1[7] = Word.U.fromArray("pointerCatDV\0".toCharArray());
        t0[8] = Word.U.fromSInt(655011510);
        t1[8] = Word.U.fromArray("build0\0".toCharArray());
        t2 = new Record(FORMAT_9);
        t2.setField(0, "size", Value.U.fromSInt(9));
        t2.setField(1, "nsize", Value.U.fromSInt(9));
        t2.setField(2, "values", (Value)Word.U.fromArray(t0));
        t3 = new Record(FORMAT_9);
        t3.setField(0, "size", Value.U.fromSInt(9));
        t3.setField(1, "nsize", Value.U.fromSInt(9));
        t3.setField(2, "values", (Value)Word.U.fromArray(t1));
        ccall_XxWW(Clos.fromValue(Globals.getGlobal("rtAddStrings")), Word.U.fromRec(t2), Word.U.fromRec(t3));
        return;
    }
    
    private Fn C1_addLevel0 = new Fn("C1_addLevel0") { 
        public Value ocall(Env env, Value ... vals) {
            Clos ret = c1_addLevel0(env, Word.U.fromValue(vals[0]));
            return ret;
        }

    };
    private Clos c1_addLevel0(Env env1, Word p0_domain) {
        final Env env0 = new Env(null, env1);
        ccall_WxWW(Clos.fromValue(Globals.getGlobal("domainAddNameFn!")), p0_domain, ccall_WxA(Clos.fromValue(Globals.getGlobal("rtConstNameFn")), "PointerCatObj\0".toCharArray()));
        ccall_WxWI(Clos.fromValue(Globals.getGlobal("domainAddHash!")), p0_domain, 763249769);
        return new Clos(env0, C2_addLevel1);
    }
    
    private Fn C2_addLevel1 = new Fn("C2_addLevel1") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c2_addLevel1(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c2_addLevel1(Env env1, Word p0_domain, Word p1_hashcode) {
        Word [] t0, t1, t2;
        Record t3, t4, t5;
        int t6 = 0, t7 = 0, t8 = 0, t9 = 0, t10 = 0, t11 = 0, t12, t13, t14;
        final Env env0 = new Env(new EnvRecord(FORMAT_11), env1);
        final EnvRecord lvl0 = env0.level();
        t0 = new Word[9];
        t1 = new Word[9];
        t2 = new Word[9];
        lvl0.setField(9, "", Value.U.fromSInt(p1_hashcode.toSInt()));
        lvl0.setField(8, "new", new Clos(env0, C3_new));
        lvl0.setField(7, "deref", new Clos(env0, C4_deref));
        lvl0.setField(6, "name0", new Clos(env0, C5_name0));
        lvl0.setField(5, "build0", new Clos(env0, C6_build0));
        lvl0.setField(4, "get0", new Clos(env0, C7_get0));
        lvl0.setField(3, "hash0", new Clos(env0, C8_hash0));
        lvl0.setField(2, "parentCount0", new Clos(env0, C9_parentCount0));
        lvl0.setField(1, "parentGet0", new Clos(env0, C10_parentGet0));
        lvl0.setField(0, "pointerCatDV", new Clos(env0, C11_pointerCatDV));
        t12 = Math.hashCombine(lvl0.getField(9, "").toSInt(), 51489085);
        t13 = Math.hashCombine(32236, t12);
        t6 = Math.hashCombine(339414697, t13);
        t7 = Math.hashCombine(411206131, t13);
        t14 = Math.hashCombine(1073128398, t12);
        t8 = Math.hashCombine(339414697, Math.hashCombine(32236, t14));
        t9 = Math.hashCombine(313017700, Math.hashCombine(32236, Math.hashCombine(313017700, Math.hashCombine(33717313, Math.hashCombine(33717313, t14)))));
        t10 = Math.hashCombine(33717313, t13);
        t11 = Math.hashCombine(339414697, Math.hashCombine(32236, Math.hashCombine(33717313, t12)));
        t3 = new Record(FORMAT_9);
        t3.setField(0, "size", Value.U.fromSInt(9));
        t3.setField(1, "nsize", Value.U.fromSInt(9));
        t3.setField(2, "values", (Value)Word.U.fromArray(t0));
        t4 = new Record(FORMAT_9);
        t4.setField(0, "size", Value.U.fromSInt(9));
        t4.setField(1, "nsize", Value.U.fromSInt(9));
        t4.setField(2, "values", (Value)Word.U.fromArray(t1));
        t5 = new Record(FORMAT_9);
        t5.setField(0, "size", Value.U.fromSInt(9));
        t5.setField(1, "nsize", Value.U.fromSInt(9));
        t5.setField(2, "values", (Value)Word.U.fromArray(t2));
        ccall_XxWRRR(Clos.fromValue(Globals.getGlobal("domainAddExports!")), p0_domain, t3, t4, t5);
        t0[0] = Word.U.fromSInt(318528389);
        t1[0] = Word.U.fromSInt(898735017);
        t2[0] = Word.U.fromClos(Clos.fromValue(lvl0.getField(8, "new")));
        t0[1] = Word.U.fromSInt(883586323);
        t1[1] = Word.U.fromSInt(t6);
        t2[1] = Word.U.fromClos(Clos.fromValue(lvl0.getField(7, "deref")));
        t0[2] = Word.U.fromSInt(8616158);
        t1[2] = Word.U.fromSInt(t7);
        t2[2] = Word.U.fromClos(Clos.fromValue(lvl0.getField(6, "name0")));
        t0[3] = Word.U.fromSInt(655011510);
        t1[3] = Word.U.fromSInt(t8);
        t2[3] = Word.U.fromClos(Clos.fromValue(lvl0.getField(5, "build0")));
        t0[4] = Word.U.fromSInt(797050388);
        t1[4] = Word.U.fromSInt(t9);
        t2[4] = Word.U.fromClos(Clos.fromValue(lvl0.getField(4, "get0")));
        t0[5] = Word.U.fromSInt(680881121);
        t1[5] = Word.U.fromSInt(t10);
        t2[5] = Word.U.fromClos(Clos.fromValue(lvl0.getField(3, "hash0")));
        t0[6] = Word.U.fromSInt(798033327);
        t1[6] = Word.U.fromSInt(t10);
        t2[6] = Word.U.fromClos(Clos.fromValue(lvl0.getField(2, "parentCount0")));
        t0[7] = Word.U.fromSInt(829109748);
        t1[7] = Word.U.fromSInt(t11);
        t2[7] = Word.U.fromClos(Clos.fromValue(lvl0.getField(1, "parentGet0")));
        t0[8] = Word.U.fromSInt(277869983);
        t1[8] = Word.U.fromSInt(975748295);
        t2[8] = Word.U.fromClos(Clos.fromValue(lvl0.getField(0, "pointerCatDV")));
        return p0_domain;
    }
    
    private Fn C3_new = new Fn("C3_new") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c3_new(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c3_new(Env env1, Word p0_fn) {
        Record t0;
        t0 = new Record(FORMAT_10);
        t0.setField(0, "tag", Value.U.fromSInt(0));
        t0.setField(1, "value", (Value)p0_fn);
        return Word.U.fromRec(t0);
    }
    
    private Fn C4_deref = new Fn("C4_deref") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c4_deref(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c4_deref(Env env1, Word p0_c) {
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            return Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            case 0: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C5_name0 = new Fn("C5_name0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c5_name0(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c5_name0(Env env1, Word p0_c) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(1, "namer"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "catRep")));
            case 0: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C6_build0 = new Fn("C6_build0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c6_build0(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c6_build0(Env env1, Word p0_c, Word p1_dom) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(5, "builder"));
            return ccall_WxWW(t0, Word.U.fromValue(t2.getField(1, "catRep")), p1_dom);
            case 0: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C7_get0 = new Fn("C7_get0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c7_get0(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]), Word.U.fromValue(vals[2]), Word.U.fromValue(vals[3]), Word.U.fromValue(vals[4]));
            return (Value)ret;
        }

    };
    private Word c7_get0(Env env1, Word p0_c, Word p1_pc, Word p2_n1, Word p3_n2, Word p4_box) {
        Record t3 = null, t6 = null, t10 = null, t13 = null;
        boolean t14 = false;
        int t1 = 0;
        Word t0 = null, t2 = null, t5 = null, t8 = null, t9 = null, t12 = null, t15 = null, t16 = null;
        Clos t4 = null, t7 = null, t11 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 7; continue;}
            case 8: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 10; continue;}
            throw new FoamException(103);
            case 10: 
            t15 = Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            t13 = new Record(FORMAT_16);
            t13.setField(0, "first", (Value)t15);
            t13.setField(1, "rest", (Value)null);
            t3 = t13;
            case 0: 
            t14 = t3 == null;
            if (t14) {target = 1; continue;}
            t10 = (Record)Word.U.fromValue(t3.getField(0, "first"));
            t9 = Word.U.fromValue(t3.getField(1, "rest"));
            t3 = (Record)t9;
            t5 = Word.U.fromValue(t10.getField(0, "cdv"));
            t4 = Clos.fromValue(((Record)t5).getField(3, "getter"));
            t2 = ccall_WxWWWWW(t4, Word.U.fromValue(t10.getField(1, "catRep")), p1_pc, p2_n1, p3_n2, p4_box);
            if (Word.U.toPtr(t2) == null) {target = 4; continue;}
            t16 = t2;
            case 6: 
            return t16;
            case 4: 
            t12 = Word.U.fromValue(t10.getField(0, "cdv"));
            t11 = Clos.fromValue(((Record)t12).getField(6, "parentCounter"));
            t1 = ccall_WxW(t11, Word.U.fromValue(t10.getField(1, "catRep"))).toSInt();
            case 2: 
            if (t1 > 0) {target = 5; continue;}
            target = 0;
            continue;
            case 5: 
            t8 = Word.U.fromValue(t10.getField(0, "cdv"));
            t7 = Clos.fromValue(((Record)t8).getField(7, "parentGetter"));
            t0 = ccall_WxWW(t7, Word.U.fromValue(t10.getField(1, "catRep")), Word.U.fromSInt(t1));
            if (Word.U.toPtr(t0) == null) {target = 3; continue;}
            t6 = new Record(FORMAT_16);
            t6.setField(0, "first", (Value)t0);
            t6.setField(1, "rest", (Value)Word.U.fromRec(t3));
            t3 = t6;
            case 3: 
            t1 = t1 - 1;
            target = 2;
            continue;
            case 1: 
            t16 = null;
            target = 6;
            continue;
            case 7: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 9; continue;}
            throw new FoamException(103);
            case 9: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 8;
            continue;}
        }
    }
    
    private Fn C8_hash0 = new Fn("C8_hash0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c8_hash0(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c8_hash0(Env env1, Word p0_c) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(4, "hasher"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "catRep")));
            case 0: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C9_parentCount0 = new Fn("C9_parentCount0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c9_parentCount0(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c9_parentCount0(Env env1, Word p0_c) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(6, "parentCounter"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "catRep")));
            case 0: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C10_parentGet0 = new Fn("C10_parentGet0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c10_parentGet0(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c10_parentGet0(Env env1, Word p0_c, Word p1_n) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_c).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(7, "parentGetter"));
            return ccall_WxWW(t0, Word.U.fromValue(t2.getField(1, "catRep")), p1_n);
            case 0: 
            if (((Record)p0_c).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_c).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_c).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_c).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C11_pointerCatDV = new Fn("C11_pointerCatDV") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c11_pointerCatDV(env);
            return (Value)ret;
        }

    };
    private Word c11_pointerCatDV(Env env1) {
        Record t6;
        Clos t0_pg0 = null, t1_pc0 = null, t2_h0 = null, t3_g0 = null, t4_b0 = null, t5_n0 = null;
        final Env env0 = new Env(null, env1);
        t5_n0 = new Clos(env0, C12_n0);
        t4_b0 = new Clos(env0, C13_b0);
        t3_g0 = new Clos(env0, C14_g0);
        t2_h0 = new Clos(env0, C15_h0);
        t1_pc0 = new Clos(env0, C16_pc0);
        t0_pg0 = new Clos(env0, C17_pg0);
        t6 = new Record(FORMAT_15);
        t6.setField(0, "tag", (Value)Word.U.fromSInt(10));
        t6.setField(1, "namer", t5_n0);
        t6.setField(2, "noname", (Value)null);
        t6.setField(3, "getter", t3_g0);
        t6.setField(4, "hasher", t2_h0);
        t6.setField(5, "builder", t4_b0);
        t6.setField(6, "parentCounter", t1_pc0);
        t6.setField(7, "parentGetter", t0_pg0);
        return Word.U.fromRec(t6);
    }
    
    private Fn C12_n0 = new Fn("C12_n0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c12_n0(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c12_n0(Env env1, Word p0_x) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_x).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(1, "namer"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "catRep")));
            case 0: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_x).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_x).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_x).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C13_b0 = new Fn("C13_b0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c13_b0(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c13_b0(Env env1, Word p0_x, Word p1_d) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_x).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(5, "builder"));
            return ccall_WxWW(t0, Word.U.fromValue(t2.getField(1, "catRep")), p1_d);
            case 0: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_x).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_x).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_x).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C14_g0 = new Fn("C14_g0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c14_g0(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]), Word.U.fromValue(vals[2]), Word.U.fromValue(vals[3]), Word.U.fromValue(vals[4]));
            return (Value)ret;
        }

    };
    private Word c14_g0(Env env1, Word p0_x, Word p1_d, Word p2_h, Word p3_h2, Word p4_b) {
        Record t3 = null, t6 = null, t10 = null, t13 = null;
        boolean t14 = false;
        int t1 = 0;
        Word t0 = null, t2 = null, t5 = null, t8 = null, t9 = null, t12 = null, t15 = null, t16 = null;
        Clos t4 = null, t7 = null, t11 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 7; continue;}
            case 8: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 1) {target = 10; continue;}
            throw new FoamException(103);
            case 10: 
            t15 = Word.U.fromValue(((Record)p0_x).getField(1, "value"));
            t13 = new Record(FORMAT_16);
            t13.setField(0, "first", (Value)t15);
            t13.setField(1, "rest", (Value)null);
            t3 = t13;
            case 0: 
            t14 = t3 == null;
            if (t14) {target = 1; continue;}
            t10 = (Record)Word.U.fromValue(t3.getField(0, "first"));
            t9 = Word.U.fromValue(t3.getField(1, "rest"));
            t3 = (Record)t9;
            t5 = Word.U.fromValue(t10.getField(0, "cdv"));
            t4 = Clos.fromValue(((Record)t5).getField(3, "getter"));
            t2 = ccall_WxWWWWW(t4, Word.U.fromValue(t10.getField(1, "catRep")), p1_d, p2_h, p3_h2, p4_b);
            if (Word.U.toPtr(t2) == null) {target = 4; continue;}
            t16 = t2;
            case 6: 
            return t16;
            case 4: 
            t12 = Word.U.fromValue(t10.getField(0, "cdv"));
            t11 = Clos.fromValue(((Record)t12).getField(6, "parentCounter"));
            t1 = ccall_WxW(t11, Word.U.fromValue(t10.getField(1, "catRep"))).toSInt();
            case 2: 
            if (t1 > 0) {target = 5; continue;}
            target = 0;
            continue;
            case 5: 
            t8 = Word.U.fromValue(t10.getField(0, "cdv"));
            t7 = Clos.fromValue(((Record)t8).getField(7, "parentGetter"));
            t0 = ccall_WxWW(t7, Word.U.fromValue(t10.getField(1, "catRep")), Word.U.fromSInt(t1));
            if (Word.U.toPtr(t0) == null) {target = 3; continue;}
            t6 = new Record(FORMAT_16);
            t6.setField(0, "first", (Value)t0);
            t6.setField(1, "rest", (Value)Word.U.fromRec(t3));
            t3 = t6;
            case 3: 
            t1 = t1 - 1;
            target = 2;
            continue;
            case 1: 
            t16 = null;
            target = 6;
            continue;
            case 7: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 9; continue;}
            throw new FoamException(103);
            case 9: 
            ((Record)p0_x).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_x).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_x).getField(1, "value"))));
            target = 8;
            continue;}
        }
    }
    
    private Fn C15_h0 = new Fn("C15_h0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c15_h0(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c15_h0(Env env1, Word p0_x) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_x).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(4, "hasher"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "catRep")));
            case 0: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_x).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_x).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_x).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C16_pc0 = new Fn("C16_pc0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c16_pc0(env, Word.U.fromValue(vals[0]));
            return (Value)ret;
        }

    };
    private Word c16_pc0(Env env1, Word p0_x) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_x).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(6, "parentCounter"));
            return ccall_WxW(t0, Word.U.fromValue(t2.getField(1, "catRep")));
            case 0: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_x).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_x).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_x).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private Fn C17_pg0 = new Fn("C17_pg0") { 
        public Value ocall(Env env, Value ... vals) {
            Word ret = c17_pg0(env, Word.U.fromValue(vals[0]), Word.U.fromValue(vals[1]));
            return (Value)ret;
        }

    };
    private Word c17_pg0(Env env1, Word p0_x, Word p1_i) {
        Record t2 = null;
        Word t1 = null;
        Clos t0 = null;
        int target = -1;
        while (true) {
            switch (target) {case -1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 0; continue;}
            case 1: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 1) {target = 3; continue;}
            throw new FoamException(103);
            case 3: 
            t2 = (Record)Word.U.fromValue(((Record)p0_x).getField(1, "value"));
            t1 = Word.U.fromValue(t2.getField(0, "cdv"));
            t0 = Clos.fromValue(((Record)t1).getField(7, "parentGetter"));
            return ccall_WxWW(t0, Word.U.fromValue(t2.getField(1, "catRep")), p1_i);
            case 0: 
            if (((Record)p0_x).getField(0, "tag").toSInt() == 0) {target = 2; continue;}
            throw new FoamException(103);
            case 2: 
            ((Record)p0_x).setField(0, "tag", Value.U.fromSInt(1));
            ((Record)p0_x).setField(1, "value", (Value)ccall_Wx((Clos)Word.U.fromValue(((Record)p0_x).getField(1, "value"))));
            target = 1;
            continue;}
        }
    }
    
    private static Word ccall_WxWWWWW(Clos _0, Word _1, Word _2, Word _3, Word _4, Word _5) {
        Value result = _0.call((Value)_1, (Value)_2, (Value)_3, (Value)_4, (Value)_5);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxW(Clos _0, Word _1) {
        Value result = _0.call((Value)_1);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_Wx(Clos _0) {
        Value result = _0.call();
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWRRR(Clos _0, Word _1, Record _2, Record _3, Record _4) {
        _0.call((Value)_1, _2, _3, _4);
        return;
    }
    
    private static Word ccall_WxA(Clos _0, char [] _1) {
        Value result = _0.call(Value.U.fromArray(_1));
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWW(Clos _0, Word _1, Word _2) {
        Value result = _0.call((Value)_1, (Value)_2);
        return Word.U.fromValue(result);
    }
    
    private static Word ccall_WxWI(Clos _0, Word _1, int _2) {
        Value result = _0.call((Value)_1, Value.U.fromSInt(_2));
        return Word.U.fromValue(result);
    }
    
    private static void ccall_Xx(Clos _0) {
        _0.call();
        return;
    }
    
    private static Word ccall_WxC(Clos _0, Clos _1) {
        Value result = _0.call(_1);
        return Word.U.fromValue(result);
    }
    
    private static void ccall_XxWW(Clos _0, Word _1, Word _2) {
        _0.call((Value)_1, (Value)_2);
        return;
    }

}
