# ======================================================================
# This code was written all or part by Dr. Manuel Bronstein from
# Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
# decided to publish this code under the CeCILL open source license in
# memory of Dr. Manuel Bronstein.
# 
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and Inria at the following URL :
# http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
# 
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided
# only with a limited warranty and the software's author, the holder of
# the economic rights, and the successive licensors have only limited
# liability.
# 
# In this respect, the user's attention is drawn to the risks associated
# with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards
# their requirements in conditions enabling the security of their
# systems and/or data to be ensured and, more generally, to use and
# operate it in the same conditions as regards security.
# 
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.
# ======================================================================
# 
MSGFLAGS = -Mno-mactext -M2
AFLAGS=  -fao $(MSGFLAGS) -Y $(LibDir) -I $(IncDir)
XFLAGS= -Csmax=0 -Fo -lsalli -Y $(LibDir)

LN = ln -f -s

AOFLAGS=$(AFLAGS) -q5 -qinline-all
AODFLAGS=$(AFLAGS) -q1 -dDEBUG
RELFLAGS=$(XFLAGS) -q5 -O -qinline-all
PROFFLAGS=$(XFLAGS) -q5 -O -Zprof -qinline-all
DBGFLAGS=$(XFLAGS) -q1 -Zdb -dDEBUG


ARREPLFLAGS  = rv

ARREPLOFLAGS = rv

# Implicit rule for building .test.as files
${TestDir}/%.test.as: %.as
	@(echo Extracting test from $*.as ... ;		\
	  extract -mSALLITEST -o$*.test $*.as;		\
	  if [ -f '$*.test' ] ; then	\
		mv $*.test ${TestDir}/$*.test.as;	\
	  else				\
		false;				\
	  fi)

# Implicit rule for building .tex files
${DocDir}/%.tex: %.as
	@(echo Extracting doc from $*.as ... ;		\
	  extract -mALDOC $*.as;		\
	  if [ -f '$*.tex' ] ; then	\
		mv $*.tex ${DocDir};	\
	  else				\
		false;				\
	  fi)

# Implicit rule for building .al file
${SALLI}(%.ao): %.as
	@(here=`pwd`; 				\
          cd `dirname ${SALLI}`;			\
	  echo Compiling $*.as ... ;		\
	  $(AXIOMXL) $$here/$*.as;	\
	  if [ -f '$*.ao' ] ; then 		\
		${AR} $(ARREPLFLAGS) ${SALLI} $*.ao;	\
		rm -rf $*.ao;			\
	        rm -rf /tmp/vAAA*;             \
	  else					\
		false;				\
	  fi)

# Rules for compiling .ao files to .o files
${SALLIM}(%.o): ${SALLI}(%.ao)
	@(here=`pwd`;				\
	  cd `dirname ${SALLI}` ; 			\
	  ar x ${SALLI} $*.ao  ;			\
	  echo Compiling $*.ao;			\
	  $(AXIOMXLO)  $*.ao ;			\
	  if [ -f '$%' ] ; then			\
		$(AR) $(ARREPLOFLAGS) ${SALLIM} $% ;	\
		rm -rf $% $*.ao;		\
	        rm -rf /tmp/vAAA*;             \
	  else					\
		false;				\
	  fi)	


# Generic rules
def.rule:
	@echo "type gmake aobj to make libsalli.al (release)"
	@echo "type gmake objects to make libsalli.a as well (release)"
	@echo "type gmake aobjd to make libsalli.al (debug)"
	@echo "type gmake dbg to make libsalli.a as well (debug)"
	@echo "type gmake doc to make the reference manual"
	@echo "type gmake test to make the tests"

