-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
---------------------------- linearmap.as -------------------------------
#include "sumit"

macro {
	I	== SingleInteger;
	Z	== Integer;
	ARR	== Array;
	VEC	== Vector;
}

#if ASDOC
\thistype{LinearMapToMatrix}
\History{Manuel Bronstein}{10 January 96}{created}
\Usage{import from \this(R, A, M)}
\Params{
{\em R} & IntegralDomain & A coefficient ring\\
{\em A} & AbelianGroup & An R-module\\
{\em M} & MatrixCategory R & A matrix type over R\\
}
\Descr{\this(R, A, M) provides functions for converting R-linear maps on A
into matrices, as well as lineary algebra algorithms on such maps.}
\begin{exports}
matrix: & (Array A, (A, $\ZZ$) $\to$ R, A $\to \ZZ$) $\to$ M &
Matrix of a submodule\\
matrix: & (A $\to$ A, Array A, (A, $\ZZ$) $\to$ R, A $\to \ZZ$) $\to$ M &
Matrix of a linear map\\
matrix: & (A $\to$ A, A, $\ZZ$, (A, $\ZZ$) $\to$ R, A $\to \ZZ$) $\to$ M &
Matrix of an orbit\\
\end{exports}
\begin{exports}[if R has IntegralDomain then]
cyclicLinearDependences: & (A $\to$ A, A, $\ZZ$, (A, $\ZZ$) $\to$ R) $\to$ KER &
Linear dependences\\
undeterminedCoefficients: &
(A $\to$ A, ARR, (A, $\ZZ$) $\to$ R, A $\to \ZZ$) $\to$ KER &
Kernel of a map\\
\end{exports}
\Aswhere{
ARR &==& Array A\\
KER &==& List Vector R\\
}
#endif

LinearMapToMatrix(R:SumitRing, M:AbelianGroup, MAT:MatrixCategory R): with {
	matrix: (M -> M, ARR M, (M, Z) -> R, M -> Z) -> MAT;
	matrix: (M -> M, M, Z, (M, Z) -> R, M -> Z) -> MAT;
	matrix: (ARR M, (M, Z) -> R, M -> Z) -> MAT;
#if ASDOC
\aspage{matrix}
\Usage{
\name($[b_1,\dots,b_n]$,$\pi$,$\nu$) \\
\name(L,$[b_1,\dots,b_n]$,$\pi$,$\nu$) \\
\name(L, b, n, $\pi$, $\nu$)
}
\Signatures{
\name: & (Array A, (A, Integer) $\to$ R, A $\to$ Integer) $\to$ M \\
\name: & (A $\to$ A, Array A, (A, Integer) $\to$ R, A $\to$ Integer) $\to$ M \\
\name: & (A $\to$ A, A, $\ZZ$, (A, Integer) $\to$ R, A $\to$ Integer) $\to$ M \\
}
\Params{
$b_1,\dots,b_n$ & A & Generators of a submodule\\
{\em L} & A $\to$ A & An R-linear map\\
{\em b} & R & Generator of an orbit\\
{\em n} & Integer & Size of the orbit\\
$\pi$ & (A, Integer) $\to$ R & Coefficient function\\
$\sigma$ & A $\to$ Integer & Size function\\
}
\Descr{
\name($[b_1,\dots,b_n]$,$\pi$,$\nu$) returns the matrix of the subspace
generated by $[b_1,\dots,b_n]$, but the number of rows is set to $m$ in the
first case, while
\name(L,$[b_1,\dots,b_n]$,$\pi$,$\nu$) returns the matrix of the image
of the subspace generated by $[b_1,\dots,b_n]$ under L, and
\name(L, b, n, $\pi$, $\nu$) returns the matrix of the subspace generated
by $[b, L b, L^2 b, \dots, L^{n-1} b]$.}
\Remarks{
A module basis is implicitely given by the coefficient
function $\pi$, where $\pi(a,i)$ returns the \Th{i} coefficient of a.
The size function $\nu$ returns an upper bound on the number of basis
elements needed, \ie~$\pi(a,i) = 0$ for $i > \nu(a)$.
It is assumed for $\pi$ and $\nu$ that the first basis element has
index 1, not 0. This implies that $\nu(a) > 0$ for any $a \ne 0$.
}
#endif
	if R has IntegralDomain then {
		cyclicLinearDependences:(M->M, M, Z, (M,Z)->R) -> List VEC R;
#if ASDOC
\aspage{cyclicLinearDependences}
\Usage{\name(L, b, n, $\pi$)}
\Signature{(A $\to$ A, A, Integer, (A, Integer) $\to$ R)}{List Vector R}
\Params{
{\em L} & A $\to$ A & An R-linear map\\
{\em b} & R & Generator of an orbit\\
{\em n} & Integer & Upper bound on orbit dimension\\
$\pi$ & (A, Integer) $\to$ R & Coefficient function\\
}
\Retval{Returns all the linear dependences over R among the set
$\{b, L b, L^2 b, \dots, L^n b\}$.}
\Remarks{
A module basis is implicitely given by the coefficient
function $\pi$, where $\pi(a,i)$ returns the \Th{i} coefficient of a.
It is assumed for $\pi$ that the first basis element has index 1, not 0.}
#endif
		undeterminedCoefficients:
			(M -> M, ARR M, (M, Z) -> R, M -> Z) -> List VEC R;
#if ASDOC
\aspage{undeterminedCoefficients}
\Usage{\name(L, $[b_1,\dots,b_n]$, $\pi$, $\sigma$)}
\Signature{(A $\to$ A, Array A, (A, Integer) $\to$ R, A $\to$ Integer)}
{List Array R}
\Params{
{\em L} & A $\to$ A & An R-linear map\\
$b_1,\dots,b_n$ & A & Generators of a submodule\\
$\pi$ & (A, Integer) $\to$ R & Coefficient function\\
$\sigma$ & A $\to$ Integer & Size function\\
}
\Retval{Returns a basis of $\Ker(L) \cap S$, where S is the submodule
of A generated by $[b_1,\dots,b_n]$.}
\Remarks{
A module basis is implicitely given by the coefficient
function $\pi$, where $\pi(a,i)$ returns the \Th{i} coefficient of a.
The size function $\nu$ returns an upper bound on the number of basis
elements needed, \ie~$\pi(a,i) = 0$ for $i > \nu(a)$.
It is assumed for $\pi$ and $\nu$ that the first basis element has
index 1, not 0. This implies that $\nu(a) > 0$ for any $a \ne 0$.
}
#endif
	}
} == add {
	-- coef must have second argument starting with 1
	-- size must be at least 1 for nonzero elements
	matrix(L:M -> M, basis:ARR M, coef:(M, Z) -> R, size:M -> Z):MAT ==
		matrix([L b for b in basis], coef, size);

	-- coef must have second argument starting with 1
	-- size must be at least 1 for nonzero elements
	matrix(space:ARR M, coef:(M, Z) -> R, size:M -> Z):MAT == {
		import from I;
		g:Z := 0;
		for b in space | ~zero? b repeat
			if g < (d := size b) then g := d;
		matrix(space, coef, retract g);
	}

	-- coef must have second argument starting with 1
	local matrix(space:ARR M, coef:(M, Z) -> R, rows:I):MAT == {
		import from Z;
		m := #space;
		zero? rows => zero(1, m);
		mat := zero(rows, m);
		for j in 1..m | ~zero?(b := space.j) repeat
			for i in 1..rows repeat mat(i, j) := coef(b, i::Z);
		mat;
	}

	-- coef must have second argument starting with 1
	-- size must be at least 1 for nonzero elements
	matrix(L:M -> M, v:M, cols:Z, coef:(M, Z) -> R, size:M -> Z):MAT == {
		import from I, M;
		orbit:ARR M := new(m := retract cols, 0);
		for i in 1..prev m repeat {
			orbit.i := v;
			v := L v;
		}
		orbit.m := v;
		matrix(orbit, coef, size);
	}

	if R has IntegralDomain then {
		-- coef must have second argument starting with 1
		-- size must be at least 1 for nonzero elements
		undeterminedCoefficients(L:M -> M, basis:ARR M,
				coef:(M,Z) -> R, size:M -> Z):List VEC R == {
					import from MAT;
					nullSpace matrix(L, basis, coef, size);
		}

		-- coef must have second argument starting with 1
		cyclicLinearDependences(L:M -> M, v:M, n:Z, coef:(M, Z) -> R):
			List VEC R == {
				import from MAT;
				nullSpace matrix(L, v, next n,coef,(x:M):Z+->n);
		}
	}
}
