-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
------------------------------ CATlodo0.as ------------------------------
#include "sumit"

macro Z	== Integer;

#if ASDOC
\thistype{LinearOrdinaryDifferentialOperatorCategory0}
\History{Manuel Bronstein}{18/5/95}{created}
\Usage{ \this~R: Category}
\Params{
{\em R} & CommutativeRing & The coefficient ring of the operators\\
}
\Descr{\this~R is the category of linear ordinary differential
operators with coefficients in R.}
\begin{exports}
\category{UnivariateSkewPolynomialCategory R}\\
adjoint: & \% $\to$ \% & Adjoint operator\\
apply: & (\%, R) $\to$ R & Applies an operator to an element of R\\
derivation: & $\to$ Derivation R & The derivation used on R\\
\end{exports}
\begin{exports}[if R has IntegralDomain then]
exteriorPower: & (\&, Integer) $\to$ \% & Exterior power\\
symmetricPower: & (\%, Integer) $\to$ \% & Symmetric power\\
\end{exports}
#endif

LinearOrdinaryDifferentialOperatorCategory0(R:CommutativeRing):
  Category == UnivariateSkewPolynomialCategory R with {
	adjoint: % -> %;
#if ASDOC
\aspage{adjoint}
\Usage{\name~L}
\Signature{\%}{\%}
\Params{ {\em L} & \% & A differential operator\\ }
\Retval{Returns
$$
\tilde L = \sum_{i=0}^n (-1)^i \partial^i a_i
$$
where $L = \sum_{i=0}^n a_i \partial^i$.}
#endif
	apply: (%, R) -> R;
#if ASDOC
\aspage{apply}
\Usage{ \name(L, x)\\L~x }
\Signature{(\%, R)}{R}
\Params{
{\em L} & \% & A differential operator\\
{\em x} & R & A ring element\\
}
\Retval{Returns
$$
L x = \sum_{i=0}^n a_i x^{(i)}
$$
where $L = \sum_{i=0}^n a_i \partial^i$.}
#endif
	derivation: Derivation R;
#if ASDOC
\aspage{derivation}
\Usage{\name}
\Signature{}{Derivation R}
\Retval{Returns the derivation of R given by $x \to \partial x$, where
$\partial$ is the monic operator of degree one.}
#endif
	if R has IntegralDomain then {
		exteriorPower: (%, Z) -> %;
#if ASDOC
\aspage{exteriorPower}
\Usage{\name(L, n)}
\Signature{(\%, Integer)}{\%}
\Params{
{\em L} & \% & A differential operator\\
{\em n} & Integer & A positive integer\\
}
\Retval{Returns a differential operator $\extpow{L}{n}$ of minimal order
whose kernel is generated by the Wronskians of $n$ elements
of a basis of $\Ker(L)$.}
\seealso{symmetricPower(\this)}
#endif
		symmetricPower: (%, Z) -> %;
#if ASDOC
\aspage{symmetricPower}
\Usage{\name(L, n)}
\Signature{(\%, Integer)}{\%}
\Params{
{\em L} & \% & A differential operator\\
{\em n} & Integer & A positive integer\\
}
\Retval{Returns a differential operator $\sympow{L}{n}$
of minimal order whose kernel is generated by the all the products of $n$
elements of a basis of $\Ker(L)$.}
\seealso{exteriorPower(\this)}
#endif
	}
	default {
		apply(L:%, r:R):R	== apply(L, 0, r);
		local pm1(n:Z):R	== { odd? n => - 1; 1 };
		derivation:Derivation R	== derivation((x:R):R +-> monom x);

		adjoint(L:%):% == {
			import from R;
			a:% := 0;
			for term in L repeat {
				(c, n) := term;
				a := add!(a, pm1 n, monomial(1, n) * (c::%));
			}
			a;
		}
	}
}
