# ======================================================================
# This code was written all or part by Dr. Manuel Bronstein from
# Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
# decided to publish this code under the CeCILL open source license in
# memory of Dr. Manuel Bronstein.
# 
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and Inria at the following URL :
# http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
# 
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided
# only with a limited warranty and the software's author, the holder of
# the economic rights, and the successive licensors have only limited
# liability.
# 
# In this respect, the user's attention is drawn to the risks associated
# with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards
# their requirements in conditions enabling the security of their
# systems and/or data to be ensured and, more generally, to use and
# operate it in the same conditions as regards security.
# 
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.
# ======================================================================
# 
objects   = CATlodo0.o cyclicvec.o sympow.o sympow2.o optimize.o ffcyclicvec.o ffsympow.o CATlodo.o lodo.o lodotools.o
asobjects = CATlodo0.ao cyclicvec.ao sympow.ao sympow2.ao optimize.ao ffcyclicvec.ao ffsympow.ao CATlodo.ao lodo.ao lodotools.ao
options	  = -M2 -Fao -Fo -Q3 -Csmax=0 -Mno-mactext
tex  = CATlodo0.tex optimize.tex CATlodo.tex lodo.tex lodotools.tex
test      = Tlodo.as
testdir   = ../../../test
libsumit  = ../../../lib/libsumit.a
sumitasl  = ../../../lib/libsumit.al

all: datestamp

datestamp: $(objects)
	ar rv $(libsumit) $(objects)
	touch datestamp

CATlodo0.o: CATlodo0.as ../skpolycat.o ../../mat/matdense.o
	axiomxl $(options) CATlodo0.as
	ar rv $(sumitasl) CATlodo0.ao

cyclicvec.o: cyclicvec.as CATlodo0.o
	axiomxl $(options) cyclicvec.as
	ar rv $(sumitasl) cyclicvec.ao

sympow.o: sympow.as cyclicvec.o ../../multpoly/dhpoly.o ../../multpoly/dhextpow.o
	axiomxl $(options) sympow.as
	ar rv $(sumitasl) sympow.ao

sympow2.o: sympow2.as CATlodo0.o
	axiomxl $(options) sympow2.as
	ar rv $(sumitasl) sympow2.ao

optimize.o: optimize.as ../../mat/categories/matcat0.o ../../polyfactor0/zringint.o
	axiomxl $(options) optimize.as
	ar rv $(sumitasl) optimize.ao

ffcyclicvec.o: ffcyclicvec.as CATlodo0.o optimize.o ../../fraction/quotientby.o ../../mat/gauss/FF2GE.o
	axiomxl $(options) ffcyclicvec.as
	ar rv $(sumitasl) ffcyclicvec.ao

ffsympow.o: ffsympow.as ffcyclicvec.o ../../multpoly/dhpoly.o ../../multpoly/dhextpow.o
	axiomxl $(options) ffsympow.as
	ar rv $(sumitasl) ffsympow.ao

CATlodo.o: CATlodo.as sympow.o sympow2.o ffsympow.o
	axiomxl $(options) CATlodo.as
	ar rv $(sumitasl) CATlodo.ao

lodo.o: lodo.as ../skewdup.o CATlodo.o
	axiomxl $(options) lodo.as
	ar rv $(sumitasl) lodo.ao

lodotools.o: lodotools.as lodo.o
	axiomxl $(options) lodotools.as
	ar rv $(sumitasl) lodotools.ao

.PHONY: doc
doc: $(tex)

CATlodo0.tex: CATlodo0.as
	as2doc CATlodo0

optimize.tex: optimize.as
	as2doc optimize

CATlodo.tex: CATlodo.as
	as2doc CATlodo

lodo.tex: lodo.as
	as2doc lodo

lodotools.tex: lodotools.as
	as2doc lodotools


.PHONY: test
test: $(test)

Tlodo.as: lodo.as
	as2test lodo
	cp Tlodo.as $(testdir)

.PHONY: clean
clean:
	-rm $(objects) $(asobjects) $(tex) $(test)

