-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
------------------------------ sit_sympow2.as -----------------------------
-- Copyright (c) Manuel Bronstein 1997
-- Copyright (c) INRIA 1999, Version 0.1.12
-- Logiciel Sum^it ©INRIA 1999, dans sa version 0.1.12
-- Copyright (c) Swiss Federal Polytechnic Institute Zurich, 1997
-----------------------------------------------------------------------------

#include "sumit"

macro Z	== Integer;

#if ALDOC
\thistype{SecondOrderSymmetricPower}
\History{Manuel Bronstein}{14/1/97}{created}
\Usage{ import from \this(R, Rd) }
\Params{
{\em R} & \astype{IntegralDomain} & The coefficient domain\\
{\em Rd} & \astype{LinearOrdinaryDifferentialOperatorCategory0} R &
A LODO type over R\\
}
\Descr{\this(R, Rd) implements a fast iteration for computing the
symmetric powers of operators of order $2$.}
\begin{exports}
\asexp{symmetricPower}: & (Rd, \astype{Integer}) $\to$ Rd & symmetric power\\
\end{exports}
#endif

SecondOrderSymmetricPower(R:IntegralDomain,
	Rd:LinearOrdinaryDifferentialOperatorCategory0 R): with {
		symmetricPower: (Rd, Z) -> Rd;
#if ALDOC
\aspage{symmetricPower}
\Usage{\name(L, n)}
\Signature{(Rd, \astype{Integer})}{Rd}
\Params{
{\em L} & Rd & A differential operator of order $2$\\
{\em n} & \astype{Integer} & A positive integer\\
}
\Retval{Returns a differential operator $\sympow{L}{n}$
of minimal order whose kernel is generated by the all the products of
the form $y_1^{e_1} y_2^{e_2}$ where $e_1 + e_2 = n$ and
$y_1,y_2$ is a basis of $\Ker(L)$.}
\Remarks{Uses the iteration described in:\\
M.~Bronstein, T.~Mulders \& J.A.~Weil,
{\em On symmetric powers of differential operators},
Proceedings of ISSAC'97, ACM Press (1997), 156--163.}
#endif
} == add {
	local gcd?:Boolean == R has GcdDomain;

	-- TEMPORARY: The brain-dead compiler won't compile w/o this wrapper
	local primpart(L:Rd):Rd == {
		gcd? => primpart0 L;
		never;
	}

	if R has GcdDomain then {
		local primpart0(L:Rd):Rd == primitivePart L;
	}

	symmetricPower(L:Rd, n:Z):Rd == {
		assert(n > 0);
		assert(degree L = 2);
		import from R, Partial R;
		TRACE("symmetricPower, L = ", L);
		TRACE("n = ", n);
		one? n => L;
		p := leadingCoefficient L;
		failed?(u := reciprocal p) => ffsympow(L, n, p);
		sympow(L, n, retract u);
	}

	-- case where the leading coeff of L is invertible
	-- ainv = inverse of leading coeff
	-- can then perform the iteration in R
	local sympow(L:Rd, n:Z, ainv:R):Rd == {
		TRACE("symmetricPower, L = ", L);
		TRACE("n = ", n);
		TRACE("ainv = ", n);
		assert(n > 1);
		a := ainv * coefficient(L, 1);
		aa := a::Rd;
		b := ainv * coefficient(L, 0);
		D:Rd := monom;
		-- the basic iteration is L0 = 1, L1 = pD,
		--  L_{i+1} = D L_i + i a L_i + i (m-(i-1)) b L_{i-1}
		L1 := D;
		L2 := D^2 + a * D + (n * b)::Rd;
		for i in 2..n repeat {
			L3 := (D + i * aa) * L2;
			L3 := add!(L3, i * (n - prev i) * b, L1);
			L1 := L2;
			L2 := L3;
		}
		assert(degree L2 = next n);
		L2;
	}

	-- TEMPORARY: R IS NOT SEEN TO BE A GCD-DOMAIN OTHERWISE
	macro RGCD == (R pretend GcdDomain);
	-- case where the leading coeff p of L is not invertible
	local ffsympow(L:Rd, n:Z, p:R):Rd == {
		import from Derivation R;
		assert(n > 1);
		TIMESTART;
		a := coefficient(L, 1);
		bnz? := ~zero?(b := coefficient(L, 0));
		DR := derivation$Rd;
		Dp := DR p;
		ampp := a - Dp;
		-- e = gcd(p, p', a - p')   o = gcd(e, b p/e)
		e:R := 1; o:R := 1;
		-- pe = p / e     dpe = p' / e
		pe := p;  dpe := Dp;
		if gcd? then {
			(e, pe, dpe) := gcdquo(p, Dp)$RGCD;
			if ~zero?(ampp) then {
				e := gcd(e, ampp)$RGCD;
				pe := quotient(p, e);
				dpe := quotient(Dp, e);
			}
			if bnz? then o := gcd(e, b * pe)$RGCD;
		}
		-- amppe = (a - p') / e
		amppe := quotient(ampp, e);
		-- loge = p / e  e' / e  +  p / e  o' / o
		loge := quotient(pe * DR e, e) + quotient(pe * DR o, o);
		-- po = p / o     dpo = p' / o     amppo = (a - p') / o
		-- logo = p / o  e' / e  +  p / o  o' / o   logo1 = p/o e'/e
		po := pe;
		dpo := dpe;
		coefo := dpo;
		amppo := amppe;
		logo := loge;
		if gcd? and bnz? then {
			po := quotient(p, o);
			amppo := quotient(ampp, o);
			dpo := quotient(Dp, o);
			logo1 := quotient(po * DR e, e);
			logo := logo1 + quotient(po * DR o, o);
			coefo := dpo + logo1;
		}
		coefP1 := quotient(b * pe, o);		-- (p b) / (e o)
		TIME("ffsympow::symmetricPower: recurrence coefficients at ");
		D:Rd := monom;
		P1 := p * D^2 + a * D + (n * b)::Rd;
		P2 := (pe*D + (2*amppe+dpe)::Rd) * P1 + ((2 * prev n)*pe*b) * D;
		for i in 3..n repeat {
			local coefP2, coefDP2:R; local P3:Rd;
			j := prev(i quo 2);	-- either i/2 - 1 or (i-1)/2 - 1
			if even? i then {
				coefDP2 := pe;
				coefP2 := i * amppe + j * loge + dpe;
			}
			else {
				coefDP2 := po;
				coefP2 := i * amppo + j * logo + coefo;
			}
			P3 := (coefDP2 * D + coefP2::Rd) * P2;
			if bnz? then
				P3 := add!(P3, (i * (n - prev i)) * coefP1, P1);
			P1 := P2;
			P2 := P3;
		}
		assert(degree P2 = next(n::Z));
		TIME("sympow2::symmetricPower: non-primitive operator at ");
		gcd? => primpart P2;
		P2;
	}
}
