-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
---------------------------- sal_lstruc.as ----------------------------------
--
-- This file defines linear structures
--
-- Copyright (c) Manuel Bronstein 1998
-- Copyright (c) INRIA 1998, Version 29-10-98
-- Logiciel Salli ©INRIA 1998, dans sa version du 29/10/1998
-----------------------------------------------------------------------------

#include "salli"

macro Z == MachineInteger;

#if ALDOC
\thistype{LinearStructureType}
\History{Manuel Bronstein}{28/9/98}{created}
\Usage{\this~T: Category}
\Params{{\em T} & Type & the type of the entries\\}
\Descr{\this~is the category of linear structures whose entries are
of type T.}
\begin{exports}
\asexp{[]}: & \astype{Generator} T $\to$ \% & construction of a structure\\
\asexp{apply}:
& (\%, \astype{MachineInteger}) $\to$ T & extraction of an entry\\
\asexp{firstIndex}: & \astype{MachineInteger} & index of first element\\
\asexp{free!}: & \% $\to$ () & memory disposal\\
\asexp{set!}:
& (\%, \astype{MachineInteger}, T) $\to$ T & modification of an entry\\
\end{exports}
\begin{exports}[if $T$ has \astype{PrimitiveType} then]
\asexp{equal?}:
& (\%, \%, \astype{MachineInteger}) $\to$ \asexp{Boolean} &
compare the first $n$ elements\\
\end{exports}
#endif

define LinearStructureType(T:Type): Category == with {
	bracket: Generator T -> %;
#if ALDOC
\aspage{[]}
\Usage{[t for t in g]}
\Signature{\astype{Generator} T}{\%}
\Params{
{\em g} & \astype{Generator} T & an iterator producing elements of T\\
}
\Retval{Returns the structure
composed of all the elements generated by g in
the order in which they are generated.}
#endif
	apply: (%, Z) -> T;
#if ALDOC
\aspage{apply}
\Usage{\name(a, n)\\ a.n}
\Signature{(\%, \astype{MachineInteger})}{T}
\Params{
{\em a} & \% & a linear structure\\
{\em n} & \astype{MachineInteger} & an index\\
}
\Retval{Returns the element of $a$ with index $n$. The position
of that element depends on the indexing scheme of each actual type,
for example if it is $0$-indexed, then $a.n$ returns the ${(n+1)}^{{\rm st}}$
element of $a$, while if it is $1$-indexed, then $a.n$ returns the
$\sth{n}$ element of $a$.}
\Remarks{Bound checking depends on the actual type, some perform it and
some do not.}
#endif
	firstIndex: Z;
#if ALDOC
\aspage{firstIndex}
\Usage{\name}
\Signature{}{\astype{MachineInteger}}
\Retval{Returns the index of the first element of a structure.}
#endif
	free!: % -> ();
#if ALDOC
\aspage{free!}
\Usage{\name~a}
\Signature{\%}{()}
\Params{ {\em a} & \% & a linear structure\\ }
\Descr{Releases the memory occupied by $a$.}
#endif
	set!: (%, Z, T) -> T;
#if ALDOC
\aspage{set!}
\Usage{\name(a, n, x)\\ a.n := x; }
\Signature{(\%, \astype{MachineInteger}, T)}{T}
\Params{
{\em a} & \% & a linear structure\\
{\em n} & \astype{MachineInteger} & an index\\
{\em x} & T & an entry\\
}
\Descr{Sets the element of $a$ with index $n$ to $x$ and returns $x$.
The position of that element depends on the indexing scheme of each actual
type, for example if it is $0$-indexed, then $a.n := x$ sets the
${(n+1)}^{{\rm st}}$
element of $a$, while if it is $1$-indexed, then $a.n := x$ sets the
$\sth{n}$ element of $a$.}
\Remarks{Bound checking depends on the actual type, some perform it and
some do not.}
#endif
	if T has PrimitiveType then {
		equal?: (%, %, Z) -> Boolean;
#if ALDOC
\aspage{equal?}
\Usage{\name(a, b, n)}
\Signature{(\%, \%, \astype{MachineInteger})}{\astype{Boolean}}
\Params{
{\em a, b} & \% & linear structures\\
{\em n} & \astype{MachineInteger} & a nonnegative integer\\
}
\Retval{Returns~\true if the first $n$ elements of $a$ and $b$ are
all equal, \false otherwise.}
\Remarks{$a$ and $b$ must both have at least $n$ elements.}
#endif
	}
}

