;;;
;;; Lisp code generated by Aldor from file "bool.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-bool-bool|) ((|e1| |Env|)))

(declare-prog
  (|C1-bool-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-bool-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-bool-bool|)
  ((|P0-self| |Word|) (|P1-dom| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-bool-=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-bool-~=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-bool->| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C7-bool-<| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C8-bool-<=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-bool->=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog (|C10-bool-~| |Word|) ((|P0-a| |Word|) (|e1| |Env|)))

(declare-prog
  (|C11-bool-/\\| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C12-bool-\\/| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C13-bool-max| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-bool-min| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C15-bool-toJava| |Bool|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C16-bool-fromJava| |Word|)
  ((|P0-i| |Bool|) (|e1| |Env|)))

(declare-prog (|C17-bool-test| |Word|) ((|P0-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C18-bool-<<| |Word|)
  ((|P0-p| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog (|C19-bool-hash| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog (|C20-bool-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog (|C21-bool-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C22-bool-case| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C23-bool-xor| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C24-bool-extend0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C25-bool-machine-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C26-bool-basic-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C27-bool-foamcat-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-bool| |Clos|)

(declare-type |G-bool_Boolean_186642606| |Word|)

(declare-type |G-bool_Boolean_111100038| |Word|)

(defspecials |G-bool_Boolean_111100038| |G-bool_Boolean_186642606|)

(|DDecl|
  |Struct-bool-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl| |Struct-bool-7| (|x-0| |Word|))

(|DDecl|
  |Struct-bool-8|
  (|xor-0| |Clos|)
  (|case-1| |Clos|)
  (|hash-2| |Clos|)
  (<<-3 |Clos|)
  (<<-4 |Clos|)
  (|test-5| |Clos|)
  (|fromJava-6| |Clos|)
  (|toJava-7| |Clos|)
  (|\\/-8| |Clos|)
  (|/\\-9| |Clos|)
  (~-10 |Clos|)
  (|max-11| |Clos|)
  (|min-12| |Clos|)
  (>=-13 |Clos|)
  (<=-14 |Clos|)
  (<-15 |Clos|)
  (>-16 |Clos|)
  (~=-17 |Clos|)
  (=-18 |Clos|)
  (|Rep-19| |Word|)
  (\-20 |SInt|))

(|DDecl|
  |Struct-bool-10|
  (|Boolean-0| |Word|)
  (|Machine-1| |Word|)
  (|OrderedFinite-2| |Word|)
  (|Conditional-3| |Word|)
  (|Logic-4| |Word|)
  (|Bool-5| |Word|)
  (|dom-6| |Word|)
  (\-7 |Bool|)
  (\-8 |Bool|)
  (\-9 |Bool|))

(|DDecl| |Struct-bool-11| (\-0 |Clos|) (\-1 |Clos|) (\-2 |Clos|))

(defprog
  ((|C0-bool-bool|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Arr|)
    (t4 |Arr|)
    (t5 |Record|)
    (t6 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-bool-10| |Struct-bool-10|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-bool| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C27-bool-foamcat-init|))
  (setq t1 (|Clos| |e0| |C25-bool-machine-init|))
  (setq t2 (|Clos| |e0| |C26-bool-basic-init|))
  (setq
    |G-bool_Boolean_186642606|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-bool-addLevel0|)))
  (setq
    |G-bool_Boolean_111100038|
    (|CCall| |G-extendMake| (|Clos| |e0| |C24-bool-extend0|)))
  (|SetLex| |Struct-bool-10--7| 7 |l0| (the |Bool| nil))
  (|SetLex| |Struct-bool-10--8| 8 |l0| (the |Bool| nil))
  (|SetLex| |Struct-bool-10--9| 9 |l0| (the |Bool| nil))
  (setq t3 (|ANew| |Word| (the |SInt| 23)))
  (setq t4 (|ANew| |Word| (the |SInt| 23)))
  (|SetAElt| t3 (the |SInt| 0) (the |SInt| 317608340))
  (|SetAElt| t4 (the |SInt| 0) (|MakeLit| "xor"))
  (|SetAElt| t3 (the |SInt| 1) (the |SInt| 51492427))
  (|SetAElt| t4 (the |SInt| 1) (|MakeLit| "<="))
  (|SetAElt| t3 (the |SInt| 2) (the |SInt| 200102))
  (|SetAElt| t4 (the |SInt| 2) (|MakeLit| "="))
  (|SetAElt| t3 (the |SInt| 3) (the |SInt| 445790171))
  (|SetAElt| t4 (the |SInt| 3) (|MakeLit| "toJava"))
  (|SetAElt| t3 (the |SInt| 4) (the |SInt| 200103))
  (|SetAElt| t4 (the |SInt| 4) (|MakeLit| ">"))
  (|SetAElt| t3 (the |SInt| 5) (the |SInt| 51509389))
  (|SetAElt| t4 (the |SInt| 5) (|MakeLit| "~="))
  (|SetAElt| t3 (the |SInt| 6) (the |SInt| 200076))
  (|SetAElt| t4 (the |SInt| 6) (|MakeLit| "#"))
  (|SetAElt| t3 (the |SInt| 7) (the |SInt| 200167))
  (|SetAElt| t4 (the |SInt| 7) (|MakeLit| "~"))
  (|SetAElt| t3 (the |SInt| 8) (the |SInt| 316169058))
  (|SetAElt| t4 (the |SInt| 8) (|MakeLit| "Rep"))
  (|SetAElt| t3 (the |SInt| 9) (the |SInt| 13900568))
  (|SetAElt| t4 (the |SInt| 9) (|MakeLit| "false"))
  (|SetAElt| t3 (the |SInt| 10) (the |SInt| 318461825))
  (|SetAElt| t4 (the |SInt| 10) (|MakeLit| "max"))
  (|SetAElt| t3 (the |SInt| 11) (the |SInt| 51492941))
  (|SetAElt| t4 (the |SInt| 11) (|MakeLit| ">="))
  (|SetAElt| t3 (the |SInt| 12) (the |SInt| 255806968))
  (|SetAElt| t4 (the |SInt| 12) (|MakeLit| "sample"))
  (|SetAElt| t3 (the |SInt| 13) (the |SInt| 318459775))
  (|SetAElt| t4 (the |SInt| 13) (|MakeLit| "min"))
  (|SetAElt| t3 (the |SInt| 14) (the |SInt| 864625472))
  (|SetAElt| t4 (the |SInt| 14) (|MakeLit| "case"))
  (|SetAElt| t3 (the |SInt| 15) (the |SInt| 5509732))
  (|SetAElt| t4 (the |SInt| 15) (|MakeLit| "test"))
  (|SetAElt| t3 (the |SInt| 16) (the |SInt| 11137124))
  (|SetAElt| t4 (the |SInt| 16) (|MakeLit| "true"))
  (|SetAElt| t3 (the |SInt| 17) (the |SInt| 51487581))
  (|SetAElt| t4 (the |SInt| 17) (|MakeLit| "/\\"))
  (|SetAElt| t3 (the |SInt| 18) (the |SInt| 51492426))
  (|SetAElt| t4 (the |SInt| 18) (|MakeLit| "<<"))
  (|SetAElt| t3 (the |SInt| 19) (the |SInt| 746853960))
  (|SetAElt| t4 (the |SInt| 19) (|MakeLit| "hash"))
  (|SetAElt| t3 (the |SInt| 20) (the |SInt| 484454270))
  (|SetAElt| t4 (the |SInt| 20) (|MakeLit| "fromJava"))
  (|SetAElt| t3 (the |SInt| 21) (the |SInt| 51500637))
  (|SetAElt| t4 (the |SInt| 21) (|MakeLit| "\\/"))
  (|SetAElt| t3 (the |SInt| 22) (the |SInt| 200101))
  (|SetAElt| t4 (the |SInt| 22) (|MakeLit| "<"))
  (setq t5 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t5 (the |SInt| 23))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t5 (the |SInt| 23))
  (|SetRElt| |Struct-bool-5| |values| 2 t5 t3)
  (setq t6 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t6 (the |SInt| 23))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t6 (the |SInt| 23))
  (|SetRElt| |Struct-bool-5| |values| 2 t6 t4)
  (|CCall| |G-rtAddStrings| t5 t6)
  (|SetLex|
    |Struct-bool-10-Conditional-3|
    3
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-bool-10-Logic-4|
    4
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 1)))
  (|SetLex|
    |Struct-bool-10-OrderedFinite-2|
    2
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 2)))
  (|SetLex|
    |Struct-bool-10-Machine-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-bool-10-dom-6|
    6
    |l0|
    (|Lex| |Struct-bool-10-Machine-1| 1 |l0|))
  (|SetLex|
    |Struct-bool-10-Bool-5|
    5
    |l0|
    (|CCall|
      |G-domainGetExport!|
      (|Lex| |Struct-bool-10-dom-6| 6 |l0|)
      (the |SInt| 988818480)
      (the |SInt| 547382598)))
  (|SetLex|
    |Struct-bool-10-Boolean-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 4)))
  (block-return |C0-bool-bool| ()))

(defprog
  ((|C1-bool-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Boolean")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 740244383))
  (block-return |C1-bool-addLevel0| (|Clos| |e0| |C2-bool-addLevel1|)))

(defprog
  ((|C2-bool-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |SInt|)
    (t14 |SInt|)
    (t15 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-bool-8| |Struct-bool-8|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (setq t0 (|ANew| |Word| (the |SInt| 26)))
  (setq t1 (|ANew| |Word| (the |SInt| 26)))
  (setq t2 (|ANew| |Word| (the |SInt| 26)))
  (setq t6 (|CCall| |G-domainMakeDispatch| |P0-domain|))
  (|SetLex| |Struct-bool-8--20| 20 |l0| |P1-hashcode|)
  (|SetLex| |Struct-bool-8-=-18| 18 |l0| (|Clos| |e0| |C4-bool-=|))
  (|SetLex| |Struct-bool-8-~=-17| 17 |l0| (|Clos| |e0| |C5-bool-~=|))
  (|SetLex| |Struct-bool-8->-16| 16 |l0| (|Clos| |e0| |C6-bool->|))
  (|SetLex| |Struct-bool-8-<-15| 15 |l0| (|Clos| |e0| |C7-bool-<|))
  (|SetLex| |Struct-bool-8-<=-14| 14 |l0| (|Clos| |e0| |C8-bool-<=|))
  (|SetLex| |Struct-bool-8->=-13| 13 |l0| (|Clos| |e0| |C9-bool->=|))
  (|SetLex| |Struct-bool-8-~-10| 10 |l0| (|Clos| |e0| |C10-bool-~|))
  (|SetLex| |Struct-bool-8-/\\-9| 9 |l0| (|Clos| |e0| |C11-bool-/\\|))
  (|SetLex| |Struct-bool-8-\\/-8| 8 |l0| (|Clos| |e0| |C12-bool-\\/|))
  (|SetLex|
    |Struct-bool-8-max-11|
    11
    |l0|
    (|Clos| |e0| |C13-bool-max|))
  (|SetLex|
    |Struct-bool-8-min-12|
    12
    |l0|
    (|Clos| |e0| |C14-bool-min|))
  (|SetLex|
    |Struct-bool-8-toJava-7|
    7
    |l0|
    (|Clos| |e0| |C15-bool-toJava|))
  (|SetLex|
    |Struct-bool-8-fromJava-6|
    6
    |l0|
    (|Clos| |e0| |C16-bool-fromJava|))
  (|SetLex|
    |Struct-bool-8-test-5|
    5
    |l0|
    (|Clos| |e0| |C17-bool-test|))
  (|SetLex| |Struct-bool-8-<<-3| 3 |l0| (|Clos| |e0| |C18-bool-<<|))
  (|SetLex|
    |Struct-bool-8-hash-2|
    2
    |l0|
    (|Clos| |e0| |C19-bool-hash|))
  (|SetLex| |Struct-bool-8-<<-4| 4 |l0| (|Clos| |e0| |C20-bool-<<|))
  (|SetLex|
    |Struct-bool-8-case-1|
    1
    |l0|
    (|Clos| |e0| |C22-bool-case|))
  (|SetLex| |Struct-bool-8-xor-0| 0 |l0| (|Clos| |e0| |C23-bool-xor|))
  (setq
    t14
    (|SIntHashCombine|
      (|Lex| |Struct-bool-8--20| 20 |l0|)
      (the |SInt| 51489085)))
  (setq
    t8
    (|SIntHashCombine|
      (the |SInt| 740244383)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine| (|Lex| |Struct-bool-8--20| 20 |l0|) t14))))
  (setq t15 (|SIntHashCombine| (the |SInt| 32236) t14))
  (setq t9 (|SIntHashCombine| (|Lex| |Struct-bool-8--20| 20 |l0|) t15))
  (setq
    t10
    (|SIntHashCombine|
      (the |SInt| 182752316)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-bool-8--20| 20 |l0|)
          (the |SInt| 102896482)))))
  (setq t11 (|SIntHashCombine| (the |SInt| 33717313) t15))
  (setq t12 (|SIntHashCombine| (the |SInt| 755420535) t15))
  (setq t13 (|Lex| |Struct-bool-8--20| 20 |l0|))
  (setq t3 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t3 (the |SInt| 26))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t3 (the |SInt| 26))
  (|SetRElt| |Struct-bool-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t4 (the |SInt| 26))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t4 (the |SInt| 26))
  (|SetRElt| |Struct-bool-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t5 (the |SInt| 26))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t5 (the |SInt| 26))
  (|SetRElt| |Struct-bool-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|CCall|
    |G-domainAddDefaults!|
    |P0-domain|
    (|CCall|
      |G-categoryMake|
      (|Clos| |e0| |C3-bool-bool|)
      (|CCall| |G-rtConstSIntFn| (the |SInt| 740244383))
      (|CCall| |G-rtConstNameFn| (|MakeLit| "Boolean")))
    t6)
  (|SetLex|
    |Struct-bool-8-Rep-19|
    19
    |l0|
    (|CCall| |G-domainMakeDummy|))
  (setq t7 (|Lex| |Struct-bool-8-Rep-19| 19 |l0|))
  (|SetLex|
    |Struct-bool-8-Rep-19|
    19
    |l0|
    (|Lex| |Struct-bool-10-Bool-5| 5 |l2|))
  (|CCall| |G-domainFill!| t7 (|Lex| |Struct-bool-8-Rep-19| 19 |l0|))
  (|SetLex| |Struct-bool-8-Rep-19| 19 |l0| t7)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 316169058))
  (|SetAElt| t1 (the |SInt| 0) (the |SInt| 547382598))
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-bool-8-Rep-19| 19 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 200102))
  (|SetAElt| t1 (the |SInt| 1) t8)
  (|SetAElt| t2 (the |SInt| 1) (|Lex| |Struct-bool-8-=-18| 18 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 51509389))
  (|SetAElt| t1 (the |SInt| 2) t8)
  (|SetAElt| t2 (the |SInt| 2) (|Lex| |Struct-bool-8-~=-17| 17 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 200103))
  (|SetAElt| t1 (the |SInt| 3) t8)
  (|SetAElt| t2 (the |SInt| 3) (|Lex| |Struct-bool-8->-16| 16 |l0|))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 200101))
  (|SetAElt| t1 (the |SInt| 4) t8)
  (|SetAElt| t2 (the |SInt| 4) (|Lex| |Struct-bool-8-<-15| 15 |l0|))
  (|SetAElt| t0 (the |SInt| 5) (the |SInt| 51492427))
  (|SetAElt| t1 (the |SInt| 5) t8)
  (|SetAElt| t2 (the |SInt| 5) (|Lex| |Struct-bool-8-<=-14| 14 |l0|))
  (|SetAElt| t0 (the |SInt| 6) (the |SInt| 51492941))
  (|SetAElt| t1 (the |SInt| 6) t8)
  (|SetAElt| t2 (the |SInt| 6) (|Lex| |Struct-bool-8->=-13| 13 |l0|))
  (|SetAElt| t0 (the |SInt| 7) (the |SInt| 200167))
  (|SetAElt| t1 (the |SInt| 7) t9)
  (|SetAElt| t2 (the |SInt| 7) (|Lex| |Struct-bool-8-~-10| 10 |l0|))
  (|SetAElt| t0 (the |SInt| 8) (the |SInt| 51487581))
  (|SetAElt| t1 (the |SInt| 8) t8)
  (|SetAElt| t2 (the |SInt| 8) (|Lex| |Struct-bool-8-/\\-9| 9 |l0|))
  (|SetAElt| t0 (the |SInt| 9) (the |SInt| 51500637))
  (|SetAElt| t1 (the |SInt| 9) t8)
  (|SetAElt| t2 (the |SInt| 9) (|Lex| |Struct-bool-8-\\/-8| 8 |l0|))
  (|SetAElt| t0 (the |SInt| 10) (the |SInt| 318461825))
  (|SetAElt| t1 (the |SInt| 10) t8)
  (|SetAElt|
    t2
    (the |SInt| 10)
    (|Lex| |Struct-bool-8-max-11| 11 |l0|))
  (|SetAElt| t0 (the |SInt| 11) (the |SInt| 318459775))
  (|SetAElt| t1 (the |SInt| 11) t8)
  (|SetAElt|
    t2
    (the |SInt| 11)
    (|Lex| |Struct-bool-8-min-12| 12 |l0|))
  (|SetAElt| t0 (the |SInt| 12) (the |SInt| 445790171))
  (|SetAElt|
    t1
    (the |SInt| 12)
    (|SIntHashCombine|
      (the |SInt| 988818480)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-bool-8--20| 20 |l0|)
          (the |SInt| 51489085)))))
  (|SetAElt|
    t2
    (the |SInt| 12)
    (|Lex| |Struct-bool-8-toJava-7| 7 |l0|))
  (|SetAElt| t0 (the |SInt| 13) (the |SInt| 484454270))
  (|SetAElt|
    t1
    (the |SInt| 13)
    (|SIntHashCombine|
      (|Lex| |Struct-bool-8--20| 20 |l0|)
      (the |SInt| 896235851)))
  (|SetAElt|
    t2
    (the |SInt| 13)
    (|Lex| |Struct-bool-8-fromJava-6| 6 |l0|))
  (|SetAElt| t0 (the |SInt| 14) (the |SInt| 5509732))
  (|SetAElt| t1 (the |SInt| 14) t9)
  (|SetAElt|
    t2
    (the |SInt| 14)
    (|Lex| |Struct-bool-8-test-5| 5 |l0|))
  (|SetAElt| t0 (the |SInt| 15) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 15) t10)
  (|SetAElt| t2 (the |SInt| 15) (|Lex| |Struct-bool-8-<<-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 16) (the |SInt| 746853960))
  (|SetAElt| t1 (the |SInt| 16) t11)
  (|SetAElt|
    t2
    (the |SInt| 16)
    (|Lex| |Struct-bool-8-hash-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 17) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 17) t12)
  (|SetAElt| t2 (the |SInt| 17) (|Lex| |Struct-bool-8-<<-4| 4 |l0|))
  (|SetAElt| t0 (the |SInt| 18) (the |SInt| 864625472))
  (|SetAElt| t1 (the |SInt| 18) t8)
  (|SetAElt|
    t2
    (the |SInt| 18)
    (|Lex| |Struct-bool-8-case-1| 1 |l0|))
  (|SetAElt| t0 (the |SInt| 19) (the |SInt| 317608340))
  (|SetAElt| t1 (the |SInt| 19) t8)
  (|SetAElt| t2 (the |SInt| 19) (|Lex| |Struct-bool-8-xor-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 20) (the |SInt| 200076))
  (|SetAElt| t1 (the |SInt| 20) (the |SInt| 484208045))
  (|SetAElt| t2 (the |SInt| 20) (the |BInt| 2))
  (|SetAElt| t0 (the |SInt| 21) (the |SInt| 318459775))
  (|SetAElt| t1 (the |SInt| 21) t13)
  (|SetAElt| t2 (the |SInt| 21) (the |Bool| nil))
  (|SetAElt| t0 (the |SInt| 22) (the |SInt| 318461825))
  (|SetAElt| t1 (the |SInt| 22) t13)
  (|SetAElt| t2 (the |SInt| 22) (the |Bool| t))
  (|SetAElt| t0 (the |SInt| 23) (the |SInt| 13900568))
  (|SetAElt| t1 (the |SInt| 23) t13)
  (|SetAElt| t2 (the |SInt| 23) (the |Bool| nil))
  (|SetAElt| t0 (the |SInt| 24) (the |SInt| 11137124))
  (|SetAElt| t1 (the |SInt| 24) t13)
  (|SetAElt| t2 (the |SInt| 24) (the |Bool| t))
  (|SetAElt| t0 (the |SInt| 25) (the |SInt| 255806968))
  (|SetAElt| t1 (the |SInt| 25) t13)
  (|SetAElt| t2 (the |SInt| 25) (the |Bool| t))
  (block-return |C2-bool-addLevel1| |P0-domain|))

(defprog
  ((|C3-bool-bool|) ((|P0-self| |Word|) (|P1-dom| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Arr|)
    (t7 |Record|)
    (|e3| |Env|)
    (|l3| |Level|))
  (setq |e3| (|EnvNext| (|EnvNext| |e1|)))
  (setq |l3| (|EnvLevel| |e3|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t6 (|ANew| |Word| (the |SInt| 3)))
  (setq t3 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-bool-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-bool-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-bool-5| |values| 2 t5 t2)
  (|CCall| |G-categoryAddExports!| |P0-self| t3 t4 t5)
  (|SetAElt|
    t6
    (the |SInt| 0)
    (|Lex| |Struct-bool-10-Conditional-3| 3 |l3|))
  (|SetAElt|
    t6
    (the |SInt| 1)
    (|Lex| |Struct-bool-10-Logic-4| 4 |l3|))
  (|SetAElt|
    t6
    (the |SInt| 2)
    (|Lex| |Struct-bool-10-OrderedFinite-2| 2 |l3|))
  (setq t7 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t7 (the |SInt| 3))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t7 (the |SInt| 3))
  (|SetRElt| |Struct-bool-5| |values| 2 t7 t6)
  (|CCall| |G-categoryAddParents!| |P0-self| t7 |P1-dom|)
  (block-return |C3-bool-bool| ()))

(defprog
  ((|C4-bool-=| |Word|) ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C4-bool-=| (|BoolEQ| |P0-a| |P1-b|)))

(defprog
  ((|C5-bool-~=| |Word|) ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C5-bool-~=| (|BoolNE| |P0-a| |P1-b|)))

(defprog
  ((|C6-bool->| |Word|) ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C6-bool->| (|BoolAnd| |P0-a| (|BoolNot| |P1-b|))))

(defprog
  ((|C7-bool-<| |Word|) ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C7-bool-<| (|BoolAnd| (|BoolNot| |P0-a|) |P1-b|)))

(defprog
  ((|C8-bool-<=| |Word|) ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C8-bool-<=| (|BoolOr| (|BoolNot| |P0-a|) |P1-b|)))

(defprog
  ((|C9-bool->=| |Word|) ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C9-bool->=| (|BoolOr| |P0-a| (|BoolNot| |P1-b|))))

(defprog
  ((|C10-bool-~| |Word|) ((|P0-a| |Word|) (|e1| |Env|)))
  ()
  (block-return |C10-bool-~| (|BoolNot| |P0-a|)))

(defprog
  ((|C11-bool-/\\| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C11-bool-/\\| (|BoolAnd| |P0-a| |P1-b|)))

(defprog
  ((|C12-bool-\\/| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C12-bool-\\/| (|BoolOr| |P0-a| |P1-b|)))

(defprog
  ((|C13-bool-max| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C13-bool-max| (|BoolOr| |P0-a| |P1-b|)))

(defprog
  ((|C14-bool-min| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C14-bool-min| (|BoolAnd| |P0-a| |P1-b|)))

(defprog
  ((|C15-bool-toJava| |Bool|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C15-bool-toJava| |P0-i|))

(defprog
  ((|C16-bool-fromJava| |Word|) ((|P0-i| |Bool|) (|e1| |Env|)))
  ()
  (block-return |C16-bool-fromJava| |P0-i|))

(defprog
  ((|C17-bool-test| |Word|) ((|P0-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C17-bool-test| |P0-b|))

(defprog
  ((|C18-bool-<<| |Word|)
    ((|P0-p| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ((t0 |Word|) (t1 |Clos|) (t2 |Clos|) (t3 |Clos|))
  (tagbody
    (when |P1-b| (go |Lab0|))
    (setq t0 (|MakeLit| "false"))
    |Lab1|
    (multiple-value-setq (t1 t2 t3) (|CCall| |P0-p|))
    (|CCall| t2 t0 (the |SInt| 1) (the |SInt| 0))
    (block-return |C18-bool-<<| |P0-p|)
    |Lab0|
    (setq t0 (|MakeLit| "true"))
    (go |Lab1|)))

(defprog
  ((|C19-bool-hash| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ()
  (block-return |C19-bool-hash| (the |SInt| 0)))

(defprog
  ((|C20-bool-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-bool-7| |Struct-bool-7|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-bool-7-x-0| 0 |l0| |P0-x|)
  (block-return |C20-bool-<<| (|Clos| |e0| |C21-bool-<<|)))

(defprog
  ((|C21-bool-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Bool|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t4 (|Lex| |Struct-bool-7-x-0| 0 |l1|))
    (when t4 (go |Lab0|))
    (setq t0 (|MakeLit| "false"))
    |Lab1|
    (multiple-value-setq (t1 t2 t3) (|CCall| |P0-p|))
    (|CCall| t2 t0 (the |SInt| 1) (the |SInt| 0))
    (block-return |C21-bool-<<| |P0-p|)
    |Lab0|
    (setq t0 (|MakeLit| "true"))
    (go |Lab1|)))

(defprog
  ((|C22-bool-case| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ()
  (block-return |C22-bool-case| (|BoolEQ| |P0-x| |P1-y|)))

(defprog
  ((|C23-bool-xor| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |Bool|))
  (setq t0 (|BoolAnd| |P0-x| (|BoolNot| |P1-y|)))
  (block-return
    |C23-bool-xor|
    (|BoolOr| t0 (|BoolAnd| (|BoolNot| |P0-x|) |P1-y|))))

(defprog
  ((|C24-bool-extend0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Arr|) (t1 |Record|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t0 (|ANew| |Word| (the |SInt| 2)))
  (|SetAElt|
    t0
    (the |SInt| 1)
    (|Lex| |Struct-bool-10-Boolean-0| 0 |l1|))
  (|SetAElt| t0 (the |SInt| 0) |G-bool_Boolean_186642606|)
  (setq t1 (|RNew| |Struct-bool-5|))
  (|SetRElt| |Struct-bool-5| |size| 0 t1 (the |SInt| 2))
  (|SetRElt| |Struct-bool-5| |nsize| 1 t1 (the |SInt| 2))
  (|SetRElt| |Struct-bool-5| |values| 2 t1 t0)
  (|CCall| |G-extendFill!| |P0-domain| t1)
  (block-return |C24-bool-extend0| nil))

(defprog
  ((|C25-bool-machine-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-bool-10--7| 7 |l1|) (go |Lab0|))
    (|SetLex| |Struct-bool-10--7| 7 |l1| (the |Bool| t))
    (|CCall| |G-machine|)
    |Lab0|
    (block-return |C25-bool-machine-init| |G-machine_Machine_915715331|)))

(defprog
  ((|C26-bool-basic-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-bool-10--8| 8 |l1|) (go |Lab0|))
    (|SetLex| |Struct-bool-10--8| 8 |l1| (the |Bool| t))
    (|CCall| |G-basic|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 4)) (go |Lab1|))
    (block-return |C26-bool-basic-init| |G-basic_Boolean_727749971|)
    |Lab1|
    (when (|SIntNE| |P0-idx| (the |SInt| 3)) (go |Lab2|))
    (block-return |C26-bool-basic-init| |G-basic_Integer_117694970|)
    |Lab2|
    (when (|SIntNE| |P0-idx| (the |SInt| 2)) (go |Lab3|))
    (block-return
      |C26-bool-basic-init|
      |G-basic_MachineInteger_885893404|)
    |Lab3|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab4|))
    (block-return |C26-bool-basic-init| |G-basic_TextWriter_360221334|)
    |Lab4|
    (block-return |C26-bool-basic-init| |G-basic_String_641272169|)))

(defprog
  ((|C27-bool-foamcat-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-bool-10--9| 9 |l1|) (go |Lab0|))
    (|SetLex| |Struct-bool-10--9| 9 |l1| (the |Bool| t))
    (|CCall| |G-foamcat|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 2)) (go |Lab1|))
    (block-return
      |C27-bool-foamcat-init|
      |G-foamcat_OrderedFinite_544701037|)
    |Lab1|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab2|))
    (block-return |C27-bool-foamcat-init| |G-foamcat_Logic_688403051|)
    |Lab2|
    (block-return
      |C27-bool-foamcat-init|
      |G-foamcat_Conditional_436267619|)))

(setq |G-bool| (|Clos| nil |C0-bool-bool|))

(setq |G-bool_Boolean_186642606| nil)

(setq |G-bool_Boolean_111100038| nil)

(setq |C28-bool-#| (the |BInt| 2))

(setq |C29-bool-min| (the |Bool| nil))

(setq |C30-bool-max| (the |Bool| t))

(setq |C31-bool-false| (the |Bool| nil))

(setq |C32-bool-true| (the |Bool| t))

(setq |C33-bool-sample| (the |Bool| t))

(file-imports
  '((|G-foamcat| "foamcat" |initializer| "")
      (|G-basic| "basic" |initializer| "")
      (|G-machine| "machine" |initializer| "")
      (|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-extendMake| "extendMake" 0 "")
      (|G-extendFill!| "extendFill!" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-basic_Boolean_727749971| "Boolean" 727749971 "basic")
      (|G-basic_Integer_117694970| "Integer" 117694970 "basic")
      (|G-basic_MachineInteger_885893404|
        "MachineInteger"
        885893404
        "basic")
      (|G-basic_TextWriter_360221334| "TextWriter" 360221334 "basic")
      (|G-basic_String_641272169| "String" 641272169 "basic")
      (|G-domainFill!| "domainFill!" 0 "")
      (|G-domainMakeDummy| "domainMakeDummy" 0 "")
      (|G-domainAddDefaults!| "domainAddDefaults!" 0 "")
      (|G-categoryMake| "categoryMake" 0 "")
      (|G-domainGetExport!| "domainGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-machine_Machine_915715331| "Machine" 915715331 "machine")
      (|G-categoryAddParents!| "categoryAddParents!" 0 "")
      (|G-foamcat_OrderedFinite_544701037|
        "OrderedFinite"
        544701037
        "foamcat")
      (|G-foamcat_Logic_688403051| "Logic" 688403051 "foamcat")
      (|G-rtLazyCatFrInit| "rtLazyCatFrInit" 0 "")
      (|G-foamcat_Conditional_436267619| "Conditional" 436267619 "foamcat")
      (|G-categoryAddExports!| "categoryAddExports!" 0 "")
      (|G-rtConstSIntFn| "rtConstSIntFn" 0 "")
      (|G-domainMakeDispatch| "domainMakeDispatch" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-bool_Boolean_111100038| "Boolean" 111100038 "bool")
      (|G-bool_Boolean_186642606| "Boolean" 186642606 "bool")
      (|G-bool| "bool" |initializer| "")))
