;;;
;;; Lisp code generated by Aldor from file "character.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-character-character|) ((|e1| |Env|)))

(declare-prog
  (|C1-character-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-character-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-character-digit?| |Word|)
  ((|P0-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-character-letter?| |Word|)
  ((|P0-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-character-=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-character-~=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C7-character-<| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C8-character->| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-character-<=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-character->=| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))

(declare-prog
  (|C11-character-lower| |Word|)
  ((|P0-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C12-character-upper| |Word|)
  ((|P0-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C13-character-<<| |Word|)
  ((|P0-w| |Word|) (|P1-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-character-<<| |Clos|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C15-character-<<| |Word|)
  ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C16-character-hash| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C17-character-case| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C18-character-max| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C19-character-min| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C20-character-extend0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C21-character-machine-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C22-character-basic-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C23-character-foamcat-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-character| |Clos|)

(declare-type |G-character_Character_1042150609| |Word|)

(declare-type |G-character_Character_086019548| |Word|)

(defspecials
  |G-character_Character_086019548|
  |G-character_Character_1042150609|)

(|DDecl|
  |Struct-character-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl| |Struct-character-6| (|x-0| |Word|))

(|DDecl|
  |Struct-character-7|
  (|case-0| |Clos|)
  (|hash-1| |Clos|)
  (<<-2 |Clos|)
  (<<-3 |Clos|)
  (|upper-4| |Clos|)
  (|lower-5| |Clos|)
  (>=-6 |Clos|)
  (<=-7 |Clos|)
  (>-8 |Clos|)
  (<-9 |Clos|)
  (~=-10 |Clos|)
  (=-11 |Clos|)
  (|letter?-12| |Clos|)
  (|digit?-13| |Clos|)
  (|#-14| |Word|)
  (|max-15| |Word|)
  (|max-16| |Clos|)
  (|min-17| |Word|)
  (|min-18| |Clos|)
  (|Rep-19| |Word|)
  (\-20 |SInt|))

(|DDecl|
  |Struct-character-9|
  (|Character-0| |Word|)
  (|Machine-1| |Word|)
  (|OrderedFinite-2| |Word|)
  (|Char-3| |Word|)
  (|max-4| |Word|)
  (|min-5| |Word|)
  (|dom-6| |Word|)
  (\-7 |Bool|)
  (\-8 |Bool|)
  (\-9 |Bool|))

(|DDecl| |Struct-character-10| (\-0 |Clos|) (\-1 |Clos|) (\-2 |Clos|))

(defprog
  ((|C0-character-character|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Arr|)
    (t4 |Arr|)
    (t5 |Record|)
    (t6 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-character-9| |Struct-character-9|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-character| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C23-character-foamcat-init|))
  (setq t1 (|Clos| |e0| |C21-character-machine-init|))
  (setq t2 (|Clos| |e0| |C22-character-basic-init|))
  (setq
    |G-character_Character_1042150609|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-character-addLevel0|)))
  (setq
    |G-character_Character_086019548|
    (|CCall| |G-extendMake| (|Clos| |e0| |C20-character-extend0|)))
  (|SetLex| |Struct-character-9--7| 7 |l0| (the |Bool| nil))
  (|SetLex| |Struct-character-9--8| 8 |l0| (the |Bool| nil))
  (|SetLex| |Struct-character-9--9| 9 |l0| (the |Bool| nil))
  (setq t3 (|ANew| |Word| (the |SInt| 21)))
  (setq t4 (|ANew| |Word| (the |SInt| 21)))
  (|SetAElt| t3 (the |SInt| 0) (the |SInt| 315787122))
  (|SetAElt| t4 (the |SInt| 0) (|MakeLit| "tab"))
  (|SetAElt| t3 (the |SInt| 1) (the |SInt| 51492427))
  (|SetAElt| t4 (the |SInt| 1) (|MakeLit| "<="))
  (|SetAElt| t3 (the |SInt| 2) (the |SInt| 200102))
  (|SetAElt| t4 (the |SInt| 2) (|MakeLit| "="))
  (|SetAElt| t3 (the |SInt| 3) (the |SInt| 200103))
  (|SetAElt| t4 (the |SInt| 3) (|MakeLit| ">"))
  (|SetAElt| t3 (the |SInt| 4) (the |SInt| 51509389))
  (|SetAElt| t4 (the |SInt| 4) (|MakeLit| "~="))
  (|SetAElt| t3 (the |SInt| 5) (the |SInt| 158725806))
  (|SetAElt| t4 (the |SInt| 5) (|MakeLit| "letter?"))
  (|SetAElt| t3 (the |SInt| 6) (the |SInt| 200076))
  (|SetAElt| t4 (the |SInt| 6) (|MakeLit| "#"))
  (|SetAElt| t3 (the |SInt| 7) (the |SInt| 316169058))
  (|SetAElt| t4 (the |SInt| 7) (|MakeLit| "Rep"))
  (|SetAElt| t3 (the |SInt| 8) (the |SInt| 318461825))
  (|SetAElt| t4 (the |SInt| 8) (|MakeLit| "max"))
  (|SetAElt| t3 (the |SInt| 9) (the |SInt| 493486801))
  (|SetAElt| t4 (the |SInt| 9) (|MakeLit| "newline"))
  (|SetAElt| t3 (the |SInt| 10) (the |SInt| 51492941))
  (|SetAElt| t4 (the |SInt| 10) (|MakeLit| ">="))
  (|SetAElt| t3 (the |SInt| 11) (the |SInt| 814719174))
  (|SetAElt| t4 (the |SInt| 11) (|MakeLit| "digit?"))
  (|SetAElt| t3 (the |SInt| 12) (the |SInt| 318459775))
  (|SetAElt| t4 (the |SInt| 12) (|MakeLit| "min"))
  (|SetAElt| t3 (the |SInt| 13) (the |SInt| 255806968))
  (|SetAElt| t4 (the |SInt| 13) (|MakeLit| "sample"))
  (|SetAElt| t3 (the |SInt| 14) (the |SInt| 864625472))
  (|SetAElt| t4 (the |SInt| 14) (|MakeLit| "case"))
  (|SetAElt| t3 (the |SInt| 15) (the |SInt| 983329337))
  (|SetAElt| t4 (the |SInt| 15) (|MakeLit| "upper"))
  (|SetAElt| t3 (the |SInt| 16) (the |SInt| 800877593))
  (|SetAElt| t4 (the |SInt| 16) (|MakeLit| "space"))
  (|SetAElt| t3 (the |SInt| 17) (the |SInt| 239585078))
  (|SetAElt| t4 (the |SInt| 17) (|MakeLit| "lower"))
  (|SetAElt| t3 (the |SInt| 18) (the |SInt| 746853960))
  (|SetAElt| t4 (the |SInt| 18) (|MakeLit| "hash"))
  (|SetAElt| t3 (the |SInt| 19) (the |SInt| 51492426))
  (|SetAElt| t4 (the |SInt| 19) (|MakeLit| "<<"))
  (|SetAElt| t3 (the |SInt| 20) (the |SInt| 200101))
  (|SetAElt| t4 (the |SInt| 20) (|MakeLit| "<"))
  (setq t5 (|RNew| |Struct-character-5|))
  (|SetRElt| |Struct-character-5| |size| 0 t5 (the |SInt| 21))
  (|SetRElt| |Struct-character-5| |nsize| 1 t5 (the |SInt| 21))
  (|SetRElt| |Struct-character-5| |values| 2 t5 t3)
  (setq t6 (|RNew| |Struct-character-5|))
  (|SetRElt| |Struct-character-5| |size| 0 t6 (the |SInt| 21))
  (|SetRElt| |Struct-character-5| |nsize| 1 t6 (the |SInt| 21))
  (|SetRElt| |Struct-character-5| |values| 2 t6 t4)
  (|CCall| |G-rtAddStrings| t5 t6)
  (|SetLex|
    |Struct-character-9-OrderedFinite-2|
    2
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-character-9-Machine-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-character-9-dom-6|
    6
    |l0|
    (|Lex| |Struct-character-9-Machine-1| 1 |l0|))
  (|SetLex|
    |Struct-character-9-Char-3|
    3
    |l0|
    (|CCall|
      |G-domainGetExport!|
      (|Lex| |Struct-character-9-dom-6| 6 |l0|)
      (the |SInt| 321172770)
      (the |SInt| 547382598)))
  (|SetLex|
    |Struct-character-9-Character-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 2)))
  (|SetLex|
    |Struct-character-9-min-5|
    5
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-character-9-dom-6| 6 |l0|)
      (the |SInt| 318459775)
      (the |SInt| 321172770)))
  (|SetLex|
    |Struct-character-9-max-4|
    4
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-character-9-dom-6| 6 |l0|)
      (the |SInt| 318461825)
      (the |SInt| 321172770)))
  (block-return |C0-character-character| ()))

(defprog
  ((|C1-character-addLevel0| |Clos|)
    ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Character")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 803414590))
  (block-return
    |C1-character-addLevel0|
    (|Clos| |e0| |C2-character-addLevel1|)))

(defprog
  ((|C2-character-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |SInt|)
    (t14 |SInt|)
    (t15 |SInt|)
    (t16 |SInt|)
    (t17 |SInt|)
    (t18 |SInt|)
    (t19 |SInt|)
    (t20 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-character-7| |Struct-character-7|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (setq t0 (|ANew| |Word| (the |SInt| 24)))
  (setq t1 (|ANew| |Word| (the |SInt| 24)))
  (setq t2 (|ANew| |Word| (the |SInt| 24)))
  (setq t6 (|CCall| |G-domainMakeDispatch| |P0-domain|))
  (|SetLex| |Struct-character-7--20| 20 |l0| |P1-hashcode|)
  (|SetLex|
    |Struct-character-7-digit?-13|
    13
    |l0|
    (|Clos| |e0| |C3-character-digit?|))
  (|SetLex|
    |Struct-character-7-letter?-12|
    12
    |l0|
    (|Clos| |e0| |C4-character-letter?|))
  (|SetLex|
    |Struct-character-7-=-11|
    11
    |l0|
    (|Clos| |e0| |C5-character-=|))
  (|SetLex|
    |Struct-character-7-~=-10|
    10
    |l0|
    (|Clos| |e0| |C6-character-~=|))
  (|SetLex|
    |Struct-character-7-<-9|
    9
    |l0|
    (|Clos| |e0| |C7-character-<|))
  (|SetLex|
    |Struct-character-7->-8|
    8
    |l0|
    (|Clos| |e0| |C8-character->|))
  (|SetLex|
    |Struct-character-7-<=-7|
    7
    |l0|
    (|Clos| |e0| |C9-character-<=|))
  (|SetLex|
    |Struct-character-7->=-6|
    6
    |l0|
    (|Clos| |e0| |C10-character->=|))
  (|SetLex|
    |Struct-character-7-lower-5|
    5
    |l0|
    (|Clos| |e0| |C11-character-lower|))
  (|SetLex|
    |Struct-character-7-upper-4|
    4
    |l0|
    (|Clos| |e0| |C12-character-upper|))
  (|SetLex|
    |Struct-character-7-<<-2|
    2
    |l0|
    (|Clos| |e0| |C13-character-<<|))
  (|SetLex|
    |Struct-character-7-<<-3|
    3
    |l0|
    (|Clos| |e0| |C14-character-<<|))
  (|SetLex|
    |Struct-character-7-hash-1|
    1
    |l0|
    (|Clos| |e0| |C16-character-hash|))
  (|SetLex|
    |Struct-character-7-case-0|
    0
    |l0|
    (|Clos| |e0| |C17-character-case|))
  (|SetLex|
    |Struct-character-7-max-16|
    16
    |l0|
    (|Clos| |e0| |C18-character-max|))
  (|SetLex|
    |Struct-character-7-min-18|
    18
    |l0|
    (|Clos| |e0| |C19-character-min|))
  (setq
    t17
    (|SIntHashCombine|
      (|Lex| |Struct-character-7--20| 20 |l0|)
      (the |SInt| 51489085)))
  (setq t18 (|SIntHashCombine| (the |SInt| 32236) t17))
  (setq t8 (|SIntHashCombine| (the |SInt| 740244383) t18))
  (setq
    t19
    (|SIntHashCombine| (|Lex| |Struct-character-7--20| 20 |l0|) t17))
  (setq t20 (|SIntHashCombine| (the |SInt| 32236) t19))
  (setq t9 (|SIntHashCombine| (the |SInt| 740244383) t20))
  (setq
    t10
    (|SIntHashCombine| (|Lex| |Struct-character-7--20| 20 |l0|) t18))
  (setq
    t11
    (|SIntHashCombine|
      (the |SInt| 182752316)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-character-7--20| 20 |l0|)
          (the |SInt| 102896482)))))
  (setq t12 (|SIntHashCombine| (the |SInt| 755420535) t18))
  (setq t13 (|SIntHashCombine| (the |SInt| 33717313) t18))
  (setq
    t14
    (|SIntHashCombine| (|Lex| |Struct-character-7--20| 20 |l0|) t20))
  (setq t15 (|Lex| |Struct-character-7--20| 20 |l0|))
  (setq t3 (|RNew| |Struct-character-5|))
  (|SetRElt| |Struct-character-5| |size| 0 t3 (the |SInt| 24))
  (|SetRElt| |Struct-character-5| |nsize| 1 t3 (the |SInt| 24))
  (|SetRElt| |Struct-character-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-character-5|))
  (|SetRElt| |Struct-character-5| |size| 0 t4 (the |SInt| 24))
  (|SetRElt| |Struct-character-5| |nsize| 1 t4 (the |SInt| 24))
  (|SetRElt| |Struct-character-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-character-5|))
  (|SetRElt| |Struct-character-5| |size| 0 t5 (the |SInt| 24))
  (|SetRElt| |Struct-character-5| |nsize| 1 t5 (the |SInt| 24))
  (|SetRElt| |Struct-character-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|CCall|
    |G-domainAddDefaults!|
    |P0-domain|
    (|Lex| |Struct-character-9-OrderedFinite-2| 2 |l2|)
    t6)
  (|SetLex|
    |Struct-character-7-Rep-19|
    19
    |l0|
    (|CCall| |G-domainMakeDummy|))
  (setq t7 (|Lex| |Struct-character-7-Rep-19| 19 |l0|))
  (|SetLex|
    |Struct-character-7-Rep-19|
    19
    |l0|
    (|Lex| |Struct-character-9-Char-3| 3 |l2|))
  (|CCall|
    |G-domainFill!|
    t7
    (|Lex| |Struct-character-7-Rep-19| 19 |l0|))
  (|SetLex| |Struct-character-7-Rep-19| 19 |l0| t7)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 316169058))
  (|SetAElt| t1 (the |SInt| 0) (the |SInt| 547382598))
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-character-7-Rep-19| 19 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 814719174))
  (|SetAElt| t1 (the |SInt| 1) t8)
  (|SetAElt|
    t2
    (the |SInt| 1)
    (|Lex| |Struct-character-7-digit?-13| 13 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 158725806))
  (|SetAElt| t1 (the |SInt| 2) t8)
  (|SetAElt|
    t2
    (the |SInt| 2)
    (|Lex| |Struct-character-7-letter?-12| 12 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 200102))
  (|SetAElt| t1 (the |SInt| 3) t9)
  (|SetAElt|
    t2
    (the |SInt| 3)
    (|Lex| |Struct-character-7-=-11| 11 |l0|))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 51509389))
  (|SetAElt| t1 (the |SInt| 4) t9)
  (|SetAElt|
    t2
    (the |SInt| 4)
    (|Lex| |Struct-character-7-~=-10| 10 |l0|))
  (|SetAElt| t0 (the |SInt| 5) (the |SInt| 200101))
  (|SetAElt| t1 (the |SInt| 5) t9)
  (|SetAElt|
    t2
    (the |SInt| 5)
    (|Lex| |Struct-character-7-<-9| 9 |l0|))
  (|SetAElt| t0 (the |SInt| 6) (the |SInt| 200103))
  (|SetAElt| t1 (the |SInt| 6) t9)
  (|SetAElt|
    t2
    (the |SInt| 6)
    (|Lex| |Struct-character-7->-8| 8 |l0|))
  (|SetAElt| t0 (the |SInt| 7) (the |SInt| 51492427))
  (|SetAElt| t1 (the |SInt| 7) t9)
  (|SetAElt|
    t2
    (the |SInt| 7)
    (|Lex| |Struct-character-7-<=-7| 7 |l0|))
  (|SetAElt| t0 (the |SInt| 8) (the |SInt| 51492941))
  (|SetAElt| t1 (the |SInt| 8) t9)
  (|SetAElt|
    t2
    (the |SInt| 8)
    (|Lex| |Struct-character-7->=-6| 6 |l0|))
  (|SetAElt| t0 (the |SInt| 9) (the |SInt| 239585078))
  (|SetAElt| t1 (the |SInt| 9) t10)
  (|SetAElt|
    t2
    (the |SInt| 9)
    (|Lex| |Struct-character-7-lower-5| 5 |l0|))
  (|SetAElt| t0 (the |SInt| 10) (the |SInt| 983329337))
  (|SetAElt| t1 (the |SInt| 10) t10)
  (|SetAElt|
    t2
    (the |SInt| 10)
    (|Lex| |Struct-character-7-upper-4| 4 |l0|))
  (|SetAElt| t0 (the |SInt| 11) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 11) t11)
  (|SetAElt|
    t2
    (the |SInt| 11)
    (|Lex| |Struct-character-7-<<-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 12) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 12) t12)
  (|SetAElt|
    t2
    (the |SInt| 12)
    (|Lex| |Struct-character-7-<<-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 13) (the |SInt| 746853960))
  (|SetAElt| t1 (the |SInt| 13) t13)
  (|SetAElt|
    t2
    (the |SInt| 13)
    (|Lex| |Struct-character-7-hash-1| 1 |l0|))
  (|SetAElt| t0 (the |SInt| 14) (the |SInt| 864625472))
  (|SetAElt| t1 (the |SInt| 14) t9)
  (|SetAElt|
    t2
    (the |SInt| 14)
    (|Lex| |Struct-character-7-case-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 15) (the |SInt| 318461825))
  (|SetAElt| t1 (the |SInt| 15) t14)
  (|SetAElt|
    t2
    (the |SInt| 15)
    (|Lex| |Struct-character-7-max-16| 16 |l0|))
  (|SetAElt| t0 (the |SInt| 16) (the |SInt| 318459775))
  (|SetAElt| t1 (the |SInt| 16) t14)
  (|SetAElt|
    t2
    (the |SInt| 16)
    (|Lex| |Struct-character-7-min-18| 18 |l0|))
  (|SetAElt| t0 (the |SInt| 17) (the |SInt| 255806968))
  (|SetAElt| t1 (the |SInt| 17) t15)
  (|SetAElt| t2 (the |SInt| 17) (the |Char| #\Space))
  (|SetAElt| t0 (the |SInt| 18) (the |SInt| 800877593))
  (|SetAElt| t1 (the |SInt| 18) t15)
  (|SetAElt| t2 (the |SInt| 18) (the |Char| #\Space))
  (|SetAElt| t0 (the |SInt| 19) (the |SInt| 493486801))
  (|SetAElt| t1 (the |SInt| 19) t15)
  (|SetAElt| t2 (the |SInt| 19) (the |Char| #\Newline))
  (|SetAElt| t0 (the |SInt| 20) (the |SInt| 315787122))
  (|SetAElt| t1 (the |SInt| 20) t15)
  (|SetAElt| t2 (the |SInt| 20) (the |Char| #\Tab))
  (|SetLex|
    |Struct-character-7-min-17|
    17
    |l0|
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-character-9-min-5| 5 |l2|)))
  (|SetAElt| t0 (the |SInt| 21) (the |SInt| 318459775))
  (|SetAElt| t1 (the |SInt| 21) t15)
  (|SetAElt|
    t2
    (the |SInt| 21)
    (|Lex| |Struct-character-7-min-17| 17 |l0|))
  (|SetLex|
    |Struct-character-7-max-15|
    15
    |l0|
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-character-9-max-4| 4 |l2|)))
  (|SetAElt| t0 (the |SInt| 22) (the |SInt| 318461825))
  (|SetAElt| t1 (the |SInt| 22) t15)
  (|SetAElt|
    t2
    (the |SInt| 22)
    (|Lex| |Struct-character-7-max-15| 15 |l0|))
  (setq
    t16
    (|SIntNext|
      (|SIntMinus|
        (|CharOrd|
          (|CCall|
            |G-lazyForceImport|
            (|Lex| |Struct-character-9-max-4| 4 |l2|)))
        (|CharOrd|
          (|CCall|
            |G-lazyForceImport|
            (|Lex| |Struct-character-9-min-5| 5 |l2|))))))
  (|SetLex| |Struct-character-7-#-14| 14 |l0| (|SIntToBInt| t16))
  (|SetAElt| t0 (the |SInt| 23) (the |SInt| 200076))
  (|SetAElt| t1 (the |SInt| 23) (the |SInt| 484208045))
  (|SetAElt|
    t2
    (the |SInt| 23)
    (|Lex| |Struct-character-7-#-14| 14 |l0|))
  (block-return |C2-character-addLevel1| |P0-domain|))

(defprog
  ((|C3-character-digit?| |Word|) ((|P0-c| |Word|) (|e1| |Env|)))
  ()
  (block-return |C3-character-digit?| (|CharIsDigit| |P0-c|)))

(defprog
  ((|C4-character-letter?| |Word|) ((|P0-c| |Word|) (|e1| |Env|)))
  ()
  (block-return |C4-character-letter?| (|CharIsLetter| |P0-c|)))

(defprog
  ((|C5-character-=| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C5-character-=| (|CharEQ| |P0-a| |P1-b|)))

(defprog
  ((|C6-character-~=| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C6-character-~=| (|CharNE| |P0-a| |P1-b|)))

(defprog
  ((|C7-character-<| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C7-character-<| (|CharLT| |P0-a| |P1-b|)))

(defprog
  ((|C8-character->| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C8-character->| (|CharLT| |P1-b| |P0-a|)))

(defprog
  ((|C9-character-<=| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C9-character-<=| (|CharLE| |P0-a| |P1-b|)))

(defprog
  ((|C10-character->=| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|e1| |Env|)))
  ()
  (block-return |C10-character->=| (|CharLE| |P1-b| |P0-a|)))

(defprog
  ((|C11-character-lower| |Word|) ((|P0-c| |Word|) (|e1| |Env|)))
  ()
  (block-return |C11-character-lower| (|CharLower| |P0-c|)))

(defprog
  ((|C12-character-upper| |Word|) ((|P0-c| |Word|) (|e1| |Env|)))
  ()
  (block-return |C12-character-upper| (|CharUpper| |P0-c|)))

(defprog
  ((|C13-character-<<| |Word|)
    ((|P0-w| |Word|) (|P1-c| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-w|))
  (|CCall| t0 |P1-c|)
  (block-return |C13-character-<<| |P0-w|))

(defprog
  ((|C14-character-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-character-6| |Struct-character-6|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-character-6-x-0| 0 |l0| |P0-x|)
  (block-return |C14-character-<<| (|Clos| |e0| |C15-character-<<|)))

(defprog
  ((|C15-character-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|) (t3 |Word|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t3 (|Lex| |Struct-character-6-x-0| 0 |l1|))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-p|))
  (|CCall| t0 t3)
  (block-return |C15-character-<<| |P0-p|))

(defprog
  ((|C16-character-hash| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ()
  (block-return |C16-character-hash| (the |SInt| 0)))

(defprog
  ((|C17-character-case| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ()
  (block-return |C17-character-case| (|CharEQ| |P0-x| |P1-y|)))

(defprog
  ((|C18-character-max| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |Word|))
  (tagbody
    (when (|CharLT| |P1-y| |P0-x|) (go |Lab0|))
    (setq t0 |P1-y|)
    |Lab1|
    (block-return |C18-character-max| t0)
    |Lab0|
    (setq t0 |P0-x|)
    (go |Lab1|)))

(defprog
  ((|C19-character-min| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |Word|))
  (tagbody
    (when (|CharLT| |P0-x| |P1-y|) (go |Lab0|))
    (setq t0 |P1-y|)
    |Lab1|
    (block-return |C19-character-min| t0)
    |Lab0|
    (setq t0 |P0-x|)
    (go |Lab1|)))

(defprog
  ((|C20-character-extend0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Arr|) (t1 |Record|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t0 (|ANew| |Word| (the |SInt| 2)))
  (|SetAElt|
    t0
    (the |SInt| 1)
    (|Lex| |Struct-character-9-Character-0| 0 |l1|))
  (|SetAElt| t0 (the |SInt| 0) |G-character_Character_1042150609|)
  (setq t1 (|RNew| |Struct-character-5|))
  (|SetRElt| |Struct-character-5| |size| 0 t1 (the |SInt| 2))
  (|SetRElt| |Struct-character-5| |nsize| 1 t1 (the |SInt| 2))
  (|SetRElt| |Struct-character-5| |values| 2 t1 t0)
  (|CCall| |G-extendFill!| |P0-domain| t1)
  (block-return |C20-character-extend0| nil))

(defprog
  ((|C21-character-machine-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-character-9--7| 7 |l1|) (go |Lab0|))
    (|SetLex| |Struct-character-9--7| 7 |l1| (the |Bool| t))
    (|CCall| |G-machine|)
    |Lab0|
    (block-return
      |C21-character-machine-init|
      |G-machine_Machine_915715331|)))

(defprog
  ((|C22-character-basic-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-character-9--8| 8 |l1|) (go |Lab0|))
    (|SetLex| |Struct-character-9--8| 8 |l1| (the |Bool| t))
    (|CCall| |G-basic|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 4)) (go |Lab1|))
    (block-return |C22-character-basic-init| |G-basic_Integer_117694970|)
    |Lab1|
    (when (|SIntNE| |P0-idx| (the |SInt| 3)) (go |Lab2|))
    (block-return
      |C22-character-basic-init|
      |G-basic_MachineInteger_885893404|)
    |Lab2|
    (when (|SIntNE| |P0-idx| (the |SInt| 2)) (go |Lab3|))
    (block-return
      |C22-character-basic-init|
      |G-basic_Character_415857542|)
    |Lab3|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab4|))
    (block-return
      |C22-character-basic-init|
      |G-basic_TextWriter_360221334|)
    |Lab4|
    (block-return |C22-character-basic-init| |G-basic_Boolean_727749971|)))

(defprog
  ((|C23-character-foamcat-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-character-9--9| 9 |l1|) (go |Lab0|))
    (|SetLex| |Struct-character-9--9| 9 |l1| (the |Bool| t))
    (|CCall| |G-foamcat|)
    |Lab0|
    (block-return
      |C23-character-foamcat-init|
      |G-foamcat_OrderedFinite_544701037|)))

(setq |G-character| (|Clos| nil |C0-character-character|))

(setq |G-character_Character_1042150609| nil)

(setq |G-character_Character_086019548| nil)

(setq |C24-character-sample| (the |Char| #\Space))

(setq |C25-character-space| (the |Char| #\Space))

(setq |C26-character-newline| (the |Char| #\Newline))

(setq |C27-character-tab| (the |Char| #\Tab))

(file-imports
  '((|G-foamcat| "foamcat" |initializer| "")
      (|G-basic| "basic" |initializer| "")
      (|G-machine| "machine" |initializer| "")
      (|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-extendMake| "extendMake" 0 "")
      (|G-extendFill!| "extendFill!" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-basic_Integer_117694970| "Integer" 117694970 "basic")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-basic_MachineInteger_885893404|
        "MachineInteger"
        885893404
        "basic")
      (|G-basic_Character_415857542| "Character" 415857542 "basic")
      (|G-basic_TextWriter_360221334| "TextWriter" 360221334 "basic")
      (|G-basic_Boolean_727749971| "Boolean" 727749971 "basic")
      (|G-domainGetExport!| "domainGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-machine_Machine_915715331| "Machine" 915715331 "machine")
      (|G-domainFill!| "domainFill!" 0 "")
      (|G-domainMakeDummy| "domainMakeDummy" 0 "")
      (|G-domainAddDefaults!| "domainAddDefaults!" 0 "")
      (|G-rtLazyCatFrInit| "rtLazyCatFrInit" 0 "")
      (|G-foamcat_OrderedFinite_544701037|
        "OrderedFinite"
        544701037
        "foamcat")
      (|G-domainMakeDispatch| "domainMakeDispatch" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-character_Character_086019548| "Character" 86019548 "character")
      (|G-character_Character_1042150609|
        "Character"
        1042150609
        "character")
      (|G-character| "character" |initializer| "")))
