;;;
;;; Lisp code generated by Aldor from file "file.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-file-file|) ((|e1| |Env|)))

(declare-prog
  (|C1-file-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-file-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C3-file-open| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-file-open?| |Word|)
  ((|P0-ouf| |Word|) (|e1| |Env|)))

(declare-prog (|C5-file-close|) ((|P0-ouf| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-file-write!|)
  ((|P0-ouf| |Word|) (|P1-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C7-file-write!| |Word|)
  ((|P0-ouf| |Word|)
    (|P1-s| |Word|)
    (|P2-start| |Word|)
    (|P3-limit| |Word|)
    (|e1| |Env|)))

(declare-prog
  (|C8-file-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-file-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-file-open| |Word|)
  ((|P0-fn| |Word|) (|e1| |Env|)))

(declare-prog
  (|C11-file-open?| |Word|)
  ((|P0-inf| |Word|) (|e1| |Env|)))

(declare-prog (|C12-file-close|) ((|P0-inf| |Word|) (|e1| |Env|)))

(declare-prog
  (|C13-file-readchar!| |Word|)
  ((|P0-inf| |Word|) (|P1-eof| |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-file-readline!| |Word|)
  ((|P0-inf| |Word|)
    (|P1-s| |Word|)
    (|P2-start| |Word|)
    (|P3-limit| |Word|)
    (|e1| |Env|)))

(declare-prog
  (|C15-file-readline!| |Word|)
  ((|P0-inf| |Word|) (|e1| |Env|)))

(declare-type |G-file| |Clos|)

(declare-type |G-file_OutFile_420710551| |Word|)

(declare-type |G-file_InFile_587546911| |Word|)

(defspecials |G-file_InFile_587546911| |G-file_OutFile_420710551|)

(|DDecl|
  |Struct-file-5|
  (p0-0 |Word|)
  (p1-1 |Word|)
  (\-2 |Nil|)
  (r0-3 |Word|))

(|DDecl| |Struct-file-6| (p0-0 |Word|) (\-1 |Nil|) (r0-2 |Word|))

(|DDecl|
  |Struct-file-7|
  (p0-0 |Word|)
  (p1-1 |Word|)
  (p2-2 |Word|)
  (p3-3 |Word|)
  (\-4 |Nil|)
  (r0-5 |Word|))

(|DDecl|
  |Struct-file-8|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl|
  |Struct-file-10|
  (|write!-0| |Clos|)
  (|write!-1| |Clos|)
  (|close-2| |Clos|)
  (|open?-3| |Clos|)
  (|open-4| |Clos|)
  (\-5 |SInt|))

(|DDecl|
  |Struct-file-12|
  (|readline!-0| |Clos|)
  (|readline!-1| |Clos|)
  (|readchar!-2| |Clos|)
  (|close-3| |Clos|)
  (|open?-4| |Clos|)
  (|open-5| |Clos|)
  (\-6 |SInt|))

(|DDecl|
  |Struct-file-14|
  (|dir-0| |Word|)
  (|name-1| |Word|)
  (|type-2| |Word|)
  (|native-3| |Word|))

(defprog
  ((|C0-file-file|) ((|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-file-13| |Struct-file-13|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-file| |G-noOperation|)
  (setq
    |G-file_OutFile_420710551|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-file-addLevel0|)))
  (setq
    |G-file_InFile_587546911|
    (|CCall| |G-domainMake| (|Clos| |e0| |C8-file-addLevel0|)))
  (setq t0 (|ANew| |Word| (the |SInt| 6)))
  (setq t1 (|ANew| |Word| (the |SInt| 6)))
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 664284502))
  (|SetAElt| t1 (the |SInt| 0) (|MakeLit| "open"))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 272337676))
  (|SetAElt| t1 (the |SInt| 1) (|MakeLit| "readchar!"))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 21485846))
  (|SetAElt| t1 (the |SInt| 2) (|MakeLit| "readline!"))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 1069058302))
  (|SetAElt| t1 (the |SInt| 3) (|MakeLit| "open?"))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 330716195))
  (|SetAElt| t1 (the |SInt| 4) (|MakeLit| "close"))
  (|SetAElt| t0 (the |SInt| 5) (the |SInt| 599195330))
  (|SetAElt| t1 (the |SInt| 5) (|MakeLit| "write!"))
  (setq t2 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t2 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |nsize| 1 t2 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |values| 2 t2 t0)
  (setq t3 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t3 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |nsize| 1 t3 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |values| 2 t3 t1)
  (|CCall| |G-rtAddStrings| t2 t3)
  (block-return |C0-file-file| ()))

(defprog
  ((|C1-file-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "OutFile")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 842010775))
  (block-return |C1-file-addLevel0| (|Clos| |e0| |C2-file-addLevel1|)))

(defprog
  ((|C2-file-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |SInt|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-file-10| |Struct-file-10|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq t0 (|ANew| |Word| (the |SInt| 5)))
  (setq t1 (|ANew| |Word| (the |SInt| 5)))
  (setq t2 (|ANew| |Word| (the |SInt| 5)))
  (|SetLex| |Struct-file-10--5| 5 |l0| |P1-hashcode|)
  (|SetLex|
    |Struct-file-10-open-4|
    4
    |l0|
    (|Clos| |e0| |C3-file-open|))
  (|SetLex|
    |Struct-file-10-open?-3|
    3
    |l0|
    (|Clos| |e0| |C4-file-open?|))
  (|SetLex|
    |Struct-file-10-close-2|
    2
    |l0|
    (|Clos| |e0| |C5-file-close|))
  (|SetLex|
    |Struct-file-10-write!-0|
    0
    |l0|
    (|Clos| |e0| |C6-file-write!|))
  (|SetLex|
    |Struct-file-10-write!-1|
    1
    |l0|
    (|Clos| |e0| |C7-file-write!|))
  (setq
    t6
    (|SIntHashCombine|
      (|Lex| |Struct-file-10--5| 5 |l0|)
      (the |SInt| 317087076)))
  (setq
    t9
    (|SIntHashCombine|
      (|Lex| |Struct-file-10--5| 5 |l0|)
      (the |SInt| 51489085)))
  (setq t10 (|SIntHashCombine| (the |SInt| 32236) t9))
  (setq t7 (|SIntHashCombine| (the |SInt| 740244383) t10))
  (setq
    t8
    (|SIntHashCombine|
      (the |SInt| 32236)
      (|SIntHashCombine| (the |SInt| 803414590) t9)))
  (setq t3 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t3 (the |SInt| 5))
  (|SetRElt| |Struct-file-8| |nsize| 1 t3 (the |SInt| 5))
  (|SetRElt| |Struct-file-8| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t4 (the |SInt| 5))
  (|SetRElt| |Struct-file-8| |nsize| 1 t4 (the |SInt| 5))
  (|SetRElt| |Struct-file-8| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t5 (the |SInt| 5))
  (|SetRElt| |Struct-file-8| |nsize| 1 t5 (the |SInt| 5))
  (|SetRElt| |Struct-file-8| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 664284502))
  (|SetAElt| t1 (the |SInt| 0) t6)
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-file-10-open-4| 4 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 1069058302))
  (|SetAElt| t1 (the |SInt| 1) t7)
  (|SetAElt|
    t2
    (the |SInt| 1)
    (|Lex| |Struct-file-10-open?-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 330716195))
  (|SetAElt| t1 (the |SInt| 2) t10)
  (|SetAElt|
    t2
    (the |SInt| 2)
    (|Lex| |Struct-file-10-close-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 599195330))
  (|SetAElt| t1 (the |SInt| 3) t8)
  (|SetAElt|
    t2
    (the |SInt| 3)
    (|Lex| |Struct-file-10-write!-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 599195330))
  (|SetAElt|
    t1
    (the |SInt| 4)
    (|SIntHashCombine|
      (the |SInt| 33717313)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (the |SInt| 33717313)
          (|SIntHashCombine|
            (the |SInt| 33717313)
            (|SIntHashCombine|
              (the |SInt| 585242861)
              (|SIntHashCombine|
                (|Lex| |Struct-file-10--5| 5 |l0|)
                (the |SInt| 51489085))))))))
  (|SetAElt|
    t2
    (the |SInt| 4)
    (|Lex| |Struct-file-10-write!-1| 1 |l0|))
  (block-return |C2-file-addLevel1| |P0-domain|))

(defprog
  ((|C3-file-open| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))
  ()
  (block-return
    |C3-file-open|
    (|fopen|
      (|RElt| |Struct-file-14| |native| 3 |P0-fn|)
      (|MakeLit| "w"))))

(defprog
  ((|C4-file-open?| |Word|) ((|P0-ouf| |Word|) (|e1| |Env|)))
  ()
  (block-return |C4-file-open?| (|BoolNot| (|PtrIsNil| |P0-ouf|))))

(defprog
  ((|C5-file-close|) ((|P0-ouf| |Word|) (|e1| |Env|)))
  ()
  (|fclose| |P0-ouf|)
  (block-return |C5-file-close| ()))

(defprog
  ((|C6-file-write!|) ((|P0-ouf| |Word|) (|P1-c| |Word|) (|e1| |Env|)))
  ()
  (tagbody
    (when (|PtrIsNil| |P0-ouf|) (go |Lab1|))
    (|fputc| (|CharOrd| |P1-c|) |P0-ouf|)
    |Lab1|
    (block-return |C6-file-write!| ())))

(defprog
  ((|C7-file-write!| |Word|)
    ((|P0-ouf| |Word|)
      (|P1-s| |Word|)
      (|P2-start| |Word|)
      (|P3-limit| |Word|)
      (|e1| |Env|)))
  ((t0 |Word|) (t1 |Word|) (t2 |SInt|) (t3 |SInt|))
  (tagbody
    (when (|PtrIsNil| |P0-ouf|) (go |Lab7|))
    (setq
      t0
      (|fputss|
        |P1-s|
        (|SIntPrev| |P2-start|)
        (|SIntPrev| |P3-limit|)
        |P0-ouf|))
    |Lab1|
    (block-return |C7-file-write!| t0)
    |Lab7|
    (when (|SIntIsZero| |P3-limit|) (go |Lab2|))
    (setq t1 (|SIntMinus| |P3-limit| |P2-start|))
    |Lab3|
    (setq t0 t1)
    (go |Lab1|)
    |Lab2|
    (setq t2 (the |SInt| 1))
    |Lab4|
    (setq t3 (|SIntPrev| t2))
    (when
      (|CharEQ| (|AElt| |P1-s| t3) (the |Char| |CharCode0|))
      (go |Lab5|))
    (setq t2 (|SIntNext| t2))
    (go |Lab4|)
    |Lab5|
    (setq t1 (|SIntMinus| (|SIntNext| t3) |P2-start|))
    (go |Lab3|)))

(defprog
  ((|C8-file-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "InFile")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 915910317))
  (block-return |C8-file-addLevel0| (|Clos| |e0| |C9-file-addLevel1|)))

(defprog
  ((|C9-file-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |SInt|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-file-12| |Struct-file-12|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq t0 (|ANew| |Word| (the |SInt| 6)))
  (setq t1 (|ANew| |Word| (the |SInt| 6)))
  (setq t2 (|ANew| |Word| (the |SInt| 6)))
  (|SetLex| |Struct-file-12--6| 6 |l0| |P1-hashcode|)
  (|SetLex|
    |Struct-file-12-open-5|
    5
    |l0|
    (|Clos| |e0| |C10-file-open|))
  (|SetLex|
    |Struct-file-12-open?-4|
    4
    |l0|
    (|Clos| |e0| |C11-file-open?|))
  (|SetLex|
    |Struct-file-12-close-3|
    3
    |l0|
    (|Clos| |e0| |C12-file-close|))
  (|SetLex|
    |Struct-file-12-readchar!-2|
    2
    |l0|
    (|Clos| |e0| |C13-file-readchar!|))
  (|SetLex|
    |Struct-file-12-readline!-0|
    0
    |l0|
    (|Clos| |e0| |C14-file-readline!|))
  (|SetLex|
    |Struct-file-12-readline!-1|
    1
    |l0|
    (|Clos| |e0| |C15-file-readline!|))
  (setq
    t6
    (|SIntHashCombine|
      (|Lex| |Struct-file-12--6| 6 |l0|)
      (the |SInt| 317087076)))
  (setq
    t10
    (|SIntHashCombine|
      (|Lex| |Struct-file-12--6| 6 |l0|)
      (the |SInt| 51489085)))
  (setq t11 (|SIntHashCombine| (the |SInt| 32236) t10))
  (setq t7 (|SIntHashCombine| (the |SInt| 740244383) t11))
  (setq
    t8
    (|SIntHashCombine|
      (the |SInt| 33717313)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (the |SInt| 33717313)
          (|SIntHashCombine|
            (the |SInt| 33717313)
            (|SIntHashCombine| (the |SInt| 585242861) t10))))))
  (setq t9 (|SIntHashCombine| (the |SInt| 585242861) t11))
  (setq t3 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t3 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |nsize| 1 t3 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t4 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |nsize| 1 t4 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-file-8|))
  (|SetRElt| |Struct-file-8| |size| 0 t5 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |nsize| 1 t5 (the |SInt| 6))
  (|SetRElt| |Struct-file-8| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 664284502))
  (|SetAElt| t1 (the |SInt| 0) t6)
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-file-12-open-5| 5 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 1069058302))
  (|SetAElt| t1 (the |SInt| 1) t7)
  (|SetAElt|
    t2
    (the |SInt| 1)
    (|Lex| |Struct-file-12-open?-4| 4 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 330716195))
  (|SetAElt| t1 (the |SInt| 2) t11)
  (|SetAElt|
    t2
    (the |SInt| 2)
    (|Lex| |Struct-file-12-close-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 272337676))
  (|SetAElt|
    t1
    (the |SInt| 3)
    (|SIntHashCombine|
      (the |SInt| 803414590)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (the |SInt| 803414590)
          (|SIntHashCombine|
            (|Lex| |Struct-file-12--6| 6 |l0|)
            (the |SInt| 51489085))))))
  (|SetAElt|
    t2
    (the |SInt| 3)
    (|Lex| |Struct-file-12-readchar!-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 21485846))
  (|SetAElt| t1 (the |SInt| 4) t8)
  (|SetAElt|
    t2
    (the |SInt| 4)
    (|Lex| |Struct-file-12-readline!-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 5) (the |SInt| 21485846))
  (|SetAElt| t1 (the |SInt| 5) t9)
  (|SetAElt|
    t2
    (the |SInt| 5)
    (|Lex| |Struct-file-12-readline!-1| 1 |l0|))
  (block-return |C9-file-addLevel1| |P0-domain|))

(defprog
  ((|C10-file-open| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))
  ()
  (block-return
    |C10-file-open|
    (|fopen|
      (|RElt| |Struct-file-14| |native| 3 |P0-fn|)
      (|MakeLit| "r"))))

(defprog
  ((|C11-file-open?| |Word|) ((|P0-inf| |Word|) (|e1| |Env|)))
  ()
  (block-return |C11-file-open?| (|BoolNot| (|PtrIsNil| |P0-inf|))))

(defprog
  ((|C12-file-close|) ((|P0-inf| |Word|) (|e1| |Env|)))
  ()
  (|fclose| |P0-inf|)
  (block-return |C12-file-close| ()))

(defprog
  ((|C13-file-readchar!| |Word|)
    ((|P0-inf| |Word|) (|P1-eof| |Word|) (|e1| |Env|)))
  ((|T0-n| |SInt|) (t1 |Word|))
  (tagbody
    (setq |T0-n| (|fgetc| |P0-inf|))
    (when (|SIntEQ| |T0-n| (the |SInt| -1)) (go |Lab0|))
    (setq t1 (|CharNum| |T0-n|))
    |Lab1|
    (block-return |C13-file-readchar!| t1)
    |Lab0|
    (setq t1 |P1-eof|)
    (go |Lab1|)))

(defprog
  ((|C14-file-readline!| |Word|)
    ((|P0-inf| |Word|)
      (|P1-s| |Word|)
      (|P2-start| |Word|)
      (|P3-limit| |Word|)
      (|e1| |Env|)))
  ()
  (block-return
    |C14-file-readline!|
    (|fgetss|
      |P1-s|
      (|SIntPrev| |P2-start|)
      (|SIntPrev| |P3-limit|)
      |P0-inf|)))

(defprog
  ((|C15-file-readline!| |Word|) ((|P0-inf| |Word|) (|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (t4 |Arr|)
    (t5 |Arr|)
    (t6 |SInt|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |Char|)
    (t10 |Arr|)
    (t11 |SInt|)
    (t12 |SInt|)
    (|T13-size| |SInt|)
    (|T14-nvalues| |SInt|)
    (|T15-values| |Arr|))
  (tagbody
    (setq |T13-size| (the |SInt| 0))
    (setq |T14-nvalues| (the |SInt| 0))
    (setq |T15-values| (|ANew| |Word| (the |SInt| 0)))
    |Lab0|
    (setq t8 (|fgetc| |P0-inf|))
    (when (|SIntEQ| t8 (the |SInt| -1)) (go |Lab10|))
    (setq t9 (|CharNum| t8))
    |Lab11|
    (when (|CharEQ| t9 (the |Char| |CharCode0|)) (go |Lab1|))
    (when (|SIntEQ| |T14-nvalues| |T13-size|) (go |Lab2|))
    |Lab3|
    (setq |T14-nvalues| (|SIntNext| |T14-nvalues|))
    (setq t1 (|SIntPrev| |T14-nvalues|))
    (|SetAElt| |T15-values| t1 t9)
    (when (|CharEQ| t9 (the |Char| #\Newline)) (go |Lab1|))
    (go |Lab0|)
    |Lab1|
    (setq t10 (|ANew| |Char| (|SIntNext| |T14-nvalues|)))
    (|SetAElt| t10 (the |SInt| 0) (the |Char| |CharCode0|))
    (|SetAElt| t10 |T14-nvalues| (the |Char| |CharCode0|))
    (setq t11 (the |SInt| 1))
    |Lab12|
    (when (|SIntLE| t11 |T14-nvalues|) (go |Lab13|))
    (|FoamFree| |T15-values|)
    (block-return |C15-file-readline!| t10)
    |Lab13|
    (setq t12 (|SIntPrev| t11))
    (|SetAElt| t10 t12 (|AElt| |T15-values| t12))
    (setq t11 (|SIntNext| t11))
    (go |Lab12|)
    |Lab2|
    (setq t0 (|SIntQuo| |T13-size| (the |SInt| 2)))
    (setq t3 (|SIntPlus| |T13-size| t0))
    (when (|SIntLT| t3 (the |SInt| 4)) (go |Lab4|))
    (setq t2 t3)
    |Lab5|
    (when (|SIntLE| t2 |T13-size|) (go |Lab6|))
    (setq t4 (|ANew| |Word| t2))
    (setq t6 (the |SInt| 1))
    |Lab8|
    (when (|SIntLE| t6 |T13-size|) (go |Lab9|))
    (|FoamFree| |T15-values|)
    (setq t5 t4)
    |Lab7|
    (setq |T15-values| t5)
    (setq |T13-size| t2)
    (go |Lab3|)
    |Lab9|
    (setq t7 (|SIntPrev| t6))
    (|SetAElt| t4 t7 (|AElt| |T15-values| t7))
    (setq t6 (|SIntNext| t6))
    (go |Lab8|)
    |Lab6|
    (setq t5 |T15-values|)
    (go |Lab7|)
    |Lab4|
    (setq t2 (the |SInt| 4))
    (go |Lab5|)
    |Lab10|
    (setq t9 (the |Char| |CharCode0|))
    (go |Lab11|)))

(setq |G-file| (|Clos| nil |C0-file-file|))

(setq |G-file_InFile_587546911| nil)

(setq |G-file_OutFile_420710551| nil)

(file-imports
  '((|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-file_OutFile_420710551| "OutFile" 420710551 "file")
      (|G-file_InFile_587546911| "InFile" 587546911 "file")
      (|G-file| "file" |initializer| "")))
