;;;
;;; Lisp code generated by Aldor from file "fname.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-fname-fname|) ((|e1| |Env|)))

(declare-prog
  (|C1-fname-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-fname-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-fname-filename| |Word|)
  ((|P0-s| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-fname-filename| |Word|)
  ((|P0-dir| |Word|) (|P1-name| |Word|) (|P2-type| |Word|) (|e1| |Env|)))

(declare-prog (|C5-fname-dir| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-fname-name| |Word|)
  ((|P0-fn| |Word|) (|e1| |Env|)))

(declare-prog
  (|C7-fname-type| |Word|)
  ((|P0-fn| |Word|) (|e1| |Env|)))

(declare-prog
  (|C8-fname-unparse| |Word|)
  ((|P0-fn| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-fname-=| |Word|)
  ((|P0-fn1| |Word|) (|P1-fn2| |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-fname-~=| |Word|)
  ((|P0-fn1| |Word|) (|P1-fn2| |Word|) (|e1| |Env|)))

(declare-prog
  (|C11-fname-<<| |Word|)
  ((|P0-p| |Word|) (|P1-fn| |Word|) (|e1| |Env|)))

(declare-prog (|C12-fname-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog (|C13-fname-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-fname-hash| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C15-fname-case| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C16-fname-oslow-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C17-fname-pointer-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C18-fname-foamcat-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-fname| |Clos|)

(declare-type |G-fname_FileName_901471140| |Word|)

(defspecials |G-fname_FileName_901471140|)

(|DDecl|
  |Struct-fname-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl|
  |Struct-fname-6|
  (|dir-0| |Word|)
  (|name-1| |Word|)
  (|type-2| |Word|)
  (|native-3| |Word|))

(|DDecl| |Struct-fname-7| (|x-0| |Word|))

(|DDecl|
  |Struct-fname-8|
  (|case-0| |Clos|)
  (|hash-1| |Clos|)
  (<<-2 |Clos|)
  (<<-3 |Clos|)
  (~=-4 |Clos|)
  (=-5 |Clos|)
  (|unparse-6| |Clos|)
  (|type-7| |Clos|)
  (|name-8| |Clos|)
  (|dir-9| |Clos|)
  (|filename-10| |Clos|)
  (|filename-11| |Clos|)
  (|sample-12| |Word|)
  (\-13 |SInt|))

(|DDecl|
  |Struct-fname-10|
  (|BasicType-0| |Word|)
  (|Pointer-1| |Word|)
  (|OperatingSystemInterface-2| |Word|)
  (|nil-3| |Clos|)
  (|fnameNParts-4| |Word|)
  (|dom-5| |Word|)
  (|dom-6| |Word|)
  (\-7 |Bool|)
  (\-8 |Bool|)
  (\-9 |Bool|))

(|DDecl|
  |Struct-fname-11|
  (p0-0 |Word|)
  (p1-1 |Word|)
  (\-2 |Nil|)
  (r0-3 |Word|))

(|DDecl|
  |Struct-fname-12|
  (p0-0 |Word|)
  (p1-1 |Word|)
  (p2-2 |Word|)
  (\-3 |Nil|)
  (r0-4 |Word|))

(|DDecl|
  |Struct-fname-13|
  (p0-0 |Word|)
  (p1-1 |Word|)
  (p2-2 |Word|)
  (p3-3 |Word|)
  (\-4 |Nil|))

(|DDecl| |Struct-fname-14| (\-0 |Clos|) (\-1 |Clos|) (\-2 |Clos|))

(defprog
  ((|C0-fname-fname|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Arr|)
    (t4 |Arr|)
    (t5 |Record|)
    (t6 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-fname-10| |Struct-fname-10|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-fname| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C18-fname-foamcat-init|))
  (setq t1 (|Clos| |e0| |C16-fname-oslow-init|))
  (setq t2 (|Clos| |e0| |C17-fname-pointer-init|))
  (setq
    |G-fname_FileName_901471140|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-fname-addLevel0|)))
  (|SetLex| |Struct-fname-10--7| 7 |l0| (the |Bool| nil))
  (|SetLex| |Struct-fname-10--8| 8 |l0| (the |Bool| nil))
  (|SetLex| |Struct-fname-10--9| 9 |l0| (the |Bool| nil))
  (setq t3 (|ANew| |Word| (the |SInt| 11)))
  (setq t4 (|ANew| |Word| (the |SInt| 11)))
  (|SetAElt| t3 (the |SInt| 0) (the |SInt| 200102))
  (|SetAElt| t4 (the |SInt| 0) (|MakeLit| "="))
  (|SetAElt| t3 (the |SInt| 1) (the |SInt| 51509389))
  (|SetAElt| t4 (the |SInt| 1) (|MakeLit| "~="))
  (|SetAElt| t3 (the |SInt| 2) (the |SInt| 5811165))
  (|SetAElt| t4 (the |SInt| 2) (|MakeLit| "unparse"))
  (|SetAElt| t3 (the |SInt| 3) (the |SInt| 783167045))
  (|SetAElt| t4 (the |SInt| 3) (|MakeLit| "name"))
  (|SetAElt| t3 (the |SInt| 4) (the |SInt| 237885833))
  (|SetAElt| t4 (the |SInt| 4) (|MakeLit| "filename"))
  (|SetAElt| t3 (the |SInt| 5) (the |SInt| 255806968))
  (|SetAElt| t4 (the |SInt| 5) (|MakeLit| "sample"))
  (|SetAElt| t3 (the |SInt| 6) (the |SInt| 864625472))
  (|SetAElt| t4 (the |SInt| 6) (|MakeLit| "case"))
  (|SetAElt| t3 (the |SInt| 7) (the |SInt| 12649830))
  (|SetAElt| t4 (the |SInt| 7) (|MakeLit| "type"))
  (|SetAElt| t3 (the |SInt| 8) (the |SInt| 746853960))
  (|SetAElt| t4 (the |SInt| 8) (|MakeLit| "hash"))
  (|SetAElt| t3 (the |SInt| 9) (the |SInt| 51492426))
  (|SetAElt| t4 (the |SInt| 9) (|MakeLit| "<<"))
  (|SetAElt| t3 (the |SInt| 10) (the |SInt| 316825466))
  (|SetAElt| t4 (the |SInt| 10) (|MakeLit| "dir"))
  (setq t5 (|RNew| |Struct-fname-5|))
  (|SetRElt| |Struct-fname-5| |size| 0 t5 (the |SInt| 11))
  (|SetRElt| |Struct-fname-5| |nsize| 1 t5 (the |SInt| 11))
  (|SetRElt| |Struct-fname-5| |values| 2 t5 t3)
  (setq t6 (|RNew| |Struct-fname-5|))
  (|SetRElt| |Struct-fname-5| |size| 0 t6 (the |SInt| 11))
  (|SetRElt| |Struct-fname-5| |nsize| 1 t6 (the |SInt| 11))
  (|SetRElt| |Struct-fname-5| |values| 2 t6 t4)
  (|CCall| |G-rtAddStrings| t5 t6)
  (|SetLex|
    |Struct-fname-10-BasicType-0|
    0
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-fname-10-OperatingSystemInterface-2|
    2
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-fname-10-dom-5|
    5
    |l0|
    (|Lex| |Struct-fname-10-OperatingSystemInterface-2| 2 |l0|))
  (|SetLex|
    |Struct-fname-10-fnameNParts-4|
    4
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-fname-10-dom-5| 5 |l0|)
      (the |SInt| 603177698)
      (the |SInt| 33717313)))
  (|SetLex|
    |Struct-fname-10-Pointer-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 0)))
  (|SetLex|
    |Struct-fname-10-dom-6|
    6
    |l0|
    (|Lex| |Struct-fname-10-Pointer-1| 1 |l0|))
  (|SetLex|
    |Struct-fname-10-nil-3|
    3
    |l0|
    (|CCall|
      |G-stdGetRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-fname-10-dom-6| 6 |l0|)
        (the |SInt| 318525310)
        (the |SInt| 1050822588))))
  (block-return |C0-fname-fname| ()))

(defprog
  ((|C1-fname-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "FileName")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 37097289))
  (block-return |C1-fname-addLevel0| (|Clos| |e0| |C2-fname-addLevel1|)))

(defprog
  ((|C2-fname-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Word|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |SInt|)
    (t14 |SInt|)
    (t15 |Env|)
    (t16 |Word|)
    (t17 |SInt|)
    (t18 |Record|)
    (t19 |Arr|)
    (t20 |Arr|)
    (t21 |SInt|)
    (t22 |SInt|)
    (t23 |SInt|)
    (t24 |Word|)
    (t25 |Word|)
    (t26 |Word|)
    (t27 |SInt|)
    (t28 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-fname-8| |Struct-fname-8|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq t0 (|ANew| |Word| (the |SInt| 13)))
    (setq t1 (|ANew| |Word| (the |SInt| 13)))
    (setq t2 (|ANew| |Word| (the |SInt| 13)))
    (setq t6 (|CCall| |G-domainMakeDispatch| |P0-domain|))
    (|SetLex| |Struct-fname-8--13| 13 |l0| |P1-hashcode|)
    (|SetLex|
      |Struct-fname-8-filename-10|
      10
      |l0|
      (|Clos| |e0| |C3-fname-filename|))
    (|SetLex|
      |Struct-fname-8-filename-11|
      11
      |l0|
      (|Clos| |e0| |C4-fname-filename|))
    (|SetLex|
      |Struct-fname-8-dir-9|
      9
      |l0|
      (|Clos| |e0| |C5-fname-dir|))
    (|SetLex|
      |Struct-fname-8-name-8|
      8
      |l0|
      (|Clos| |e0| |C6-fname-name|))
    (|SetLex|
      |Struct-fname-8-type-7|
      7
      |l0|
      (|Clos| |e0| |C7-fname-type|))
    (|SetLex|
      |Struct-fname-8-unparse-6|
      6
      |l0|
      (|Clos| |e0| |C8-fname-unparse|))
    (|SetLex| |Struct-fname-8-=-5| 5 |l0| (|Clos| |e0| |C9-fname-=|))
    (|SetLex| |Struct-fname-8-~=-4| 4 |l0| (|Clos| |e0| |C10-fname-~=|))
    (|SetLex| |Struct-fname-8-<<-2| 2 |l0| (|Clos| |e0| |C11-fname-<<|))
    (|SetLex| |Struct-fname-8-<<-3| 3 |l0| (|Clos| |e0| |C12-fname-<<|))
    (|SetLex|
      |Struct-fname-8-hash-1|
      1
      |l0|
      (|Clos| |e0| |C14-fname-hash|))
    (|SetLex|
      |Struct-fname-8-case-0|
      0
      |l0|
      (|Clos| |e0| |C15-fname-case|))
    (setq
      t7
      (|SIntHashCombine|
        (|Lex| |Struct-fname-8--13| 13 |l0|)
        (the |SInt| 134790492)))
    (setq
      t8
      (|SIntHashCombine|
        (|Lex| |Struct-fname-8--13| 13 |l0|)
        (the |SInt| 757722190)))
    (setq
      t27
      (|SIntHashCombine|
        (|Lex| |Struct-fname-8--13| 13 |l0|)
        (the |SInt| 51489085)))
    (setq t28 (|SIntHashCombine| (the |SInt| 32236) t27))
    (setq t9 (|SIntHashCombine| (the |SInt| 585242861) t28))
    (setq
      t10
      (|SIntHashCombine|
        (the |SInt| 740244383)
        (|SIntHashCombine|
          (the |SInt| 32236)
          (|SIntHashCombine| (|Lex| |Struct-fname-8--13| 13 |l0|) t27))))
    (setq
      t11
      (|SIntHashCombine|
        (the |SInt| 182752316)
        (|SIntHashCombine|
          (the |SInt| 32236)
          (|SIntHashCombine|
            (|Lex| |Struct-fname-8--13| 13 |l0|)
            (the |SInt| 102896482)))))
    (setq t12 (|SIntHashCombine| (the |SInt| 755420535) t28))
    (setq t13 (|SIntHashCombine| (the |SInt| 33717313) t28))
    (setq t14 (|Lex| |Struct-fname-8--13| 13 |l0|))
    (setq t3 (|RNew| |Struct-fname-5|))
    (|SetRElt| |Struct-fname-5| |size| 0 t3 (the |SInt| 13))
    (|SetRElt| |Struct-fname-5| |nsize| 1 t3 (the |SInt| 13))
    (|SetRElt| |Struct-fname-5| |values| 2 t3 t0)
    (setq t4 (|RNew| |Struct-fname-5|))
    (|SetRElt| |Struct-fname-5| |size| 0 t4 (the |SInt| 13))
    (|SetRElt| |Struct-fname-5| |nsize| 1 t4 (the |SInt| 13))
    (|SetRElt| |Struct-fname-5| |values| 2 t4 t1)
    (setq t5 (|RNew| |Struct-fname-5|))
    (|SetRElt| |Struct-fname-5| |size| 0 t5 (the |SInt| 13))
    (|SetRElt| |Struct-fname-5| |nsize| 1 t5 (the |SInt| 13))
    (|SetRElt| |Struct-fname-5| |values| 2 t5 t2)
    (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
    (|CCall|
      |G-domainAddDefaults!|
      |P0-domain|
      (|Lex| |Struct-fname-10-BasicType-0| 0 |l2|)
      t6)
    (|SetAElt| t0 (the |SInt| 0) (the |SInt| 237885833))
    (|SetAElt| t1 (the |SInt| 0) t7)
    (|SetAElt|
      t2
      (the |SInt| 0)
      (|Lex| |Struct-fname-8-filename-10| 10 |l0|))
    (|SetAElt| t0 (the |SInt| 1) (the |SInt| 237885833))
    (|SetAElt| t1 (the |SInt| 1) t8)
    (|SetAElt|
      t2
      (the |SInt| 1)
      (|Lex| |Struct-fname-8-filename-11| 11 |l0|))
    (|SetAElt| t0 (the |SInt| 2) (the |SInt| 316825466))
    (|SetAElt| t1 (the |SInt| 2) t9)
    (|SetAElt|
      t2
      (the |SInt| 2)
      (|Lex| |Struct-fname-8-dir-9| 9 |l0|))
    (|SetAElt| t0 (the |SInt| 3) (the |SInt| 783167045))
    (|SetAElt| t1 (the |SInt| 3) t9)
    (|SetAElt|
      t2
      (the |SInt| 3)
      (|Lex| |Struct-fname-8-name-8| 8 |l0|))
    (|SetAElt| t0 (the |SInt| 4) (the |SInt| 12649830))
    (|SetAElt| t1 (the |SInt| 4) t9)
    (|SetAElt|
      t2
      (the |SInt| 4)
      (|Lex| |Struct-fname-8-type-7| 7 |l0|))
    (|SetAElt| t0 (the |SInt| 5) (the |SInt| 5811165))
    (|SetAElt| t1 (the |SInt| 5) t9)
    (|SetAElt|
      t2
      (the |SInt| 5)
      (|Lex| |Struct-fname-8-unparse-6| 6 |l0|))
    (|SetAElt| t0 (the |SInt| 6) (the |SInt| 200102))
    (|SetAElt| t1 (the |SInt| 6) t10)
    (|SetAElt| t2 (the |SInt| 6) (|Lex| |Struct-fname-8-=-5| 5 |l0|))
    (|SetAElt| t0 (the |SInt| 7) (the |SInt| 51509389))
    (|SetAElt| t1 (the |SInt| 7) t10)
    (|SetAElt| t2 (the |SInt| 7) (|Lex| |Struct-fname-8-~=-4| 4 |l0|))
    (|SetAElt| t0 (the |SInt| 8) (the |SInt| 51492426))
    (|SetAElt| t1 (the |SInt| 8) t11)
    (|SetAElt| t2 (the |SInt| 8) (|Lex| |Struct-fname-8-<<-2| 2 |l0|))
    (|SetAElt| t0 (the |SInt| 9) (the |SInt| 51492426))
    (|SetAElt| t1 (the |SInt| 9) t12)
    (|SetAElt| t2 (the |SInt| 9) (|Lex| |Struct-fname-8-<<-3| 3 |l0|))
    (|SetAElt| t0 (the |SInt| 10) (the |SInt| 746853960))
    (|SetAElt| t1 (the |SInt| 10) t13)
    (|SetAElt|
      t2
      (the |SInt| 10)
      (|Lex| |Struct-fname-8-hash-1| 1 |l0|))
    (|SetAElt| t0 (the |SInt| 11) (the |SInt| 864625472))
    (|SetAElt| t1 (the |SInt| 11) t10)
    (|SetAElt|
      t2
      (the |SInt| 11)
      (|Lex| |Struct-fname-8-case-0| 0 |l0|))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-fname-8-filename-11| 11 |l0|)))
    (setq t15 (|ClosEnv| (|Lex| |Struct-fname-8-filename-11| 11 |l0|)))
    (setq t24 (|MakeLit| "a"))
    (setq t25 (|MakeLit| "b"))
    (setq t26 (|MakeLit| "c"))
    (setq
      t23
      (|CCall|
        |G-lazyForceImport|
        (|EElt|
          |Struct-fname-10-fnameNParts-4|
          4
          (|EnvLevel| (|EnvNext| (|EnvNext| t15))))))
    (setq t20 (|ANew| |Word| t23))
    (setq t22 (the |SInt| 1))
    |Lab0|
    (when (|SIntLE| t22 t23) (go |Lab1|))
    (|SetAElt| t20 (the |SInt| 0) t24)
    (|SetAElt| t20 (the |SInt| 1) t25)
    (|SetAElt| t20 (the |SInt| 2) t26)
    (setq t17 (|osFnameUnparseSize| t20 (the |Bool| nil)))
    (setq t19 (|ANew| |Char| (|SIntNext| t17)))
    (|SetAElt| t19 (the |SInt| 0) (the |Char| |CharCode0|))
    (|SetAElt| t19 t17 (the |Char| |CharCode0|))
    (setq t16 (|osFnameUnparse| t19 t20 (the |Bool| nil)))
    (setq t18 (|RNew| |Struct-fname-6|))
    (|SetRElt| |Struct-fname-6| |dir| 0 t18 t24)
    (|SetRElt| |Struct-fname-6| |name| 1 t18 t25)
    (|SetRElt| |Struct-fname-6| |type| 2 t18 t26)
    (|SetRElt| |Struct-fname-6| |native| 3 t18 t16)
    (|FoamFree| t20)
    (|SetLex| |Struct-fname-8-sample-12| 12 |l0| t18)
    (|SetAElt| t0 (the |SInt| 12) (the |SInt| 255806968))
    (|SetAElt| t1 (the |SInt| 12) t14)
    (|SetAElt|
      t2
      (the |SInt| 12)
      (|Lex| |Struct-fname-8-sample-12| 12 |l0|))
    (block-return |C2-fname-addLevel1| |P0-domain|)
    |Lab1|
    (setq t21 (|SIntPrev| t22))
    (|SetAElt| t20 t21 (|MakeLit| ""))
    (setq t22 (|SIntNext| t22))
    (go |Lab0|)))

(defprog
  ((|C3-fname-filename| |Word|) ((|P0-s| |Word|) (|e1| |Env|)))
  ((|T0-flen| |SInt|)
    (t1 |Record|)
    (t2 |Arr|)
    (t3 |Arr|)
    (t4 |SInt|)
    (t5 |SInt|)
    (t6 |SInt|)
    (t7 |Arr|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (|e3| |Env|)
    (|l3| |Level|))
  (setq |e3| (|EnvNext| (|EnvNext| |e1|)))
  (setq |l3| (|EnvLevel| |e3|))
  (tagbody
    (setq
      t6
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-fname-10-fnameNParts-4| 4 |l3|)))
    (setq t3 (|ANew| |Word| t6))
    (setq t5 (the |SInt| 1))
    |Lab0|
    (when (|SIntLE| t5 t6) (go |Lab1|))
    (setq
      |T0-flen|
      (|osFnameParseSize| |P0-s| (|Lex| |Struct-fname-10-nil-3| 3 |l3|)))
    (setq t2 (|ANew| |Char| (|SIntNext| |T0-flen|)))
    (|SetAElt| t2 (the |SInt| 0) (the |Char| |CharCode0|))
    (|SetAElt| t2 |T0-flen| (the |Char| |CharCode0|))
    (|osFnameParse| t3 t2 |P0-s| (|Lex| |Struct-fname-10-nil-3| 3 |l3|))
    (setq t1 (|RNew| |Struct-fname-6|))
    (|SetRElt| |Struct-fname-6| |dir| 0 t1 (|AElt| t3 (the |SInt| 0)))
    (|SetRElt|
      |Struct-fname-6|
      |name|
      1
      t1
      (|AElt| t3 (the |SInt| 1)))
    (|SetRElt|
      |Struct-fname-6|
      |type|
      2
      t1
      (|AElt| t3 (the |SInt| 2)))
    (setq t8 (the |SInt| 1))
    |Lab2|
    (setq t10 (|SIntPrev| t8))
    (when
      (|CharEQ| (|AElt| |P0-s| t10) (the |Char| |CharCode0|))
      (go |Lab3|))
    (setq t8 (|SIntNext| t8))
    (go |Lab2|)
    |Lab3|
    (setq t7 (|ANew| |Char| (|SIntNext| t10)))
    (|SetAElt| t7 (the |SInt| 0) (the |Char| |CharCode0|))
    (|SetAElt| t7 t10 (the |Char| |CharCode0|))
    (setq t9 (the |SInt| 1))
    |Lab4|
    (when (|SIntLE| t9 t10) (go |Lab5|))
    (|SetRElt| |Struct-fname-6| |native| 3 t1 t7)
    (|FoamFree| t3)
    (block-return |C3-fname-filename| t1)
    |Lab5|
    (setq t11 (|SIntPrev| t9))
    (|SetAElt| t7 t11 (|AElt| |P0-s| t11))
    (setq t9 (|SIntNext| t9))
    (go |Lab4|)
    |Lab1|
    (setq t4 (|SIntPrev| t5))
    (|SetAElt| t3 t4 (|MakeLit| ""))
    (setq t5 (|SIntNext| t5))
    (go |Lab0|)))

(defprog
  ((|C4-fname-filename| |Word|)
    ((|P0-dir| |Word|) (|P1-name| |Word|) (|P2-type| |Word|) (|e1| |Env|)))
  ((|T0-s| |Word|)
    (|T1-flen| |SInt|)
    (t2 |Record|)
    (t3 |Arr|)
    (t4 |Arr|)
    (t5 |SInt|)
    (t6 |SInt|)
    (t7 |SInt|)
    (|e3| |Env|)
    (|l3| |Level|))
  (setq |e3| (|EnvNext| (|EnvNext| |e1|)))
  (setq |l3| (|EnvLevel| |e3|))
  (tagbody
    (setq
      t7
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-fname-10-fnameNParts-4| 4 |l3|)))
    (setq t4 (|ANew| |Word| t7))
    (setq t6 (the |SInt| 1))
    |Lab0|
    (when (|SIntLE| t6 t7) (go |Lab1|))
    (|SetAElt| t4 (the |SInt| 0) |P0-dir|)
    (|SetAElt| t4 (the |SInt| 1) |P1-name|)
    (|SetAElt| t4 (the |SInt| 2) |P2-type|)
    (setq |T1-flen| (|osFnameUnparseSize| t4 (the |Bool| nil)))
    (setq t3 (|ANew| |Char| (|SIntNext| |T1-flen|)))
    (|SetAElt| t3 (the |SInt| 0) (the |Char| |CharCode0|))
    (|SetAElt| t3 |T1-flen| (the |Char| |CharCode0|))
    (setq |T0-s| (|osFnameUnparse| t3 t4 (the |Bool| nil)))
    (setq t2 (|RNew| |Struct-fname-6|))
    (|SetRElt| |Struct-fname-6| |dir| 0 t2 |P0-dir|)
    (|SetRElt| |Struct-fname-6| |name| 1 t2 |P1-name|)
    (|SetRElt| |Struct-fname-6| |type| 2 t2 |P2-type|)
    (|SetRElt| |Struct-fname-6| |native| 3 t2 |T0-s|)
    (|FoamFree| t4)
    (block-return |C4-fname-filename| t2)
    |Lab1|
    (setq t5 (|SIntPrev| t6))
    (|SetAElt| t4 t5 (|MakeLit| ""))
    (setq t6 (|SIntNext| t6))
    (go |Lab0|)))

(defprog
  ((|C5-fname-dir| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))
  ()
  (block-return
    |C5-fname-dir|
    (|RElt| |Struct-fname-6| |dir| 0 |P0-fn|)))

(defprog
  ((|C6-fname-name| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))
  ()
  (block-return
    |C6-fname-name|
    (|RElt| |Struct-fname-6| |name| 1 |P0-fn|)))

(defprog
  ((|C7-fname-type| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))
  ()
  (block-return
    |C7-fname-type|
    (|RElt| |Struct-fname-6| |type| 2 |P0-fn|)))

(defprog
  ((|C8-fname-unparse| |Word|) ((|P0-fn| |Word|) (|e1| |Env|)))
  ()
  (block-return
    |C8-fname-unparse|
    (|RElt| |Struct-fname-6| |native| 3 |P0-fn|)))

(defprog
  ((|C9-fname-=| |Word|)
    ((|P0-fn1| |Word|) (|P1-fn2| |Word|) (|e1| |Env|)))
  ((t0 |Char|)
    (t1 |Char|)
    (t2 |SInt|)
    (t3 |SInt|)
    (t4 |Arr|)
    (t5 |Arr|)
    (t6 |Word|))
  (tagbody
    (setq t4 (|RElt| |Struct-fname-6| |native| 3 |P0-fn1|))
    (setq t5 (|RElt| |Struct-fname-6| |native| 3 |P1-fn2|))
    (setq t2 (the |SInt| 1))
    |Lab2|
    (setq t3 (|SIntPrev| t2))
    (when (|CharEQ| (|AElt| t4 t3) (the |Char| |CharCode0|)) (go |Lab0|))
    (setq t0 (|AElt| t4 t3))
    (setq t1 (|AElt| t5 t3))
    (when (|CharNE| t0 t1) (go |Lab1|))
    (setq t2 (|SIntNext| t2))
    (go |Lab2|)
    |Lab1|
    (setq t6 (the |Bool| nil))
    |Lab3|
    (block-return |C9-fname-=| t6)
    |Lab0|
    (setq t6 (|CharEQ| (|AElt| t5 t3) (the |Char| |CharCode0|)))
    (go |Lab3|)))

(defprog
  ((|C10-fname-~=| |Word|)
    ((|P0-fn1| |Word|) (|P1-fn2| |Word|) (|e1| |Env|)))
  ((t0 |Char|)
    (t1 |Char|)
    (t2 |Bool|)
    (t3 |SInt|)
    (t4 |SInt|)
    (t5 |Arr|)
    (t6 |Arr|))
  (tagbody
    (setq t5 (|RElt| |Struct-fname-6| |native| 3 |P0-fn1|))
    (setq t6 (|RElt| |Struct-fname-6| |native| 3 |P1-fn2|))
    (setq t3 (the |SInt| 1))
    |Lab3|
    (setq t4 (|SIntPrev| t3))
    (when (|CharEQ| (|AElt| t5 t4) (the |Char| |CharCode0|)) (go |Lab0|))
    (setq t0 (|AElt| t5 t4))
    (setq t1 (|AElt| t6 t4))
    (when (|CharNE| t0 t1) (go |Lab1|))
    (setq t3 (|SIntNext| t3))
    (go |Lab3|)
    |Lab1|
    (setq t2 (the |Bool| nil))
    |Lab2|
    (block-return |C10-fname-~=| (|BoolNot| t2))
    |Lab0|
    (setq t2 (|CharEQ| (|AElt| t6 t4) (the |Char| |CharCode0|)))
    (go |Lab2|)))

(defprog
  ((|C11-fname-<<| |Word|)
    ((|P0-p| |Word|) (|P1-fn| |Word|) (|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Clos|)
    (t5 |Clos|)
    (t6 |Word|)
    (t7 |Clos|)
    (t8 |Clos|)
    (t9 |Clos|))
  (multiple-value-setq (t7 t8 t9) (|CCall| |P0-p|))
  (|CCall| t8 (|MakeLit| "\"") (the |SInt| 1) (the |SInt| 0))
  (setq t6 (|RElt| |Struct-fname-6| |native| 3 |P1-fn|))
  (multiple-value-setq (t3 t4 t5) (|CCall| |P0-p|))
  (|CCall| t4 t6 (the |SInt| 1) (the |SInt| 0))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-p|))
  (|CCall| t1 (|MakeLit| "\"") (the |SInt| 1) (the |SInt| 0))
  (block-return |C11-fname-<<| |P0-p|))

(defprog
  ((|C12-fname-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-fname-7| |Struct-fname-7|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-fname-7-x-0| 0 |l0| |P0-x|)
  (block-return |C12-fname-<<| (|Clos| |e0| |C13-fname-<<|)))

(defprog
  ((|C13-fname-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Clos|)
    (t5 |Clos|)
    (t6 |Word|)
    (t7 |Clos|)
    (t8 |Clos|)
    (t9 |Clos|)
    (t10 |Record|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t10 (|Lex| |Struct-fname-7-x-0| 0 |l1|))
  (multiple-value-setq (t7 t8 t9) (|CCall| |P0-p|))
  (|CCall| t8 (|MakeLit| "\"") (the |SInt| 1) (the |SInt| 0))
  (setq t6 (|RElt| |Struct-fname-6| |native| 3 t10))
  (multiple-value-setq (t3 t4 t5) (|CCall| |P0-p|))
  (|CCall| t4 t6 (the |SInt| 1) (the |SInt| 0))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-p|))
  (|CCall| t1 (|MakeLit| "\"") (the |SInt| 1) (the |SInt| 0))
  (block-return |C13-fname-<<| |P0-p|))

(defprog
  ((|C14-fname-hash| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ()
  (block-return |C14-fname-hash| (the |SInt| 0)))

(defprog
  ((|C15-fname-case| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |Char|)
    (t1 |Char|)
    (t2 |SInt|)
    (t3 |SInt|)
    (t4 |Arr|)
    (t5 |Arr|)
    (t6 |Word|))
  (tagbody
    (setq t4 (|RElt| |Struct-fname-6| |native| 3 |P0-x|))
    (setq t5 (|RElt| |Struct-fname-6| |native| 3 |P1-y|))
    (setq t2 (the |SInt| 1))
    |Lab2|
    (setq t3 (|SIntPrev| t2))
    (when (|CharEQ| (|AElt| t4 t3) (the |Char| |CharCode0|)) (go |Lab0|))
    (setq t0 (|AElt| t4 t3))
    (setq t1 (|AElt| t5 t3))
    (when (|CharNE| t0 t1) (go |Lab1|))
    (setq t2 (|SIntNext| t2))
    (go |Lab2|)
    |Lab1|
    (setq t6 (the |Bool| nil))
    |Lab3|
    (block-return |C15-fname-case| t6)
    |Lab0|
    (setq t6 (|CharEQ| (|AElt| t5 t3) (the |Char| |CharCode0|)))
    (go |Lab3|)))

(defprog
  ((|C16-fname-oslow-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-fname-10--7| 7 |l1|) (go |Lab0|))
    (|SetLex| |Struct-fname-10--7| 7 |l1| (the |Bool| t))
    (|CCall| |G-oslow|)
    |Lab0|
    (block-return
      |C16-fname-oslow-init|
      |G-oslow_OperatingSystemInterface_198516253|)))

(defprog
  ((|C17-fname-pointer-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-fname-10--8| 8 |l1|) (go |Lab0|))
    (|SetLex| |Struct-fname-10--8| 8 |l1| (the |Bool| t))
    (|CCall| |G-pointer|)
    |Lab0|
    (block-return |C17-fname-pointer-init| |G-pointer_Pointer_476980157|)))

(defprog
  ((|C18-fname-foamcat-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-fname-10--9| 9 |l1|) (go |Lab0|))
    (|SetLex| |Struct-fname-10--9| 9 |l1| (the |Bool| t))
    (|CCall| |G-foamcat|)
    |Lab0|
    (block-return
      |C18-fname-foamcat-init|
      |G-foamcat_BasicType_906312337|)))

(setq |G-fname| (|Clos| nil |C0-fname-fname|))

(setq |G-fname_FileName_901471140| nil)

(file-imports
  '((|G-foamcat| "foamcat" |initializer| "")
      (|G-pointer| "pointer" |initializer| "")
      (|G-oslow| "oslow" |initializer| "")
      (|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-stdGetRetWord0| "stdGetRetWord0" 0 "")
      (|G-pointer_Pointer_476980157| "Pointer" 476980157 "pointer")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-oslow_OperatingSystemInterface_198516253|
        "OperatingSystemInterface"
        198516253
        "oslow")
      (|G-domainAddDefaults!| "domainAddDefaults!" 0 "")
      (|G-rtLazyCatFrInit| "rtLazyCatFrInit" 0 "")
      (|G-foamcat_BasicType_906312337| "BasicType" 906312337 "foamcat")
      (|G-domainMakeDispatch| "domainMakeDispatch" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-fname_FileName_901471140| "FileName" 901471140 "fname")
      (|G-fname| "fname" |initializer| "")))
