;;;
;;; Lisp code generated by Aldor from file "format.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-format-format|) ((|e1| |Env|)))

(declare-prog
  (|C1-format-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-format-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-format-format| |Word|)
  ((|P0-si| |Word|) (|P1-s| |Word|) (|P2-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-format-format| |Word|)
  ((|P0-bi| |Word|) (|P1-s| |Word|) (|P2-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-format-scan| |Word| |Word|)
  ((|P0-s| |Word|) (|P1-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-format-scan| |Word| |Word|)
  ((|P0-s| |Word|) (|P1-i| |Word|) (|e1| |Env|)))

(declare-type |G-format| |Clos|)

(declare-type |G-format_Format_042942907| |Word|)

(defspecials |G-format_Format_042942907|)

(|DDecl|
  |Struct-format-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl| |Struct-format-6| (\-0 |Word|) (\-1 |Word|))

(|DDecl|
  |Struct-format-9|
  (|scan-0| |Clos|)
  (|scan-1| |Clos|)
  (|format-2| |Clos|)
  (|format-3| |Clos|))

(|DDecl| |Struct-format-12| (\-0 |SInt|) (\-1 |SInt|))

(|DDecl| |Struct-format-13| (\-0 |BInt|) (\-1 |SInt|))

(defprog
  ((|C0-format-format|) ((|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-format-11| |Struct-format-11|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-format| |G-noOperation|)
  (setq
    |G-format_Format_042942907|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-format-addLevel0|)))
  (setq t0 (|ANew| |Word| (the |SInt| 2)))
  (setq t1 (|ANew| |Word| (the |SInt| 2)))
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 101877503))
  (|SetAElt| t1 (the |SInt| 0) (|MakeLit| "format"))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 56100169))
  (|SetAElt| t1 (the |SInt| 1) (|MakeLit| "scan"))
  (setq t2 (|RNew| |Struct-format-5|))
  (|SetRElt| |Struct-format-5| |size| 0 t2 (the |SInt| 2))
  (|SetRElt| |Struct-format-5| |nsize| 1 t2 (the |SInt| 2))
  (|SetRElt| |Struct-format-5| |values| 2 t2 t0)
  (setq t3 (|RNew| |Struct-format-5|))
  (|SetRElt| |Struct-format-5| |size| 0 t3 (the |SInt| 2))
  (|SetRElt| |Struct-format-5| |nsize| 1 t3 (the |SInt| 2))
  (|SetRElt| |Struct-format-5| |values| 2 t3 t1)
  (|CCall| |G-rtAddStrings| t2 t3)
  (block-return |C0-format-format| ()))

(defprog
  ((|C1-format-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Format")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 114435807))
  (block-return
    |C1-format-addLevel0|
    (|Clos| |e0| |C2-format-addLevel1|)))

(defprog
  ((|C2-format-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-format-9| |Struct-format-9|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq t0 (|ANew| |Word| (the |SInt| 4)))
  (setq t1 (|ANew| |Word| (the |SInt| 4)))
  (setq t2 (|ANew| |Word| (the |SInt| 4)))
  (|SetLex|
    |Struct-format-9-format-2|
    2
    |l0|
    (|Clos| |e0| |C3-format-format|))
  (|SetLex|
    |Struct-format-9-format-3|
    3
    |l0|
    (|Clos| |e0| |C4-format-format|))
  (|SetLex|
    |Struct-format-9-scan-0|
    0
    |l0|
    (|Clos| |e0| |C5-format-scan|))
  (|SetLex|
    |Struct-format-9-scan-1|
    1
    |l0|
    (|Clos| |e0| |C6-format-scan|))
  (setq t3 (|RNew| |Struct-format-5|))
  (|SetRElt| |Struct-format-5| |size| 0 t3 (the |SInt| 4))
  (|SetRElt| |Struct-format-5| |nsize| 1 t3 (the |SInt| 4))
  (|SetRElt| |Struct-format-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-format-5|))
  (|SetRElt| |Struct-format-5| |size| 0 t4 (the |SInt| 4))
  (|SetRElt| |Struct-format-5| |nsize| 1 t4 (the |SInt| 4))
  (|SetRElt| |Struct-format-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-format-5|))
  (|SetRElt| |Struct-format-5| |size| 0 t5 (the |SInt| 4))
  (|SetRElt| |Struct-format-5| |nsize| 1 t5 (the |SInt| 4))
  (|SetRElt| |Struct-format-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 101877503))
  (|SetAElt| t1 (the |SInt| 0) (the |SInt| 530147449))
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-format-9-format-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 101877503))
  (|SetAElt| t1 (the |SInt| 1) (the |SInt| 1037481679))
  (|SetAElt|
    t2
    (the |SInt| 1)
    (|Lex| |Struct-format-9-format-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 56100169))
  (|SetAElt| t1 (the |SInt| 2) (the |SInt| 941494304))
  (|SetAElt|
    t2
    (the |SInt| 2)
    (|Lex| |Struct-format-9-scan-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 56100169))
  (|SetAElt| t1 (the |SInt| 3) (the |SInt| 511420636))
  (|SetAElt|
    t2
    (the |SInt| 3)
    (|Lex| |Struct-format-9-scan-1| 1 |l0|))
  (block-return |C2-format-addLevel1| |P0-domain|))

(defprog
  ((|C3-format-format| |Word|)
    ((|P0-si| |Word|) (|P1-s| |Word|) (|P2-i| |Word|) (|e1| |Env|)))
  ((t0 |SInt|) (t1 |SInt|))
  (setq t1 (|SIntPrev| |P2-i|))
  (setq t0 (|FormatSInt| |P0-si| |P1-s| t1))
  (block-return |C3-format-format| (|SIntNext| t0)))

(defprog
  ((|C4-format-format| |Word|)
    ((|P0-bi| |Word|) (|P1-s| |Word|) (|P2-i| |Word|) (|e1| |Env|)))
  ((t0 |SInt|) (t1 |SInt|))
  (setq t1 (|SIntPrev| |P2-i|))
  (setq t0 (|FormatBInt| |P0-bi| |P1-s| t1))
  (block-return |C4-format-format| (|SIntNext| t0)))

(defprog
  ((|C5-format-scan| |Word| |Word|)
    ((|P0-s| |Word|) (|P1-i| |Word|) (|e1| |Env|)))
  ((t0 |Word|) (t1 |SInt|) (t2 |SInt|))
  (multiple-value-setq (t1 t2) (|ScanSInt| |P0-s| (|SIntPrev| |P1-i|)))
  (setq t0 (|SIntNext| t2))
  (block-return |C5-format-scan| (values t1 t0)))

(defprog
  ((|C6-format-scan| |Word| |Word|)
    ((|P0-s| |Word|) (|P1-i| |Word|) (|e1| |Env|)))
  ((t0 |Word|) (t1 |BInt|) (t2 |SInt|))
  (multiple-value-setq (t1 t2) (|ScanBInt| |P0-s| (|SIntPrev| |P1-i|)))
  (setq t0 (|SIntNext| t2))
  (block-return |C6-format-scan| (values t1 t0)))

(setq |G-format| (|Clos| nil |C0-format-format|))

(setq |G-format_Format_042942907| nil)

(file-imports
  '((|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-format_Format_042942907| "Format" 42942907 "format")
      (|G-format| "format" |initializer| "")))
