;;;
;;; Lisp code generated by Aldor from file "lang.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-lang-lang|) ((|e1| |Env|)))

(declare-prog
  (|C1-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-lang-->| |Word|)
  ((p0-a |Word|) (p1-r |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C7-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C8-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-lang-->*| |Word|)
  ((p0-a |Word|) (p1-r |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C11-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C12-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C13-lang-Tuple| |Word|) ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C15-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C16-lang-Cross| |Word|) ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C17-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C18-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C19-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C20-lang-Record| |Word|) ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C21-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C22-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C23-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C24-lang-Union| |Word|) ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C25-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C26-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C27-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C28-lang-Enumeration| |Word|)
  ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C29-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C30-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C31-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C32-lang-TrailingArray| |Word|)
  ((p0-i |Word|) (p1-a |Word|) (|e1| |Env|)))

(declare-prog
  (|C33-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog (|C34-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C35-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C36-lang-Join| |Word|) ((p0-t |Word|) (|e1| |Env|)))

(declare-prog (|C37-lang-defhash0| |SInt|) ((|e1| |Env|)))

(declare-prog
  (|C38-lang-Join|)
  ((|P0-self| |Word|) (|P1-dom| |Word|) (|e1| |Env|)))

(declare-prog (|C39-lang-addNameFn| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C40-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C41-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C42-lang-Generator| |Word|)
  ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C43-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C44-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C45-lang-Ref| |Word|) ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C46-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C47-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C48-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C49-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C50-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C51-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C52-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C53-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C54-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C55-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C56-lang-Foreign| |Word|)
  ((p0-t |Word|) (|e1| |Env|)))

(declare-prog
  (|C57-lang-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C58-lang-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-type |G-lang| |Clos|)

(declare-type |G-lang_Type_394624008| |Word|)

(declare-type |G-lang_Category_394624008| |Word|)

(declare-type |G-lang_->_586592031| |Clos|)

(declare-type |G-lang_->*_586592031| |Clos|)

(declare-type |G-lang_Tuple_814586999| |Clos|)

(declare-type |G-lang_Cross_799856246| |Clos|)

(declare-type |G-lang_Record_799856246| |Clos|)

(declare-type |G-lang_Union_799856246| |Clos|)

(declare-type |G-lang_Enumeration_799856246| |Clos|)

(declare-type |G-lang_TrailingArray_283473430| |Clos|)

(declare-type |G-lang_Join_459849284| |Clos|)

(declare-type |G-lang_Exit_394624008| |Word|)

(declare-type |G-lang_Generator_814586999| |Clos|)

(declare-type |G-lang_Ref_814586999| |Clos|)

(declare-type |G-lang_Literal_394624008| |Word|)

(declare-type |G-lang_Builtin_394624008| |Word|)

(declare-type |G-lang_C_394624008| |Word|)

(declare-type |G-lang_Lisp_394624008| |Word|)

(declare-type |G-lang_Foreign_814586999| |Clos|)

(defspecials
  |G-lang_Foreign_814586999|
  |G-lang_Lisp_394624008|
  |G-lang_C_394624008|
  |G-lang_Builtin_394624008|
  |G-lang_Literal_394624008|
  |G-lang_Ref_814586999|
  |G-lang_Generator_814586999|
  |G-lang_Exit_394624008|
  |G-lang_Join_459849284|
  |G-lang_TrailingArray_283473430|
  |G-lang_Enumeration_799856246|
  |G-lang_Union_799856246|
  |G-lang_Record_799856246|
  |G-lang_Cross_799856246|
  |G-lang_Tuple_814586999|
  |G-lang_->*_586592031|
  |G-lang_->_586592031|
  |G-lang_Category_394624008|
  |G-lang_Type_394624008|)

(|DDecl|
  |Struct-lang-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl| |Struct-lang-8| (|size-0| |SInt|) (|values-1| |Arr|))

(|DDecl| |Struct-lang-9| (|found-0| |Word|) (|value-1| |Word|))

(|DDecl| |Struct-lang-11| (a-0 |Word|) (r-1 |Word|))

(|DDecl| |Struct-lang-13| (a-0 |Word|) (r-1 |Word|))

(|DDecl| |Struct-lang-15| (t-0 |Word|))

(|DDecl| |Struct-lang-17| (t-0 |Word|))

(|DDecl| |Struct-lang-19| (t-0 |Word|))

(|DDecl| |Struct-lang-21| (t-0 |Word|))

(|DDecl| |Struct-lang-23| (t-0 |Word|))

(|DDecl| |Struct-lang-25| (i-0 |Word|) (a-1 |Word|))

(|DDecl| |Struct-lang-27| (t-0 |Word|))

(|DDecl| |Struct-lang-30| (t-0 |Word|))

(|DDecl| |Struct-lang-32| (t-0 |Word|))

(|DDecl| |Struct-lang-38| (t-0 |Word|))

(|DDecl|
  |Struct-lang-39|
  (\-0 |Word|)
  (\-1 |Word|)
  (\-2 |Word|)
  (\-3 |Word|)
  (\-4 |Word|)
  (\-5 |Word|)
  (\-6 |Word|)
  (\-7 |Word|)
  (\-8 |Word|)
  (\-9 |Word|)
  (\-10 |Word|)
  (\-11 |Word|))

(defprog
  ((|C0-lang-lang|) ((|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-39| |Struct-lang-39|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-lang| |G-noOperation|)
  (setq
    |G-lang_Type_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-lang-addLevel0|)))
  (setq
    |G-lang_Category_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C3-lang-addLevel0|)))
  (|SetLex| |Struct-lang-39--0| 0 |l0| nil)
  (setq |G-lang_->_586592031| (|Clos| |e0| |C5-lang-->|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_->_586592031|)
    (the |SInt| 51489085))
  (|SetLex| |Struct-lang-39--1| 1 |l0| nil)
  (setq |G-lang_->*_586592031| (|Clos| |e0| |C9-lang-->*|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_->*_586592031|)
    (the |SInt| 314286544))
  (|SetLex| |Struct-lang-39--2| 2 |l0| nil)
  (setq |G-lang_Tuple_814586999| (|Clos| |e0| |C13-lang-Tuple|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Tuple_814586999|)
    (the |SInt| 617884183))
  (|SetLex| |Struct-lang-39--3| 3 |l0| nil)
  (setq |G-lang_Cross_799856246| (|Clos| |e0| |C16-lang-Cross|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Cross_799856246|)
    (the |SInt| 697326103))
  (|SetLex| |Struct-lang-39--4| 4 |l0| nil)
  (setq |G-lang_Record_799856246| (|Clos| |e0| |C20-lang-Record|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Record_799856246|)
    (the |SInt| 296043733))
  (|SetLex| |Struct-lang-39--5| 5 |l0| nil)
  (setq |G-lang_Union_799856246| (|Clos| |e0| |C24-lang-Union|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Union_799856246|)
    (the |SInt| 900348438))
  (|SetLex| |Struct-lang-39--6| 6 |l0| nil)
  (setq
    |G-lang_Enumeration_799856246|
    (|Clos| |e0| |C28-lang-Enumeration|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Enumeration_799856246|)
    (the |SInt| 151783690))
  (|SetLex| |Struct-lang-39--7| 7 |l0| nil)
  (setq
    |G-lang_TrailingArray_283473430|
    (|Clos| |e0| |C32-lang-TrailingArray|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_TrailingArray_283473430|)
    (the |SInt| 28977038))
  (|SetLex| |Struct-lang-39--8| 8 |l0| nil)
  (setq |G-lang_Join_459849284| (|Clos| |e0| |C36-lang-Join|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Join_459849284|)
    (the |SInt| 850925108))
  (setq
    |G-lang_Exit_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C40-lang-addLevel0|)))
  (|SetLex| |Struct-lang-39--9| 9 |l0| nil)
  (setq |G-lang_Generator_814586999| (|Clos| |e0| |C42-lang-Generator|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Generator_814586999|)
    (the |SInt| 83976792))
  (|SetLex| |Struct-lang-39--10| 10 |l0| nil)
  (setq |G-lang_Ref_814586999| (|Clos| |e0| |C45-lang-Ref|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Ref_814586999|)
    (the |SInt| 316169048))
  (setq
    |G-lang_Literal_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C48-lang-addLevel0|)))
  (setq
    |G-lang_Builtin_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C50-lang-addLevel0|)))
  (setq
    |G-lang_C_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C52-lang-addLevel0|)))
  (setq
    |G-lang_Lisp_394624008|
    (|CCall| |G-domainMake| (|Clos| |e0| |C54-lang-addLevel0|)))
  (|SetLex| |Struct-lang-39--11| 11 |l0| nil)
  (setq |G-lang_Foreign_814586999| (|Clos| |e0| |C56-lang-Foreign|))
  (|SetProgHashCode|
    (|ClosFun| |G-lang_Foreign_814586999|)
    (the |SInt| 215472809))
  (block-return |C0-lang-lang| ()))

(defprog
  ((|C1-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Type")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 547382598))
  (block-return |C1-lang-addLevel0| (|Clos| |e0| |C2-lang-addLevel1|)))

(defprog
  ((|C2-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C2-lang-addLevel1| |P0-domain|))

(defprog
  ((|C3-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Category")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 82345606))
  (block-return |C3-lang-addLevel0| (|Clos| |e0| |C4-lang-addLevel1|)))

(defprog
  ((|C4-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C4-lang-addLevel1| |P0-domain|))

(defprog
  ((|C5-lang-->| |Word|) ((p0-a |Word|) (p1-r |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-11| |Struct-lang-11|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-11-A-0| 0 |l0| p0-a)
    (|SetLex| |Struct-lang-11-R-1| 1 |l0| p1-r)
    (setq t0 (|ANew| |Word| (the |SInt| 2)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--0| 0 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-11-A-0| 0 |l0|))
    (|SetAElt| t0 (the |SInt| 1) (|Lex| |Struct-lang-11-R-1| 1 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--0| 0 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C6-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--0| 0 |l1|) t1 t2))
    |Lab0|
    (block-return |C5-lang-->| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--0|
      0
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C6-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Record|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t3 (the |SInt| 51489085))
    (setq t0 (|Lex| |Struct-lang-11-A-0| 0 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab0|
    (when (|SIntEQ| t2 t1) (go |Lab1|))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab0|)
    |Lab1|
    (setq t0 (|Lex| |Struct-lang-11-R-1| 1 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab2|
    (when (|SIntEQ| t2 t1) (go |Lab3|))
    (setq t3 (|SIntHashCombine| (the |SInt| 32236) t3))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab2|)
    |Lab3|
    (|CCall|
      |G-domainAddNameFn!|
      |P0-domain|
      (|Clos| |e0| |C7-lang-addNameFn|))
    (|CCall| |G-domainAddHash!| |P0-domain| t3)
    (block-return |C6-lang-addLevel0| (|Clos| |e0| |C8-lang-addLevel1|))))

(defprog
  ((|C7-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |SInt|)
    (t4 |Arr|)
    (t5 |Record|)
    (t6 |Arr|)
    (t7 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-11-A-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-11-A-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq
      t3
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-11-R-1| 1 |l2|)))
    (setq t4 (|ANew| |Word| t3))
    (setq t5 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t5 t3)
    (|SetRElt| |Struct-lang-8| |values| 1 t5 t4)
    |Lab2|
    (setq t3 (|SIntPrev| t3))
    (when (|SIntIsNeg| t3) (go |Lab3|))
    (|SetAElt|
      t4
      t3
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-11-R-1| 1 |l2|))
          t3)))
    (go |Lab2|)
    |Lab3|
    (setq t6 (|ANew| |Word| (the |SInt| 3)))
    (|SetAElt|
      t6
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "->")))
    (|SetAElt|
      t6
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (|SetAElt|
      t6
      (the |SInt| 2)
      (|CCall| |G-namePartConcat| (the |Bool| t) t5))
    (setq t7 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t7 (the |SInt| 3))
    (|SetRElt| |Struct-lang-8| |values| 1 t7 t6)
    (block-return
      |C7-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t7))))

(defprog
  ((|C8-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C8-lang-addLevel1| |P0-domain|))

(defprog
  ((|C9-lang-->*| |Word|) ((p0-a |Word|) (p1-r |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-13| |Struct-lang-13|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-13-A-0| 0 |l0| p0-a)
    (|SetLex| |Struct-lang-13-R-1| 1 |l0| p1-r)
    (setq t0 (|ANew| |Word| (the |SInt| 2)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--1| 1 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-13-A-0| 0 |l0|))
    (|SetAElt| t0 (the |SInt| 1) (|Lex| |Struct-lang-13-R-1| 1 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--1| 1 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C10-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--1| 1 |l1|) t1 t2))
    |Lab0|
    (block-return |C9-lang-->*| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--1|
      1
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C10-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Record|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t3 (the |SInt| 314286544))
    (setq t0 (|Lex| |Struct-lang-13-A-0| 0 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab0|
    (when (|SIntEQ| t2 t1) (go |Lab1|))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab0|)
    |Lab1|
    (setq t0 (|Lex| |Struct-lang-13-R-1| 1 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab2|
    (when (|SIntEQ| t2 t1) (go |Lab3|))
    (setq t3 (|SIntHashCombine| (the |SInt| 54955) t3))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab2|)
    |Lab3|
    (|CCall|
      |G-domainAddNameFn!|
      |P0-domain|
      (|Clos| |e0| |C11-lang-addNameFn|))
    (|CCall| |G-domainAddHash!| |P0-domain| t3)
    (block-return |C10-lang-addLevel0| (|Clos| |e0| |C12-lang-addLevel1|))))

(defprog
  ((|C11-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |SInt|)
    (t4 |Arr|)
    (t5 |Record|)
    (t6 |Arr|)
    (t7 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-13-A-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-13-A-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq
      t3
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-13-R-1| 1 |l2|)))
    (setq t4 (|ANew| |Word| t3))
    (setq t5 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t5 t3)
    (|SetRElt| |Struct-lang-8| |values| 1 t5 t4)
    |Lab2|
    (setq t3 (|SIntPrev| t3))
    (when (|SIntIsNeg| t3) (go |Lab3|))
    (|SetAElt|
      t4
      t3
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-13-R-1| 1 |l2|))
          t3)))
    (go |Lab2|)
    |Lab3|
    (setq t6 (|ANew| |Word| (the |SInt| 3)))
    (|SetAElt|
      t6
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "->*")))
    (|SetAElt|
      t6
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (|SetAElt|
      t6
      (the |SInt| 2)
      (|CCall| |G-namePartConcat| (the |Bool| t) t5))
    (setq t7 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t7 (the |SInt| 3))
    (|SetRElt| |Struct-lang-8| |values| 1 t7 t6)
    (block-return
      |C11-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t7))))

(defprog
  ((|C12-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C12-lang-addLevel1| |P0-domain|))

(defprog
  ((|C13-lang-Tuple| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-15| |Struct-lang-15|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-15-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--2| 2 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-15-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--2| 2 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C14-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--2| 2 |l1|) t1 t2))
    |Lab0|
    (block-return |C13-lang-Tuple| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--2|
      2
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C14-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|) (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall|
      |G-rtSingleParamNameFn|
      (|MakeLit| "Tuple")
      (|Lex| |Struct-lang-15-T-0| 0 |l1|)))
  (|CCall|
    |G-domainAddHash!|
    |P0-domain|
    (|SIntHashCombine|
      (|CCall| |G-domainHash!| (|Lex| |Struct-lang-15-T-0| 0 |l1|))
      (the |SInt| 617884183)))
  (block-return |C14-lang-addLevel0| (|Clos| |e0| |C15-lang-addLevel1|)))

(defprog
  ((|C15-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C15-lang-addLevel1| |P0-domain|))

(defprog
  ((|C16-lang-Cross| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-17| |Struct-lang-17|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-17-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--3| 3 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-17-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--3| 3 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C17-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--3| 3 |l1|) t1 t2))
    |Lab0|
    (block-return |C16-lang-Cross| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--3|
      3
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C17-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Record|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t3 (the |SInt| 697326103))
    (setq t0 (|Lex| |Struct-lang-17-T-0| 0 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab0|
    (when (|SIntEQ| t2 t1) (go |Lab1|))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab0|)
    |Lab1|
    (|CCall|
      |G-domainAddNameFn!|
      |P0-domain|
      (|Clos| |e0| |C18-lang-addNameFn|))
    (|CCall| |G-domainAddHash!| |P0-domain| t3)
    (block-return |C17-lang-addLevel0| (|Clos| |e0| |C19-lang-addLevel1|))))

(defprog
  ((|C18-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Arr|)
    (t4 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-17-T-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-17-T-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq t3 (|ANew| |Word| (the |SInt| 2)))
    (|SetAElt|
      t3
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "Cross")))
    (|SetAElt|
      t3
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (setq t4 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t4 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t4 t3)
    (block-return
      |C18-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t4))))

(defprog
  ((|C19-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C19-lang-addLevel1| |P0-domain|))

(defprog
  ((|C20-lang-Record| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-19| |Struct-lang-19|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-19-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--4| 4 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-19-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--4| 4 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C21-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--4| 4 |l1|) t1 t2))
    |Lab0|
    (block-return |C20-lang-Record| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--4|
      4
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C21-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Record|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t3 (the |SInt| 296043733))
    (setq t0 (|Lex| |Struct-lang-19-T-0| 0 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab0|
    (when (|SIntEQ| t2 t1) (go |Lab1|))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab0|)
    |Lab1|
    (|CCall|
      |G-domainAddNameFn!|
      |P0-domain|
      (|Clos| |e0| |C22-lang-addNameFn|))
    (|CCall| |G-domainAddHash!| |P0-domain| t3)
    (block-return |C21-lang-addLevel0| (|Clos| |e0| |C23-lang-addLevel1|))))

(defprog
  ((|C22-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Arr|)
    (t4 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-19-T-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-19-T-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq t3 (|ANew| |Word| (the |SInt| 2)))
    (|SetAElt|
      t3
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "Record")))
    (|SetAElt|
      t3
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (setq t4 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t4 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t4 t3)
    (block-return
      |C22-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t4))))

(defprog
  ((|C23-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C23-lang-addLevel1| |P0-domain|))

(defprog
  ((|C24-lang-Union| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-21| |Struct-lang-21|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-21-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--5| 5 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-21-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--5| 5 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C25-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--5| 5 |l1|) t1 t2))
    |Lab0|
    (block-return |C24-lang-Union| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--5|
      5
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C25-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Record|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t3 (the |SInt| 900348438))
    (setq t0 (|Lex| |Struct-lang-21-T-0| 0 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab0|
    (when (|SIntEQ| t2 t1) (go |Lab1|))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-domainHash!|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab0|)
    |Lab1|
    (|CCall|
      |G-domainAddNameFn!|
      |P0-domain|
      (|Clos| |e0| |C26-lang-addNameFn|))
    (|CCall| |G-domainAddHash!| |P0-domain| t3)
    (block-return |C25-lang-addLevel0| (|Clos| |e0| |C27-lang-addLevel1|))))

(defprog
  ((|C26-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Arr|)
    (t4 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-21-T-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-21-T-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq t3 (|ANew| |Word| (the |SInt| 2)))
    (|SetAElt|
      t3
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "Union")))
    (|SetAElt|
      t3
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (setq t4 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t4 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t4 t3)
    (block-return
      |C26-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t4))))

(defprog
  ((|C27-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C27-lang-addLevel1| |P0-domain|))

(defprog
  ((|C28-lang-Enumeration| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-23| |Struct-lang-23|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-23-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--6| 6 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-23-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--6| 6 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C29-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--6| 6 |l1|) t1 t2))
    |Lab0|
    (block-return |C28-lang-Enumeration| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--6|
      6
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C29-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Record|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq t3 (the |SInt| 151783690))
    (setq t0 (|Lex| |Struct-lang-23-T-0| 0 |l1|))
    (setq t1 (|RElt| |Struct-lang-8| |size| 0 t0))
    (setq t2 (the |SInt| 0))
    |Lab0|
    (when (|SIntEQ| t2 t1) (go |Lab1|))
    (setq
      t3
      (|SIntHashCombine|
        (|CCall|
          |G-stringHash|
          (|AElt| (|RElt| |Struct-lang-8| |values| 1 t0) t2))
        t3))
    (setq t2 (|SIntNext| t2))
    (go |Lab0|)
    |Lab1|
    (|CCall|
      |G-domainAddNameFn!|
      |P0-domain|
      (|Clos| |e0| |C30-lang-addNameFn|))
    (|CCall| |G-domainAddHash!| |P0-domain| t3)
    (block-return |C29-lang-addLevel0| (|Clos| |e0| |C31-lang-addLevel1|))))

(defprog
  ((|C30-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Arr|)
    (t4 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-23-T-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-namePartFrString|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-23-T-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq t3 (|ANew| |Word| (the |SInt| 2)))
    (|SetAElt|
      t3
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "Enumeration")))
    (|SetAElt|
      t3
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (setq t4 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t4 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t4 t3)
    (block-return
      |C30-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t4))))

(defprog
  ((|C31-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C31-lang-addLevel1| |P0-domain|))

(defprog
  ((|C32-lang-TrailingArray| |Word|)
    ((p0-i |Word|) (p1-a |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-25| |Struct-lang-25|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-25-I-0| 0 |l0| p0-i)
    (|SetLex| |Struct-lang-25-A-1| 1 |l0| p1-a)
    (setq t0 (|ANew| |Word| (the |SInt| 2)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--7| 7 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-25-I-0| 0 |l0|))
    (|SetAElt| t0 (the |SInt| 1) (|Lex| |Struct-lang-25-A-1| 1 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--7| 7 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C33-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--7| 7 |l1|) t1 t2))
    |Lab0|
    (block-return |C32-lang-TrailingArray| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--7|
      7
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C33-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|Clos| |e0| |C34-lang-addNameFn|))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 744839909))
  (block-return |C33-lang-addLevel0| (|Clos| |e0| |C35-lang-addLevel1|)))

(defprog
  ((|C34-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |SInt|)
    (t4 |Arr|)
    (t5 |Record|)
    (t6 |Arr|)
    (t7 |Record|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-25-I-0| 0 |l2|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-25-I-0| 0 |l2|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq
      t3
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-25-A-1| 1 |l2|)))
    (setq t4 (|ANew| |Word| t3))
    (setq t5 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t5 t3)
    (|SetRElt| |Struct-lang-8| |values| 1 t5 t4)
    |Lab2|
    (setq t3 (|SIntPrev| t3))
    (when (|SIntIsNeg| t3) (go |Lab3|))
    (|SetAElt|
      t4
      t3
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-25-A-1| 1 |l2|))
          t3)))
    (go |Lab2|)
    |Lab3|
    (setq t6 (|ANew| |Word| (the |SInt| 3)))
    (|SetAElt|
      t6
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "TrailingArray")))
    (|SetAElt|
      t6
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (|SetAElt|
      t6
      (the |SInt| 2)
      (|CCall| |G-namePartConcat| (the |Bool| t) t5))
    (setq t7 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t7 (the |SInt| 3))
    (|SetRElt| |Struct-lang-8| |values| 1 t7 t6)
    (block-return
      |C34-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t7))))

(defprog
  ((|C35-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C35-lang-addLevel1| |P0-domain|))

(defprog
  ((|C36-lang-Join| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-27| |Struct-lang-27|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-27-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--8| 8 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-27-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--8| 8 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq
      t2
      (|CCall|
        |G-categoryMake|
        (|Clos| |e0| |C38-lang-Join|)
        (|Clos| |e0| |C37-lang-defhash0|)
        (|Clos| |e0| |C39-lang-addNameFn|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--8| 8 |l1|) t1 t2))
    |Lab0|
    (block-return |C36-lang-Join| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--8|
      8
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C37-lang-defhash0| |SInt|) ((|e1| |Env|)))
  ()
  (block-return |C37-lang-defhash0| (the |SInt| 587876332)))

(defprog
  ((|C38-lang-Join|)
    ((|P0-self| |Word|) (|P1-dom| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 1)))
  (setq t1 (|ANew| |Word| (the |SInt| 1)))
  (setq t2 (|ANew| |Word| (the |SInt| 1)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 1))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 1))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 1))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 1))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 1))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 1))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-categoryAddExports!| |P0-self| t3 t4 t5)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 51482908))
  (|SetAElt| t1 (the |SInt| 0) (the |SInt| 587876332))
  (|SetAElt| t2 (the |SInt| 0) |P1-dom|)
  (block-return |C38-lang-Join| ()))

(defprog
  ((|C39-lang-addNameFn| |Word|) ((|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |Arr|)
    (t2 |Record|)
    (t3 |Arr|)
    (t4 |Record|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq
      t0
      (|RElt|
        |Struct-lang-8|
        |size|
        0
        (|Lex| |Struct-lang-27-T-0| 0 |l1|)))
    (setq t1 (|ANew| |Word| t0))
    (setq t2 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t2 t0)
    (|SetRElt| |Struct-lang-8| |values| 1 t2 t1)
    |Lab0|
    (setq t0 (|SIntPrev| t0))
    (when (|SIntIsNeg| t0) (go |Lab1|))
    (|SetAElt|
      t1
      t0
      (|CCall|
        |G-domainName|
        (|AElt|
          (|RElt|
            |Struct-lang-8|
            |values|
            1
            (|Lex| |Struct-lang-27-T-0| 0 |l1|))
          t0)))
    (go |Lab0|)
    |Lab1|
    (setq t3 (|ANew| |Word| (the |SInt| 2)))
    (|SetAElt|
      t3
      (the |SInt| 0)
      (|CCall| |G-namePartFrString| (|MakeLit| "Join")))
    (|SetAElt|
      t3
      (the |SInt| 1)
      (|CCall| |G-namePartConcat| (the |Bool| t) t2))
    (setq t4 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t4 (the |SInt| 2))
    (|SetRElt| |Struct-lang-8| |values| 1 t4 t3)
    (block-return
      |C39-lang-addNameFn|
      (|CCall| |G-namePartConcat| (the |Bool| nil) t4))))

(defprog
  ((|C40-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Exit")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 837958462))
  (block-return |C40-lang-addLevel0| (|Clos| |e0| |C41-lang-addLevel1|)))

(defprog
  ((|C41-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C41-lang-addLevel1| |P0-domain|))

(defprog
  ((|C42-lang-Generator| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-30| |Struct-lang-30|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-30-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--9| 9 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-30-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--9| 9 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C43-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--9| 9 |l1|) t1 t2))
    |Lab0|
    (block-return |C42-lang-Generator| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--9|
      9
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C43-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|) (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall|
      |G-rtSingleParamNameFn|
      (|MakeLit| "Generator")
      (|Lex| |Struct-lang-30-T-0| 0 |l1|)))
  (|CCall|
    |G-domainAddHash!|
    |P0-domain|
    (|SIntHashCombine|
      (|CCall| |G-domainHash!| (|Lex| |Struct-lang-30-T-0| 0 |l1|))
      (the |SInt| 83976792)))
  (block-return |C43-lang-addLevel0| (|Clos| |e0| |C44-lang-addLevel1|)))

(defprog
  ((|C44-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C44-lang-addLevel1| |P0-domain|))

(defprog
  ((|C45-lang-Ref| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-32| |Struct-lang-32|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-32-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--10| 10 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-32-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--10| 10 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C46-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--10| 10 |l1|) t1 t2))
    |Lab0|
    (block-return |C45-lang-Ref| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--10|
      10
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C46-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|) (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall|
      |G-rtSingleParamNameFn|
      (|MakeLit| "Ref")
      (|Lex| |Struct-lang-32-T-0| 0 |l1|)))
  (|CCall|
    |G-domainAddHash!|
    |P0-domain|
    (|SIntHashCombine|
      (|CCall| |G-domainHash!| (|Lex| |Struct-lang-32-T-0| 0 |l1|))
      (the |SInt| 316169048)))
  (block-return |C46-lang-addLevel0| (|Clos| |e0| |C47-lang-addLevel1|)))

(defprog
  ((|C47-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C47-lang-addLevel1| |P0-domain|))

(defprog
  ((|C48-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Literal")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 887424172))
  (block-return |C48-lang-addLevel0| (|Clos| |e0| |C49-lang-addLevel1|)))

(defprog
  ((|C49-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C49-lang-addLevel1| |P0-domain|))

(defprog
  ((|C50-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Builtin")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 771223478))
  (block-return |C50-lang-addLevel0| (|Clos| |e0| |C51-lang-addLevel1|)))

(defprog
  ((|C51-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C51-lang-addLevel1| |P0-domain|))

(defprog
  ((|C52-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "C")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 200108))
  (block-return |C52-lang-addLevel0| (|Clos| |e0| |C53-lang-addLevel1|)))

(defprog
  ((|C53-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C53-lang-addLevel1| |P0-domain|))

(defprog
  ((|C54-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Lisp")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 144194108))
  (block-return |C54-lang-addLevel0| (|Clos| |e0| |C55-lang-addLevel1|)))

(defprog
  ((|C55-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C55-lang-addLevel1| |P0-domain|))

(defprog
  ((|C56-lang-Foreign| |Word|) ((p0-t |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Bool|)
    (t4 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-lang-38| |Struct-lang-38|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-lang-38-T-0| 0 |l0| p0-t)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-lang-8|))
    (|SetRElt| |Struct-lang-8| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-lang-8| |values| 1 t1 t0)
    (when (|PtrIsNil| (|Lex| |Struct-lang-39--11| 11 |l1|)) (go |Lab3|))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-lang-38-T-0| 0 |l0|))
    (multiple-value-setq
      (t2 t4)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-lang-39--11| 11 |l1|) t1))
    (setq t3 t4)
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C57-lang-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-lang-39--11| 11 |l1|) t1 t2))
    |Lab0|
    (block-return |C56-lang-Foreign| t2)
    |Lab3|
    (|SetLex|
      |Struct-lang-39--11|
      11
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    (go |Lab1|)))

(defprog
  ((|C57-lang-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|) (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall|
      |G-rtSingleParamNameFn|
      (|MakeLit| "Foreign")
      (|Lex| |Struct-lang-38-T-0| 0 |l1|)))
  (|CCall|
    |G-domainAddHash!|
    |P0-domain|
    (|SIntHashCombine|
      (|CCall| |G-domainHash!| (|Lex| |Struct-lang-38-T-0| 0 |l1|))
      (the |SInt| 215472809)))
  (block-return |C57-lang-addLevel0| (|Clos| |e0| |C58-lang-addLevel1|)))

(defprog
  ((|C58-lang-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t3 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-lang-5|))
  (|SetRElt| |Struct-lang-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-lang-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (block-return |C58-lang-addLevel1| |P0-domain|))

(setq |G-lang| (|Clos| nil |C0-lang-lang|))

(setq |G-lang_Foreign_814586999| nil)

(setq |G-lang_Lisp_394624008| nil)

(setq |G-lang_C_394624008| nil)

(setq |G-lang_Builtin_394624008| nil)

(setq |G-lang_Literal_394624008| nil)

(setq |G-lang_Ref_814586999| nil)

(setq |G-lang_Generator_814586999| nil)

(setq |G-lang_Exit_394624008| nil)

(setq |G-lang_Join_459849284| nil)

(setq |G-lang_TrailingArray_283473430| nil)

(setq |G-lang_Enumeration_799856246| nil)

(setq |G-lang_Union_799856246| nil)

(setq |G-lang_Record_799856246| nil)

(setq |G-lang_Cross_799856246| nil)

(setq |G-lang_->*_586592031| nil)

(setq |G-lang_Tuple_814586999| nil)

(setq |G-lang_->_586592031| nil)

(setq |G-lang_Category_394624008| nil)

(setq |G-lang_Type_394624008| nil)

(file-imports
  '((|G-categoryMake| "categoryMake" 0 "")
      (|G-categoryAddExports!| "categoryAddExports!" 0 "")
      (|G-stringHash| "stringHash" 0 "")
      (|G-rtSingleParamNameFn| "rtSingleParamNameFn" 0 "")
      (|G-rtCacheAdd| "rtCacheAdd" 0 "")
      (|G-namePartConcat| "namePartConcat" 0 "")
      (|G-domainName| "domainName" 0 "")
      (|G-namePartFrString| "namePartFrString" 0 "")
      (|G-domainHash!| "domainHash!" 0 "")
      (|G-rtCacheCheck| "rtCacheCheck" 0 "")
      (|G-rtCacheExplicitMake| "rtCacheExplicitMake" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-lang_Type_394624008| "Type" 394624008 "lang")
      (|G-lang_Category_394624008| "Category" 394624008 "lang")
      (|G-lang_->_586592031| "->" 586592031 "lang")
      (|G-lang_Tuple_814586999| "Tuple" 814586999 "lang")
      (|G-lang_->*_586592031| "->*" 586592031 "lang")
      (|G-lang_Cross_799856246| "Cross" 799856246 "lang")
      (|G-lang_Record_799856246| "Record" 799856246 "lang")
      (|G-lang_Union_799856246| "Union" 799856246 "lang")
      (|G-lang_Enumeration_799856246| "Enumeration" 799856246 "lang")
      (|G-lang_TrailingArray_283473430| "TrailingArray" 283473430 "lang")
      (|G-lang_Join_459849284| "Join" 459849284 "lang")
      (|G-lang_Exit_394624008| "Exit" 394624008 "lang")
      (|G-lang_Generator_814586999| "Generator" 814586999 "lang")
      (|G-lang_Ref_814586999| "Ref" 814586999 "lang")
      (|G-lang_Literal_394624008| "Literal" 394624008 "lang")
      (|G-lang_Builtin_394624008| "Builtin" 394624008 "lang")
      (|G-lang_C_394624008| "C" 394624008 "lang")
      (|G-lang_Lisp_394624008| "Lisp" 394624008 "lang")
      (|G-lang_Foreign_814586999| "Foreign" 814586999 "lang")
      (|G-lang| "lang" |initializer| "")))
