;;;
;;; Lisp code generated by Aldor from file "pointer.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-pointer-pointer|) ((|e1| |Env|)))

(declare-prog
  (|C1-pointer-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-pointer-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog (|C3-pointer-nil| |Word|) ((|e1| |Env|)))

(declare-prog
  (|C4-pointer-nil?| |Word|)
  ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-pointer-=| |Word|)
  ((|P0-p| |Word|) (|P1-q| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-pointer-<<| |Word|)
  ((|P0-w| |Word|) (|P1-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C7-pointer-coerce| |Word|)
  ((|P0-p| |Ptr|) (|e1| |Env|)))

(declare-prog
  (|C8-pointer-coerce| |Ptr|)
  ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-pointer-test| |Word|)
  ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-pointer-~=| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C11-pointer-<<| |Clos|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C12-pointer-<<| |Word|)
  ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C13-pointer-hash| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-pointer-case| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C15-pointer-extend0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C16-pointer-basic-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C17-pointer-foamcat-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-pointer| |Clos|)

(declare-type |G-pointer_Pointer_931707449| |Word|)

(declare-type |G-pointer_Pointer_476980157| |Word|)

(defspecials
  |G-pointer_Pointer_476980157|
  |G-pointer_Pointer_931707449|)

(|DDecl|
  |Struct-pointer-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl| |Struct-pointer-6| (|x-0| |Word|))

(|DDecl|
  |Struct-pointer-7|
  (|case-0| |Clos|)
  (|hash-1| |Clos|)
  (~=-2 |Clos|)
  (|test-3| |Clos|)
  (|coerce-4| |Clos|)
  (|coerce-5| |Clos|)
  (<<-6 |Clos|)
  (<<-7 |Clos|)
  (=-8 |Clos|)
  (|nil?-9| |Clos|)
  (|nil-10| |Clos|)
  (\-11 |SInt|))

(|DDecl|
  |Struct-pointer-9|
  (|Pointer-0| |Word|)
  (|Conditional-1| |Word|)
  (\-2 |Bool|)
  (\-3 |Bool|))

(|DDecl| |Struct-pointer-10| (\-0 |Clos|) (\-1 |Clos|) (\-2 |Clos|))

(defprog
  ((|C0-pointer-pointer|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Arr|)
    (t3 |Arr|)
    (t4 |Record|)
    (t5 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-pointer-9| |Struct-pointer-9|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-pointer| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C17-pointer-foamcat-init|))
  (setq t1 (|Clos| |e0| |C16-pointer-basic-init|))
  (setq
    |G-pointer_Pointer_931707449|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-pointer-addLevel0|)))
  (setq
    |G-pointer_Pointer_476980157|
    (|CCall| |G-extendMake| (|Clos| |e0| |C15-pointer-extend0|)))
  (|SetLex| |Struct-pointer-9--2| 2 |l0| (the |Bool| nil))
  (|SetLex| |Struct-pointer-9--3| 3 |l0| (the |Bool| nil))
  (setq t2 (|ANew| |Word| (the |SInt| 10)))
  (setq t3 (|ANew| |Word| (the |SInt| 10)))
  (|SetAElt| t2 (the |SInt| 0) (the |SInt| 770345191))
  (|SetAElt| t3 (the |SInt| 0) (|MakeLit| "coerce"))
  (|SetAElt| t2 (the |SInt| 1) (the |SInt| 200102))
  (|SetAElt| t3 (the |SInt| 1) (|MakeLit| "="))
  (|SetAElt| t2 (the |SInt| 2) (the |SInt| 783695654))
  (|SetAElt| t3 (the |SInt| 2) (|MakeLit| "nil?"))
  (|SetAElt| t2 (the |SInt| 3) (the |SInt| 51509389))
  (|SetAElt| t3 (the |SInt| 3) (|MakeLit| "~="))
  (|SetAElt| t2 (the |SInt| 4) (the |SInt| 255806968))
  (|SetAElt| t3 (the |SInt| 4) (|MakeLit| "sample"))
  (|SetAElt| t2 (the |SInt| 5) (the |SInt| 864625472))
  (|SetAElt| t3 (the |SInt| 5) (|MakeLit| "case"))
  (|SetAElt| t2 (the |SInt| 6) (the |SInt| 5509732))
  (|SetAElt| t3 (the |SInt| 6) (|MakeLit| "test"))
  (|SetAElt| t2 (the |SInt| 7) (the |SInt| 318525310))
  (|SetAElt| t3 (the |SInt| 7) (|MakeLit| "nil"))
  (|SetAElt| t2 (the |SInt| 8) (the |SInt| 746853960))
  (|SetAElt| t3 (the |SInt| 8) (|MakeLit| "hash"))
  (|SetAElt| t2 (the |SInt| 9) (the |SInt| 51492426))
  (|SetAElt| t3 (the |SInt| 9) (|MakeLit| "<<"))
  (setq t4 (|RNew| |Struct-pointer-5|))
  (|SetRElt| |Struct-pointer-5| |size| 0 t4 (the |SInt| 10))
  (|SetRElt| |Struct-pointer-5| |nsize| 1 t4 (the |SInt| 10))
  (|SetRElt| |Struct-pointer-5| |values| 2 t4 t2)
  (setq t5 (|RNew| |Struct-pointer-5|))
  (|SetRElt| |Struct-pointer-5| |size| 0 t5 (the |SInt| 10))
  (|SetRElt| |Struct-pointer-5| |nsize| 1 t5 (the |SInt| 10))
  (|SetRElt| |Struct-pointer-5| |values| 2 t5 t3)
  (|CCall| |G-rtAddStrings| t4 t5)
  (|SetLex|
    |Struct-pointer-9-Conditional-1|
    1
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-pointer-9-Pointer-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 4)))
  (block-return |C0-pointer-pointer| ()))

(defprog
  ((|C1-pointer-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "Pointer")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 195553216))
  (block-return
    |C1-pointer-addLevel0|
    (|Clos| |e0| |C2-pointer-addLevel1|)))

(defprog
  ((|C2-pointer-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Word|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |SInt|)
    (t14 |SInt|)
    (t15 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-pointer-7| |Struct-pointer-7|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (setq t0 (|ANew| |Word| (the |SInt| 12)))
  (setq t1 (|ANew| |Word| (the |SInt| 12)))
  (setq t2 (|ANew| |Word| (the |SInt| 12)))
  (setq t6 (|CCall| |G-domainMakeDispatch| |P0-domain|))
  (|SetLex| |Struct-pointer-7--11| 11 |l0| |P1-hashcode|)
  (|SetLex|
    |Struct-pointer-7-nil-10|
    10
    |l0|
    (|Clos| |e0| |C3-pointer-nil|))
  (|SetLex|
    |Struct-pointer-7-nil?-9|
    9
    |l0|
    (|Clos| |e0| |C4-pointer-nil?|))
  (|SetLex|
    |Struct-pointer-7-=-8|
    8
    |l0|
    (|Clos| |e0| |C5-pointer-=|))
  (|SetLex|
    |Struct-pointer-7-<<-6|
    6
    |l0|
    (|Clos| |e0| |C6-pointer-<<|))
  (|SetLex|
    |Struct-pointer-7-coerce-4|
    4
    |l0|
    (|Clos| |e0| |C7-pointer-coerce|))
  (|SetLex|
    |Struct-pointer-7-coerce-5|
    5
    |l0|
    (|Clos| |e0| |C8-pointer-coerce|))
  (|SetLex|
    |Struct-pointer-7-test-3|
    3
    |l0|
    (|Clos| |e0| |C9-pointer-test|))
  (|SetLex|
    |Struct-pointer-7-~=-2|
    2
    |l0|
    (|Clos| |e0| |C10-pointer-~=|))
  (|SetLex|
    |Struct-pointer-7-<<-7|
    7
    |l0|
    (|Clos| |e0| |C11-pointer-<<|))
  (|SetLex|
    |Struct-pointer-7-hash-1|
    1
    |l0|
    (|Clos| |e0| |C13-pointer-hash|))
  (|SetLex|
    |Struct-pointer-7-case-0|
    0
    |l0|
    (|Clos| |e0| |C14-pointer-case|))
  (setq
    t7
    (|SIntHashCombine|
      (|Lex| |Struct-pointer-7--11| 11 |l0|)
      (the |SInt| 275363373)))
  (setq
    t14
    (|SIntHashCombine|
      (|Lex| |Struct-pointer-7--11| 11 |l0|)
      (the |SInt| 51489085)))
  (setq t15 (|SIntHashCombine| (the |SInt| 32236) t14))
  (setq t8 (|SIntHashCombine| (the |SInt| 740244383) t15))
  (setq
    t9
    (|SIntHashCombine|
      (the |SInt| 740244383)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine| (|Lex| |Struct-pointer-7--11| 11 |l0|) t14))))
  (setq
    t10
    (|SIntHashCombine|
      (the |SInt| 182752316)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-pointer-7--11| 11 |l0|)
          (the |SInt| 102896482)))))
  (setq t11 (|SIntHashCombine| (the |SInt| 755420535) t15))
  (setq t12 (|SIntHashCombine| (the |SInt| 33717313) t15))
  (setq t13 (|Lex| |Struct-pointer-7--11| 11 |l0|))
  (setq t3 (|RNew| |Struct-pointer-5|))
  (|SetRElt| |Struct-pointer-5| |size| 0 t3 (the |SInt| 12))
  (|SetRElt| |Struct-pointer-5| |nsize| 1 t3 (the |SInt| 12))
  (|SetRElt| |Struct-pointer-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-pointer-5|))
  (|SetRElt| |Struct-pointer-5| |size| 0 t4 (the |SInt| 12))
  (|SetRElt| |Struct-pointer-5| |nsize| 1 t4 (the |SInt| 12))
  (|SetRElt| |Struct-pointer-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-pointer-5|))
  (|SetRElt| |Struct-pointer-5| |size| 0 t5 (the |SInt| 12))
  (|SetRElt| |Struct-pointer-5| |nsize| 1 t5 (the |SInt| 12))
  (|SetRElt| |Struct-pointer-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|CCall|
    |G-domainAddDefaults!|
    |P0-domain|
    (|Lex| |Struct-pointer-9-Conditional-1| 1 |l2|)
    t6)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 318525310))
  (|SetAElt| t1 (the |SInt| 0) t7)
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-pointer-7-nil-10| 10 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 783695654))
  (|SetAElt| t1 (the |SInt| 1) t8)
  (|SetAElt|
    t2
    (the |SInt| 1)
    (|Lex| |Struct-pointer-7-nil?-9| 9 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 200102))
  (|SetAElt| t1 (the |SInt| 2) t9)
  (|SetAElt|
    t2
    (the |SInt| 2)
    (|Lex| |Struct-pointer-7-=-8| 8 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 3) t10)
  (|SetAElt|
    t2
    (the |SInt| 3)
    (|Lex| |Struct-pointer-7-<<-6| 6 |l0|))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 770345191))
  (|SetAElt|
    t1
    (the |SInt| 4)
    (|SIntHashCombine|
      (|Lex| |Struct-pointer-7--11| 11 |l0|)
      (the |SInt| 650859879)))
  (|SetAElt|
    t2
    (the |SInt| 4)
    (|Lex| |Struct-pointer-7-coerce-4| 4 |l0|))
  (|SetAElt| t0 (the |SInt| 5) (the |SInt| 770345191))
  (|SetAElt|
    t1
    (the |SInt| 5)
    (|SIntHashCombine|
      (the |SInt| 316039793)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-pointer-7--11| 11 |l0|)
          (the |SInt| 51489085)))))
  (|SetAElt|
    t2
    (the |SInt| 5)
    (|Lex| |Struct-pointer-7-coerce-5| 5 |l0|))
  (|SetAElt| t0 (the |SInt| 6) (the |SInt| 5509732))
  (|SetAElt| t1 (the |SInt| 6) t8)
  (|SetAElt|
    t2
    (the |SInt| 6)
    (|Lex| |Struct-pointer-7-test-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 7) (the |SInt| 51509389))
  (|SetAElt| t1 (the |SInt| 7) t9)
  (|SetAElt|
    t2
    (the |SInt| 7)
    (|Lex| |Struct-pointer-7-~=-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 8) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 8) t11)
  (|SetAElt|
    t2
    (the |SInt| 8)
    (|Lex| |Struct-pointer-7-<<-7| 7 |l0|))
  (|SetAElt| t0 (the |SInt| 9) (the |SInt| 746853960))
  (|SetAElt| t1 (the |SInt| 9) t12)
  (|SetAElt|
    t2
    (the |SInt| 9)
    (|Lex| |Struct-pointer-7-hash-1| 1 |l0|))
  (|SetAElt| t0 (the |SInt| 10) (the |SInt| 864625472))
  (|SetAElt| t1 (the |SInt| 10) t9)
  (|SetAElt|
    t2
    (the |SInt| 10)
    (|Lex| |Struct-pointer-7-case-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 11) (the |SInt| 255806968))
  (|SetAElt| t1 (the |SInt| 11) t13)
  (|SetAElt| t2 (the |SInt| 11) nil)
  (block-return |C2-pointer-addLevel1| |P0-domain|))

(defprog
  ((|C3-pointer-nil| |Word|) ((|e1| |Env|)))
  ()
  (block-return |C3-pointer-nil| nil))

(defprog
  ((|C4-pointer-nil?| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ()
  (block-return |C4-pointer-nil?| (|PtrIsNil| |P0-p|)))

(defprog
  ((|C5-pointer-=| |Word|)
    ((|P0-p| |Word|) (|P1-q| |Word|) (|e1| |Env|)))
  ()
  (block-return |C5-pointer-=| (|PtrEQ| |P0-p| |P1-q|)))

(defprog
  ((|C6-pointer-<<| |Word|)
    ((|P0-w| |Word|) (|P1-p| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|) (t3 |Word|))
  (setq t3 (|formatSInt| (|PtrToSInt| |P1-p|)))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-w|))
  (|CCall| t1 t3 (the |SInt| 1) (the |SInt| 0))
  (block-return |C6-pointer-<<| |P0-w|))

(defprog
  ((|C7-pointer-coerce| |Word|) ((|P0-p| |Ptr|) (|e1| |Env|)))
  ()
  (block-return |C7-pointer-coerce| |P0-p|))

(defprog
  ((|C8-pointer-coerce| |Ptr|) ((|P0-p| |Word|) (|e1| |Env|)))
  ()
  (block-return |C8-pointer-coerce| |P0-p|))

(defprog
  ((|C9-pointer-test| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ()
  (block-return |C9-pointer-test| (|BoolNot| (|PtrIsNil| |P0-p|))))

(defprog
  ((|C10-pointer-~=| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ()
  (block-return |C10-pointer-~=| (|BoolNot| (|PtrEQ| |P0-x| |P1-y|))))

(defprog
  ((|C11-pointer-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-pointer-6| |Struct-pointer-6|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-pointer-6-x-0| 0 |l0| |P0-x|)
  (block-return |C11-pointer-<<| (|Clos| |e0| |C12-pointer-<<|)))

(defprog
  ((|C12-pointer-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Word|)
    (t4 |Word|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t4 (|Lex| |Struct-pointer-6-x-0| 0 |l1|))
  (setq t3 (|formatSInt| (|PtrToSInt| t4)))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-p|))
  (|CCall| t1 t3 (the |SInt| 1) (the |SInt| 0))
  (block-return |C12-pointer-<<| |P0-p|))

(defprog
  ((|C13-pointer-hash| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ()
  (block-return |C13-pointer-hash| (the |SInt| 0)))

(defprog
  ((|C14-pointer-case| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ()
  (block-return |C14-pointer-case| (|PtrEQ| |P0-x| |P1-y|)))

(defprog
  ((|C15-pointer-extend0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Arr|) (t1 |Record|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t0 (|ANew| |Word| (the |SInt| 2)))
  (|SetAElt|
    t0
    (the |SInt| 1)
    (|Lex| |Struct-pointer-9-Pointer-0| 0 |l1|))
  (|SetAElt| t0 (the |SInt| 0) |G-pointer_Pointer_931707449|)
  (setq t1 (|RNew| |Struct-pointer-5|))
  (|SetRElt| |Struct-pointer-5| |size| 0 t1 (the |SInt| 2))
  (|SetRElt| |Struct-pointer-5| |nsize| 1 t1 (the |SInt| 2))
  (|SetRElt| |Struct-pointer-5| |values| 2 t1 t0)
  (|CCall| |G-extendFill!| |P0-domain| t1)
  (block-return |C15-pointer-extend0| nil))

(defprog
  ((|C16-pointer-basic-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-pointer-9--2| 2 |l1|) (go |Lab0|))
    (|SetLex| |Struct-pointer-9--2| 2 |l1| (the |Bool| t))
    (|CCall| |G-basic|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 4)) (go |Lab1|))
    (block-return |C16-pointer-basic-init| |G-basic_Pointer_091505407|)
    |Lab1|
    (when (|SIntNE| |P0-idx| (the |SInt| 3)) (go |Lab2|))
    (block-return
      |C16-pointer-basic-init|
      |G-basic_MachineInteger_885893404|)
    |Lab2|
    (when (|SIntNE| |P0-idx| (the |SInt| 2)) (go |Lab3|))
    (block-return |C16-pointer-basic-init| |G-basic_String_641272169|)
    |Lab3|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab4|))
    (block-return |C16-pointer-basic-init| |G-basic_TextWriter_360221334|)
    |Lab4|
    (block-return |C16-pointer-basic-init| |G-basic_Boolean_727749971|)))

(defprog
  ((|C17-pointer-foamcat-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-pointer-9--3| 3 |l1|) (go |Lab0|))
    (|SetLex| |Struct-pointer-9--3| 3 |l1| (the |Bool| t))
    (|CCall| |G-foamcat|)
    |Lab0|
    (block-return
      |C17-pointer-foamcat-init|
      |G-foamcat_Conditional_436267619|)))

(setq |G-pointer| (|Clos| nil |C0-pointer-pointer|))

(setq |G-pointer_Pointer_931707449| nil)

(setq |G-pointer_Pointer_476980157| nil)

(setq |C18-pointer-sample| nil)

(file-imports
  '((|G-foamcat| "foamcat" |initializer| "")
      (|G-basic| "basic" |initializer| "")
      (|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-extendMake| "extendMake" 0 "")
      (|G-extendFill!| "extendFill!" 0 "")
      (|G-basic_Pointer_091505407| "Pointer" 91505407 "basic")
      (|G-domainMake| "domainMake" 0 "")
      (|G-basic_MachineInteger_885893404|
        "MachineInteger"
        885893404
        "basic")
      (|G-basic_String_641272169| "String" 641272169 "basic")
      (|G-basic_TextWriter_360221334| "TextWriter" 360221334 "basic")
      (|G-basic_Boolean_727749971| "Boolean" 727749971 "basic")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-domainAddDefaults!| "domainAddDefaults!" 0 "")
      (|G-rtLazyCatFrInit| "rtLazyCatFrInit" 0 "")
      (|G-foamcat_Conditional_436267619| "Conditional" 436267619 "foamcat")
      (|G-domainMakeDispatch| "domainMakeDispatch" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-pointer_Pointer_476980157| "Pointer" 476980157 "pointer")
      (|G-pointer_Pointer_931707449| "Pointer" 931707449 "pointer")
      (|G-pointer| "pointer" |initializer| "")))
