;;;
;;; Lisp code generated by Aldor from file "sinteger.ao".
;;;

(in-package "FOAM-USER")

(declare-prog (|C0-sinteger-sinteger|) ((|e1| |Env|)))

(declare-prog
  (|C1-sinteger-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-sinteger-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-sinteger-sinteger|)
  ((|P0-self| |Word|) (|P1-dom| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-sinteger-toJava| |SInt|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-sinteger-fromJava| |Word|)
  ((|P0-i| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C6-sinteger-integer| |Word|)
  ((|P0-l| |Word|) (|e1| |Env|)))

(declare-prog
  (|C7-sinteger-zero?| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C8-sinteger-negative?| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-sinteger-positive?| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-sinteger-even?| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C11-sinteger-odd?| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C12-sinteger-single?| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C13-sinteger-=| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C14-sinteger-~=| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C15-sinteger-<| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C16-sinteger->| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C17-sinteger-<=| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C18-sinteger->=| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C19-sinteger-prev| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C20-sinteger-next| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C21-sinteger-+| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C22-sinteger--| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C23-sinteger-+| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C24-sinteger--| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C25-sinteger-*| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C26-sinteger-coerce| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C27-sinteger-retract| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C28-sinteger-^| |Word|)
  ((|P0-x| |Word|) (|P1-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C29-sinteger-coerce| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C30-sinteger-coerce| |Word|)
  ((|P0-i| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C31-sinteger-quo| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C32-sinteger-rem| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C33-sinteger-gcd| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C34-sinteger-length| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C35-sinteger-shift| |Word|)
  ((|P0-i| |Word|) (|P1-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C36-sinteger-bit| |Word|)
  ((|P0-i| |Word|) (|P1-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C37-sinteger-~| |Word|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C38-sinteger-/\\| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C39-sinteger-\\/| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C40-sinteger-xor| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C41-sinteger-mod| |Word|)
  ((|P0-i| |Word|) (|P1-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C42-sinteger-mod+| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C43-sinteger-mod-| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C44-sinteger-mod*| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C45-sinteger-mod/| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C46-sinteger-mod^| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C47-sinteger-divide| |Word| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C48-sinteger-^| |Word|)
  ((|P0-x| |Word|) (|P1-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C49-sinteger-stepsBetween| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|P2-step| |Word|) (|e1| |Env|)))

(declare-prog
  (|C50-sinteger-<<| |Word|)
  ((|P0-w| |Word|) (|P1-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C51-sinteger-max| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C52-sinteger-min| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C53-sinteger-hash| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C54-sinteger-coerce| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C55-sinteger-<<| |Clos|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C56-sinteger-<<| |Word|)
  ((|P0-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C57-sinteger-case| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C58-sinteger-abs| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C59-sinteger-sign| |Word|)
  ((|P0-x| |Word|) (|e1| |Env|)))

(declare-prog
  (|C60-sinteger-stepsBetween| |Word|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))

(declare-prog
  (|C61-sinteger-extend0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C62-sinteger-machine-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C63-sinteger-basic-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C64-sinteger-segment-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C65-sinteger-foamcat-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-sinteger| |Clos|)

(declare-type |G-sinteger_MachineInteger_695469395| |Word|)

(declare-type |G-sinteger_MachineInteger_009988596| |Word|)

(defspecials
  |G-sinteger_MachineInteger_009988596|
  |G-sinteger_MachineInteger_695469395|)

(|DDecl|
  |Struct-sinteger-5|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl| |Struct-sinteger-7| (\-0 |Word|) (\-1 |Word|))

(|DDecl| |Struct-sinteger-10| (|x-0| |Word|))

(|DDecl|
  |Struct-sinteger-11|
  (|sign-0| |Clos|)
  (|abs-1| |Clos|)
  (|case-2| |Clos|)
  (|hash-3| |Clos|)
  (<<-4 |Clos|)
  (<<-5 |Clos|)
  (|stepsBetween-6| |Clos|)
  (|stepsBetween-7| |Clos|)
  (|divide-8| |Clos|)
  (|mod^-9| |Clos|)
  (|mod/-10| |Clos|)
  (|mod*-11| |Clos|)
  (|mod--12| |Clos|)
  (|mod+-13| |Clos|)
  (|mod-14| |Clos|)
  (|xor-15| |Clos|)
  (|\\/-16| |Clos|)
  (|/\\-17| |Clos|)
  (~-18 |Clos|)
  (|bit-19| |Clos|)
  (|shift-20| |Clos|)
  (|length-21| |Clos|)
  (|gcd-22| |Clos|)
  (|rem-23| |Clos|)
  (|quo-24| |Clos|)
  (\^-25 |Clos|)
  (\^-26 |Clos|)
  (|retract-27| |Clos|)
  (|coerce-28| |Clos|)
  (|coerce-29| |Clos|)
  (|coerce-30| |Clos|)
  (|coerce-31| |Clos|)
  (*-32 |Clos|)
  (|next-33| |Clos|)
  (|prev-34| |Clos|)
  (>=-35 |Clos|)
  (<=-36 |Clos|)
  (>-37 |Clos|)
  (<-38 |Clos|)
  (~=-39 |Clos|)
  (=-40 |Clos|)
  (|single?-41| |Clos|)
  (|odd?-42| |Clos|)
  (|even?-43| |Clos|)
  (|positive?-44| |Clos|)
  (|negative?-45| |Clos|)
  (|zero?-46| |Clos|)
  (|integer-47| |Clos|)
  (|fromJava-48| |Clos|)
  (|toJava-49| |Clos|)
  (\--50 |Clos|)
  (\--51 |Clos|)
  (\+-52 |Clos|)
  (\+-53 |Clos|)
  (|#-54| |Word|)
  (|max-55| |Word|)
  (|max-56| |Clos|)
  (|min-57| |Word|)
  (|min-58| |Clos|)
  (|Rep-59| |Word|)
  (\-60 |SInt|))

(|DDecl|
  |Struct-sinteger-13|
  (|MachineInteger-0| |Word|)
  (|Machine-1| |Word|)
  (|IntegerNumberSystem-2| |Word|)
  (|OrderedFinite-3| |Word|)
  (|Logic-4| |Word|)
  (|Steppable-5| |Word|)
  (|SInt-6| |Word|)
  (|max-7| |Word|)
  (|min-8| |Word|)
  (|dom-9| |Word|)
  (\-10 |Bool|)
  (\-11 |Bool|)
  (\-12 |Bool|)
  (\-13 |Bool|))

(|DDecl| |Struct-sinteger-14| (\-0 |Word|) (\-1 |Word|))

(|DDecl| |Struct-sinteger-15| (\-0 |Word|) (\-1 |Word|) (\-2 |Word|))

(|DDecl| |Struct-sinteger-16| (\-0 |SInt|) (\-1 |SInt|))

(|DDecl| |Struct-sinteger-17| (\-0 |Clos|) (\-1 |Clos|) (\-2 |Clos|))

(defprog
  ((|C0-sinteger-sinteger|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Arr|)
    (t5 |Arr|)
    (t6 |Record|)
    (t7 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-sinteger-13| |Struct-sinteger-13|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-sinteger| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C65-sinteger-foamcat-init|))
  (setq t1 (|Clos| |e0| |C64-sinteger-segment-init|))
  (setq t2 (|Clos| |e0| |C62-sinteger-machine-init|))
  (setq t3 (|Clos| |e0| |C63-sinteger-basic-init|))
  (setq
    |G-sinteger_MachineInteger_695469395|
    (|CCall| |G-domainMake| (|Clos| |e0| |C1-sinteger-addLevel0|)))
  (setq
    |G-sinteger_MachineInteger_009988596|
    (|CCall| |G-extendMake| (|Clos| |e0| |C61-sinteger-extend0|)))
  (|SetLex| |Struct-sinteger-13--10| 10 |l0| (the |Bool| nil))
  (|SetLex| |Struct-sinteger-13--11| 11 |l0| (the |Bool| nil))
  (|SetLex| |Struct-sinteger-13--12| 12 |l0| (the |Bool| nil))
  (|SetLex| |Struct-sinteger-13--13| 13 |l0| (the |Bool| nil))
  (setq t4 (|ANew| |Word| (the |SInt| 53)))
  (setq t5 (|ANew| |Word| (the |SInt| 53)))
  (|SetAElt| t4 (the |SInt| 0) (the |SInt| 61935445))
  (|SetAElt| t5 (the |SInt| 0) (|MakeLit| "sign"))
  (|SetAElt| t4 (the |SInt| 1) (the |SInt| 315051633))
  (|SetAElt| t5 (the |SInt| 1) (|MakeLit| "abs"))
  (|SetAElt| t4 (the |SInt| 2) (the |SInt| 200135))
  (|SetAElt| t5 (the |SInt| 2) (|MakeLit| "^"))
  (|SetAElt| t4 (the |SInt| 3) (the |SInt| 699481107))
  (|SetAElt| t5 (the |SInt| 3) (|MakeLit| "mod/"))
  (|SetAElt| t4 (the |SInt| 4) (the |SInt| 200083))
  (|SetAElt| t5 (the |SInt| 4) (|MakeLit| "*"))
  (|SetAElt| t4 (the |SInt| 5) (the |SInt| 255806968))
  (|SetAElt| t5 (the |SInt| 5) (|MakeLit| "sample"))
  (|SetAElt| t4 (the |SInt| 6) (the |SInt| 484454270))
  (|SetAElt| t5 (the |SInt| 6) (|MakeLit| "fromJava"))
  (|SetAElt| t4 (the |SInt| 7) (the |SInt| 782953315))
  (|SetAElt| t5 (the |SInt| 7) (|MakeLit| "next"))
  (|SetAElt| t4 (the |SInt| 8) (the |SInt| 375083307))
  (|SetAElt| t5 (the |SInt| 8) (|MakeLit| "shift"))
  (|SetAElt| t4 (the |SInt| 9) (the |SInt| 200084))
  (|SetAElt| t5 (the |SInt| 9) (|MakeLit| "+"))
  (|SetAElt| t4 (the |SInt| 10) (the |SInt| 386811348))
  (|SetAElt| t5 (the |SInt| 10) (|MakeLit| "retract"))
  (|SetAElt| t4 (the |SInt| 11) (the |SInt| 362464416))
  (|SetAElt| t5 (the |SInt| 11) (|MakeLit| "single?"))
  (|SetAElt| t4 (the |SInt| 12) (the |SInt| 315119482))
  (|SetAElt| t5 (the |SInt| 12) (|MakeLit| "bit"))
  (|SetAElt| t4 (the |SInt| 13) (the |SInt| 51487581))
  (|SetAElt| t5 (the |SInt| 13) (|MakeLit| "/\\"))
  (|SetAElt| t4 (the |SInt| 14) (the |SInt| 200086))
  (|SetAElt| t5 (the |SInt| 14) (|MakeLit| "-"))
  (|SetAElt| t4 (the |SInt| 15) (the |SInt| 498514682))
  (|SetAElt| t5 (the |SInt| 15) (|MakeLit| "even?"))
  (|SetAElt| t4 (the |SInt| 16) (the |SInt| 424301635))
  (|SetAElt| t5 (the |SInt| 16) (|MakeLit| "negative?"))
  (|SetAElt| t4 (the |SInt| 17) (the |SInt| 770345191))
  (|SetAElt| t5 (the |SInt| 17) (|MakeLit| "coerce"))
  (|SetAElt| t4 (the |SInt| 18) (the |SInt| 200101))
  (|SetAElt| t5 (the |SInt| 18) (|MakeLit| "<"))
  (|SetAElt| t4 (the |SInt| 19) (the |SInt| 318266239))
  (|SetAElt| t5 (the |SInt| 19) (|MakeLit| "rem"))
  (|SetAElt| t4 (the |SInt| 20) (the |SInt| 200076))
  (|SetAElt| t5 (the |SInt| 20) (|MakeLit| "#"))
  (|SetAElt| t4 (the |SInt| 21) (the |SInt| 318461825))
  (|SetAElt| t5 (the |SInt| 21) (|MakeLit| "max"))
  (|SetAElt| t4 (the |SInt| 22) (the |SInt| 200089))
  (|SetAElt| t5 (the |SInt| 22) (|MakeLit| "0"))
  (|SetAElt| t4 (the |SInt| 23) (the |SInt| 51500637))
  (|SetAElt| t5 (the |SInt| 23) (|MakeLit| "\\/"))
  (|SetAElt| t4 (the |SInt| 24) (the |SInt| 51492941))
  (|SetAElt| t5 (the |SInt| 24) (|MakeLit| ">="))
  (|SetAElt| t4 (the |SInt| 25) (the |SInt| 200167))
  (|SetAElt| t5 (the |SInt| 25) (|MakeLit| "~"))
  (|SetAElt| t4 (the |SInt| 26) (the |SInt| 200102))
  (|SetAElt| t5 (the |SInt| 26) (|MakeLit| "="))
  (|SetAElt| t4 (the |SInt| 27) (the |SInt| 200090))
  (|SetAElt| t5 (the |SInt| 27) (|MakeLit| "1"))
  (|SetAElt| t4 (the |SInt| 28) (the |SInt| 318204816))
  (|SetAElt| t5 (the |SInt| 28) (|MakeLit| "quo"))
  (|SetAElt| t4 (the |SInt| 29) (the |SInt| 200103))
  (|SetAElt| t5 (the |SInt| 29) (|MakeLit| ">"))
  (|SetAElt| t4 (the |SInt| 30) (the |SInt| 613807201))
  (|SetAElt| t5 (the |SInt| 30) (|MakeLit| "prev"))
  (|SetAElt| t4 (the |SInt| 31) (the |SInt| 417900517))
  (|SetAElt| t5 (the |SInt| 31) (|MakeLit| "stepsBetween"))
  (|SetAElt| t4 (the |SInt| 32) (the |SInt| 746853960))
  (|SetAElt| t5 (the |SInt| 32) (|MakeLit| "hash"))
  (|SetAElt| t4 (the |SInt| 33) (the |SInt| 699481154))
  (|SetAElt| t5 (the |SInt| 33) (|MakeLit| "mod^"))
  (|SetAElt| t4 (the |SInt| 34) (the |SInt| 699481102))
  (|SetAElt| t5 (the |SInt| 34) (|MakeLit| "mod*"))
  (|SetAElt| t4 (the |SInt| 35) (the |SInt| 318461307))
  (|SetAElt| t5 (the |SInt| 35) (|MakeLit| "mod"))
  (|SetAElt| t4 (the |SInt| 36) (the |SInt| 445790171))
  (|SetAElt| t5 (the |SInt| 36) (|MakeLit| "toJava"))
  (|SetAElt| t4 (the |SInt| 37) (the |SInt| 864625472))
  (|SetAElt| t5 (the |SInt| 37) (|MakeLit| "case"))
  (|SetAElt| t4 (the |SInt| 38) (the |SInt| 699481103))
  (|SetAElt| t5 (the |SInt| 38) (|MakeLit| "mod+"))
  (|SetAElt| t4 (the |SInt| 39) (the |SInt| 437828088))
  (|SetAElt| t5 (the |SInt| 39) (|MakeLit| "length"))
  (|SetAElt| t4 (the |SInt| 40) (the |SInt| 477900237))
  (|SetAElt| t5 (the |SInt| 40) (|MakeLit| "integer"))
  (|SetAElt| t4 (the |SInt| 41) (the |SInt| 51509389))
  (|SetAElt| t5 (the |SInt| 41) (|MakeLit| "~="))
  (|SetAElt| t4 (the |SInt| 42) (the |SInt| 318459775))
  (|SetAElt| t5 (the |SInt| 42) (|MakeLit| "min"))
  (|SetAElt| t4 (the |SInt| 43) (the |SInt| 316169058))
  (|SetAElt| t5 (the |SInt| 43) (|MakeLit| "Rep"))
  (|SetAElt| t4 (the |SInt| 44) (the |SInt| 733146723))
  (|SetAElt| t5 (the |SInt| 44) (|MakeLit| "positive?"))
  (|SetAElt| t4 (the |SInt| 45) (the |SInt| 317608340))
  (|SetAElt| t5 (the |SInt| 45) (|MakeLit| "xor"))
  (|SetAElt| t4 (the |SInt| 46) (the |SInt| 51492426))
  (|SetAElt| t5 (the |SInt| 46) (|MakeLit| "<<"))
  (|SetAElt| t4 (the |SInt| 47) (the |SInt| 699481105))
  (|SetAElt| t5 (the |SInt| 47) (|MakeLit| "mod-"))
  (|SetAElt| t4 (the |SInt| 48) (the |SInt| 665072666))
  (|SetAElt| t5 (the |SInt| 48) (|MakeLit| "odd?"))
  (|SetAElt| t4 (the |SInt| 49) (the |SInt| 206475020))
  (|SetAElt| t5 (the |SInt| 49) (|MakeLit| "zero?"))
  (|SetAElt| t4 (the |SInt| 50) (the |SInt| 42114539))
  (|SetAElt| t5 (the |SInt| 50) (|MakeLit| "divide"))
  (|SetAElt| t4 (the |SInt| 51) (the |SInt| 318604649))
  (|SetAElt| t5 (the |SInt| 51) (|MakeLit| "gcd"))
  (|SetAElt| t4 (the |SInt| 52) (the |SInt| 51492427))
  (|SetAElt| t5 (the |SInt| 52) (|MakeLit| "<="))
  (setq t6 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t6 (the |SInt| 53))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t6 (the |SInt| 53))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t6 t4)
  (setq t7 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t7 (the |SInt| 53))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t7 (the |SInt| 53))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t7 t5)
  (|CCall| |G-rtAddStrings| t6 t7)
  (|SetLex|
    |Struct-sinteger-13-Logic-4|
    4
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-sinteger-13-OrderedFinite-3|
    3
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 1)))
  (|SetLex|
    |Struct-sinteger-13-IntegerNumberSystem-2|
    2
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t0 (the |SInt| 2)))
  (|SetLex|
    |Struct-sinteger-13-Steppable-5|
    5
    |l0|
    (|CCall| |G-rtLazyCatFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-sinteger-13-Machine-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 0)))
  (|SetLex|
    |Struct-sinteger-13-dom-9|
    9
    |l0|
    (|Lex| |Struct-sinteger-13-Machine-1| 1 |l0|))
  (|SetLex|
    |Struct-sinteger-13-SInt-6|
    6
    |l0|
    (|CCall|
      |G-domainGetExport!|
      (|Lex| |Struct-sinteger-13-dom-9| 9 |l0|)
      (the |SInt| 594651170)
      (the |SInt| 547382598)))
  (|SetLex|
    |Struct-sinteger-13-min-8|
    8
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-sinteger-13-dom-9| 9 |l0|)
      (the |SInt| 318459775)
      (the |SInt| 594651170)))
  (|SetLex|
    |Struct-sinteger-13-max-7|
    7
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-sinteger-13-dom-9| 9 |l0|)
      (the |SInt| 318461825)
      (the |SInt| 594651170)))
  (|SetLex|
    |Struct-sinteger-13-MachineInteger-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t3 (the |SInt| 4)))
  (block-return |C0-sinteger-sinteger| ()))

(defprog
  ((|C1-sinteger-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall| |G-rtConstNameFn| (|MakeLit| "MachineInteger")))
  (|CCall| |G-domainAddHash!| |P0-domain| (the |SInt| 33717313))
  (block-return
    |C1-sinteger-addLevel0|
    (|Clos| |e0| |C2-sinteger-addLevel1|)))

(defprog
  ((|C2-sinteger-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |SInt|)
    (t14 |SInt|)
    (t15 |SInt|)
    (t16 |SInt|)
    (t17 |SInt|)
    (t18 |SInt|)
    (t19 |SInt|)
    (t20 |SInt|)
    (t21 |SInt|)
    (t22 |SInt|)
    (t23 |SInt|)
    (t24 |SInt|)
    (t25 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-sinteger-11| |Struct-sinteger-11|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (setq t0 (|ANew| |Word| (the |SInt| 63)))
  (setq t1 (|ANew| |Word| (the |SInt| 63)))
  (setq t2 (|ANew| |Word| (the |SInt| 63)))
  (setq t6 (|CCall| |G-domainMakeDispatch| |P0-domain|))
  (|SetLex| |Struct-sinteger-11--60| 60 |l0| |P1-hashcode|)
  (|SetLex|
    |Struct-sinteger-11-toJava-49|
    49
    |l0|
    (|Clos| |e0| |C4-sinteger-toJava|))
  (|SetLex|
    |Struct-sinteger-11-fromJava-48|
    48
    |l0|
    (|Clos| |e0| |C5-sinteger-fromJava|))
  (|SetLex|
    |Struct-sinteger-11-integer-47|
    47
    |l0|
    (|Clos| |e0| |C6-sinteger-integer|))
  (|SetLex|
    |Struct-sinteger-11-zero?-46|
    46
    |l0|
    (|Clos| |e0| |C7-sinteger-zero?|))
  (|SetLex|
    |Struct-sinteger-11-negative?-45|
    45
    |l0|
    (|Clos| |e0| |C8-sinteger-negative?|))
  (|SetLex|
    |Struct-sinteger-11-positive?-44|
    44
    |l0|
    (|Clos| |e0| |C9-sinteger-positive?|))
  (|SetLex|
    |Struct-sinteger-11-even?-43|
    43
    |l0|
    (|Clos| |e0| |C10-sinteger-even?|))
  (|SetLex|
    |Struct-sinteger-11-odd?-42|
    42
    |l0|
    (|Clos| |e0| |C11-sinteger-odd?|))
  (|SetLex|
    |Struct-sinteger-11-single?-41|
    41
    |l0|
    (|Clos| |e0| |C12-sinteger-single?|))
  (|SetLex|
    |Struct-sinteger-11-=-40|
    40
    |l0|
    (|Clos| |e0| |C13-sinteger-=|))
  (|SetLex|
    |Struct-sinteger-11-~=-39|
    39
    |l0|
    (|Clos| |e0| |C14-sinteger-~=|))
  (|SetLex|
    |Struct-sinteger-11-<-38|
    38
    |l0|
    (|Clos| |e0| |C15-sinteger-<|))
  (|SetLex|
    |Struct-sinteger-11->-37|
    37
    |l0|
    (|Clos| |e0| |C16-sinteger->|))
  (|SetLex|
    |Struct-sinteger-11-<=-36|
    36
    |l0|
    (|Clos| |e0| |C17-sinteger-<=|))
  (|SetLex|
    |Struct-sinteger-11->=-35|
    35
    |l0|
    (|Clos| |e0| |C18-sinteger->=|))
  (|SetLex|
    |Struct-sinteger-11-prev-34|
    34
    |l0|
    (|Clos| |e0| |C19-sinteger-prev|))
  (|SetLex|
    |Struct-sinteger-11-next-33|
    33
    |l0|
    (|Clos| |e0| |C20-sinteger-next|))
  (|SetLex|
    |Struct-sinteger-11-+-52|
    52
    |l0|
    (|Clos| |e0| |C21-sinteger-+|))
  (|SetLex|
    |Struct-sinteger-11---50|
    50
    |l0|
    (|Clos| |e0| |C22-sinteger--|))
  (|SetLex|
    |Struct-sinteger-11-+-53|
    53
    |l0|
    (|Clos| |e0| |C23-sinteger-+|))
  (|SetLex|
    |Struct-sinteger-11---51|
    51
    |l0|
    (|Clos| |e0| |C24-sinteger--|))
  (|SetLex|
    |Struct-sinteger-11-*-32|
    32
    |l0|
    (|Clos| |e0| |C25-sinteger-*|))
  (|SetLex|
    |Struct-sinteger-11-coerce-28|
    28
    |l0|
    (|Clos| |e0| |C26-sinteger-coerce|))
  (|SetLex|
    |Struct-sinteger-11-retract-27|
    27
    |l0|
    (|Clos| |e0| |C27-sinteger-retract|))
  (|SetLex|
    |Struct-sinteger-11-^-25|
    25
    |l0|
    (|Clos| |e0| |C28-sinteger-^|))
  (|SetLex|
    |Struct-sinteger-11-coerce-29|
    29
    |l0|
    (|Clos| |e0| |C29-sinteger-coerce|))
  (|SetLex|
    |Struct-sinteger-11-coerce-30|
    30
    |l0|
    (|Clos| |e0| |C30-sinteger-coerce|))
  (|SetLex|
    |Struct-sinteger-11-quo-24|
    24
    |l0|
    (|Clos| |e0| |C31-sinteger-quo|))
  (|SetLex|
    |Struct-sinteger-11-rem-23|
    23
    |l0|
    (|Clos| |e0| |C32-sinteger-rem|))
  (|SetLex|
    |Struct-sinteger-11-gcd-22|
    22
    |l0|
    (|Clos| |e0| |C33-sinteger-gcd|))
  (|SetLex|
    |Struct-sinteger-11-length-21|
    21
    |l0|
    (|Clos| |e0| |C34-sinteger-length|))
  (|SetLex|
    |Struct-sinteger-11-shift-20|
    20
    |l0|
    (|Clos| |e0| |C35-sinteger-shift|))
  (|SetLex|
    |Struct-sinteger-11-bit-19|
    19
    |l0|
    (|Clos| |e0| |C36-sinteger-bit|))
  (|SetLex|
    |Struct-sinteger-11-~-18|
    18
    |l0|
    (|Clos| |e0| |C37-sinteger-~|))
  (|SetLex|
    |Struct-sinteger-11-/\\-17|
    17
    |l0|
    (|Clos| |e0| |C38-sinteger-/\\|))
  (|SetLex|
    |Struct-sinteger-11-\\/-16|
    16
    |l0|
    (|Clos| |e0| |C39-sinteger-\\/|))
  (|SetLex|
    |Struct-sinteger-11-xor-15|
    15
    |l0|
    (|Clos| |e0| |C40-sinteger-xor|))
  (|SetLex|
    |Struct-sinteger-11-mod-14|
    14
    |l0|
    (|Clos| |e0| |C41-sinteger-mod|))
  (|SetLex|
    |Struct-sinteger-11-mod+-13|
    13
    |l0|
    (|Clos| |e0| |C42-sinteger-mod+|))
  (|SetLex|
    |Struct-sinteger-11-mod--12|
    12
    |l0|
    (|Clos| |e0| |C43-sinteger-mod-|))
  (|SetLex|
    |Struct-sinteger-11-mod*-11|
    11
    |l0|
    (|Clos| |e0| |C44-sinteger-mod*|))
  (|SetLex|
    |Struct-sinteger-11-mod/-10|
    10
    |l0|
    (|Clos| |e0| |C45-sinteger-mod/|))
  (|SetLex|
    |Struct-sinteger-11-mod^-9|
    9
    |l0|
    (|Clos| |e0| |C46-sinteger-mod^|))
  (|SetLex|
    |Struct-sinteger-11-divide-8|
    8
    |l0|
    (|Clos| |e0| |C47-sinteger-divide|))
  (|SetLex|
    |Struct-sinteger-11-^-26|
    26
    |l0|
    (|Clos| |e0| |C48-sinteger-^|))
  (|SetLex|
    |Struct-sinteger-11-stepsBetween-6|
    6
    |l0|
    (|Clos| |e0| |C49-sinteger-stepsBetween|))
  (|SetLex|
    |Struct-sinteger-11-<<-4|
    4
    |l0|
    (|Clos| |e0| |C50-sinteger-<<|))
  (|SetLex|
    |Struct-sinteger-11-max-56|
    56
    |l0|
    (|Clos| |e0| |C51-sinteger-max|))
  (|SetLex|
    |Struct-sinteger-11-min-58|
    58
    |l0|
    (|Clos| |e0| |C52-sinteger-min|))
  (|SetLex|
    |Struct-sinteger-11-hash-3|
    3
    |l0|
    (|Clos| |e0| |C53-sinteger-hash|))
  (|SetLex|
    |Struct-sinteger-11-coerce-31|
    31
    |l0|
    (|Clos| |e0| |C54-sinteger-coerce|))
  (|SetLex|
    |Struct-sinteger-11-<<-5|
    5
    |l0|
    (|Clos| |e0| |C55-sinteger-<<|))
  (|SetLex|
    |Struct-sinteger-11-case-2|
    2
    |l0|
    (|Clos| |e0| |C57-sinteger-case|))
  (|SetLex|
    |Struct-sinteger-11-abs-1|
    1
    |l0|
    (|Clos| |e0| |C58-sinteger-abs|))
  (|SetLex|
    |Struct-sinteger-11-sign-0|
    0
    |l0|
    (|Clos| |e0| |C59-sinteger-sign|))
  (|SetLex|
    |Struct-sinteger-11-stepsBetween-7|
    7
    |l0|
    (|Clos| |e0| |C60-sinteger-stepsBetween|))
  (setq
    t8
    (|SIntHashCombine|
      (|Lex| |Struct-sinteger-11--60| 60 |l0|)
      (the |SInt| 711292475)))
  (setq
    t20
    (|SIntHashCombine|
      (|Lex| |Struct-sinteger-11--60| 60 |l0|)
      (the |SInt| 51489085)))
  (setq t21 (|SIntHashCombine| (the |SInt| 32236) t20))
  (setq t9 (|SIntHashCombine| (the |SInt| 740244383) t21))
  (setq
    t22
    (|SIntHashCombine| (|Lex| |Struct-sinteger-11--60| 60 |l0|) t20))
  (setq t23 (|SIntHashCombine| (the |SInt| 32236) t22))
  (setq t10 (|SIntHashCombine| (the |SInt| 740244383) t23))
  (setq
    t11
    (|SIntHashCombine| (|Lex| |Struct-sinteger-11--60| 60 |l0|) t21))
  (setq
    t24
    (|SIntHashCombine| (|Lex| |Struct-sinteger-11--60| 60 |l0|) t23))
  (setq
    t12
    (|SIntHashCombine|
      (|Lex| |Struct-sinteger-11--60| 60 |l0|)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine| (the |SInt| 484208045) t20))))
  (setq
    t13
    (|SIntHashCombine|
      (|Lex| |Struct-sinteger-11--60| 60 |l0|)
      (the |SInt| 366858836)))
  (setq
    t14
    (|SIntHashCombine|
      (|Lex| |Struct-sinteger-11--60| 60 |l0|)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine| (|Lex| |Struct-sinteger-11--60| 60 |l0|) t22))))
  (setq
    t15
    (|SIntHashCombine| (|Lex| |Struct-sinteger-11--60| 60 |l0|) t24))
  (setq
    t16
    (|SIntHashCombine|
      (the |SInt| 182752316)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-sinteger-11--60| 60 |l0|)
          (the |SInt| 102896482)))))
  (setq t17 (|SIntHashCombine| (the |SInt| 585242861) t21))
  (setq t18 (|SIntHashCombine| (the |SInt| 755420535) t21))
  (setq t19 (|Lex| |Struct-sinteger-11--60| 60 |l0|))
  (setq t3 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t3 (the |SInt| 63))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t3 (the |SInt| 63))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t4 (the |SInt| 63))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t4 (the |SInt| 63))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t5 (the |SInt| 63))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t5 (the |SInt| 63))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t5 t2)
  (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
  (|CCall|
    |G-domainAddDefaults!|
    |P0-domain|
    (|CCall|
      |G-categoryMake|
      (|Clos| |e0| |C3-sinteger-sinteger|)
      (|CCall| |G-rtConstSIntFn| (the |SInt| 33717313))
      (|CCall| |G-rtConstNameFn| (|MakeLit| "MachineInteger")))
    t6)
  (|SetLex|
    |Struct-sinteger-11-Rep-59|
    59
    |l0|
    (|CCall| |G-domainMakeDummy|))
  (setq t7 (|Lex| |Struct-sinteger-11-Rep-59| 59 |l0|))
  (|SetLex|
    |Struct-sinteger-11-Rep-59|
    59
    |l0|
    (|Lex| |Struct-sinteger-13-SInt-6| 6 |l2|))
  (|CCall|
    |G-domainFill!|
    t7
    (|Lex| |Struct-sinteger-11-Rep-59| 59 |l0|))
  (|SetLex| |Struct-sinteger-11-Rep-59| 59 |l0| t7)
  (|SetAElt| t0 (the |SInt| 0) (the |SInt| 316169058))
  (|SetAElt| t1 (the |SInt| 0) (the |SInt| 547382598))
  (|SetAElt|
    t2
    (the |SInt| 0)
    (|Lex| |Struct-sinteger-11-Rep-59| 59 |l0|))
  (|SetAElt| t0 (the |SInt| 1) (the |SInt| 445790171))
  (|SetAElt|
    t1
    (the |SInt| 1)
    (|SIntHashCombine|
      (the |SInt| 594651170)
      (|SIntHashCombine|
        (the |SInt| 32236)
        (|SIntHashCombine|
          (|Lex| |Struct-sinteger-11--60| 60 |l0|)
          (the |SInt| 51489085)))))
  (|SetAElt|
    t2
    (the |SInt| 1)
    (|Lex| |Struct-sinteger-11-toJava-49| 49 |l0|))
  (|SetAElt| t0 (the |SInt| 2) (the |SInt| 484454270))
  (setq
    t25
    (|SIntHashCombine|
      (|Lex| |Struct-sinteger-11--60| 60 |l0|)
      (the |SInt| 1005564120)))
  (|SetAElt| t1 (the |SInt| 2) t25)
  (|SetAElt|
    t2
    (the |SInt| 2)
    (|Lex| |Struct-sinteger-11-fromJava-48| 48 |l0|))
  (|SetAElt| t0 (the |SInt| 3) (the |SInt| 477900237))
  (|SetAElt| t1 (the |SInt| 3) t8)
  (|SetAElt|
    t2
    (the |SInt| 3)
    (|Lex| |Struct-sinteger-11-integer-47| 47 |l0|))
  (|SetAElt| t0 (the |SInt| 4) (the |SInt| 206475020))
  (|SetAElt| t1 (the |SInt| 4) t9)
  (|SetAElt|
    t2
    (the |SInt| 4)
    (|Lex| |Struct-sinteger-11-zero?-46| 46 |l0|))
  (|SetAElt| t0 (the |SInt| 5) (the |SInt| 424301635))
  (|SetAElt| t1 (the |SInt| 5) t9)
  (|SetAElt|
    t2
    (the |SInt| 5)
    (|Lex| |Struct-sinteger-11-negative?-45| 45 |l0|))
  (|SetAElt| t0 (the |SInt| 6) (the |SInt| 733146723))
  (|SetAElt| t1 (the |SInt| 6) t9)
  (|SetAElt|
    t2
    (the |SInt| 6)
    (|Lex| |Struct-sinteger-11-positive?-44| 44 |l0|))
  (|SetAElt| t0 (the |SInt| 7) (the |SInt| 498514682))
  (|SetAElt| t1 (the |SInt| 7) t9)
  (|SetAElt|
    t2
    (the |SInt| 7)
    (|Lex| |Struct-sinteger-11-even?-43| 43 |l0|))
  (|SetAElt| t0 (the |SInt| 8) (the |SInt| 665072666))
  (|SetAElt| t1 (the |SInt| 8) t9)
  (|SetAElt|
    t2
    (the |SInt| 8)
    (|Lex| |Struct-sinteger-11-odd?-42| 42 |l0|))
  (|SetAElt| t0 (the |SInt| 9) (the |SInt| 362464416))
  (|SetAElt| t1 (the |SInt| 9) t9)
  (|SetAElt|
    t2
    (the |SInt| 9)
    (|Lex| |Struct-sinteger-11-single?-41| 41 |l0|))
  (|SetAElt| t0 (the |SInt| 10) (the |SInt| 200102))
  (|SetAElt| t1 (the |SInt| 10) t10)
  (|SetAElt|
    t2
    (the |SInt| 10)
    (|Lex| |Struct-sinteger-11-=-40| 40 |l0|))
  (|SetAElt| t0 (the |SInt| 11) (the |SInt| 51509389))
  (|SetAElt| t1 (the |SInt| 11) t10)
  (|SetAElt|
    t2
    (the |SInt| 11)
    (|Lex| |Struct-sinteger-11-~=-39| 39 |l0|))
  (|SetAElt| t0 (the |SInt| 12) (the |SInt| 200101))
  (|SetAElt| t1 (the |SInt| 12) t10)
  (|SetAElt|
    t2
    (the |SInt| 12)
    (|Lex| |Struct-sinteger-11-<-38| 38 |l0|))
  (|SetAElt| t0 (the |SInt| 13) (the |SInt| 200103))
  (|SetAElt| t1 (the |SInt| 13) t10)
  (|SetAElt|
    t2
    (the |SInt| 13)
    (|Lex| |Struct-sinteger-11->-37| 37 |l0|))
  (|SetAElt| t0 (the |SInt| 14) (the |SInt| 51492427))
  (|SetAElt| t1 (the |SInt| 14) t10)
  (|SetAElt|
    t2
    (the |SInt| 14)
    (|Lex| |Struct-sinteger-11-<=-36| 36 |l0|))
  (|SetAElt| t0 (the |SInt| 15) (the |SInt| 51492941))
  (|SetAElt| t1 (the |SInt| 15) t10)
  (|SetAElt|
    t2
    (the |SInt| 15)
    (|Lex| |Struct-sinteger-11->=-35| 35 |l0|))
  (|SetAElt| t0 (the |SInt| 16) (the |SInt| 613807201))
  (|SetAElt| t1 (the |SInt| 16) t11)
  (|SetAElt|
    t2
    (the |SInt| 16)
    (|Lex| |Struct-sinteger-11-prev-34| 34 |l0|))
  (|SetAElt| t0 (the |SInt| 17) (the |SInt| 782953315))
  (|SetAElt| t1 (the |SInt| 17) t11)
  (|SetAElt|
    t2
    (the |SInt| 17)
    (|Lex| |Struct-sinteger-11-next-33| 33 |l0|))
  (|SetAElt| t0 (the |SInt| 18) (the |SInt| 200084))
  (|SetAElt| t1 (the |SInt| 18) t11)
  (|SetAElt|
    t2
    (the |SInt| 18)
    (|Lex| |Struct-sinteger-11-+-52| 52 |l0|))
  (|SetAElt| t0 (the |SInt| 19) (the |SInt| 200086))
  (|SetAElt| t1 (the |SInt| 19) t11)
  (|SetAElt|
    t2
    (the |SInt| 19)
    (|Lex| |Struct-sinteger-11---50| 50 |l0|))
  (|SetAElt| t0 (the |SInt| 20) (the |SInt| 200084))
  (|SetAElt| t1 (the |SInt| 20) t24)
  (|SetAElt|
    t2
    (the |SInt| 20)
    (|Lex| |Struct-sinteger-11-+-53| 53 |l0|))
  (|SetAElt| t0 (the |SInt| 21) (the |SInt| 200086))
  (|SetAElt| t1 (the |SInt| 21) t24)
  (|SetAElt|
    t2
    (the |SInt| 21)
    (|Lex| |Struct-sinteger-11---51| 51 |l0|))
  (|SetAElt| t0 (the |SInt| 22) (the |SInt| 200083))
  (|SetAElt| t1 (the |SInt| 22) t24)
  (|SetAElt|
    t2
    (the |SInt| 22)
    (|Lex| |Struct-sinteger-11-*-32| 32 |l0|))
  (|SetAElt| t0 (the |SInt| 23) (the |SInt| 770345191))
  (|SetAElt| t1 (the |SInt| 23) t11)
  (|SetAElt|
    t2
    (the |SInt| 23)
    (|Lex| |Struct-sinteger-11-coerce-28| 28 |l0|))
  (|SetAElt| t0 (the |SInt| 24) (the |SInt| 386811348))
  (|SetAElt| t1 (the |SInt| 24) t11)
  (|SetAElt|
    t2
    (the |SInt| 24)
    (|Lex| |Struct-sinteger-11-retract-27| 27 |l0|))
  (|SetAElt| t0 (the |SInt| 25) (the |SInt| 200135))
  (|SetAElt| t1 (the |SInt| 25) t12)
  (|SetAElt|
    t2
    (the |SInt| 25)
    (|Lex| |Struct-sinteger-11-^-25| 25 |l0|))
  (|SetAElt| t0 (the |SInt| 26) (the |SInt| 770345191))
  (|SetAElt| t1 (the |SInt| 26) t13)
  (|SetAElt|
    t2
    (the |SInt| 26)
    (|Lex| |Struct-sinteger-11-coerce-29| 29 |l0|))
  (|SetAElt| t0 (the |SInt| 27) (the |SInt| 770345191))
  (|SetAElt| t1 (the |SInt| 27) t25)
  (|SetAElt|
    t2
    (the |SInt| 27)
    (|Lex| |Struct-sinteger-11-coerce-30| 30 |l0|))
  (|SetAElt| t0 (the |SInt| 28) (the |SInt| 318204816))
  (|SetAElt| t1 (the |SInt| 28) t24)
  (|SetAElt|
    t2
    (the |SInt| 28)
    (|Lex| |Struct-sinteger-11-quo-24| 24 |l0|))
  (|SetAElt| t0 (the |SInt| 29) (the |SInt| 318266239))
  (|SetAElt| t1 (the |SInt| 29) t24)
  (|SetAElt|
    t2
    (the |SInt| 29)
    (|Lex| |Struct-sinteger-11-rem-23| 23 |l0|))
  (|SetAElt| t0 (the |SInt| 30) (the |SInt| 318604649))
  (|SetAElt| t1 (the |SInt| 30) t24)
  (|SetAElt|
    t2
    (the |SInt| 30)
    (|Lex| |Struct-sinteger-11-gcd-22| 22 |l0|))
  (|SetAElt| t0 (the |SInt| 31) (the |SInt| 437828088))
  (|SetAElt| t1 (the |SInt| 31) t11)
  (|SetAElt|
    t2
    (the |SInt| 31)
    (|Lex| |Struct-sinteger-11-length-21| 21 |l0|))
  (|SetAElt| t0 (the |SInt| 32) (the |SInt| 375083307))
  (|SetAElt| t1 (the |SInt| 32) t24)
  (|SetAElt|
    t2
    (the |SInt| 32)
    (|Lex| |Struct-sinteger-11-shift-20| 20 |l0|))
  (|SetAElt| t0 (the |SInt| 33) (the |SInt| 315119482))
  (|SetAElt| t1 (the |SInt| 33) t10)
  (|SetAElt|
    t2
    (the |SInt| 33)
    (|Lex| |Struct-sinteger-11-bit-19| 19 |l0|))
  (|SetAElt| t0 (the |SInt| 34) (the |SInt| 200167))
  (|SetAElt| t1 (the |SInt| 34) t11)
  (|SetAElt|
    t2
    (the |SInt| 34)
    (|Lex| |Struct-sinteger-11-~-18| 18 |l0|))
  (|SetAElt| t0 (the |SInt| 35) (the |SInt| 51487581))
  (|SetAElt| t1 (the |SInt| 35) t24)
  (|SetAElt|
    t2
    (the |SInt| 35)
    (|Lex| |Struct-sinteger-11-/\\-17| 17 |l0|))
  (|SetAElt| t0 (the |SInt| 36) (the |SInt| 51500637))
  (|SetAElt| t1 (the |SInt| 36) t24)
  (|SetAElt|
    t2
    (the |SInt| 36)
    (|Lex| |Struct-sinteger-11-\\/-16| 16 |l0|))
  (|SetAElt| t0 (the |SInt| 37) (the |SInt| 317608340))
  (|SetAElt| t1 (the |SInt| 37) t24)
  (|SetAElt|
    t2
    (the |SInt| 37)
    (|Lex| |Struct-sinteger-11-xor-15| 15 |l0|))
  (|SetAElt| t0 (the |SInt| 38) (the |SInt| 318461307))
  (|SetAElt| t1 (the |SInt| 38) t24)
  (|SetAElt|
    t2
    (the |SInt| 38)
    (|Lex| |Struct-sinteger-11-mod-14| 14 |l0|))
  (|SetAElt| t0 (the |SInt| 39) (the |SInt| 699481103))
  (|SetAElt| t1 (the |SInt| 39) t14)
  (|SetAElt|
    t2
    (the |SInt| 39)
    (|Lex| |Struct-sinteger-11-mod+-13| 13 |l0|))
  (|SetAElt| t0 (the |SInt| 40) (the |SInt| 699481105))
  (|SetAElt| t1 (the |SInt| 40) t14)
  (|SetAElt|
    t2
    (the |SInt| 40)
    (|Lex| |Struct-sinteger-11-mod--12| 12 |l0|))
  (|SetAElt| t0 (the |SInt| 41) (the |SInt| 699481102))
  (|SetAElt| t1 (the |SInt| 41) t14)
  (|SetAElt|
    t2
    (the |SInt| 41)
    (|Lex| |Struct-sinteger-11-mod*-11| 11 |l0|))
  (|SetAElt| t0 (the |SInt| 42) (the |SInt| 699481107))
  (|SetAElt| t1 (the |SInt| 42) t14)
  (|SetAElt|
    t2
    (the |SInt| 42)
    (|Lex| |Struct-sinteger-11-mod/-10| 10 |l0|))
  (|SetAElt| t0 (the |SInt| 43) (the |SInt| 699481154))
  (|SetAElt| t1 (the |SInt| 43) t14)
  (|SetAElt|
    t2
    (the |SInt| 43)
    (|Lex| |Struct-sinteger-11-mod^-9| 9 |l0|))
  (|SetAElt| t0 (the |SInt| 44) (the |SInt| 42114539))
  (|SetAElt| t1 (the |SInt| 44) t15)
  (|SetAElt|
    t2
    (the |SInt| 44)
    (|Lex| |Struct-sinteger-11-divide-8| 8 |l0|))
  (|SetAElt| t0 (the |SInt| 45) (the |SInt| 200135))
  (|SetAElt| t1 (the |SInt| 45) t24)
  (|SetAElt|
    t2
    (the |SInt| 45)
    (|Lex| |Struct-sinteger-11-^-26| 26 |l0|))
  (|SetAElt| t0 (the |SInt| 46) (the |SInt| 417900517))
  (|SetAElt| t1 (the |SInt| 46) t14)
  (|SetAElt|
    t2
    (the |SInt| 46)
    (|Lex| |Struct-sinteger-11-stepsBetween-6| 6 |l0|))
  (|SetAElt| t0 (the |SInt| 47) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 47) t16)
  (|SetAElt|
    t2
    (the |SInt| 47)
    (|Lex| |Struct-sinteger-11-<<-4| 4 |l0|))
  (|SetAElt| t0 (the |SInt| 48) (the |SInt| 318461825))
  (|SetAElt| t1 (the |SInt| 48) t24)
  (|SetAElt|
    t2
    (the |SInt| 48)
    (|Lex| |Struct-sinteger-11-max-56| 56 |l0|))
  (|SetAElt| t0 (the |SInt| 49) (the |SInt| 318459775))
  (|SetAElt| t1 (the |SInt| 49) t24)
  (|SetAElt|
    t2
    (the |SInt| 49)
    (|Lex| |Struct-sinteger-11-min-58| 58 |l0|))
  (|SetAElt| t0 (the |SInt| 50) (the |SInt| 746853960))
  (|SetAElt| t1 (the |SInt| 50) t11)
  (|SetAElt|
    t2
    (the |SInt| 50)
    (|Lex| |Struct-sinteger-11-hash-3| 3 |l0|))
  (|SetAElt| t0 (the |SInt| 51) (the |SInt| 770345191))
  (|SetAElt| t1 (the |SInt| 51) t17)
  (|SetAElt|
    t2
    (the |SInt| 51)
    (|Lex| |Struct-sinteger-11-coerce-31| 31 |l0|))
  (|SetAElt| t0 (the |SInt| 52) (the |SInt| 51492426))
  (|SetAElt| t1 (the |SInt| 52) t18)
  (|SetAElt|
    t2
    (the |SInt| 52)
    (|Lex| |Struct-sinteger-11-<<-5| 5 |l0|))
  (|SetAElt| t0 (the |SInt| 53) (the |SInt| 864625472))
  (|SetAElt| t1 (the |SInt| 53) t10)
  (|SetAElt|
    t2
    (the |SInt| 53)
    (|Lex| |Struct-sinteger-11-case-2| 2 |l0|))
  (|SetAElt| t0 (the |SInt| 54) (the |SInt| 315051633))
  (|SetAElt| t1 (the |SInt| 54) t11)
  (|SetAElt|
    t2
    (the |SInt| 54)
    (|Lex| |Struct-sinteger-11-abs-1| 1 |l0|))
  (|SetAElt| t0 (the |SInt| 55) (the |SInt| 61935445))
  (|SetAElt| t1 (the |SInt| 55) t11)
  (|SetAElt|
    t2
    (the |SInt| 55)
    (|Lex| |Struct-sinteger-11-sign-0| 0 |l0|))
  (|SetAElt| t0 (the |SInt| 56) (the |SInt| 417900517))
  (|SetAElt| t1 (the |SInt| 56) t24)
  (|SetAElt|
    t2
    (the |SInt| 56)
    (|Lex| |Struct-sinteger-11-stepsBetween-7| 7 |l0|))
  (|SetAElt| t0 (the |SInt| 57) (the |SInt| 200089))
  (|SetAElt| t1 (the |SInt| 57) t19)
  (|SetAElt| t2 (the |SInt| 57) (the |SInt| 0))
  (|SetAElt| t0 (the |SInt| 58) (the |SInt| 200090))
  (|SetAElt| t1 (the |SInt| 58) t19)
  (|SetAElt| t2 (the |SInt| 58) (the |SInt| 1))
  (|SetLex|
    |Struct-sinteger-11-min-57|
    57
    |l0|
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-sinteger-13-min-8| 8 |l2|)))
  (|SetAElt| t0 (the |SInt| 59) (the |SInt| 318459775))
  (|SetAElt| t1 (the |SInt| 59) t19)
  (|SetAElt|
    t2
    (the |SInt| 59)
    (|Lex| |Struct-sinteger-11-min-57| 57 |l0|))
  (|SetLex|
    |Struct-sinteger-11-max-55|
    55
    |l0|
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-sinteger-13-max-7| 7 |l2|)))
  (|SetAElt| t0 (the |SInt| 60) (the |SInt| 318461825))
  (|SetAElt| t1 (the |SInt| 60) t19)
  (|SetAElt|
    t2
    (the |SInt| 60)
    (|Lex| |Struct-sinteger-11-max-55| 55 |l0|))
  (|SetLex|
    |Struct-sinteger-11-#-54|
    54
    |l0|
    (|BIntNext|
      (|BIntMinus|
        (|SIntToBInt| (|Lex| |Struct-sinteger-11-max-55| 55 |l0|))
        (|SIntToBInt| (|Lex| |Struct-sinteger-11-min-57| 57 |l0|)))))
  (|SetAElt| t0 (the |SInt| 61) (the |SInt| 200076))
  (|SetAElt| t1 (the |SInt| 61) (the |SInt| 484208045))
  (|SetAElt|
    t2
    (the |SInt| 61)
    (|Lex| |Struct-sinteger-11-#-54| 54 |l0|))
  (|SetAElt| t0 (the |SInt| 62) (the |SInt| 255806968))
  (|SetAElt| t1 (the |SInt| 62) t19)
  (|SetAElt| t2 (the |SInt| 62) (the |SInt| 0))
  (block-return |C2-sinteger-addLevel1| |P0-domain|))

(defprog
  ((|C3-sinteger-sinteger|)
    ((|P0-self| |Word|) (|P1-dom| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |Arr|)
    (t7 |Record|)
    (|e3| |Env|)
    (|l3| |Level|))
  (setq |e3| (|EnvNext| (|EnvNext| |e1|)))
  (setq |l3| (|EnvLevel| |e3|))
  (setq t0 (|ANew| |Word| (the |SInt| 0)))
  (setq t1 (|ANew| |Word| (the |SInt| 0)))
  (setq t2 (|ANew| |Word| (the |SInt| 0)))
  (setq t6 (|ANew| |Word| (the |SInt| 4)))
  (setq t3 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t3 (the |SInt| 0))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t3 (the |SInt| 0))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t3 t0)
  (setq t4 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t4 (the |SInt| 0))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t4 (the |SInt| 0))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t4 t1)
  (setq t5 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t5 (the |SInt| 0))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t5 (the |SInt| 0))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t5 t2)
  (|CCall| |G-categoryAddExports!| |P0-self| t3 t4 t5)
  (|SetAElt|
    t6
    (the |SInt| 0)
    (|Lex| |Struct-sinteger-13-Logic-4| 4 |l3|))
  (|SetAElt|
    t6
    (the |SInt| 1)
    (|Lex| |Struct-sinteger-13-OrderedFinite-3| 3 |l3|))
  (|SetAElt|
    t6
    (the |SInt| 2)
    (|Lex| |Struct-sinteger-13-IntegerNumberSystem-2| 2 |l3|))
  (|SetAElt|
    t6
    (the |SInt| 3)
    (|Lex| |Struct-sinteger-13-Steppable-5| 5 |l3|))
  (setq t7 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t7 (the |SInt| 4))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t7 (the |SInt| 4))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t7 t6)
  (|CCall| |G-categoryAddParents!| |P0-self| t7 |P1-dom|)
  (block-return |C3-sinteger-sinteger| ()))

(defprog
  ((|C4-sinteger-toJava| |SInt|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C4-sinteger-toJava| |P0-i|))

(defprog
  ((|C5-sinteger-fromJava| |Word|) ((|P0-i| |SInt|) (|e1| |Env|)))
  ()
  (block-return |C5-sinteger-fromJava| |P0-i|))

(defprog
  ((|C6-sinteger-integer| |Word|) ((|P0-l| |Word|) (|e1| |Env|)))
  ()
  (block-return |C6-sinteger-integer| (|ArrToSInt| |P0-l|)))

(defprog
  ((|C7-sinteger-zero?| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C7-sinteger-zero?| (|SIntIsZero| |P0-i|)))

(defprog
  ((|C8-sinteger-negative?| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C8-sinteger-negative?| (|SIntIsNeg| |P0-i|)))

(defprog
  ((|C9-sinteger-positive?| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C9-sinteger-positive?| (|SIntIsPos| |P0-i|)))

(defprog
  ((|C10-sinteger-even?| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C10-sinteger-even?| (|SIntIsEven| |P0-i|)))

(defprog
  ((|C11-sinteger-odd?| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C11-sinteger-odd?| (|SIntIsOdd| |P0-i|)))

(defprog
  ((|C12-sinteger-single?| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C12-sinteger-single?| (the |Bool| t)))

(defprog
  ((|C13-sinteger-=| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C13-sinteger-=| (|SIntEQ| |P0-i| |P1-j|)))

(defprog
  ((|C14-sinteger-~=| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C14-sinteger-~=| (|SIntNE| |P0-i| |P1-j|)))

(defprog
  ((|C15-sinteger-<| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C15-sinteger-<| (|SIntLT| |P0-i| |P1-j|)))

(defprog
  ((|C16-sinteger->| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C16-sinteger->| (|SIntLT| |P1-j| |P0-i|)))

(defprog
  ((|C17-sinteger-<=| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C17-sinteger-<=| (|SIntLE| |P0-i| |P1-j|)))

(defprog
  ((|C18-sinteger->=| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C18-sinteger->=| (|SIntLE| |P1-j| |P0-i|)))

(defprog
  ((|C19-sinteger-prev| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C19-sinteger-prev| (|SIntPrev| |P0-i|)))

(defprog
  ((|C20-sinteger-next| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C20-sinteger-next| (|SIntNext| |P0-i|)))

(defprog
  ((|C21-sinteger-+| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C21-sinteger-+| |P0-i|))

(defprog
  ((|C22-sinteger--| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C22-sinteger--| (|SIntNegate| |P0-i|)))

(defprog
  ((|C23-sinteger-+| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C23-sinteger-+| (|SIntPlus| |P0-i| |P1-j|)))

(defprog
  ((|C24-sinteger--| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C24-sinteger--| (|SIntMinus| |P0-i| |P1-j|)))

(defprog
  ((|C25-sinteger-*| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C25-sinteger-*| (|SIntTimes| |P0-i| |P1-j|)))

(defprog
  ((|C26-sinteger-coerce| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C26-sinteger-coerce| |P0-i|))

(defprog
  ((|C27-sinteger-retract| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C27-sinteger-retract| |P0-i|))

(defprog
  ((|C28-sinteger-^| |Word|)
    ((|P0-x| |Word|) (|P1-n| |Word|) (|e1| |Env|)))
  ((t0 |SInt|)
    (t1 |SInt|)
    (t2 |SInt|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|)
    (t6 |SInt|)
    (t7 |SInt|))
  (tagbody
    (setq t6 |P0-x|)
    (setq t7 (|BIntToSInt| |P1-n|))
    (when (|SIntIsZero| t7) (go |Lab0|))
    (when (|SIntEQ| t7 (the |SInt| 1)) (go |Lab2|))
    (when (|SIntEQ| t7 (the |SInt| 2)) (go |Lab4|))
    (setq t2 (the |SInt| 1))
    (setq t1 (the |SInt| 0))
    (setq t0 (|SIntLength| t7))
    |Lab6|
    (when (|SIntLT| t1 t0) (go |Lab14|))
    (setq t5 t2)
    |Lab5|
    (setq t4 t5)
    |Lab3|
    (setq t3 t4)
    |Lab1|
    (block-return |C28-sinteger-^| t3)
    |Lab14|
    (when (|SIntBit| t7 t1) (go |Lab8|))
    |Lab9|
    (setq t6 (|SIntTimes| t6 t6))
    (setq t1 (|SIntNext| t1))
    (go |Lab6|)
    |Lab8|
    (setq t2 (|SIntTimes| t2 t6))
    (go |Lab9|)
    |Lab4|
    (setq t5 (|SIntTimes| |P0-x| |P0-x|))
    (go |Lab5|)
    |Lab2|
    (setq t4 |P0-x|)
    (go |Lab3|)
    |Lab0|
    (setq t3 (the |SInt| 1))
    (go |Lab1|)))

(defprog
  ((|C29-sinteger-coerce| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C29-sinteger-coerce| (|BIntToSInt| |P0-i|)))

(defprog
  ((|C30-sinteger-coerce| |Word|) ((|P0-i| |SInt|) (|e1| |Env|)))
  ()
  (block-return |C30-sinteger-coerce| |P0-i|))

(defprog
  ((|C31-sinteger-quo| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C31-sinteger-quo| (|SIntQuo| |P0-i| |P1-j|)))

(defprog
  ((|C32-sinteger-rem| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C32-sinteger-rem| (|SIntRem| |P0-i| |P1-j|)))

(defprog
  ((|C33-sinteger-gcd| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C33-sinteger-gcd| (|SIntGcd| |P0-i| |P1-j|)))

(defprog
  ((|C34-sinteger-length| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C34-sinteger-length| (|SIntLength| |P0-i|)))

(defprog
  ((|C35-sinteger-shift| |Word|)
    ((|P0-i| |Word|) (|P1-n| |Word|) (|e1| |Env|)))
  ((t0 |Word|) (t1 |Word|))
  (tagbody
    (when (|SIntIsPos| |P1-n|) (go |Lab0|))
    (when (|SIntLT| |P1-n| (the |SInt| 0)) (go |Lab2|))
    (setq t1 |P0-i|)
    |Lab3|
    (setq t0 t1)
    |Lab1|
    (block-return |C35-sinteger-shift| t0)
    |Lab2|
    (setq t1 (|SIntShiftDn| |P0-i| (|SIntNegate| |P1-n|)))
    (go |Lab3|)
    |Lab0|
    (setq t0 (|SIntShiftUp| |P0-i| |P1-n|))
    (go |Lab1|)))

(defprog
  ((|C36-sinteger-bit| |Word|)
    ((|P0-i| |Word|) (|P1-n| |Word|) (|e1| |Env|)))
  ()
  (block-return |C36-sinteger-bit| (|SIntBit| |P0-i| |P1-n|)))

(defprog
  ((|C37-sinteger-~| |Word|) ((|P0-i| |Word|) (|e1| |Env|)))
  ()
  (block-return |C37-sinteger-~| (|SIntNot| |P0-i|)))

(defprog
  ((|C38-sinteger-/\\| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C38-sinteger-/\\| (|SIntAnd| |P0-i| |P1-j|)))

(defprog
  ((|C39-sinteger-\\/| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C39-sinteger-\\/| (|SIntOr| |P0-i| |P1-j|)))

(defprog
  ((|C40-sinteger-xor| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ()
  (block-return |C40-sinteger-xor| (|SIntXOr| |P0-i| |P1-j|)))

(defprog
  ((|C41-sinteger-mod| |Word|)
    ((|P0-i| |Word|) (|P1-n| |Word|) (|e1| |Env|)))
  ((|T0-k| |SInt|))
  (tagbody
    (setq |T0-k| (|SIntRem| |P0-i| |P1-n|))
    (when (|SIntLT| |T0-k| (the |SInt| 0)) (go |Lab0|))
    |Lab1|
    (block-return |C41-sinteger-mod| |T0-k|)
    |Lab0|
    (setq |T0-k| (|SIntPlus| |T0-k| |P1-n|))
    (go |Lab1|)))

(defprog
  ((|C42-sinteger-mod+| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))
  ((|T0-k| |SInt|))
  (tagbody
    (setq |P0-i| (|SIntMinus| |P0-i| |P2-n|))
    (setq |T0-k| (|SIntPlus| |P0-i| |P1-j|))
    (when (|SIntLT| |T0-k| (the |SInt| 0)) (go |Lab0|))
    |Lab1|
    (block-return |C42-sinteger-mod+| |T0-k|)
    |Lab0|
    (setq |T0-k| (|SIntPlus| |T0-k| |P2-n|))
    (go |Lab1|)))

(defprog
  ((|C43-sinteger-mod-| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))
  ((|T0-k| |SInt|))
  (tagbody
    (setq |T0-k| (|SIntMinus| |P0-i| |P1-j|))
    (when (|SIntLT| |T0-k| (the |SInt| 0)) (go |Lab0|))
    |Lab1|
    (block-return |C43-sinteger-mod-| |T0-k|)
    |Lab0|
    (setq |T0-k| (|SIntPlus| |T0-k| |P2-n|))
    (go |Lab1|)))

(defprog
  ((|C44-sinteger-mod*| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Word|)
    (t2 |Word|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |SInt|))
  (tagbody
    (when (|SIntEQ| |P0-i| (the |SInt| 1)) (go |Lab0|))
    (when (|SIntEQ| |P1-j| (the |SInt| 1)) (go |Lab2|))
    (when (|SIntLT| |P2-n| (the |SInt| 32767)) (go |Lab5|))
    (when (|SIntLT| |P0-i| (the |SInt| 32767)) (go |Lab8|))
    |Lab9|
    (multiple-value-setq (t3 t4) (|WordTimesDouble| |P0-i| |P1-j|))
    (multiple-value-setq (t5 t6 t7) (|WordDivideDouble| t3 t4 |P2-n|))
    (setq t2 t7)
    |Lab4|
    (setq t1 t2)
    |Lab3|
    (setq t0 t1)
    |Lab1|
    (block-return |C44-sinteger-mod*| t0)
    |Lab8|
    (when (|SIntLT| |P1-j| (the |SInt| 32767)) (go |Lab5|))
    (go |Lab9|)
    |Lab5|
    (setq t8 (|SIntRem| (|SIntTimes| |P0-i| |P1-j|) |P2-n|))
    (when (|SIntLT| t8 (the |SInt| 0)) (go |Lab6|))
    |Lab7|
    (setq t2 t8)
    (go |Lab4|)
    |Lab6|
    (setq t8 (|SIntPlus| t8 |P2-n|))
    (go |Lab7|)
    |Lab2|
    (setq t1 |P0-i|)
    (go |Lab3|)
    |Lab0|
    (setq t0 |P1-j|)
    (go |Lab1|)))

(defprog
  ((|C45-sinteger-mod/| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))
  ((|T0-q| |SInt|)
    (|T1-d1| |SInt|)
    (|T2-c1| |SInt|)
    (|T3-d0| |SInt|)
    (|T4-c0| |SInt|)
    (t5 |SInt|)
    (t6 |SInt|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |Word|)
    (t10 |Word|)
    (t11 |Word|)
    (t12 |Word|)
    (t13 |Word|)
    (t14 |Word|)
    (t15 |Word|)
    (t16 |Word|)
    (t17 |SInt|))
  (tagbody
    (setq |T4-c0| |P1-j|)
    (setq |T3-d0| |P2-n|)
    (setq |T2-c1| (the |SInt| 1))
    (setq |T1-d1| (the |SInt| 0))
    |Lab0|
    (when (|SIntIsZero| |T3-d0|) (go |Lab1|))
    (setq |T0-q| (|SIntQuo| |T4-c0| |T3-d0|))
    (setq t8 (|SIntTimes| |T0-q| |T3-d0|))
    (setq t5 (|SIntMinus| |T4-c0| t8))
    (setq |T4-c0| |T3-d0|)
    (setq |T3-d0| t5)
    (setq t7 (|SIntTimes| |T0-q| |T1-d1|))
    (setq t6 (|SIntMinus| |T2-c1| t7))
    (setq |T2-c1| |T1-d1|)
    (setq |T1-d1| t6)
    (go |Lab0|)
    |Lab1|
    (when (|SIntNE| |T4-c0| (the |SInt| 1)) (go |Lab2|))
    (when (|SIntLT| |T2-c1| (the |SInt| 0)) (go |Lab3|))
    |Lab4|
    (when (|SIntEQ| |P0-i| (the |SInt| 1)) (go |Lab5|))
    (when (|SIntEQ| |T2-c1| (the |SInt| 1)) (go |Lab7|))
    (when (|SIntLT| |P2-n| (the |SInt| 32767)) (go |Lab10|))
    (when (|SIntLT| |P0-i| (the |SInt| 32767)) (go |Lab13|))
    |Lab14|
    (multiple-value-setq (t12 t13) (|WordTimesDouble| |P0-i| |T2-c1|))
    (multiple-value-setq
      (t14 t15 t16)
      (|WordDivideDouble| t12 t13 |P2-n|))
    (setq t11 t16)
    |Lab9|
    (setq t10 t11)
    |Lab8|
    (setq t9 t10)
    |Lab6|
    (block-return |C45-sinteger-mod/| t9)
    |Lab13|
    (when (|SIntLT| |T2-c1| (the |SInt| 32767)) (go |Lab10|))
    (go |Lab14|)
    |Lab10|
    (setq t17 (|SIntRem| (|SIntTimes| |P0-i| |T2-c1|) |P2-n|))
    (when (|SIntLT| t17 (the |SInt| 0)) (go |Lab11|))
    |Lab12|
    (setq t11 t17)
    (go |Lab9|)
    |Lab11|
    (setq t17 (|SIntPlus| t17 |P2-n|))
    (go |Lab12|)
    |Lab7|
    (setq t10 |P0-i|)
    (go |Lab8|)
    |Lab5|
    (setq t9 |T2-c1|)
    (go |Lab6|)
    |Lab3|
    (setq |T2-c1| (|SIntPlus| |T2-c1| |P2-n|))
    (go |Lab4|)
    |Lab2|
    (|fputs| (|MakeLit| "inverse does not exist") (|stdoutFile|))
    (|fputc| (the |SInt| 10) (|stdoutFile|))
    (|Halt| (the |SInt| 0))))

(defprog
  ((|C46-sinteger-mod^| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-n| |Word|) (|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Word|)
    (t2 |Word|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |Word|)
    (t9 |Word|)
    (t10 |Word|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |Word|)
    (t14 |Word|)
    (t15 |Word|)
    (t16 |Word|)
    (t17 |Word|)
    (t18 |Word|)
    (t19 |Word|)
    (t20 |SInt|)
    (t21 |SInt|)
    (t22 |SInt|)
    (t23 |SInt|)
    (t24 |SInt|)
    (t25 |SInt|)
    (t26 |SInt|)
    (t27 |SInt|)
    (t28 |SInt|)
    (t29 |SInt|)
    (t30 |Bool|)
    (t31 |Bool|)
    (t32 |Bool|))
  (tagbody
    (when (|SIntLT| |P1-j| (the |SInt| 0)) (go |Lab0|))
    (when (|SIntIsZero| |P1-j|) (go |Lab2|))
    (when (|SIntIsOdd| |P1-j|) (go |Lab4|))
    (setq t30 (|SIntEQ| |P0-i| (the |SInt| 1)))
    (when t30 (go |Lab14|))
    (when (|SIntLT| |P2-n| (the |SInt| 32767)) (go |Lab17|))
    (setq t31 (|SIntLT| |P0-i| (the |SInt| 32767)))
    (setq t32 (|BoolNot| t31))
    (when t32 (go |Lab18|))
    |Lab17|
    (setq t20 (|SIntRem| (|SIntTimes| |P0-i| |P0-i|) |P2-n|))
    (when (|SIntLT| t20 (the |SInt| 0)) (go |Lab19|))
    |Lab20|
    (setq t14 t20)
    |Lab16|
    (setq t13 t14)
    |Lab15|
    (setq
      t2
      (|C46-sinteger-mod^|
        t13
        (|SIntQuo| |P1-j| (the |SInt| 2))
        |P2-n|
        |e1|))
    |Lab5|
    (setq t1 t2)
    |Lab3|
    (setq t0 t1)
    |Lab1|
    (block-return |C46-sinteger-mod^| t0)
    |Lab19|
    (setq t20 (|SIntPlus| t20 |P2-n|))
    (go |Lab20|)
    |Lab18|
    (multiple-value-setq (t15 t16) (|WordTimesDouble| |P0-i| |P0-i|))
    (multiple-value-setq
      (t17 t18 t19)
      (|WordDivideDouble| t15 t16 |P2-n|))
    (setq t14 t19)
    (go |Lab16|)
    |Lab14|
    (setq t13 |P0-i|)
    (go |Lab15|)
    |Lab4|
    (setq
      t12
      (|C46-sinteger-mod^| |P0-i| (|SIntPrev| |P1-j|) |P2-n| |e1|))
    (when (|SIntEQ| |P0-i| (the |SInt| 1)) (go |Lab6|))
    (when (|SIntEQ| t12 (the |SInt| 1)) (go |Lab8|))
    (when (|SIntLT| |P2-n| (the |SInt| 32767)) (go |Lab11|))
    (when (|SIntLT| |P0-i| (the |SInt| 32767)) (go |Lab26|))
    |Lab27|
    (multiple-value-setq (t6 t7) (|WordTimesDouble| |P0-i| t12))
    (multiple-value-setq (t8 t9 t10) (|WordDivideDouble| t6 t7 |P2-n|))
    (setq t5 t10)
    |Lab10|
    (setq t4 t5)
    |Lab9|
    (setq t3 t4)
    |Lab7|
    (setq t2 t3)
    (go |Lab5|)
    |Lab26|
    (when (|SIntLT| t12 (the |SInt| 32767)) (go |Lab11|))
    (go |Lab27|)
    |Lab11|
    (setq t11 (|SIntRem| (|SIntTimes| |P0-i| t12) |P2-n|))
    (when (|SIntLT| t11 (the |SInt| 0)) (go |Lab12|))
    |Lab13|
    (setq t5 t11)
    (go |Lab10|)
    |Lab12|
    (setq t11 (|SIntPlus| t11 |P2-n|))
    (go |Lab13|)
    |Lab8|
    (setq t4 |P0-i|)
    (go |Lab9|)
    |Lab6|
    (setq t3 t12)
    (go |Lab7|)
    |Lab2|
    (setq t1 (the |SInt| 1))
    (go |Lab3|)
    |Lab0|
    (setq t25 |P0-i|)
    (setq t24 |P2-n|)
    (setq t23 (the |SInt| 1))
    (setq t22 (the |SInt| 0))
    |Lab21|
    (when (|SIntIsZero| t24) (go |Lab22|))
    (setq t21 (|SIntQuo| t25 t24))
    (setq t29 (|SIntTimes| t21 t24))
    (setq t26 (|SIntMinus| t25 t29))
    (setq t25 t24)
    (setq t24 t26)
    (setq t28 (|SIntTimes| t21 t22))
    (setq t27 (|SIntMinus| t23 t28))
    (setq t23 t22)
    (setq t22 t27)
    (go |Lab21|)
    |Lab22|
    (when (|SIntNE| t25 (the |SInt| 1)) (go |Lab23|))
    (when (|SIntLT| t23 (the |SInt| 0)) (go |Lab24|))
    |Lab25|
    (setq t0 (|C46-sinteger-mod^| t23 (|SIntNegate| |P1-j|) |P2-n| |e1|))
    (go |Lab1|)
    |Lab24|
    (setq t23 (|SIntPlus| t23 |P2-n|))
    (go |Lab25|)
    |Lab23|
    (|fputs| (|MakeLit| "inverse does not exist") (|stdoutFile|))
    (|fputc| (the |SInt| 10) (|stdoutFile|))
    (|Halt| (the |SInt| 0))))

(defprog
  ((|C47-sinteger-divide| |Word| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ((t0 |SInt|) (t1 |SInt|))
  (multiple-value-setq (t0 t1) (|SIntDivide| |P0-i| |P1-j|))
  (block-return |C47-sinteger-divide| (values t0 t1)))

(defprog
  ((|C48-sinteger-^| |Word|)
    ((|P0-x| |Word|) (|P1-n| |Word|) (|e1| |Env|)))
  ((|T0-l| |SInt|)
    (|T1-i| |SInt|)
    (|T2-y| |SInt|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|))
  (tagbody
    (when (|SIntIsZero| |P1-n|) (go |Lab0|))
    (when (|SIntEQ| |P1-n| (the |SInt| 1)) (go |Lab2|))
    (when (|SIntEQ| |P1-n| (the |SInt| 2)) (go |Lab4|))
    (setq |T2-y| (the |SInt| 1))
    (setq |T1-i| (the |SInt| 0))
    (setq |T0-l| (|SIntLength| |P1-n|))
    |Lab6|
    (when (|SIntLT| |T1-i| |T0-l|) (go |Lab14|))
    (setq t5 |T2-y|)
    |Lab5|
    (setq t4 t5)
    |Lab3|
    (setq t3 t4)
    |Lab1|
    (block-return |C48-sinteger-^| t3)
    |Lab14|
    (when (|SIntBit| |P1-n| |T1-i|) (go |Lab8|))
    |Lab9|
    (setq |P0-x| (|SIntTimes| |P0-x| |P0-x|))
    (setq |T1-i| (|SIntNext| |T1-i|))
    (go |Lab6|)
    |Lab8|
    (setq |T2-y| (|SIntTimes| |T2-y| |P0-x|))
    (go |Lab9|)
    |Lab4|
    (setq t5 (|SIntTimes| |P0-x| |P0-x|))
    (go |Lab5|)
    |Lab2|
    (setq t4 |P0-x|)
    (go |Lab3|)
    |Lab0|
    (setq t3 (the |SInt| 1))
    (go |Lab1|)))

(defprog
  ((|C49-sinteger-stepsBetween| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|P2-step| |Word|) (|e1| |Env|)))
  ((t0 |SInt|))
  (setq t0 (|SIntQuo| (|SIntMinus| |P1-y| |P0-x|) |P2-step|))
  (block-return |C49-sinteger-stepsBetween| (|SIntNext| t0)))

(defprog
  ((|C50-sinteger-<<| |Word|)
    ((|P0-w| |Word|) (|P1-i| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|) (t3 |Word|))
  (setq t3 (|formatSInt| |P1-i|))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-w|))
  (|CCall| t1 t3 (the |SInt| 1) (the |SInt| 0))
  (block-return |C50-sinteger-<<| |P0-w|))

(defprog
  ((|C51-sinteger-max| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |Word|))
  (tagbody
    (when (|SIntLT| |P1-y| |P0-x|) (go |Lab0|))
    (setq t0 |P1-y|)
    |Lab1|
    (block-return |C51-sinteger-max| t0)
    |Lab0|
    (setq t0 |P0-x|)
    (go |Lab1|)))

(defprog
  ((|C52-sinteger-min| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |Word|))
  (tagbody
    (when (|SIntLT| |P0-x| |P1-y|) (go |Lab0|))
    (setq t0 |P1-y|)
    |Lab1|
    (block-return |C52-sinteger-min| t0)
    |Lab0|
    (setq t0 |P0-x|)
    (go |Lab1|)))

(defprog
  ((|C53-sinteger-hash| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ()
  (block-return |C53-sinteger-hash| |P0-x|))

(defprog
  ((|C54-sinteger-coerce| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ()
  (block-return |C54-sinteger-coerce| (|formatSInt| |P0-x|)))

(defprog
  ((|C55-sinteger-<<| |Clos|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-sinteger-10| |Struct-sinteger-10|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-sinteger-10-x-0| 0 |l0| |P0-x|)
  (block-return |C55-sinteger-<<| (|Clos| |e0| |C56-sinteger-<<|)))

(defprog
  ((|C56-sinteger-<<| |Word|) ((|P0-p| |Word|) (|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Word|)
    (t4 |SInt|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t4 (|Lex| |Struct-sinteger-10-x-0| 0 |l1|))
  (setq t3 (|formatSInt| t4))
  (multiple-value-setq (t0 t1 t2) (|CCall| |P0-p|))
  (|CCall| t1 t3 (the |SInt| 1) (the |SInt| 0))
  (block-return |C56-sinteger-<<| |P0-p|))

(defprog
  ((|C57-sinteger-case| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ()
  (block-return |C57-sinteger-case| (|SIntEQ| |P0-x| |P1-y|)))

(defprog
  ((|C58-sinteger-abs| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((t0 |Word|))
  (tagbody
    (when (|SIntIsPos| |P0-x|) (go |Lab0|))
    (setq t0 (|SIntNegate| |P0-x|))
    |Lab1|
    (block-return |C58-sinteger-abs| t0)
    |Lab0|
    (setq t0 |P0-x|)
    (go |Lab1|)))

(defprog
  ((|C59-sinteger-sign| |Word|) ((|P0-x| |Word|) (|e1| |Env|)))
  ((t0 |Word|) (t1 |Word|))
  (tagbody
    (when (|SIntIsPos| |P0-x|) (go |Lab0|))
    (when (|SIntLT| |P0-x| (the |SInt| 0)) (go |Lab2|))
    (setq t1 (the |SInt| 0))
    |Lab3|
    (setq t0 t1)
    |Lab1|
    (block-return |C59-sinteger-sign| t0)
    |Lab2|
    (setq t1 (the |SInt| -1))
    (go |Lab3|)
    |Lab0|
    (setq t0 (the |SInt| 1))
    (go |Lab1|)))

(defprog
  ((|C60-sinteger-stepsBetween| |Word|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|e1| |Env|)))
  ((t0 |SInt|))
  (setq t0 (|SIntQuo| (|SIntMinus| |P1-y| |P0-x|) (the |SInt| 1)))
  (block-return |C60-sinteger-stepsBetween| (|SIntNext| t0)))

(defprog
  ((|C61-sinteger-extend0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((t0 |Arr|) (t1 |Record|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq t0 (|ANew| |Word| (the |SInt| 2)))
  (|SetAElt|
    t0
    (the |SInt| 1)
    (|Lex| |Struct-sinteger-13-MachineInteger-0| 0 |l1|))
  (|SetAElt| t0 (the |SInt| 0) |G-sinteger_MachineInteger_695469395|)
  (setq t1 (|RNew| |Struct-sinteger-5|))
  (|SetRElt| |Struct-sinteger-5| |size| 0 t1 (the |SInt| 2))
  (|SetRElt| |Struct-sinteger-5| |nsize| 1 t1 (the |SInt| 2))
  (|SetRElt| |Struct-sinteger-5| |values| 2 t1 t0)
  (|CCall| |G-extendFill!| |P0-domain| t1)
  (block-return |C61-sinteger-extend0| nil))

(defprog
  ((|C62-sinteger-machine-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-sinteger-13--10| 10 |l1|) (go |Lab0|))
    (|SetLex| |Struct-sinteger-13--10| 10 |l1| (the |Bool| t))
    (|CCall| |G-machine|)
    |Lab0|
    (block-return
      |C62-sinteger-machine-init|
      |G-machine_Machine_915715331|)))

(defprog
  ((|C63-sinteger-basic-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-sinteger-13--11| 11 |l1|) (go |Lab0|))
    (|SetLex| |Struct-sinteger-13--11| 11 |l1| (the |Bool| t))
    (|CCall| |G-basic|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 4)) (go |Lab1|))
    (block-return
      |C63-sinteger-basic-init|
      |G-basic_MachineInteger_885893404|)
    |Lab1|
    (when (|SIntNE| |P0-idx| (the |SInt| 3)) (go |Lab2|))
    (block-return
      |C63-sinteger-basic-init|
      |G-basic_TextWriter_360221334|)
    |Lab2|
    (when (|SIntNE| |P0-idx| (the |SInt| 2)) (go |Lab3|))
    (block-return |C63-sinteger-basic-init| |G-basic_error_011667951|)
    |Lab3|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab4|))
    (block-return |C63-sinteger-basic-init| |G-basic_Integer_117694970|)
    |Lab4|
    (block-return |C63-sinteger-basic-init| |G-basic_String_641272169|)))

(defprog
  ((|C64-sinteger-segment-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-sinteger-13--12| 12 |l1|) (go |Lab0|))
    (|SetLex| |Struct-sinteger-13--12| 12 |l1| (the |Bool| t))
    (|CCall| |G-segment|)
    |Lab0|
    (block-return
      |C64-sinteger-segment-init|
      |G-segment_Steppable_064247597|)))

(defprog
  ((|C65-sinteger-foamcat-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-sinteger-13--13| 13 |l1|) (go |Lab0|))
    (|SetLex| |Struct-sinteger-13--13| 13 |l1| (the |Bool| t))
    (|CCall| |G-foamcat|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 2)) (go |Lab1|))
    (block-return
      |C65-sinteger-foamcat-init|
      |G-foamcat_IntegerNumberSystem_021434957|)
    |Lab1|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab2|))
    (block-return
      |C65-sinteger-foamcat-init|
      |G-foamcat_OrderedFinite_544701037|)
    |Lab2|
    (block-return |C65-sinteger-foamcat-init| |G-foamcat_Logic_688403051|)))

(setq |G-sinteger| (|Clos| nil |C0-sinteger-sinteger|))

(setq |G-sinteger_MachineInteger_695469395| nil)

(setq |G-sinteger_MachineInteger_009988596| nil)

(setq |C66-sinteger-0| (the |SInt| 0))

(setq |C67-sinteger-1| (the |SInt| 1))

(setq |C68-sinteger-sample| (the |SInt| 0))

(file-imports
  '((|G-foamcat| "foamcat" |initializer| "")
      (|G-segment| "segment" |initializer| "")
      (|G-basic| "basic" |initializer| "")
      (|G-machine| "machine" |initializer| "")
      (|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-extendMake| "extendMake" 0 "")
      (|G-extendFill!| "extendFill!" 0 "")
      (|G-basic_MachineInteger_885893404|
        "MachineInteger"
        885893404
        "basic")
      (|G-domainMake| "domainMake" 0 "")
      (|G-basic_TextWriter_360221334| "TextWriter" 360221334 "basic")
      (|G-basic_error_011667951| "error" 11667951 "basic")
      (|G-basic_Integer_117694970| "Integer" 117694970 "basic")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-domainFill!| "domainFill!" 0 "")
      (|G-domainMakeDummy| "domainMakeDummy" 0 "")
      (|G-domainAddDefaults!| "domainAddDefaults!" 0 "")
      (|G-categoryMake| "categoryMake" 0 "")
      (|G-basic_String_641272169| "String" 641272169 "basic")
      (|G-domainGetExport!| "domainGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-machine_Machine_915715331| "Machine" 915715331 "machine")
      (|G-categoryAddParents!| "categoryAddParents!" 0 "")
      (|G-segment_Steppable_064247597| "Steppable" 64247597 "segment")
      (|G-foamcat_IntegerNumberSystem_021434957|
        "IntegerNumberSystem"
        21434957
        "foamcat")
      (|G-foamcat_OrderedFinite_544701037|
        "OrderedFinite"
        544701037
        "foamcat")
      (|G-rtLazyCatFrInit| "rtLazyCatFrInit" 0 "")
      (|G-foamcat_Logic_688403051| "Logic" 688403051 "foamcat")
      (|G-categoryAddExports!| "categoryAddExports!" 0 "")
      (|G-rtConstSIntFn| "rtConstSIntFn" 0 "")
      (|G-domainMakeDispatch| "domainMakeDispatch" 0 "")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtConstNameFn| "rtConstNameFn" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-sinteger_MachineInteger_009988596|
        "MachineInteger"
        9988596
        "sinteger")
      (|G-sinteger_MachineInteger_695469395|
        "MachineInteger"
        695469395
        "sinteger")
      (|G-sinteger| "sinteger" |initializer| "")))
