# ======================================================================
# This code was written all or part by Dr. Manuel Bronstein from
# Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
# decided to publish this code under the CeCILL open source license in
# memory of Dr. Manuel Bronstein.
# 
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and Inria at the following URL :
# http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
# 
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided
# only with a limited warranty and the software's author, the holder of
# the economic rights, and the successive licensors have only limited
# liability.
# 
# In this respect, the user's attention is drawn to the risks associated
# with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards
# their requirements in conditions enabling the security of their
# systems and/or data to be ensured and, more generally, to use and
# operate it in the same conditions as regards security.
# 
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.
# ======================================================================
# 
objects   = skpolycat.o skewsup.o skewdup.o lodifo.o automor.o sktools.o
asobjects = skpolycat.ao skewsup.ao skewdup.ao lodifo.ao automor.ao sktools.ao
options	  = -M2 -Fao -Fo -Q3 -Csmax=0 -Mno-mactext
tex  = skpolycat.tex skewsup.tex skewdup.tex lodifo.tex automor.tex sktools.tex
test      = Tskewsup.as Tskewdup.as
testdir   = ../../test
libsumit  = ../../lib/libsumit.a
sumitasl  = ../../lib/libsumit.al

all: datestamp

datestamp: $(objects)
	ar rv $(libsumit) $(objects)
	touch datestamp

automor.o: automor.as ../polyfactor0/zringint.o
	axiomxl $(options) automor.as
	ar rv $(sumitasl) automor.ao

skpolycat.o: skpolycat.as ../univpoly/categories/ufalg.o ../polyfactor0/zringint.o
	axiomxl $(options) skpolycat.as
	ar rv $(sumitasl) skpolycat.ao

sktools.o: sktools.as skpolycat.o automor.o
	axiomxl $(options) sktools.as
	ar rv $(sumitasl) sktools.ao

skewsup.o: skewsup.as sktools.o ../univpoly/sup.o
	axiomxl $(options) skewsup.as
	ar rv $(sumitasl) skewsup.ao

skewdup.o: skewdup.as sktools.o ../univpoly/dup.o
	axiomxl $(options) skewdup.as
	ar rv $(sumitasl) skewdup.ao
 
lodifo.o: lodifo.as skewdup.o
	axiomxl $(options) lodifo.as
	ar rv $(sumitasl) lodifo.ao

.PHONY: doc
doc: $(tex)

automor.tex: automor.as
	as2doc automor

skpolycat.tex: skpolycat.as
	as2doc skpolycat

sktools.tex: sktools.as
	as2doc sktools

skewsup.tex: skewsup.as
	as2doc skewsup

skewdup.tex: skewdup.as
	as2doc skewdup

lodifo.tex: lodifo.as
	as2doc lodifo

.PHONY: test
test: $(test)

Tskewsup.as: skewsup.as
	as2test skewsup
	cp Tskewsup.as $(testdir)

Tskewdup.as: skewdup.as
	as2test skewdup
	cp Tskewdup.as $(testdir)

.PHONY: clean
clean:
	-rm $(objects) $(asobjects) $(tex) $(test)

