-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
------------------------------ sit_lodifo0.as ------------------------------
-- Copyright (c) Manuel Bronstein 1996
-- Copyright (c) INRIA 1999, Version 0.1.12
-- Logiciel Sum^it ©INRIA 1999, dans sa version 0.1.12
-- Copyright (c) Swiss Federal Polytechnic Institute Zurich, 1996-97
-----------------------------------------------------------------------------

#include "sumit"

#if ALDOC
%
% Describes this category as LinearOrdinaryDifferenceOperatorCategory,
% which is not documented separately.
%
\thistype{LinearOrdinaryDifferenceOperatorCategory}
\History{Manuel Bronstein}{13/08/96}{created}
\Usage{ \this~R: Category }
\Params{ {\em R} & \astype{Ring} & A ring\\ }
\Descr{\this~R is the category of linear ordinary difference
operators with coefficients in R.}
\begin{exports}
\category{\astype{UnivariateSkewPolynomialCategory} R}\\
\asexp{adjoint}: & \% $\to$ \% & Adjoint operator\\
\asexp{apply}: & (\%, R) $\to$ R & Applies an operator to an element of R\\
\asexp{shift}: & $\to$ \astype{Automorphism} R & The shift used on R\\
\end{exports}
\begin{exports}[if R has \astype{GcdDomain} then]
\asexp{exteriorPower}: & (\%, \astype{Integer}) $\to$ \% & Exterior power\\
\end{exports}
#endif
define LinearOrdinaryDifferenceOperatorCategory0(R:Ring): Category ==
	UnivariateSkewPolynomialCategory R with {
		adjoint: % -> %;
#if ALDOC
\aspage{adjoint}
\Usage{\name~L}
\Signature{\%}{\%}
\Params{ {\em L} & \% & A difference operator\\ }
\Retval{Returns
$$
L^\ast = \sum_{i=d}^n \sigma^i a_{n+d-i}
$$
where $L = \sum_{i=d}^n a_i \sigma^i$.}
#endif
		apply: (%, R) -> R;
#if ALDOC
\aspage{apply}
\Usage{ \name(L, x)\\L~x }
\Signature{(\%, R)}{R}
\Params{
{\em L} & \% & A difference operator\\
{\em x} & R & A ring element\\
}
\Retval{Returns
$$
L x = \sum_{i=0}^n a_i \sigma^i x
$$
where $L = \sum_{i=0}^n a_i \sigma^i$.}
#endif
		if R has GcdDomain then {
			exteriorPower: (%, Integer) -> %;
#if ALDOC
\aspage{exteriorPower}
\Usage{\name(L, n)}
\Signature{(\%, \astype{Integer})}{\%}
\Params{
{\em L} & \% & A difference operator\\
{\em n} & \astype{Integer} & A positive integer\\
}
\Retval{Returns a difference operator
$\extpow{L}{n}$ of minimal order
whose kernel is generated by the Casoratians of $n$ elements
of a basis of $\Ker(L)$.}
#endif
		}
		shift: Automorphism R;
#if ALDOC
\aspage{shift}
\Usage{\name}
\Signature{}{\astype{Automorphism} R}
\Retval{Returns the shift of R given by $x \to E x$, where
$E$ is the monic operator of degree one.}
#endif
		default {
			apply(L:%, r:R):R	== apply(L, 1, r);
			shift:Automorphism R	== morphism((x:R):R+-> monom x);

			adjoint(L:%):% == {
				import from Integer, R;
				a:% := 0;
				zero? L => a;
				m := degree L + trailingDegree L;
				for term in terms L repeat {	-- increasing
					(c, e) := term;
					a := add!(a, monomial(1, m-e) * (c::%));
				}
				a;
			}
		}
}

