-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
----------------------------- dfreemod.as ----------------------------------
#include "sumit"

#if ASDOC
\thistype{DenseFreeModule}
\History{Manuel Bronstein}{17/2/97}{created}
\Usage{ import from \this(R, V)\\ }
\Params{
{\em R} & SumitRing & The coefficient ring\\
{\em V} & FiniteSet & A basis of the module\\
}
\Descr{\this~(R, V) implements densely the free module generated by V over R.}
\begin{exports}
\category{FreeModule(R, V)}\\
\end{exports}
#endif

macro {
	I	== SingleInteger;
	TREE	== ExpressionTree;
	OUT	== TextWriter;
	Symbol	== String;
	anon	== "\Box";
}

DenseFreeModule(R:SumitRing, V:FiniteSet, avar:Symbol == anon):
	FreeModule(R, V) == add {
	-- elements are stored as arrays of coefficients in the basis
	-- implicitely given by index and lookup in V

	macro Rep == PrimitiveArray R;
	import from I, Rep, V;

	local size:I		== { import from Integer; retract(#$V); }
	(port:OUT) << (p:%):OUT	== { import from TREE; tex(port, extree p); }
	0:%					== per new(size, 0);
	sample:%				== monomial(1, sample);
	coefficient(p:%, t:V):R			== coefficient(p, index t);
	coefficient(p:%, i:SingleInteger):R	== rep(p)(i);
	extree(p:%):TREE			== p avar;
	(a:%) + (b:%):%				== add!(copy a, b);
	(a:%) - (b:%):%				== add!(copy a, -1, b);
	- (a:%):%				== minus! copy a;
	(c:R) * (a:%):%				== times!(c, copy a);

	apply(port:OUT, p:%, x:Symbol):OUT == {
		import from TREE;
		tex(port, p x);
	}

	copy(p:%):% == {
		zero? p => p;
		a := new(size, 0);
		pv := rep p;
		for i in 1..size repeat a.i := pv.i;
		per a;
	}

	minus!(p:%):% == {
		import from R;
		zero? p => p;
		pv := rep p;
		for i in 1..size repeat pv.i := - pv.i;
		p;
	}

	add!(p:%, q:%):% == {
		import from R;
		zero? p => copy q;
		pv := rep p; qv := rep q;
		for i in 1..size repeat pv.i := pv.i + qv.i;
		p;
	}

	add!(p:%, c:R, y:V):% == {
		zero? p => monomial(c, y);
		zero? c => p;
		pv := rep p;
		i := index y;
		pv.i := pv.i + c;
		p;
	}

	add!(p:%, c:R, q:%):% == {
		import from R;
		zero? p => times!(c, copy q);
		zero? c => p;
		pv := rep p; qv := rep q;
		for i in 1..size repeat pv.i := pv.i + c * qv.i;
		p;
	}

	times!(c:R, p:%):% == {
		import from R;
		zero? p => p;
		pv := rep p;
		for i in 1..size repeat pv.i := c * pv.i;
		p;
	}

	apply(p:%, x:Symbol):TREE == {
		import from List TREE;
		zero? p => extree(0@R);
		l:List TREE := empty();
		a := rep p;
		for i in 1..size | ~zero?(c := a.i) repeat
			l := cons(extree(c, lookup(i)(x)), l);
		ASSERT(~empty? l);
		empty? rest l => first l;
		ExpressionTreePlus l;
	}

	local extree(c:R, t:TREE):TREE == {
		import from List TREE;
		one? c => t;
		negative?(tc := extree c) => {
			if c ~= -1 then t := ExpressionTreeTimes [negate tc, t];
			ExpressionTreeMinus [t];
		}
		ExpressionTreeTimes [tc, t];
	}

	monomial(c:R, t:V):% == {
		a := new(size, 0);
		a(index t) := c;
		per a;
	}

	(a:%) = (b:%):Boolean == {
		A := rep a; B := rep b;
		for i in 1..size repeat A.i ~= B.i => return false;
		true;
	}
}
