-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
----------------------------- frmodcat.as ----------------------------------
#include "sumit"

#if ASDOC
\thistype{FreeModule}
\History{Manuel Bronstein}{17/2/97}{created}
\Usage{\this(R, V):Category}
\Params{
{\em R} & SumitRing & The coefficient ring\\
{\em V} & FiniteSet & A basis of the module\\
}
\Descr{\this~(R, V) is the categories of free modules generated by V over R.}
\begin{exports}
\category{SumitType}\\
\category{AbelianGroup}\\
$*$: & (R, \%) $\to$ \% & Left-multiplication by a scalar\\
add!: & (\%, R, \%) $\to$ \% & In-place product and sum\\
add!: & (\%, R, V) $\to$ \% & In-place addition of a monomial\\
apply: & (\%, String) $\to$ TREE & Conversion to an expression tree\\
apply: & (OUT, \%, String) $\to$ OUT & Write an element to a port\\
coefficient: & (\%, V) $\to$ R & Extraction of a coefficient\\
coefficient: & (\%, SingleInteger) $\to$ R & Extraction of a coefficient\\
copy: & \% $\to$ \% & Make a copy\\
lift: & (Derivation R, V $\to$ \%) $\to$ \% $\to$ \% & Extend a derivation\\
minus!: & \% $\to$ \% & In-place negation\\
monomial: & (R, V) $\to$ \% & Creation of a monomial\\
times!: & (R, \%) $\to$ \% & In-place product by a scalar\\
\end{exports}
\Aswhere{
OUT &==& TextWriter\\
TREE &==& ExpressionTree\\
}
#endif

macro {
	I	== SingleInteger;
	TREE	== ExpressionTree;
	OUT	== TextWriter;
	Symbol	== String;
}

FreeModule(R:SumitRing,V:FiniteSet):Category==Join(SumitType,AbelianGroup) with{
	*: (R, %) -> %;
#if ASDOC
\aspage{$*$}
\Usage{r \name~p}
\Signature{(R, \%)}{\%}
\Params{
{\em r} & R & A scalar\\
{\em p} & \% & An element of the free module\\
}
\Retval{Returns the product $r p$.}
\seealso{times!(\this)}
#endif
	add!: (%, %) -> %;
	add!: (%, R, %) -> %;
	add!: (%, R, V) -> %;
#if ASDOC
\aspage{add!}
\Usage{\name(p, q) \\ \name(p, r, q)\\ \name(p, r, t)}
\Signatures{
\name: & (\%, \%) $\to$ \% \\
\name: & (\%, R, \%) $\to$ \% \\
\name: & (\%, R, V) $\to$ \% \\
}
\Params{
{\em p} & \% & An element of the free module (to be destroyed)\\
{\em r} & R & A scalar\\
{\em q} & \% & An element of the free module\\
{\em t} & V & A basis element\\
}
\Retval{\name(p,q) returns the sum $p + q$,
while \name(p, r, q) returns $p + r q$ and
\name(p, r, t) returns $p + r t$.}
\Remarks{
The storage used by p is allowed
to be destroyed or reused, so p is lost after this call.
This function may cause p to be destroyed, so do not use it unless
p has been locally allocated, and is guaranteed not to share space
with other elements. Some functions are not necessarily copying their
arguments and can thus create memory aliases.}
\seealso{minus!(\this), times!(\this)}
#endif
	apply: (%, Symbol) -> TREE;
	apply: (OUT, %, Symbol) -> OUT;
#if ASDOC
\aspage{apply}
\Usage{ \name(p, x)\\p~x\\ \name(port, p, x)\\ port(p, x) }
\Signatures{
\name: & (\%, ExpressionTree) $\to$ ExpressionTree\\
\name: & (TextWriter, \%, String) $\to$ TextWriter\\
}
\Params{
{\em p} & \% & An element of the free module\\
{\em x} & String & A name for the variables\\
{\em port} & TextWriter & An output port\\
}
\Retval{
\name(p, x) returns p as an expression tree, using x as root variable name.\\
\name(port, p, x) sends p to port using x as root variable name,
and returns the output port afterwards.
}
#endif
	coefficient: (%, V) -> R;
	coefficient: (%, SingleInteger) -> R;
#if ASDOC
\aspage{coefficient}
\Usage{\name(p, t)\\ \name(p, i)}
\Signatures{
\name: & (\%, V) $\to$ R\\
\name: & (\%, SingleInteger) $\to$ R\\
}
\Params{
{\em p} & \% & An element of the free module\\
{\em t} & V & A basis element\\
{\em i} & SingleInteger & The index of a basis element\\
}
\Retval{
\name(p, t) returns the coefficient of $p$ in $t$, \ie $c$ where $p = c t$,
while \name(p, i) returns the coefficient of $p$ in the \Th{i} basis
element in the built-in enumeration of V given by the lookup function.}
\Remarks{The version with an integer index can be used to iterate over
all the possible variables in a consistent fashion. The first index is $1$.}
#endif
	copy: % -> %;
#if ASDOC
\aspage{copy}
\Usage{\name~p}
\Signature{\%}{\%}
\Params{ {\em p} & \% & An element of the free module\\ }
\Retval{Returns a copy of p.}
\Remarks{Use \name~before making in-place operations on a parameter.}
#endif
	lift: (Derivation R, V -> %) -> % -> %;
#if ASDOC
\aspage{lift}
\Usage{\name(D,$\partial$)}
\Signature{(Derivation R, V $\to$ \%)}{\% $\to$ \%}
\Params{
{\em D} & Derivation R & A derivation on R\\
{\em $\partial$} & V $\to$ \% & A derivation on the basis elements\\
}
\Retval{Returns the derivation $\Delta$ on \% given by
$$
\Delta \paren{\sum_i a_i t_i} = \sum_i (D a_i) t_i + \sum_i a_i \partial t_i\;.
$$
}
\Remarks{$\partial$ must be a derivation.}
#endif
	minus!: % -> %;
#if ASDOC
\aspage{minus!}
\Usage{\name~p}
\Signature{\%}{\%}
\Params{ {\em p} & \% & An element of the free module (to be destroyed)\\ }
\Retval{Returns $-p$, where the storage used by p is allowed
to be destroyed or reused, so p is lost after this call.}
\Remarks{This function may cause p to be destroyed, so do not use it unless
p has been locally allocated, and is guaranteed not to share space
with other elements. Some functions are not necessarily copying their
arguments and can thus create memory aliases.}
\seealso{add!(\this), times!(\this)}
#endif
	monomial: (R, V) -> %;
#if ASDOC
\aspage{monomial}
\Usage{\name(c, m)}
\Signature{(R, V)}{\%}
\Params{
{\em c} & R & A scalar\\
{\em t} & V & A basis element\\
}
\Retval{Returns the monomial $c t$.}
#endif
	times!: (R, %) -> %;
#if ASDOC
\aspage{times!}
\Usage{\name(r, p)}
\Signature{(R, \%)}{\%}
\Params{
{\em r} & R & A scalar to be multiplied by p\\
{\em p} & \% & An element of the free module (to be destroyed)\\
}
\Retval{Returns the product $r p$.}
\Remarks{The storage used by p is allowed to be destroyed or reused, so p
is lost after this call.
This may cause p to be destroyed, so do not use this unless
p has been locally allocated, and is thus guaranteed not to share space
with other elements. Some functions, like reductum(\this) are
not necessarily copying their arguments and can thus create memory aliases.}
\seealso{$\ast$(\this), add!(\this)}
#endif
	default {
		lift(D:Derivation R, delta:V -> %)(p:%):% == {
			import from SingleInteger, Integer, R, V;
			dp:% := 0;
			dim:SingleInteger := retract(#$V);
			for i in 1..dim | ~zero?(c := coefficient(p,i)) repeat {
				dp := add!(dp, D c, t := lookup i);
				dp := add!(dp, c, delta t);
			}
			dp;
		}
	}
}
