-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
------------------------ sit_dfremod.as ----------------------------------
-- Copyright (c) Manuel Bronstein 1997
-- Copyright (c) INRIA 1999, Version 0.1.12
-- Logiciel Sum^it ©INRIA 1999, dans sa version 0.1.12
-- Copyright (c) Swiss Federal Polytechnic Institute Zurich, 1997
-----------------------------------------------------------------------------

#include "sumit"

#if ALDOC
\thistype{DenseFreeModule}
\History{Manuel Bronstein}{17/2/97}{created}
\Usage{ import from \this(R, V)\\ import from \this(R, V, x)}
\Params{
{\em R} & \astype{Ring} & The coefficient ring\\
{\em V} & \astype{FiniteSet} & A basis of the module\\
{\em x} & \astype{Symbol} & The variable name (optional)\\
}
\Descr{\this~(R, V) implements densely the free module generated by V over R.}
\begin{exports}
\category{\astype{FiniteFreeModule}(R, V)}\\
\end{exports}
#endif

macro {
	I	== MachineInteger;
	Z	== Integer;
	TREE	== ExpressionTree;
	OUT	== TextWriter;
}

DenseFreeModule(R:Ring, V:FiniteSet, avar:Symbol == new()):
	FiniteFreeModule(R, V) == add {
	-- elements are stored as arrays of coefficients in the basis
	-- implicitely given by index and lookup in V

	Rep == PrimitiveArray R;
	import from I, Rep, V;

	local size:I		== { import from Z; machine(#$V); }
	local sizem1:I		== prev size;
	local mindex(t:V):I	== { import from Z; machine index t; }
	local mlookup(i:I):V	== { import from Z; lookup(i::Z); }
	0:%			== { import from R; per new(size, 0); }
	coefficient(p:%, t:V):R	== coefficient(p, mindex t);
	coefficient(p:%, i:I):R	== rep(p)(prev i);
	extree(p:%):TREE	== p extree avar;
	(a:%) + (b:%):%		== add!(copy a, b);
	(a:%) - (b:%):%		== { import from R; add!(copy a, -1, b); }
	- (a:%):%		== minus! copy a;
	(c:R) * (a:%):%		== times!(c, copy a);
	(port:OUT) << (p:%):OUT	== { import from TREE; tex(port, extree p); }

	apply(port:OUT, p:%, x:Symbol):OUT == {
		import from TREE;
		tex(port, p extree x);
	}

	copy(p:%):% == {
		zero? p => p;
		a := new(size, 0);
		pv := rep p;
		for i in 0..sizem1 repeat a.i := pv.i;
		per a;
	}

	minus!(p:%):% == {
		import from R;
		zero? p => p;
		pv := rep p;
		for i in 0..sizem1 repeat pv.i := - pv.i;
		p;
	}

	add!(p:%, q:%):% == {
		import from R;
		zero? p => copy q;
		pv := rep p; qv := rep q;
		for i in 0..sizem1 repeat pv.i := pv.i + qv.i;
		p;
	}

	add!(p:%, c:R, y:V):% == {
		zero? p => monomial(c, y);
		zero? c => p;
		pv := rep p;
		i := prev mindex y;
		pv.i := pv.i + c;
		p;
	}

	add!(p:%, c:R, q:%):% == {
		import from R;
		zero? p => times!(c, copy q);
		zero? c => p;
		pv := rep p; qv := rep q;
		for i in 0..sizem1 repeat pv.i := pv.i + c * qv.i;
		p;
	}

	times!(c:R, p:%):% == {
		import from R;
		zero? p => p;
		pv := rep p;
		for i in 0..sizem1 repeat pv.i := c * pv.i;
		p;
	}

	apply(p:%, t:TREE):TREE == {
		import from Boolean, R, List TREE;
		zero? p => extree(0@R);
		l:List TREE := empty;
		a := rep p;
		for i in 0..sizem1 | ~zero?(c := a.i) repeat
			l := cons(extree(c, mlookup(next i)(t)), l);
		assert(~empty? l);
		empty? rest l => first l;
		ExpressionTreePlus l;
	}

	local extree(c:R, t:TREE):TREE == {
		import from List TREE;
		one? c => t;
		negative?(tc := extree c) => {
			if c ~= -1 then t := ExpressionTreeTimes [negate tc, t];
			ExpressionTreeMinus [t];
		}
		ExpressionTreeTimes [tc, t];
	}

	monomial(c:R, t:V):% == {
		a := new(size, 0);
		a(prev mindex t) := c;
		per a;
	}

	(a:%) = (b:%):Boolean == {
		import from R;
		A := rep a; B := rep b;
		for i in 0..sizem1 repeat A.i ~= B.i => return false;
		true;
	}
}
