-- ======================================================================
-- This code was written all or part by Dr. Manuel Bronstein from
-- Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
-- decided to publish this code under the CeCILL open source license in
-- memory of Dr. Manuel Bronstein.
-- 
-- This software is governed by the CeCILL license under French law and
-- abiding by the rules of distribution of free software. You can use,
-- modify and/or redistribute the software under the terms of the CeCILL
-- license as circulated by CEA, CNRS and Inria at the following URL :
-- http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
-- 
-- As a counterpart to the access to the source code and rights to copy,
-- modify and redistribute granted by the license, users are provided
-- only with a limited warranty and the software's author, the holder of
-- the economic rights, and the successive licensors have only limited
-- liability.
-- 
-- In this respect, the user's attention is drawn to the risks associated
-- with loading, using, modifying and/or developing or reproducing the
-- software by the user in light of its specific status of free software,
-- that may mean that it is complicated to manipulate, and that also
-- therefore means that it is reserved for developers and experienced
-- professionals having in-depth computer knowledge. Users are therefore
-- encouraged to load and test the software's suitability as regards
-- their requirements in conditions enabling the security of their
-- systems and/or data to be ensured and, more generally, to use and
-- operate it in the same conditions as regards security.
-- 
-- The fact that you are presently reading this means that you have had
-- knowledge of the CeCILL license and that you accept its terms.
-- ======================================================================
-- 
-------------------------- sit_fnfrmod.as ----------------------------------
-- Copyright (c) Manuel Bronstein 1997
-- Copyright (c) INRIA 1999, Version 0.1.12
-- Logiciel Sum^it ©INRIA 1999, dans sa version 0.1.12
-- Copyright (c) Swiss Federal Polytechnic Institute Zurich, 1997
-----------------------------------------------------------------------------

#include "sumit"

#if ALDOC
\thistype{FiniteFreeModule}
\History{Manuel Bronstein}{17/2/97}{created}
\Usage{\this(R, V):Category}
\Params{
{\em R} & \astype{Ring} & The coefficient ring\\
{\em V} & \astype{FiniteSet} & A basis of the module\\
}
\Descr{\this~(R, V) is the categories of free modules generated by
a finite V over R.}
\begin{exports}
\category{\astype{CopyableType}}\\
\category{\astype{Module} R}\\
\asexp{add!}: & (\%, R, V) $\to$ \% & In-place addition of a monomial\\
\asexp{apply}: & (\%, TREE) $\to$ TREE & Conversion to an expression tree\\
\asexp{apply}:
& (OUT, \%, \astype{Symbol}) $\to$ OUT & Write an element to a port\\
\asexp{coefficient}: & (\%, V) $\to$ R & Extraction of a coefficient\\
\asexp{coefficient}:
& (\%, \astype{MachineInteger}) $\to$ R & Extraction of a coefficient\\
\asexp{lift}:
& (\astype{Derivation} R, V $\to$ \%) $\to$ \% $\to$ \% & Extend a derivation\\
& (R $\to$ R, V $\to$ \%) $\to$ \% $\to$ \% & Extend a morphism\\
\asexp{monomial}: & (R, V) $\to$ \% & Creation of a monomial\\
\end{exports}
\begin{aswhere}
OUT &==& \astype{TextWriter}\\
TREE &==& \astype{ExpressionTree}\\
\end{aswhere}
#endif

define FiniteFreeModule(R:Ring, V:FiniteSet):Category ==
	Join(CopyableType, Module R) with {
	add!: (%, R, V) -> %;
#if ALDOC
\aspage{add!}
\Usage{\name(p, c, t)}
\Signature{(\%, R, V)}{\%}
\Params{
{\em p} & \% & An element of the free module (to be destroyed)\\
{\em c} & R & A scalar\\
{\em t} & V & A basis element\\
}
\Retval{Returns the sum $p + c t$.}
\Remarks{The storage used by p is allowed to be destroyed or reused, so p
is lost after this call. This may cause p to be destroyed, so do not use
this unless p has been locally allocated, and is thus guaranteed not to
share space with other elements.}
#endif
	apply: (%, ExpressionTree) -> ExpressionTree;
	apply: (TextWriter, %, Symbol) -> TextWriter;
#if ALDOC
\aspage{apply}
\Usage{ \name(p, t)\\p~t\\ \name(port, p, x)\\ port(p, x) }
\Signatures{
\name: & (\%, \astype{ExpressionTree}) $\to$ \astype{ExpressionTree}\\
\name: & (\astype{TextWriter}, \%, \astype{Symbol}) $\to$ \astype{TextWriter}\\
}
\Params{
{\em p} & \% & An element of the type\\
{\em t} & \astype{ExpressionTree} & An expression tree\\
{\em x} & \astype{Symbol} & A name for the variables\\
{\em port} & \astype{TextWriter} & An output port\\
}
\Retval{
\name(p, t) returns p as an expression tree, using t as root variable name.\\
\name(port, p, x) sends p to port using x as root variable name,
and returns the output port afterwards.
}
#endif
	coefficient: (%, V) -> R;
	coefficient: (%, MachineInteger) -> R;
#if ALDOC
\aspage{coefficient}
\Usage{\name(p, t)\\ \name(p, i)}
\Signatures{
\name: & (\%, V) $\to$ R\\
\name: & (\%, \astype{MachineInteger}) $\to$ R\\
}
\Params{
{\em p} & \% & An element of the free module\\
{\em t} & V & A basis element\\
{\em i} & \astype{MachineInteger} & The index of a basis element\\
}
\Retval{\name(p, t) returns the coefficient of $p$ in $t$, while
\name(p, i) returns the coefficient of $p$ in the \Th{i} basis
element in the built-in enumeration of V given by the lookup function.}
\Remarks{\name(p, i) can be used to iterate over
all the possible variables in a consistent fashion. The first index is $1$.}
#endif
	lift: (Derivation R, V -> %) -> % -> %;
	lift: (R -> R, V -> %) -> % -> %;
#if ALDOC
\aspage{lift}
\Usage{\name(D,$\partial$)\\ \name($\sigma$,$\tau$)}
\Signatures{
\name: & (\astype{Derivation} R, V $\to$ \%) $\to$ \% $\to$ \%\\
\name: & (R $\to$ R, V $\to$ \%) $\to$ \% $\to$ \%\\
}
\Params{
{\em D} & \astype{Derivation} R & A derivation on R\\
$\partial$ & V $\to$ \% & A derivation on the basis elements\\
$\sigma$ & R $\to$ R & A morphism on R\\
$\tau$ & V $\to$ \% & A morphism on the basis elements\\
}
\Descr{\name(D,$\partial$) returns the derivation $\Delta$ on \% given by
$$
\Delta \paren{\sum_i a_i t_i} = \sum_i (D a_i) t_i + \sum_i a_i \partial t_i
$$
while \name($\sigma$,$\tau$) returns the morphism $\rho$ on \% given by
$$
\rho \paren{\sum_i a_i t_i} = \sum_i \sigma(a_i) \tau(t_i)
$$
}
\Remarks{$\partial$ must be a derivation, $\sigma$ and $\tau$ must
be morphisms.}
#endif
	monomial: (R, V) -> %;
#if ALDOC
\aspage{monomial}
\Usage{\name(c, t)}
\Signature{(R, V)}{\%}
\Params{
{\em c} & R & A scalar\\
{\em t} & V & A basis element\\
}
\Retval{Returns the monomial $c t$.}
#endif
	default {
		add!(p:%, c:R, v:V):% == add!(p, monomial(c, v));

		lift(f:R -> R, g:V -> %)(p:%):% == {
			import from Boolean, MachineInteger, Integer, R, V;
			fp:% := 0;
			dim := machine(#$V);
			for i in 1..dim | ~zero?(c := coefficient(p,i)) repeat
				fp := add!(fp, f c, g lookup(i::Integer));
			fp;
		}

		lift(D:Derivation R, delta:V -> %)(p:%):% == {
			import from Boolean, MachineInteger, Integer, R, V;
			dp:% := 0;
			dim := machine(#$V);
			for i in 1..dim | ~zero?(c := coefficient(p,i)) repeat {
				dp := add!(dp, D c, t := lookup(i::Integer));
				dp := add!(dp, c, delta t);
			}
			dp;
		}
	}
}
