# ======================================================================
# This code was written all or part by Dr. Manuel Bronstein from
# Inria-CAFE project team. After his sudden death on June 6, 2005, Inria
# decided to publish this code under the CeCILL open source license in
# memory of Dr. Manuel Bronstein.
# 
# This software is governed by the CeCILL license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/or redistribute the software under the terms of the CeCILL
# license as circulated by CEA, CNRS and Inria at the following URL :
# http://www.cecill.info/licences/Licence_CeCILL_V2-en.html
# 
# As a counterpart to the access to the source code and rights to copy,
# modify and redistribute granted by the license, users are provided
# only with a limited warranty and the software's author, the holder of
# the economic rights, and the successive licensors have only limited
# liability.
# 
# In this respect, the user's attention is drawn to the risks associated
# with loading, using, modifying and/or developing or reproducing the
# software by the user in light of its specific status of free software,
# that may mean that it is complicated to manipulate, and that also
# therefore means that it is reserved for developers and experienced
# professionals having in-depth computer knowledge. Users are therefore
# encouraged to load and test the software's suitability as regards
# their requirements in conditions enabling the security of their
# systems and/or data to be ensured and, more generally, to use and
# operate it in the same conditions as regards security.
# 
# The fact that you are presently reading this means that you have had
# knowledge of the CeCILL license and that you accept its terms.
# ======================================================================
# 
objects   = hensel.o zfactor.o zringint.o
asobjects = hensel.ao zfactor.ao zringint.ao
flags     = -M2 -Fao -Fo -Csmax=0 -Mno-mactext
options   = $(flags) -q3
tex       = hensel.tex zfactor.tex
test      = Tzfactor.as
testdir   = ../../test
libsumit  = ../../lib/libsumit.a
sumitasl  = ../../lib/libsumit.al

all: datestamp

datestamp: $(objects)
	ar rv $(libsumit) $(objects)
	touch datestamp

hensel.o: hensel.as ../univpoly/categories/upolc0.o ../mat/zlaring.o
	axiomxl $(options) hensel.as
	ar rv $(sumitasl) hensel.ao

zfactor.o: zfactor.as hensel.o ../univpoly/dup.o ../ffield/zpf.o
	axiomxl $(options) zfactor.as
	ar rv $(sumitasl) zfactor.ao

zringint.o: zringint.as zfactor.o
	axiomxl $(options) zringint.as
	ar rv $(sumitasl) zringint.ao

.PHONY: doc
doc: $(tex)

zfactor.tex: zfactor.as
	as2doc zfactor

hensel.tex: hensel.as
	as2doc hensel

.PHONY: test
test: $(test)

Tzfactor.as: zfactor.as
	as2test zfactor
	cp Tzfactor.as $(testdir)


.PHONY: clean
clean:
	-rm $(objects) $(asobjects) $(tex) $(test)

